; This file is used to calculate which city the AI prefers to use to build a settler.
; To calculate priority, pick the block with that race's ID.
; Then, select the value that applies for the AI's home race.
; For each realm the AI has at least 4 books in, add that realm's value.
; For each realm the human player has at least 4 books in, add that realm's value in the "Humanrealm" line.
; Finally, the race that gets the highest total value is the one the AI prefers for building settlers.
; The result of this priority check is used to initialize the "Isbestrace" and "Settlerwanted" variables in AIProd.CAS.
; Warlord personality rules:
; 1) Human races (Barbarian (0), High Man (8), Nomad (11), Xuanyuan (22)) shared similar preference toward one another (4+).
; 2) Raider races (Barbarian (0), Gnoll (5), Troll (13), Goblin (25)) shared similar respect toward one another (3+)
; 3) Shorties races (Dwarf (4), Halfling (6), Goblin (25)) have less discrimination toward one another
; 4) Elves (Dark Elf (2), and High Elf (7)) are generally look down on other races, especially toward dwarf (4), and orcs (12) which feeling are mutual.
; 5) Draconian (3) and Lizardman (10) has strange patron-client relationship (4+) but while Draconian look down on others, Lizardman do not.
; 6) Orc (12) have positive relation with non-tolkienian race and bad guy races of LOTR.
; 7) Klackon (9) and Goblin (25) are pariah races, everyone hate them but while Klackon are xenophobic, goblin are not.
; 8) Beastman (1), Gnoll (5), Lizardman (10), Rakhshasa (23) are tolerate each others well with some friction between herbivore and carnivore (4+)
; 9) Halfling has good relation with other races overall (most of them 3+).
; 10) the rest depend on strategic usage.
[Cityrace0]
Homerace0=6
Homerace1=2
Homerace2=3
Homerace3=1
Homerace4=2
Homerace5=3
Homerace6=4
Homerace7=2
Homerace8=4
Homerace9=0
Homerace10=3
Homerace11=5
Homerace12=3
Homerace13=3
Homerace22=4
Homerace23=1
Homerace24=1
Homerace25=3
AIRealm1=0
AIRealm2=1
AIRealm3=0
AIRealm4=1
AIRealm5=-1
HumanRealm1=0
HumanRealm2=0
HumanRealm3=0
HumanRealm4=0
HumanRealm5=-1
[Cityrace1]
Homerace0=6
Homerace1=8
Homerace2=2
Homerace3=2
Homerace4=5
Homerace5=4
Homerace6=3
Homerace7=2
Homerace8=4
Homerace9=1
Homerace10=6
Homerace11=5
Homerace12=4
Homerace13=5
Homerace22=3
Homerace23=4
Homerace24=6
Homerace25=6
AIRealm1=0
AIRealm2=0
AIRealm3=0
AIRealm4=0
AIRealm5=0
HumanRealm1=0
HumanRealm2=0
HumanRealm3=0
HumanRealm4=0
HumanRealm5=-1
[Cityrace2]
Homerace0=6
Homerace1=6
Homerace2=9
Homerace3=2
Homerace4=1
Homerace5=6
Homerace6=6
Homerace7=7
Homerace8=6
Homerace9=3
Homerace10=6
Homerace11=6
Homerace12=1
Homerace13=7
Homerace22=4
Homerace23=6
Homerace24=7
Homerace25=4
AIRealm1=0
AIRealm2=3
AIRealm3=0
AIRealm4=0
AIRealm5=0
HumanRealm1=0
HumanRealm2=-2
HumanRealm3=-1
HumanRealm4=0
HumanRealm5=0
[Cityrace3]
Homerace0=5
Homerace1=3
Homerace2=3
Homerace3=9
Homerace4=6
Homerace5=5
Homerace6=6
Homerace7=3
Homerace8=6
Homerace9=2
Homerace10=9
Homerace11=4
Homerace12=5
Homerace13=5
Homerace22=3
Homerace23=3
Homerace24=4
Homerace25=6
AIRealm1=-1
AIRealm2=0
AIRealm3=1
AIRealm4=0
AIRealm5=1
HumanRealm1=-1
HumanRealm2=-1
HumanRealm3=-1
HumanRealm4=0
HumanRealm5=0
[Cityrace4]
Homerace0=6
Homerace1=3
Homerace2=1
Homerace3=2
Homerace4=8
Homerace5=6
Homerace6=6
Homerace7=1
Homerace8=4
Homerace9=2
Homerace10=3
Homerace11=3
Homerace12=2
Homerace13=6
Homerace22=2
Homerace23=5
Homerace24=7
Homerace25=8
AIRealm1=0
AIRealm2=-1
AIRealm3=1
AIRealm4=2
AIRealm5=0
HumanRealm1=0
HumanRealm2=0
HumanRealm3=0
HumanRealm4=0
HumanRealm5=2
[Cityrace5]
Homerace0=3
Homerace1=3
Homerace2=3
Homerace3=1
Homerace4=2
Homerace5=5
Homerace6=3
Homerace7=2
Homerace8=1
Homerace9=0
Homerace10=3
Homerace11=1
Homerace12=3
Homerace13=3
Homerace22=1
Homerace23=2
Homerace24=2
Homerace25=4
AIRealm1=2
AIRealm2=0
AIRealm3=0
AIRealm4=1
AIRealm5=0
HumanRealm1=0
HumanRealm2=-1
HumanRealm3=0
HumanRealm4=0
HumanRealm5=-1
[Cityrace6]
Homerace0=5
Homerace1=3
Homerace2=5
Homerace3=3
Homerace4=6
Homerace5=5
Homerace6=6
Homerace7=5
Homerace8=5
Homerace9=3
Homerace10=6
Homerace11=6
Homerace12=2
Homerace13=5
Homerace22=4
Homerace23=4
Homerace24=5
Homerace25=8
AIRealm1=2
AIRealm2=2
AIRealm3=1
AIRealm4=1
AIRealm5=0
HumanRealm1=0
HumanRealm2=-2
HumanRealm3=-2
HumanRealm4=0
HumanRealm5=0
[Cityrace7]
Homerace0=5
Homerace1=4
Homerace2=7
Homerace3=2
Homerace4=1
Homerace5=6
Homerace6=6
Homerace7=9
Homerace8=6
Homerace9=0
Homerace10=4
Homerace11=4
Homerace12=1
Homerace13=6
Homerace22=3
Homerace23=4
Homerace24=6
Homerace25=5
AIRealm1=0
AIRealm2=0
AIRealm3=0
AIRealm4=0
AIRealm5=0
HumanRealm1=0
HumanRealm2=0
HumanRealm3=0
HumanRealm4=0
HumanRealm5=0
[Cityrace8]
Homerace0=5
Homerace1=2
Homerace2=2
Homerace3=2
Homerace4=4
Homerace5=3
Homerace6=3
Homerace7=2
Homerace8=7
Homerace9=0
Homerace10=3
Homerace11=5
Homerace12=2
Homerace13=3
Homerace22=5
Homerace23=3
Homerace24=4
Homerace25=4
AIRealm1=0
AIRealm2=0
AIRealm3=0
AIRealm4=2
AIRealm5=0
HumanRealm1=0
HumanRealm2=0
HumanRealm3=0
HumanRealm4=0
HumanRealm5=-1
[Cityrace9]
Homerace0=0
Homerace1=0
Homerace2=0
Homerace3=0
Homerace4=0
Homerace5=0
Homerace6=3
Homerace7=0
Homerace8=0
Homerace9=8
Homerace10=0
Homerace11=0
Homerace12=0
Homerace13=0
Homerace22=0
Homerace23=0
Homerace24=0
Homerace25=0
AIRealm1=0
AIRealm2=0
AIRealm3=0
AIRealm4=1
AIRealm5=0
HumanRealm1=0
HumanRealm2=0
HumanRealm3=0
HumanRealm4=0
HumanRealm5=0
[Cityrace10]
Homerace0=3
Homerace1=4
Homerace2=2
Homerace3=4
Homerace4=2
Homerace5=3
Homerace6=3
Homerace7=2
Homerace8=2
Homerace9=0
Homerace10=7
Homerace11=2
Homerace12=3
Homerace13=3
Homerace22=1
Homerace23=4
Homerace24=3
Homerace25=2
AIRealm1=0
AIRealm2=2
AIRealm3=0
AIRealm4=2
AIRealm5=0
HumanRealm1=0
HumanRealm2=-1
HumanRealm3=1
HumanRealm4=0
HumanRealm5=-1
[Cityrace11]
Homerace0=6
Homerace1=2
Homerace2=2
Homerace3=1
Homerace4=2
Homerace5=4
Homerace6=4
Homerace7=2
Homerace8=4
Homerace9=0
Homerace10=3
Homerace11=6
Homerace12=4
Homerace13=4
Homerace22=4
Homerace23=2
Homerace24=5
Homerace25=4
AIRealm1=1
AIRealm2=0
AIRealm3=1
AIRealm4=0
AIRealm5=0
HumanRealm1=0
HumanRealm2=-1
HumanRealm3=0
HumanRealm4=0
HumanRealm5=1
[Cityrace12]
Homerace0=3
Homerace1=2
Homerace2=1
Homerace3=2
Homerace4=4
Homerace5=4
Homerace6=3
Homerace7=1
Homerace8=2
Homerace9=0
Homerace10=4
Homerace11=4
Homerace12=7
Homerace13=3
Homerace22=3
Homerace23=3
Homerace24=3
Homerace25=6
AIRealm1=0
AIRealm2=0
AIRealm3=0
AIRealm4=0
AIRealm5=0
HumanRealm1=0
HumanRealm2=0
HumanRealm3=0
HumanRealm4=0
HumanRealm5=-1
[Cityrace13]
Homerace0=3
Homerace1=2
Homerace2=3
Homerace3=2
Homerace4=3
Homerace5=4
Homerace6=5
Homerace7=2
Homerace8=2
Homerace9=0
Homerace10=3
Homerace11=2
Homerace12=4
Homerace13=5
Homerace22=2
Homerace23=2
Homerace24=2
Homerace25=3
AIRealm1=1
AIRealm2=0
AIRealm3=0
AIRealm4=0
AIRealm5=0
HumanRealm1=0
HumanRealm2=-1
HumanRealm3=0
HumanRealm4=0
HumanRealm5=-1
[Cityrace22]
Homerace0=4
Homerace1=2
Homerace2=2
Homerace3=2
Homerace4=3
Homerace5=4
Homerace6=4
Homerace7=2
Homerace8=4
Homerace9=0
Homerace10=3
Homerace11=4
Homerace12=4
Homerace13=4
Homerace22=7
Homerace23=2
Homerace24=3
Homerace25=7
AIRealm1=0
AIRealm2=1
AIRealm3=2
AIRealm4=-1
AIRealm5=0
HumanRealm1=0
HumanRealm2=-1
HumanRealm3=0
HumanRealm4=1
HumanRealm5=1
[Cityrace23]
Homerace0=4
Homerace1=3
Homerace2=2
Homerace3=2
Homerace4=5
Homerace5=4
Homerace6=4
Homerace7=2
Homerace8=4
Homerace9=0
Homerace10=4
Homerace11=4
Homerace12=4
Homerace13=4
Homerace22=2
Homerace23=7
Homerace24=4
AIRealm1=0
AIRealm2=1
AIRealm3=0
AIRealm4=0
AIRealm5=0
HumanRealm1=1
HumanRealm2=0
HumanRealm3=1
HumanRealm4=0
HumanRealm5=1
[Cityrace24]
Homerace0=3
Homerace1=4
Homerace2=4
Homerace3=3
Homerace4=4
Homerace5=3
Homerace6=4
Homerace7=4
Homerace8=4
Homerace9=0
Homerace10=4
Homerace11=4
Homerace12=3
Homerace13=3
Homerace22=2
Homerace23=3
Homerace24=7
Homerace25=3
AIRealm1=-1
AIRealm2=0
AIRealm3=0
AIRealm4=1
AIRealm5=1
HumanRealm1=0
HumanRealm2=0
HumanRealm3=0
HumanRealm4=2
HumanRealm5=2
[Cityrace25]
Homerace0=2
Homerace1=0
Homerace2=0
Homerace3=0
Homerace4=2
Homerace5=2
Homerace6=2
Homerace7=0
Homerace8=0
Homerace9=0
Homerace10=0
Homerace11=0
Homerace12=1
Homerace13=2
Homerace22=0
Homerace23=0
Homerace24=0
Homerace25=4
AIRealm1=1
AIRealm2=0
AIRealm3=1
AIRealm4=2
AIRealm5=0
HumanRealm1=0
HumanRealm2=0
HumanRealm3=0
HumanRealm4=0
HumanRealm5=0
