[System]
; Number of animations to load from this file, up to 500
Total=5
[1]
; File name for the image files. Extension must be .PNG.
Name=Ice_Ball
; Last animation frame file to load (first is 0. Highest allowed = 1000)
LastFrame=15
; The spell's effect is applied the first time this frame is displayed
TriggerFrame=11
; How many game ticks the animation frame is displayed for. (assuming 30 FPS)
Frame0T=4
; The X and Y position adjustment compared to the center
Frame0X=81
Frame0Y=-110

Frame1T=4
Frame1X=73
Frame1Y=-102

Frame2T=4
Frame2X=65
Frame2Y=-94

Frame3T=4
Frame3X=53
Frame3Y=-86

Frame4T=4
Frame4X=45
Frame4Y=-78

Frame5T=4
Frame5X=37
Frame5Y=-70

Frame6T=4
Frame6X=29
Frame6Y=-62

Frame7T=4
Frame7X=21
Frame7Y=-54

Frame8T=4
Frame8X=13
Frame8Y=-46

Frame9T=4
Frame9X=5
Frame9Y=-38

Frame10T=4
Frame10X=-6
Frame10Y=-30

Frame11T=2
Frame11X=-6
Frame11Y=-23

Frame12T=2
Frame12X=-6
Frame12Y=-23

Frame13T=2
Frame13X=-6
Frame13Y=-23

Frame14T=2
Frame14X=-6
Frame14Y=-23

Frame15T=2
Frame15X=-6
Frame15Y=-23

[2]
Name=Corrosive_Blast
LastFrame=9
TriggerFrame=5

Frame0T=1
Frame0X=-15
Frame0Y=-23

Frame1T=1
Frame1X=-15
Frame1Y=-23

Frame2T=1
Frame2X=-15
Frame2Y=-23

Frame3T=1
Frame3X=-15
Frame3Y=-23

Frame4T=1
Frame4X=-15
Frame4Y=-23

Frame5T=1
Frame5X=-15
Frame5Y=-23

Frame6T=1
Frame6X=-15
Frame6Y=-23

Frame7T=1
Frame7X=-15
Frame7Y=-23

Frame8T=1
Frame8X=-15
Frame8Y=-23

Frame9T=1
Frame9X=-15
Frame9Y=-23

[3]
Name=CallTheVoid
LastFrame=19
TriggerFrame=5

Frame0T=2
Frame0X=-32
Frame0Y=-42

Frame1T=2
Frame1X=-32
Frame1Y=-42

Frame2T=2
Frame2X=-32
Frame2Y=-42

Frame3T=2
Frame3X=-32
Frame3Y=-42

Frame4T=2
Frame4X=-32
Frame4Y=-42

Frame5T=2
Frame5X=-32
Frame5Y=-42

Frame6T=2
Frame6X=-32
Frame6Y=-42

Frame7T=2
Frame7X=-32
Frame7Y=-42

Frame8T=2
Frame8X=-32
Frame8Y=-42

Frame9T=2
Frame9X=-32
Frame9Y=-42

Frame10T=2
Frame10X=-32
Frame10Y=-42

Frame11T=2
Frame11X=-32
Frame11Y=-42

Frame12T=2
Frame12X=-32
Frame12Y=-42

Frame13T=2
Frame13X=-32
Frame13Y=-42

Frame14T=2
Frame14X=-32
Frame14Y=-42

Frame15T=2
Frame15X=-32
Frame15Y=-42

Frame16T=2
Frame16X=-32
Frame16Y=-42

Frame17T=2
Frame17X=-32
Frame17Y=-42

Frame18T=2
Frame18X=-32
Frame18Y=-42

Frame19T=2
Frame19X=-32
Frame19Y=-42

[4]
Name=Ice_Comet
LastFrame=15
TriggerFrame=11

Frame0T=1
Frame0X=68
Frame0Y=-130

Frame1T=1
Frame1X=60
Frame1Y=-122

Frame2T=1
Frame2X=52
Frame2Y=-114

Frame3T=1
Frame3X=44
Frame3Y=-106

Frame4T=1
Frame4X=36
Frame4Y=-98

Frame5T=1
Frame5X=28
Frame5Y=-90

Frame6T=1
Frame6X=20
Frame6Y=-82

Frame7T=1
Frame7X=12
Frame7Y=-74

Frame8T=1
Frame8X=4
Frame8Y=-66

Frame9T=1
Frame9X=-4
Frame9Y=-58

Frame10T=1
Frame10X=-12
Frame10Y=-50

Frame11T=2
Frame11X=-20
Frame11Y=-42

Frame12T=2
Frame12X=-20
Frame12Y=-34

Frame13T=2
Frame13X=-20
Frame13Y=-34

Frame14T=2
Frame14X=-20
Frame14Y=-34

Frame15T=2
Frame15X=-20
Frame15Y=-34

[5]
Name=WarpNode
LastFrame=15
TriggerFrame=15

Frame0T=2
Frame0X=-10
Frame0Y=-9

Frame1T=2
Frame1X=-10
Frame1Y=-9

Frame2T=2
Frame2X=-10
Frame2Y=-9

Frame3T=2
Frame3X=-10
Frame3Y=-9

Frame4T=2
Frame4X=-10
Frame4Y=-9

Frame5T=2
Frame5X=-10
Frame5Y=-9

Frame6T=2
Frame6X=-10
Frame6Y=-9

Frame7T=2
Frame7X=-10
Frame7Y=-9

Frame8T=2
Frame8X=-9
Frame8Y=-9

Frame9T=2
Frame9X=-10
Frame9Y=-9

Frame10T=2
Frame10X=-10
Frame10Y=-9

Frame11T=2
Frame11X=-10
Frame11Y=-9

Frame12T=2
Frame12X=-10
Frame12Y=-9

Frame13T=2
Frame13X=-10
Frame13Y=-9

Frame14T=2
Frame14X=-10
Frame14Y=-9

Frame15T=2
Frame15X=-10
Frame15Y=-9
