; AILightningMultiplier=?
; The multiplier for the number of turns the lightning is active for.
; To change the bolt strength, edit FortLig.CAS instead.
; AIStallInCombat=0
; Set this to 1 to allow the AI to stall for time in combat if they thing they are outnumbered and cannot win.
[Beginner]
ScorePercentage=60
AICityGrowth=100
AIOverlandCastingCost=95
AIProductionBonus=85
AIGoldBonus=100
AIPowerBonus=100
AIResearchBonus=90
AIUpkeepPercentage=100
ConquestDestructionrate=0
AIHeroEXPPercentage=0
AILightningMultiplier=0
AIStartinggold=75
AIStartingmana=0
HumanStartingGold=160
AIStallInCombat=0
MaxGenericWars=0
[Easy]
ScorePercentage=80
AICityGrowth=100
AIOverlandCastingCost=95
AIProductionBonus=85
AIGoldBonus=100
AIPowerBonus=100
AIResearchBonus=100
AIUpkeepPercentage=100
ConquestDestructionrate=5
AIHeroEXPPercentage=0
AILightningMultiplier=50
AIStartinggold=75
AIStartingmana=0
HumanStartingGold=160
AIStallInCombat=0
MaxGenericWars=1
[Normal]
ScorePercentage=100
AICityGrowth=100
AIOverlandCastingCost=95
AIProductionBonus=85
AIGoldBonus=100
AIPowerBonus=100
AIResearchBonus=90
AIUpkeepPercentage=100
ConquestDestructionrate=10
AIHeroEXPPercentage=50
AILightningMultiplier=50
AIStartinggold=120
AIStartingmana=30
HumanStartingGold=140
AIStallInCombat=0
MaxGenericWars=1
[Fair]
ScorePercentage=130
AICityGrowth=100
AIOverlandCastingCost=90
AIProductionBonus=100
AIGoldBonus=100
AIPowerBonus=115
AIResearchBonus=110
AIUpkeepPercentage=100
ConquestDestructionrate=15
AIHeroEXPPercentage=100
AILightningMultiplier=100
AIStartinggold=140
AIStartingmana=35
HumanStartingGold=120
AIStallInCombat=0
MaxGenericWars=2
[Advanced]
ScorePercentage=150
AICityGrowth=110
AIOverlandCastingCost=80
AIProductionBonus=115
AIGoldBonus=130
AIPowerBonus=125
AIResearchBonus=125
AIUpkeepPercentage=100
ConquestDestructionrate=20
AIHeroEXPPercentage=150
AILightningMultiplier=100
AIStartinggold=200
AIStartingmana=60
HumanStartingGold=100
AIStallInCombat=1
MaxGenericWars=2
[Expert]
ScorePercentage=200
AICityGrowth=120
AIOverlandCastingCost=70
AIProductionBonus=130
AIGoldBonus=150
AIPowerBonus=150
AIResearchBonus=150
AIUpkeepPercentage=90
ConquestDestructionrate=25
AIHeroEXPPercentage=200
AILightningMultiplier=150
AIStartinggold=350
AIStartingmana=125
HumanStartingGold=80
AIStallInCombat=1
MaxGenericWars=3
[Master]
ScorePercentage=250
AICityGrowth=120
AIOverlandCastingCost=60
AIProductionBonus=140
AIGoldBonus=150
AIPowerBonus=180
AIResearchBonus=170
AIUpkeepPercentage=70
ConquestDestructionrate=30
AIHeroEXPPercentage=250
AILightningMultiplier=150
AIStartinggold=700
AIStartingmana=175
HumanStartingGold=60
AIStallInCombat=1
MaxGenericWars=3
[Lunatic]
ScorePercentage=300
AICityGrowth=130
AIOverlandCastingCost=50
AIProductionBonus=160
AIGoldBonus=170
AIPowerBonus=225
AIResearchBonus=200
AIUpkeepPercentage=50
ConquestDestructionrate=35
AIHeroEXPPercentage=300
AILightningMultiplier=150
AIStartinggold=900
AIStartingmana=225
HumanStartingGold=40
AIStallInCombat=1
MaxGenericWars=4
[Phantasm]
ScorePercentage=400
AICityGrowth=140
AIOverlandCastingCost=40
AIProductionBonus=190
AIGoldBonus=200
AIPowerBonus=300
AIResearchBonus=250
AIUpkeepPercentage=30
ConquestDestructionrate=45
AIHeroEXPPercentage=350
AILightningMultiplier=150
AIStartinggold=900
AIStartingmana=225
HumanStartingGold=20
AIStallInCombat=1
MaxGenericWars=4
