; Probability of Wild Game or Nightshade if an ore is to be placed on a Forest or Swamp.
; If below 100% and the ore is not chosen, the tile will be transformed into a Hill, Moutain or Desert to place a different ore.
[Forest]
WildGame=50
[Swamp]
Nightshade=100
; Each section below needs to contain numbers that add up to exactly 100. They represent the percentage chance of each type of ore to get chosen.
[HillsPoorArcanus]
Iron=50
Coal=12
Silver=18
Gold=16
Gem=0
Mithril=3
Adamantium=0
Quork=0
Crysx=0
Orihalcon=1
[HillsPoorMyrror]
Iron=24
Coal=15
Silver=25
Gold=30
Gem=0
Mithril=4
Adamantium=1
Quork=0
Crysx=0
Orihalcon=1
[HillsFairArcanus]
Iron=28
Coal=15
Silver=25
Gold=25
Gem=0
Mithril=5
Adamantium=0
Quork=0
Crysx=0
Orihalcon=2
[HillsFairMyrror]
Iron=18
Coal=18
Silver=18
Gold=36
Gem=0
Mithril=5
Adamantium=3
Quork=0
Crysx=0
Orihalcon=2
[HillsRichArcanus]
Iron=16
Coal=16
Silver=25
Gold=33
Gem=0
Mithril=7
Adamantium=1
Quork=0
Crysx=0
Orihalcon=2
[HillsRichMyrror]
Iron=12
Coal=17
Silver=15
Gold=41
Gem=0
Mithril=7
Adamantium=3
Quork=3
Crysx=0
Orihalcon=2
[MountainPoorArcanus]
Iron=42
Coal=20
Silver=25
Gold=9
Gem=0
Mithril=3
Adamantium=0
Quork=0
Crysx=0
Orihalcon=1
[MountainPoorMyrror]
Iron=16
Coal=23
Silver=40
Gold=15
Gem=0
Mithril=4
Adamantium=1
Quork=0
Crysx=0
Orihalcon=1
[MountainFairArcanus]
Iron=30
Coal=30
Silver=12
Gold=21
Gem=0
Mithril=5
Adamantium=0
Quork=0
Crysx=0
Orihalcon=2
[MountainFairMyrror]
Iron=20
Coal=24
Silver=18
Gold=28
Gem=0
Mithril=5
Adamantium=3
Quork=0
Crysx=0
Orihalcon=2
[MountainRichArcanus]
Iron=16
Coal=30
Silver=12
Gold=27
Gem=5
Mithril=7
Adamantium=1
Quork=0
Crysx=0
Orihalcon=2
[MountainRichMyrror]
Iron=8
Coal=25
Silver=13
Gold=33
Gem=7
Mithril=7
Adamantium=3
Quork=0
Crysx=2
Orihalcon=2
[DesertPoorArcanus]
Iron=0
Coal=0
Silver=0
Gold=0
Gem=65
Mithril=0
Adamantium=0
Quork=30
Crysx=0
Orihalcon=5
[DesertPoorMyrror]
Iron=0
Coal=0
Silver=0
Gold=0
Gem=20
Mithril=0
Adamantium=0
Quork=55
Crysx=20
Orihalcon=5
[DesertFairArcanus]
Iron=0
Coal=0
Silver=0
Gold=0
Gem=65
Mithril=0
Adamantium=0
Quork=30
Crysx=0
Orihalcon=5
[DesertFairMyrror]
Iron=0
Coal=0
Silver=0
Gold=0
Gem=20
Mithril=0
Adamantium=0
Quork=55
Crysx=20
Orihalcon=5
[DesertRichArcanus]
Iron=0
Coal=0
Silver=0
Gold=0
Gem=65
Mithril=0
Adamantium=0
Quork=30
Crysx=0
Orihalcon=5
[DesertRichMyrror]
Iron=0
Coal=0
Silver=0
Gold=0
Gem=20
Mithril=0
Adamantium=0
Quork=55
Crysx=20
Orihalcon=5
; This section determines the amount of ores to be generated in each ore generation block. (10x10 map area with an overlap of 5 between blocks)
; Each 100 value represents a 100% chance to generate one additional ore.
; The type of ore generated for Desert, Hills, Mountains are regulated by the above values.
; Forest will always generate Wild Game, Swamp will always generate Nightshade.
; If a Grassland tile was chosen, it'll be converted to another type that can have an ore.
; If a Forest tile was chosen, there is a chance it'll be converted to Hills or Mountain, otherwise it'll have Wild Game.
[OreAmount]
ArcanusPoor=50
ArcanusFair=125
ArcanusRich=200
MyrrorPoor=75
MyrrorFair=187
MyrrorRich=300
; When the player starts on Arcanus, the Myrran plane will have Adamantium ore generated at a probability of one in this many replacing the default roll results. This feature exists to guarantee the endgame opponents have access to at least some of this ore regardless of luck, and/or that the other plane is relevant for "Race to the Unknown" games, without giving this advantage to the player when they start on the Myrran side which would unbalance the Myrran retort at only 1 pick cost.
MyrranAdamantiumPoor=40
MyrranAdamantiumFair=20
MyrranAdamantiumRich=10
[Volcano]
Orihalcon=1
Adamantium=4
Mithril=5
Gold=10
Silver=10
Coal=10
Iron=10
Gem=10
Quork=10
Crysx=5
None=675
; 1/X chance of Volcanoes reverting to Mountains each turn
VolcanoRevertChance=200
; Tile type to generate when a Volcano reverts.
; Default : 6 = Mountain
; (4 = Grasslands, 5=Hills, 8=Desert, 12=Forest)
VolcanoRevertTo=6
[Value]
; These values are used to determine how many and what type of ores are allowed on starting cities.
; Please be aware this also affects AI players.
WildGame=1
Nightshade=1
Adamantium=11
Mithril=6
Orihalcon=4
Iron=1
Coal=2
Silver=2
Gold=4
Gems=6
Crysx=6
Quork=4
