; The AI must have ALL three spells in at least one of these entries to be allowed into the game.
; SpellX=XXX, spell entry :
; SpellX=10XX, retort entry? :
; Maximal allowed entries : 1000
; Set entries to the last one in case want to disable reroll of spell specifically
[0]
NofEntries=194
; Cult leader synergy
[1]
; Ruler of Heaven, Dark Ritual, Retort-Cult Leader :
Spell1=234
Spell2=190
Spell3=1012
[2]
; New - Ruler of Heaven, Nature Embrace, Retort-Cult Leader :
Spell1=234
Spell2=223
Spell3=1012
[3]
; New - Ruler of Heaven, Ruler of Underworld, Retort-Cult Leader :
Spell1=234
Spell2=225
Spell3=1012
[4]
; New - Dark Ritual, Nature Embrace, Retort-Cult Leader :
Spell1=190
Spell2=223
Spell3=1012
[5]
; New - Dark Ritual, Chaos Embrace, Retort-Cult Leader :
Spell1=190
Spell2=227
Spell3=1012
[6]
; New - Dark Ritual, Ruler of Underworld, Retort-Cult Leader :
Spell1=190
Spell2=225
Spell3=1012
; Ruler of Heaven + Global Curse synergy
[7]
; New - Ruler of Heaven, Meteor Storm :
Spell1=234
Spell2=113
Spell3=0
[8]
; New - Ruler of Heaven, Doomsday :
Spell1=234
Spell2=114
Spell3=0
[9]
; New - Ruler of Heaven, Armageddon :
Spell1=234
Spell2=120
Spell3=0
[10]
; New - Ruler of Heaven, Divine Order :
Spell1=234
Spell2=135
Spell3=0
[11]
; New - Ruler of Heaven, Eternal Night :
Spell1=234
Spell2=197
Spell3=0
[12]
; New - Ruler of Heaven, Evil Omen :
Spell1=234
Spell2=198
Spell3=0
[13]
; New - Ruler of Heaven, Darkest Hour :
Spell1=234
Spell2=218
Spell3=0
; Spell Binding synergy :
[14]
; Spell Binding, Retort-Runemaster :
Spell1=76
Spell2=1014
Spell3=0
[15]
; New - Spell Binding, Retort-Channeler :
Spell1=76
Spell2=1007
Spell3=0
[16]
; New - Spell Binding, Ruler of Heaven :
Spell1=76
Spell2=234
Spell3=0
; Time Stop Synergy
[17]
; Time Stop, Call the Void :
Spell1=80
Spell2=119
Spell3=0
[18]
; Time Stop, Final Wave :
Spell1=80
Spell2=199
Spell3=0
[19]
; Time Stop, Great Unsummoning :
Spell1=80
Spell2=75
Spell3=0
[20]
; Time Stop, Retort-Alchemy :
Spell1=80
Spell2=1001
Spell3=0
; Normal Units buff Global Enchantment Synergy :
[21]
; Doom Mastery, Chaos Surge :
Spell1=108
Spell2=116
Spell3=0
[22]
; Doom Mastery, Chaos Embrace :
Spell1=108
Spell2=227
Spell3=0
[23]
; Doom Mastery, Crusade :
Spell1=108
Spell2=158
Spell3=0
[24]
; Doom Mastery, Warp Reality :
Spell1=108
Spell2=117
Spell3=0
[25]
; New - Doom Mastery, Survival Instinct :
Spell1=108
Spell2=28
Spell3=0
[26]
; New - Doom Mastery, Zombie Mastery :
Spell1=108
Spell2=188
Spell3=0
[27]
; New - Doom Mastery, Reinforce Magic :
Spell1=108
Spell2=224
Spell3=0
[28]
; New - Doom Mastery, Holy Arms :
Spell1=108
Spell2=154
Spell3=0
[29]
; New - Doom Mastery, Retort-Warlord :
Spell1=108
Spell2=1004
Spell3=0
[30]
; Crusade, Wind Mastery - weak combo :
Spell1=158
Spell2=222
Spell3=0
[31]
; Crusade, Retort-Warlord :
Spell1=158
Spell2=1004
Spell3=0
[32]
; Crusade, Charm of Life :
Spell1=158
Spell2=160
Spell3=0
[33]
; Crusade, Supreme Light - weak combo :
Spell1=158
Spell2=152
Spell3=0
[34]
; Crusade, Holy Arms :
Spell1=158
Spell2=154
Spell3=0
[35]
; Crusade, Ruler of Underworld :
Spell1=158
Spell2=225
Spell3=0
[36]
; New - Crusade, Altar of Battle :
Spell1=158
Spell2=146
Spell3=0
[37]
; New - Crusade, Enlightenment :
Spell1=158
Spell2=157
Spell3=0
[38]
; New - Enlightenment, Altar of Battle :
Spell1=157
Spell2=146
Spell3=0
[39]
; New - Holy Arms, High Prayer :
Spell1=154
Spell2=151
Spell3=0
[40]
; Holy Arms, Charm of Life :
Spell1=154
Spell2=160
Spell3=0
[41]
; New - Ruler of Underworld, Altar of Battle,  :
Spell1=225
Spell2=146
Spell3=0
; General Units Buff global enchantment synergy :
[42]
; Wind Mastery, Charm of Life :
Spell1=222
Spell2=160
Spell3=0
[43]
; Ruler of Underworld, Charm of Life,  :
Spell1=225
Spell2=160
Spell3=0
[44]
; New - Ruler of Underworld, Wind Mastery  :
Spell1=225
Spell2=222
Spell3=0
[45]
; New - Ruler of Underworld, Great Unsummoning :
Spell1=225
Spell2=75
Spell3=0
; Ruler of Underworld + city curse synergy :
[46]
; New - Ruler of Underworld, Chaos Rift :
Spell1=225
Spell2=110
Spell3=0
[47]
; New - Ruler of Underworld, Drought, Evil Presence :
Spell1=225
Spell2=189
Spell3=183
[48]
; New - Ruler of Underworld, Pestilence :
Spell1=225
Spell2=196
Spell3=0
; Research and Power Synergy
[49]
; New - Enlightenment, Retort=Sage Master *warp speed research :
Spell1=120
Spell2=1002
Spell3=0
[50]
; New - Abundance, Enlightenment :
Spell1=216
Spell2=157
Spell3=0
[51]
; New - Abundance, Life Force :
Spell1=216
Spell2=156
Spell3=0
[52]
; New - Gaia's Blessing, Roots of Genesis :
Spell1=29
Spell2=226
Spell3=0
[53]
; New - Uranus's Blessing, Enlightenment :
Spell1=61
Spell2=157
Spell3=0
[54]
; New - Uranus's Blessing, Altar of Peace :
Spell1=61
Spell2=139
Spell3=0
[55]
; New - Uranus's Blessing, Retort-Omniscient :
Spell1=61
Spell2=1009
Spell3=0
[56]
; Armageddon, Roots of Genesis :
Spell1=120
Spell2=226
Spell3=0
[57]
; Armageddon, Life Force :
Spell1=120
Spell2=156
Spell3=0
[58]
; Armageddon, Retort-Runemaster :
Spell1=120
Spell2=1014
Spell3=0
[59]
; Roots of Genesis, Life Force :
Spell1=226
Spell2=156
Spell3=0
[60]
; New - Evil Omen, Power Link :
Spell1=198
Spell2=79
Spell3=0
; Aether Binding & Fairy Ring synergy ;
[61]
; New - Aether Binding, Dispeling Wave :
Spell1=57
Spell2=52
Spell3=0
[62]
; New - Fairy Ring, Aether Binding :
Spell1=40
Spell2=57
Spell3=0
[63]
; New - Fairy Ring, Retort-Channeler :
Spell1=40
Spell2=1007
Spell3=0
[64]
; Fairy Ring, Death Knights :
Spell1=40
Spell2=193
Spell3=0
[65]
; Fairy Ring, Djinn :
Spell1=40
Spell2=71
Spell3=0
[66]
; New - Fairy Ring, Great Wyrm :
Spell1=40
Spell2=39
Spell3=0
; Global Curse synergy
[67]
; Darkest Hour, Power Link :
Spell1=218
Spell2=79
Spell3=0
[68]
; New - Darkest Hour, Evil Omen :
Spell1=218
Spell2=198
Spell3=0
[69]
; New - Darkest Hour, Pestilence :
Spell1=218
Spell2=196
Spell3=0
[70]
; Doomsday, Armageddon :
Spell1=114
Spell2=120
Spell3=0
[71]
; Doomsday, Evil Omens :
Spell1=114
Spell2=198
Spell3=0
[72]
; New - Doomsday, Pestilence :
Spell1=114
Spell2=196
Spell3=0
[73]
; Meteor Storm, Pestilence :
Spell1=113
Spell2=196
Spell3=0
[74]
; Armageddon, Pestilence :
Spell1=120
Spell2=196
Spell3=0
[75]
; New - Doomsday, Call the Void :
Spell1=114
Spell2=119
Spell3=0
[76]
; New - Armageddon, Call the Void :
Spell1=120
Spell2=119
Spell3=0
[77]
; New - Eternal Night, Final Wave :
Spell1=197
Spell2=199
Spell3=0
[78]
; New - Eternal Night, Great Unsummoning :
Spell1=197
Spell2=75
Spell3=0
[79]
; New - Eternal Night, Masscare, Annihilate :
Spell1=197
Spell2=194
Spell3=192
[80]
; New - Eternal Night, Terror :
Spell1=197
Spell2=181
Spell3=0
[81]
; New - Eternal Night, Zombie Mastery, Herb Mastery :
Spell1=197
Spell2=188
Spell3=38
[82]
; New - Dance of Death, Holy Word :
Spell1=219
Spell2=150
Spell3=0
[83]
; New - Dance of Death, Massacre :
Spell1=219
Spell2=194
Spell3=0
[84]
; New - Dance of Death, Final Wave :
Spell1=219
Spell2=199
Spell3=0
[85]
; New - Dance of Death, Creature Binding :
Spell1=219
Spell2=73
Spell3=0
[86]
; New - Dance of Death, Great Unsummoning :
Spell1=219
Spell2=75
Spell3=0
[87]
; New - Dance of Death, Petrify :
Spell1=219
Spell2=22
Spell3=0
[88]
; Power Link, Call the Void :
Spell1=79
Spell2=119
Spell3=0
[89]
; Power Link, Final Wave :
Spell1=79
Spell2=199
Spell3=0
[90]
; New - Power Link, Great Unsummoning :
Spell1=79
Spell2=75
Spell3=0
; Combat enchantment synergy :
[91]
; Entangle, Lightning Storm :
Spell1=33
Spell2=35
Spell3=0
[92]
; New - Entangle, Earth Elemental :
Spell1=33
Spell2=30
Spell3=0
[93]
; Lightning Storm, Mass Invisibility :
Spell1=35
Spell2=74
Spell3=0
[94]
; Lightning Storm, Air Elemental :
Spell1=35
Spell2=66
Spell3=0
[95]
; New - Lightning Storm, Earth Elemental :
Spell1=35
Spell2=30
Spell3=0
[96]
; New - Lightning Storm, Water Elemental :
Spell1=35
Spell2=12
Spell3=0
[97]
; Mass Invisibility, Annihilate :
Spell1=74
Spell2=192
Spell3=0
[98]
; New - Mass Invisibility, Terror :
Spell1=74
Spell2=181
Spell3=0
[99]
; New - Mass Invisibility, Haste :
Spell1=74
Spell2=77
Spell3=0
[100]
; New - Mass Invisibility, Water Elemental :
Spell1=74
Spell2=12
Spell3=0
[101]
; New - High Prayer, Altar of Battle :
Spell1=151
Spell2=146
Spell3=0
[102]
; New - Black Prayer, Terror :
Spell1=174
Spell2=181
Spell3=0
[103]
; New - Black Prayer, Gate of Hades :
Spell1=174
Spell2=182
Spell3=0
[104]
; New - Black Prayer, Massacre :
Spell1=174
Spell2=194
Spell3=0
; Combo between units and Mass Invisibility :
[105]
; Mass Invisibility, Djinn :
Spell2=74
Spell1=71
Spell3=0
[106]
; Mass Invisibility, Efreet :
Spell2=74
Spell1=106
Spell3=0
; Cloud Giant combo :
[107]
; Mass Invisibility, Cloud Giant :
Spell2=74
Spell1=65
Spell3=0
; Phoenix combo :
[108]
; New - Mass Invisibility, Phoenix  :
Spell2=74
Spell1=232
Spell3=0
[109]
; Mass Invisibility, Death Knights :
Spell1=74
Spell2=193
Spell3=0
; Specific units combo with global :
; Inner Power and creatures :
[110]
; New - Inner Power, Colossus :
Spell1=228
Spell2=36
Spell3=0
[111]
; New - Inner Power, Cloud Giant :
Spell1=228
Spell2=65
Spell3=0
[112]
; New - Inner Power, Sky Drake :
Spell1=228
Spell2=78
Spell3=0
[113]
; New - Inner Power, Efreet :
Spell1=228
Spell2=111
Spell3=0
[114]
; New - Inner Power, Great Drake :
Spell1=228
Spell2=118
Spell3=0
[115]
; New - Inner Power, Hydra :
Spell1=228
Spell2=111
Spell3=0
[116]
; New - Inner Power, Phoenix :
Spell1=228
Spell2=232
Spell3=0
; Reinforced magic and creatures :
[117]
; New - Reinforce Magic, Cloud Giant :
Spell1=224
Spell2=65
Spell3=0
[118]
; New - Reinforce Magic, Djinn :
Spell1=224
Spell2=71
Spell3=0
[119]
; New - Reinforce Magic, Efreet :
Spell1=224
Spell2=111
Spell3=0
[120]
; New - Reinforce Magic, Hydra :
Spell1=224
Spell2=111
Spell3=0
[121]
; New - Reinforce Magic, Vampire :
Spell1=224
Spell2=231
Spell3=0
[122]
; New - Reinforce Magic, Death Knight :
Spell1=224
Spell2=193
Spell3=0
[123]
; New - Reinforce Magic, Demon Lord :
Spell1=224
Spell2=200
Spell3=0
[124]
; New - Reinforce Magic, Phoenix :
Spell1=224
Spell2=232
Spell3=0
; Deadly Monster in need of Resistance from survival instinct :
[125]
; New - Survival Instinct, Gorgons :
Spell1=28
Spell2=27
Spell3=0
[126]
; New - Survival Instinct, Efreet :
Spell1=28
Spell2=111
Spell3=0
[127]
; New - Survival Instinct, Hydra :
Spell1=28
Spell2=111
Spell3=0
[128]
; New - Survival Instinct, Vampire :
Spell1=28
Spell2=231
Spell3=0
[129]
; New - Survival Instinct, Death Knight :
Spell1=28
Spell2=193
Spell3=0
[130]
; New - Survival Instinct, Demon Lord :
Spell1=28
Spell2=200
Spell3=0
[131]
; New - Survival Instinct, Phoenix :
Spell1=28
Spell2=232
Spell3=0
; Animate Dead synergy :
[132]
; New - Animate Dead, Regeneration :
Spell1=195
Spell2=31
Spell3=0
[133]
; New - Animate Dead, Eternal Night :
Spell1=195
Spell2=197
Spell3=0
[134]
; New - Animate Dead, Exaltation :
Spell1=195
Spell2=148
Spell3=0
; Overland Spells Combo :
[135]
; Final Wave, Great Unsummoning :
Spell1=199
Spell2=75
Spell3=0
[136]
; Call the Void, Disillusionise :
Spell1=119
Spell2=233
Spell3=0
[137]
; New - Call the Void, Final Wave :
Spell1=119
Spell2=199
Spell3=0
[138]
; New - Call the Void, Great Unsummoning :
Spell1=119
Spell2=75
Spell3=0
; Combat Spells Combo :
[139]
; Spirit of Chivalry, Charm of Life :
Spell1=153
Spell2=160
Spell3=0
[140]
; New - Apocalypse, Holy Word :
Spell1=115
Spell2=150
Spell3=0
[141]
; New - Apocalypse, Masscare :
Spell1=115
Spell2=194
Spell3=0
[142]
; New - Apocalypse, Flame Strike :
Spell1=115
Spell2=109
Spell3=0
[143]
; New - Apocalypse, Call the Void :
Spell1=115
Spell2=119
Spell3=0
[144]
; New - Chain Lightning, Flame Strike :
Spell1=235
Spell2=109
Spell3=0
; Life creature/High resistance + supreme light :
[145]
; Supreme Light, Djinn :
Spell1=152
Spell2=71
Spell3=0
[146]
; Supreme Light, Efreet :
Spell1=152
Spell2=106
Spell3=0
[147]
; Supreme Light, Apotheosis :
Spell1=152
Spell2=229
Spell3=0
[148]
; New - Supreme Light, Gorgons :
Spell1=152
Spell2=27
Spell3=0
[149]
; New - Supreme Light, Cloud Giant :
Spell1=152
Spell2=65
Spell3=0
[150]
; New - Supreme Light, Unicorns :
Spell1=152
Spell2=136
Spell3=0
[151]
; New - Supreme Light, Angel :
Spell1=152
Spell2=147
Spell3=0
[152]
; New - Supreme Light, Arch Angel :
Spell1=152
Spell2=159
Spell3=0
[153]
; New - Supreme Light, Demon Lord :
Spell1=152
Spell2=200
Spell3=0
[154]
; New - Supreme Light, Reinforce Magic :
Spell1=152
Spell2=224
Spell3=0
; Magic Immunity synergy :
[155]
; Magic Immunity, Retort-Runemaster???, Hydra :
Spell1=69
Spell2=1014
Spell3=111
[156]
; Magic Immunity, Retort-Runemaster???, Phoenix :
Spell1=69
Spell2=1014
Spell3=232
[157]
; Magic Immunity, Retort-Runemaster???, Death Knights :
Spell1=69
Spell2=1014
Spell3=193
[158]
; Magic Immunity, Retort-Runemaster???, Vampire :
Spell1=69
Spell2=1014
Spell3=231
[159]
; Magic Immunity, Spell Lock, Hydra :
Spell1=69
Spell2=54
Spell3=111
[160]
; Magic Immunity, Spell Lock, Phoenix :
Spell1=69
Spell2=54
Spell3=232
[161]
; Magic Immunity, Spell Lock, Death Knights :
Spell1=69
Spell2=54
Spell3=193
[162]
; Magic Immunity, Spell Lock, Vampire :
Spell1=69
Spell2=54
Spell3=231
; Focus Magic Unit combo
[163]
; New - Focus Magic, Arch Angel :
Spell1=47
Spell2=159
Spell3=0
[164]
; New - Focus Magic, Efreet :
Spell1=47
Spell2=106
Spell3=0
[165]
; New - Focus Magic, Gorgon :
Spell1=47
Spell2=27
Spell3=0
[166]
; New - Focus Magic, Angel :
Spell1=47
Spell2=147
Spell3=0
[167]
; New - Focus Magic, Djinn :
Spell1=47
Spell2=71
Spell3=0
[168]
; New - Focus Magic, Cockatrices :
Spell1=47
Spell2=17
Spell3=0
; Specific unit combo synergy :
; Hydra combo :
[169]
; Hydra, Entangle :
Spell1=111
Spell2=33
Spell3=0
[170]
; Hydra, Lightning Storm :
Spell1=111
Spell2=35
Spell3=0
[171]
; New - Hydra, Iron Skin :
Spell1=111
Spell2=24
Spell3=0
[172]
; New - Hydra, Lionheart :
Spell1=111
Spell2=141
Spell3=0
[173]
; New - Hydra, Bloodlust :
Spell1=111
Spell2=237
Spell3=0
[174]
; New - Hydra, Flight :
Spell1=111
Spell2=56
Spell3=0
; Djinn combo :
[175]
; Djinn, Entangle :
Spell1=71
Spell2=33
Spell3=0
[176]
; Djinn, Lightning Storm :
Spell1=71
Spell2=35
Spell3=0
[177]
; New - Djinn, Haste :
Spell1=71
Spell2=77
Spell3=0
[178]
; New - Djinn, Black Prayer :
Spell1=71
Spell2=174
Spell3=0
[179]
; New - Djinn, Regeneration :
Spell1=71
Spell2=31
Spell3=0
; Behemoth combo :
[180]
; Behemoth, Lightning Storm :
Spell1=32
Spell2=35
Spell3=0
[181]
; New - Behemoth, Iron Skin :
Spell1=32
Spell2=24
Spell3=0
[182]
; New - Behemoth, Invulnerability :
Spell1=32
Spell2=143
Spell3=0
[183]
; New - Behemoth, Charm of Life :
Spell1=32
Spell2=160
Spell3=0
; Death Knight combo :
[184]
; Death Knights, Eternal Night :
Spell1=193
Spell2=197
Spell3=0
[185]
; Death Knights, Charm of Life :
Spell1=193
Spell2=160
Spell3=0
[186]
; Death Knights, Wind Mastery :
Spell1=193
Spell2=222
Spell3=0
; Efreet combo :
[187]
; New - Efreet, Regeneration :
Spell1=106
Spell2=31
Spell3=0
; Colossus combo :
[188]
; Modified - Colossus, Invulnerability :
Spell1=36
Spell2=143
Spell3=0
; new additional spells :
[189]
; New - Thunderbird, Hurricane :
Spell1=263
Spell2=247
Spell3=0
[190]
; New - Inner Power, Insulation :
Spell1=228
Spell2=252
Spell3=0
[191]
; New - Chaos' Blessing, Doom Mastery :
Spell1=258
Spell2=108
Spell3=0
[192]
; New - Temporal Twist, Entangle :
Spell1=273
Spell2=33
Spell3=0
[193]
; New - Beat of Swiftness, Chaos Spawn :
Spell1=254
Spell2=103
Spell3=0
[194]
; New - Beat of Swiftness, Hydra :
Spell1=254
Spell2=111
Spell3=0
; Last condition in case want to disable reroll spell :
[195]
Spell1=0
Spell2=0
Spell3=0
