; When modding buildings, please be aware that having too many buildings displayed at
; the same time might lead to the last building(s) having no room left to display.
; Starting from version 1.2.0, this will not freeze the game anymore but the building won't
; be displayed, so the player cannot sell it, so keeping the size and amount of buildings
; low enough to display them all is strongly recommended, if necessary, by using the "replaces" feature more often.
;
; AIBuyPrio is how many times the buying price the AI needs to own in gold to buy the building.
; AIEarlyBuyPrio is same for cities below 7000 population.
; Both default to 100 if not included. These only affect whether the AI spends gold to produce these faster.
; For decisions on what to build, see AIProd.CAS and AIBuilding.CAS
;
; Special requiement code
; 101 = forest tile
; 102 = hill/mountain/volcano tile
; 103 = swamp tile
; 104 = desert tile
; 105 = tundra tile
; 106 = river tile
; 107 = ???
; 108 = ???
; 109 = ???
; 110 = shore
;
; Set Fortress=1 for buildings you want players to have in their starting city.
; Set Outpost=1 for buildings you want players to have in new outposts.
[1]
Name=Trade Goods
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
[2]
Name=Housing
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=3
[3]
; Pure military buildings cost 20-30%, Cost of Barracks increase to 200 due to it now requirement for halberdiers/pikemen/kardakes/arquebusiers units
Name=Barracks
Requirement1=39
Requirement2=0
Replaces=0
Upkeep=1
Cost=200
X=2
Y=1
Vizier=0
VizierMilitary=73
AnimationFrames=8
[4]
Name=Coliseum
Requirement1=3
Requirement2=5
Replaces=0
Upkeep=0
Cost=250
X=3
Y=2
Vizier=0
VizierMilitary=30
AnimationFrames=0
[5]
; Pure military buildings cost +20-30%, reduce cost of Fighter's Guild to encourage of using it
Name=Fighter's Guild
Requirement1=39
Requirement2=0
Replaces=39
Upkeep=2
Cost=200
X=2
Y=1
Vizier=0
VizierMilitary=73
AnimationFrames=8
AIBuyPrio=5
AIEarlyBuyPrio=10
[6]
; Pure military buildings cost +20-30%, increase cost of Armorer's Guild due to units here is nolonger fodder anymore, requires Smithy
Name=Armorer's Guild
Requirement1=5
Requirement2=8
Replaces=5
Upkeep=4
Cost=600
X=2
Y=1
Vizier=0
VizierMilitary=60
AnimationFrames=8
Tree=1
[7]
; Pure military buildings cost +20-30%, Now War College requires both Barracks and Fighter's Guild
Name=War College
Requirement1=3
Requirement2=5
Replaces=3
Upkeep=3
Cost=540
X=3
Y=3
Vizier=0
VizierMilitary=55
AnimationFrames=0
[8]
; Now Smithy cost get reduced to reduce its building time and encourage more normal units
Name=Smithy
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=75
X=2
Y=1
Vizier=20
VizierMilitary=80
AnimationFrames=8
AIBuyPrio=2
AIEarlyBuyPrio=2
Fortress=1
Outpost=1
[9]
; Military/production buildings cost increase to 120, upkeep change to 3.
Name=Stables
Requirement1=8
Requirement2=0
Replaces=0
Upkeep=2
Cost=120
X=3
Y=3
Vizier=0
VizierMilitary=80
AnimationFrames=8
AIBuyPrio=2
AIEarlyBuyPrio=2
[10]
Name=Animist's Guild
Requirement1=29
Requirement2=31
Replaces=31
Upkeep=2
Cost=240
X=2
Y=1
Vizier=60
VizierMilitary=60
AnimationFrames=0
[11]
; Military buildings cost +20-30%, increase cost of Fantastic Stable due to units here is nolonger fodder anymore
Name=Fantastic Stable
Requirement1=9
Requirement2=5
Replaces=9
Upkeep=4
Cost=750
X=3
Y=3
Vizier=0
VizierMilitary=58
AnimationFrames=8
Tree=1
[12]
; Now split dock from shipyard and generate food equal to number of sea tiles
Name=Dock
Requirement1=110
Requirement2=0
Replaces=0
Upkeep=0
Cost=120
X=3
Y=2
Vizier=60
VizierMilitary=80
AnimationFrames=0
OnShore=1
[13]
; Now Magic Market requires Marketplace and cost increase to 100
Name=Magic Market
Requirement1=26
Requirement2=0
Replaces=0
Upkeep=0
Cost=100
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[14]
; Pure Military buildings cost +20-30%
Name=Maritime Guild
Requirement1=110
Requirement2=42
Replaces=42
Upkeep=3
Cost=450
X=3
Y=1
Vizier=0
VizierMilitary=20
AnimationFrames=8
OnShore=1
Tree=1
[15]
; Sawmill rename to Mill and building cost 80
Name=Mill
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=1
Cost=80
X=2
Y=1
Vizier=100
VizierMilitary=100
AnimationFrames=8
AIBuyPrio=1
AIEarlyBuyPrio=3
Fortress=1
[16]
; Library cost increase to 80
Name=Library
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=80
X=3
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[17]
; Now Sage's Guild requires both University and Builder's Hall, cost change to 400
Name=Sage's Guild
Requirement1=20
Requirement2=19
Replaces=20
Upkeep=2
Cost=400
X=2
Y=1
Vizier=60
VizierMilitary=60
AnimationFrames=0
[18]
; Oracle has some military use, cost increase by 20-30%
Name=Oracle
Requirement1=22
Requirement2=32
Replaces=0
Upkeep=2
Cost=360
X=2
Y=2
Vizier=30
VizierMilitary=30
AnimationFrames=0
ScoutingRange=4
[19]
; Military/Power buildings cost +50%
Name=Alchemist's Guild
Requirement1=16
Requirement2=0
Replaces=0
Upkeep=2
Cost=150
X=1
Y=1
Vizier=70
VizierMilitary=70
AnimationFrames=8
AIBuyPrio=4
AIEarlyBuyPrio=10
[20]
; Now University requires both Library and Builder's Hall, cost change to 160 and upkeep reduce to 2
Name=University
Requirement1=16
Requirement2=32
Replaces=16
Upkeep=1
Cost=160
X=3
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[21]
; Now Wizard's Guild requires both Magic Market and Sage's Guild, cost change to 800, power income up to 12 but research income reduce to 2
Name=Wizard's Guild
Requirement1=13
Requirement2=17
Replaces=13
Upkeep=3
Cost=800
X=1
Y=1
Vizier=55
VizierMilitary=55
AnimationFrames=8
AIBuyPrio=10
AIEarlyBuyPrio=100
Tree=1
[22]
Name=Shrine
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=120
X=2
Y=1
Vizier=60
VizierMilitary=60
AnimationFrames=0
[23]
; Pure Power buildings cost +50% but upkeep reduce to 8, now amplifying Tower requires both Alchemist's Guild and Sage's Guild
Name=Amplifying Tower
Requirement1=17
Requirement2=19
Replaces=19
Upkeep=7
Cost=900
X=2
Y=1
Vizier=58
VizierMilitary=55
AnimationFrames=0
Tree=1
[24]
; rename Parthenon to Monastary and require both Shrine and Builder's Hall
Name=Monastery
Requirement1=22
Requirement2=32
Replaces=0
Upkeep=1
Cost=200
X=3
Y=3
Vizier=80
VizierMilitary=80
AnimationFrames=0
[25]
; Now Cathedral requires both Monastery and Builder's Hall
Name=Cathedral
Requirement1=24
Requirement2=32
Replaces=22
Upkeep=2
Cost=500
X=2
Y=3
Vizier=58
VizierMilitary=58
AnimationFrames=0
[26]
Name=Marketplace
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=80
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
AIBuyPrio=100
AIEarlyBuyPrio=1
[27]
; Now Bank requires both Marketplace and University
Name=Bank
Requirement1=26
Requirement2=20
Replaces=26
Upkeep=2
Cost=200
X=2
Y=1
Vizier=60
VizierMilitary=60
AnimationFrames=0
[28]
; Now Merchant's Guild requires both Ship Yard and Bank
Name=Merchant's Guild
Requirement1=42
Requirement2=27
Replaces=27
Upkeep=3
Cost=400
X=2
Y=1
Vizier=40
VizierMilitary=60
AnimationFrames=0
[29]
Name=Granary
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=1
Cost=80
X=1
Y=1
Vizier=80
VizierMilitary=70
AnimationFrames=0
AIBuyPrio=10
AIEarlyBuyPrio=4
[30]
Name=Farmer's Market
Requirement1=29
Requirement2=26
Replaces=29
Upkeep=1
Cost=150
X=2
Y=1
Vizier=80
VizierMilitary=60
AnimationFrames=0
[31]
Name=Forester's Guild
Requirement1=101
Requirement2=15
Replaces=15
Upkeep=1
Cost=130
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[32]
; Builder's Hall renamed to Town Hall and now generate 0.5 production per population and cost incrase to 100
Name=City Hall
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=80
X=3
Y=2
Vizier=80
VizierMilitary=80
AnimationFrames=0
[33]
; Production modifier buildings cost double, upkeep increase to 4
Name=Mechanician's Guild
Requirement1=20
Requirement2=34
Replaces=34
Upkeep=4
Cost=400
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[34]
; Production modifier buildings cost double
Name=Miner's Guild
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=2
Cost=200
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[35]
; Now Monument requires nothing and cost 75
Name=Monument
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=75
X=1
Y=1
Vizier=70
VizierMilitary=75
AnimationFrames=0
[36]
; Now Linking Tower requires Monument + Sage's Guild instead of Monument + Library, cost change to 550
Name=Linking Towers
Requirement1=35
Requirement2=17
Replaces=35
Upkeep=4
Cost=500
X=2
Y=1
Vizier=35
VizierMilitary=45
AnimationFrames=0
Tree=1
[37]
; Pure military buildings cost +20-30%
Name=City Walls
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=1
Cost=90
X=1
Y=1
Vizier=0
VizierMilitary=73
AnimationFrames=0
IsWall=1
ScoutingRange=3
[38]
; New! Dummy building for mercenary
Name=Mercenary Camp
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=75
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
[39]
; New! Armory, replacing role which used to be part of barracks for housing standing units
Name=Armory
Requirement1=8
Requirement2=0
Replaces=8
Upkeep=1
Cost=150
X=2
Y=1
Vizier=10
VizierMilitary=80
AnimationFrames=0
AIBuyPrio=4
AIEarlyBuyPrio=4
[40]
; New! Temple as replacement for Cathedral in some culture
Name=Temple
Requirement1=24
Requirement2=32
Replaces=22
Upkeep=1
Cost=400
X=3
Y=3
Vizier=58
VizierMilitary=58
AnimationFrames=0
[41]
; New! Fortification
Name=Fortification
Requirement1=37
Requirement2=33
Replaces=37
Upkeep=5
Cost=600
X=1
Y=2
Vizier=0
VizierMilitary=73
AnimationFrames=0
IsWall=1
ScoutingRange=3
Tree=1
[42]
; Now Ship Yard split from dock
Name=Shipyard
Requirement1=110
Requirement2=12
Replaces=12
Upkeep=1
Cost=300
X=3
Y=2
Vizier=40
VizierMilitary=60
AnimationFrames=0
OnShore=1
[43]
Name=Hangar
Requirement1=33
Requirement2=110
Replaces=33
Upkeep=3
Cost=400
X=2
Y=2
Vizier=0
VizierMilitary=20
AnimationFrames=8
OnShore=1
Tree=1
[44]
Name=Brewery
Requirement1=30
Requirement2=32
Replaces=30
Upkeep=2
Cost=200
X=2
Y=2
Vizier=80
VizierMilitary=70
AnimationFrames=8
[45]
Name=Lava Smelter
Requirement1=102
Requirement2=19
Replaces=19
Upkeep=20
Cost=1200
X=2
Y=2
Vizier=55
VizierMilitary=77
AnimationFrames=8
AIBuyPrio=6
Tree=1
[46]
Name=Tree of Life
Requirement1=101
Requirement2=10
Replaces=10
Upkeep=20
Cost=800
X=2
Y=2
Vizier=77
VizierMilitary=55
AnimationFrames=5
AIBuyPrio=8
Tree=1
[47]
Name=Caravanserai
Requirement1=32
Requirement2=104
Replaces=32
Upkeep=3
Cost=400
X=2
Y=1
Vizier=77
VizierMilitary=55
AnimationFrames=0
AIBuyPrio=2
Tree=1
[48]
Name=Undercity Hive Network
Requirement1=32
Requirement2=33
Replaces=32
Upkeep=10
Cost=1200
X=3
Y=1
Vizier=55
VizierMilitary=77
AnimationFrames=0
Tree=1
[49]
Name=Baray
Requirement1=106
Requirement2=24
Replaces=24
Upkeep=10
Cost=1000
X=3
Y=3
Vizier=77
VizierMilitary=55
AnimationFrames=8
Tree=1
[50]
Name=Hillfort
Requirement1=34
Requirement2=9
Replaces=9
Upkeep=3
Cost=300
X=3
Y=3
Vizier=0
VizierMilitary=60
AnimationFrames=0
[51]
Name=Warlord's Hold
Requirement1=32
Requirement2=7
Replaces=32
Upkeep=5
Cost=400
X=3
Y=2
Vizier=50
VizierMilitary=50
AnimationFrames=0
Tree=1
[52]
; Alternative to monastery for raider races, +1 poison attack to all units trained in city
Name=Witches' Convent
Requirement1=22
Requirement2=13
Replaces=0
Upkeep=3
Cost=400
X=3
Y=3
Vizier=80
VizierMilitary=80
AnimationFrames=8
[53]
Name=Academy
Requirement1=102
Requirement2=24
Replaces=24
Upkeep=10
Cost=1200
X=3
Y=3
Vizier=77
VizierMilitary=55
AnimationFrames=0
AIBuyPrio=6
Tree=1
[54]
Name=Military Workshop
Requirement1=106
Requirement2=33
Replaces=33
Upkeep=20
Cost=1200
X=2
Y=2
Vizier=55
VizierMilitary=77
AnimationFrames=8
Tree=1
[55]
Name=Idol of the Heavenly Bull
Requirement1=104
Requirement2=24
Replaces=24
Upkeep=20
Cost=1200
X=2
Y=2
Vizier=55
VizierMilitary=77
AnimationFrames=0
AIBuyPrio=2
Tree=1
[56]
Name=Tree of Magic
Requirement1=101
Requirement2=21
Replaces=21
Upkeep=20
Cost=1200
X=2
Y=2
Vizier=55
VizierMilitary=77
AnimationFrames=5
AIBuyPrio=8
Tree=1
[57]
Name=Pool of Repentance
Requirement1=101
Requirement2=24
Replaces=24
Upkeep=10
Cost=1200
X=3
Y=3
Vizier=55
VizierMilitary=77
AnimationFrames=5
AIBuyPrio=8
Tree=1
[58]
Name=Dragon Mound
Requirement1=102
Requirement2=9
Replaces=9
Upkeep=10
Cost=1200
X=3
Y=3
Vizier=55
VizierMilitary=77
AnimationFrames=8
AIBuyPrio=6
Tree=1
[59]
Name=Altar of Storm
Requirement1=110
Requirement2=52
Replaces=52
Upkeep=10
Cost=600
X=3
Y=3
Vizier=55
VizierMilitary=77
AnimationFrames=8
Tree=1
[60]
Name=Ludus Agoge
Requirement1=104
Requirement2=7
Replaces=7
Upkeep=20
Cost=1200
X=3
Y=3
Vizier=55
VizierMilitary=77
AnimationFrames=0
AIBuyPrio=2
Tree=1
[61]
Name=Altar of the Sun
Requirement1=102
Requirement2=52
Replaces=52
Upkeep=10
Cost=600
X=3
Y=3
Vizier=55
VizierMilitary=77
AnimationFrames=8
AIBuyPrio=6
Tree=1
[62]
Name=Altar of the Moon
Requirement1=103
Requirement2=52
Replaces=52
Upkeep=10
Cost=600
X=3
Y=3
Vizier=55
VizierMilitary=77
AnimationFrames=8
AIBuyPrio=2
Tree=1
[63]
Name=Frost Club Hall
Requirement1=105
Requirement2=44
Replaces=44
Upkeep=10
Cost=600
X=3
Y=2
Vizier=55
VizierMilitary=77
AnimationFrames=5
AIBuyPrio=4
Tree=1
[64]
Name=Sancta Basilica
Requirement1=104
Requirement2=25
Replaces=24
Upkeep=20
Cost=2400
X=3
Y=3
Vizier=55
VizierMilitary=77
AnimationFrames=0
AIBuyPrio=2
Tree=1
[65]
Name=Mother Fungus
Requirement1=103
Requirement2=52
Replaces=52
Upkeep=10
Cost=1200
X=2
Y=2
Vizier=55
VizierMilitary=77
AnimationFrames=0
ScoutingRange=10
AIBuyPrio=4
Tree=1
[66]
; placing by script to limit roster scope of goblins 
Name=Trickster Mycelium
Requirement1=66
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
ScoutingRange=0
AIBuyPrio=0
Tree=0
[67]
; placing by script to limit roster scope of goblins 
Name=Rabblerouser Mycelium
Requirement1=67
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
ScoutingRange=0
AIBuyPrio=0
Tree=0
[68]
; placing by script to limit roster scope of goblins 
Name=Hexer Mycelium
Requirement1=68
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
ScoutingRange=0
AIBuyPrio=0
Tree=0
[69]
; placing by script to limit roster scope of goblins 
Name=Arsonist Mycelium
Requirement1=69
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
ScoutingRange=0
AIBuyPrio=0
Tree=0
[70]
; placing by script to limit roster scope of goblins 
Name=Night Goblin Mycelium
Requirement1=70
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
ScoutingRange=0
AIBuyPrio=0
Tree=0
[71]
; placing by script to limit roster scope of goblins 
Name=Mechaniac Mycelium
Requirement1=71
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
ScoutingRange=0
AIBuyPrio=0
Tree=0
[72]
; placing by script to limit roster scope of goblins 
Name=Poxbearer Mycelium
Requirement1=72
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
ScoutingRange=0
AIBuyPrio=0
Tree=0
[73]
; no longer use, glider already limit by Hangar 
Name=Glider Mycelium
Requirement1=73
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
ScoutingRange=0
AIBuyPrio=0
Tree=0
[74]
; placing by script to limit roster scope of goblins 
Name=Spider Rider Mycelium
Requirement1=74
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
ScoutingRange=0
AIBuyPrio=0
Tree=0
