[1]
Name=Ritual Master
Help=Ritual master
HelpIcon=62
; Amount gained per level equals Bonus/BonusDiv rounded down.
Bonus=6
BonusDivisor=1
; Which hero class can obtain this ability as a random ability? (In case of dual class, both are required)
; 0 - Warrior
; 1 - Mage
; 2 - Leader
; 3 - Warrior and Leader
; 4 - Mage Leader
; 5 - Warrior Mage
; 6 - No requirement (could be using by any class)
; 7 - Restricted (only hero class 6 (unspecialized) able to gain these abilities at random)
Class=1
Super=Yes
Levelscale=Yes
; Earliest turn when a vial of this ability can be found in treasure
VialMin=-50
; Latest turn when a vial of this ability can be found in treasure
VialMax=9999
[2]
Name=AEther Master
Help=AEther master
HelpIcon=63
Bonus=8
BonusDivisor=1
Class=1
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[3]
Name=Capacity
Help=Capacity
HelpIcon=139
Bonus=1
BonusDivisor=2
Class=6
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[4]
Name=Divine Barrier
Help=Divine barrier
HelpIcon=14
Bonus=1
BonusDivisor=3
Class=4
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[5]
Name=Guiding Beacon
Help=Guiding beacon
HelpIcon=87
Bonus=1
BonusDivisor=3
Class=4
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[6]
Name=Soul Linker
Help=Soul linker
HelpIcon=141
Bonus=5
BonusDivisor=2
Class=4
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[7]
Name=Supply Commander
Help=Supply commander
HelpIcon=112
Bonus=0
BonusDivisor=1
Class=2
Super=No
Levelscale=No
VialMin=-50
VialMax=9999
[8]
Name=Logistics
Help=Logistics
HelpIcon=118
Bonus=1
BonusDivisor=2
Class=3
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[9]
Name=Battlemage
Help=Battlemage
HelpIcon=109
Bonus=1
BonusDivisor=1
Class=5
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[10]
Name=Agility
Help=Agility
HelpIcon=140
Bonus=1
BonusDivisor=1
Class=0
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[11]
Name=Arcane Power
Help=Arcane power
HelpIcon=51
Bonus=1
BonusDivisor=1
Class=1
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[12]
Name=Armsmaster
Help=Armsmaster
HelpIcon=45
Bonus=2
BonusDivisor=1
Class=2
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[13]
Name=Blademaster
Help=Blademaster
HelpIcon=46
Bonus=10
BonusDivisor=3
Class=0
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[14]
Name=Charmed
Help=Charmed
HelpIcon=56
Bonus=0
BonusDivisor=1
Class=6
Super=No
Levelscale=No
VialMin=-50
VialMax=9999
[15]
Name=Constitution
Help=Constitution
HelpIcon=49
Bonus=1
BonusDivisor=1
Class=0
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[16]
Name=Leadership
Help=Leadership
HelpIcon=43
Bonus=1
BonusDivisor=3
Class=3
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[17]
Name=Legendary
Help=Legendary
HelpIcon=44
Bonus=5
BonusDivisor=1
Class=6
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[18]
Name=Lucky
Help=Lucky
HelpIcon=55
Bonus=0
BonusDivisor=1
Class=6
Super=No
Levelscale=No
VialMin=-50
VialMax=9999
[19]
Name=Might
Help=Might
HelpIcon=50
Bonus=1
BonusDivisor=1
Class=0
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[20]
Name=Noble
Help=Noble
HelpIcon=57
Bonus=0
BonusDivisor=1
Class=6
Super=No
Levelscale=No
VialMin=-50
VialMax=120
[21]
Name=Prayermaster
Help=Prayermaster
HelpIcon=54
Bonus=1
BonusDivisor=2
Class=4
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[22]
Name=Sage
Help=Sage
HelpIcon=58
Bonus=10
BonusDivisor=1
Class=1
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[23]
; Special entry: EXTRA MP ability rolls. Only the "Bonus" lines are used.
Name=Caster
Help=Caster
Bonus=2
BonusDivisor=1
HelpIcon=0
Class=6
Super=No
Levelscale=Yes
VialMin=-50
VialMax=9999
[24]
Name=Powershot
Help=Powershot
HelpIcon=175
Bonus=1
BonusDivisor=1
Class=6
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[25]
Name=Rampage
Help=Rampage
HelpIcon=319
Bonus=2
BonusDivisor=1
Class=0
Super=Yes
Levelscale=No
VialMin=180
VialMax=9999
[26]
Name=Chosen of Gaia
Help=Chosen of Gaia
HelpIcon=330
Bonus=3
BonusDivisor=1
Class=7
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[27]
Name=Chosen of AEther
Help=Chosen of AEther
HelpIcon=331
Bonus=3
BonusDivisor=1
Class=7
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[28]
Name=Chosen of Chaos
Help=Chosen of Chaos
HelpIcon=332
Bonus=3
BonusDivisor=1
Class=7
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[29]
Name=Chosen of Life
Help=Chosen of Life
HelpIcon=333
Bonus=3
BonusDivisor=1
Class=7
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[30]
Name=Chosen of Death
Help=Chosen of Death
HelpIcon=334
Bonus=3
BonusDivisor=1
Class=7
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[31]
Name=Mechanical Master
Help=Mechanical Master
HelpIcon=335
Bonus=2
BonusDivisor=1
Class=4
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[32]
Name=Elemental Master
Help=Elemental Master
HelpIcon=336
Bonus=2
BonusDivisor=1
Class=4
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[33]
Name=Irresistible Charge
Help=Irresistible Charge
HelpIcon=337
Bonus=1
BonusDivisor=1
Class=3
Super=Yes
Levelscale=No
VialMin=-50
VialMax=9999
[34]
Name=Righteous Ward
Help=Righteous Ward
HelpIcon=370
Bonus=1
BonusDivisor=1
Class=7
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[35]
Name=Arcane Ward
Help=Arcane Ward
HelpIcon=371
Bonus=1
BonusDivisor=1
Class=7
Super=Yes
Levelscale=Yes
VialMin=-50
VialMax=9999
[36]
Name=Chaos Boon
Help=Chaos Boon
HelpIcon=372
Bonus=1
BonusDivisor=1
Class=7
Super=No
Levelscale=Yes
VialMin=-50
VialMax=9999
[37]
Name=Death Ascension
Help=Death Ascension
HelpIcon=373
Bonus=1
BonusDivisor=1
Class=7
Super=No
Levelscale=Yes
VialMin=-50
VialMax=9999
; Test Data
; [25]
; Name=Ninjutsu
; Help=Ninjutsu
; HelpIcon=63
; Bonus=5
; BonusDivisor=1
; Class=1
; Super=Yes
; Levelscale=Yes
; VialMin=0
; VialMax=9999
