[1]
; Brax the Master Engineer, nolonger melee hero but utility hero instead
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=3
; 0 - Warrior
; 1 - Mage
; 2 - Leader
; 3 - Warrior and Leader
; 4 - Mage Leader
; 5 - Warrior Mage
; 6 - Unspecialized (could using all categories of Hero Ability, included category 7)
Prisonerturn=30
AIPreference=3
AIResurrectPreference=0
AIEquipOrder=0
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Logistics=1
Guiding Beacon=1
Supply Commander=1
Mechanical Master=2
RequiredRealm=0
[2]
; Gunther the Berserker
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=0
Prisonerturn=0
AIPreference=1
AIResurrectPreference=1
AIEquipOrder=5
EquipSlot1=1
EquipSlot2=1
EquipSlot3=5
Might=1
Constitution=1
Rampage=2
RequiredRealm=0
[3]
; Zaldron the Sage
Spell1=52
Spell2=50
Spell3=45
Spell4=0
HeroMPPerLevel=7
HeroStartingMP=5
HeroRandomAbilities=0
HeroClass=1
Prisonerturn=0
AIPreference=4
AIResurrectPreference=0
AIEquipOrder=77
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Sage=2
RequiredRealm=0
[4]
; B'Shan the Dervish
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=3
Prisonerturn=0
AIPreference=2
AIResurrectPreference=0
AIEquipOrder=1
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Noble=1
Prayermaster=1
RequiredRealm=0
[5]
; Rakir the Beastmaster, fame and prisoner turn change to 10 due to how strong he is
; Beastmaster could nolonger able to equipped armor, armor slot change to accessory slot
; Beastmaster loses Soul Linker but gains Chosen of Gaia and now also requires Nature Book
Spell1=2
Spell2=4
Spell3=0
Spell4=0
HeroMPPerLevel=4
HeroStartingMP=6
HeroRandomAbilities=1
HeroClass=4
Prisonerturn=10
AIPreference=6
AIResurrectPreference=3
AIEquipOrder=95
EquipSlot1=2
EquipSlot2=5
EquipSlot3=5
Chosen of Gaia=1
RequiredRealm=1
[6]
; Valana the Bard
; Bard could nolonger able to equipped armor, armor slot change to accessory slot
Spell1=46
Spell2=53
Spell3=0
Spell4=0
HeroMPPerLevel=3
HeroStartingMP=10
HeroRandomAbilities=0
HeroClass=3
Prisonerturn=0
AIPreference=3
AIResurrectPreference=1
AIEquipOrder=7
EquipSlot1=1
EquipSlot2=5
EquipSlot3=5
Leadership=1
RequiredRealm=0
[7]
; Baghtru the Centurion, nolonger archer and now emphasis on commanding skills
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=3
Prisonerturn=10
AIPreference=3
AIResurrectPreference=0
AIEquipOrder=3
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Leadership=1
Supply Commander=1
Guiding Beacon=1
RequiredRealm=0
[8]
; Serena the Healer
; Healer could nolonger able to equipped armor, armor slot change to accessory slot
Spell1=2
Spell2=41
Spell3=125
Spell4=149
HeroMPPerLevel=5
HeroStartingMP=10
HeroRandomAbilities=1
HeroClass=4
Prisonerturn=0
AIPreference=3
AIResurrectPreference=2
AIEquipOrder=7
EquipSlot1=3
EquipSlot2=5
EquipSlot3=5
RequiredRealm=0
[9]
; Shuri the Huntress
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=1
HeroClass=3
Prisonerturn=0
AIPreference=1
AIResurrectPreference=0
AIEquipOrder=2
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Blademaster=1
Powershot=1
RequiredRealm=0
[10]
; Theria the Thief
; Thief could nolonger able to equipped armor, armor slot change to accessory slot
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=0
Prisonerturn=60
AIPreference=4
AIResurrectPreference=3
AIEquipOrder=14
EquipSlot1=1
EquipSlot2=5
EquipSlot3=5
Charmed=1
Lucky=1
Agility=1
RequiredRealm=0
[11]
; Greyfairer the Druid
Spell1=13
Spell2=22
Spell3=5
Spell4=12
HeroMPPerLevel=5
HeroStartingMP=5
HeroRandomAbilities=0
HeroClass=1
Prisonerturn=10
AIPreference=2
AIResurrectPreference=0
AIEquipOrder=4
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Ritual Master=1
RequiredRealm=0
[12]
; Taki the War Monk, could nolonger able to equipped weapon
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=0
Prisonerturn=50
AIPreference=4
AIResurrectPreference=1
AIEquipOrder=80
EquipSlot1=6
EquipSlot2=5
EquipSlot3=5
Agility=2
RequiredRealm=0
[13]
; Reywind the Warrior Mage
Spell1=5
Spell2=56
Spell3=90
Spell4=165
HeroMPPerLevel=6
HeroStartingMP=7
HeroRandomAbilities=1
HeroClass=5
Prisonerturn=35
AIPreference=3
AIResurrectPreference=0
AIEquipOrder=8
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
Battlemage=1
Agility=1
RequiredRealm=0
[14]
; Malleus the Magician
Spell1=83
Spell2=96
Spell3=90
Spell4=109
HeroMPPerLevel=6
HeroStartingMP=24
HeroRandomAbilities=1
HeroClass=1
Prisonerturn=20
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=78
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Arcane Power=1
Elemental Master=1
RequiredRealm=0
[15]
; Tumu the Assassin
; Assassin could nolonger able to equipped armor, armor slot change to accessory slot
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=18
HeroRandomAbilities=1
HeroClass=0
Prisonerturn=10
AIPreference=4
AIResurrectPreference=1
AIEquipOrder=12
EquipSlot1=1
EquipSlot2=5
EquipSlot3=5
Blademaster=2
RequiredRealm=0
[16]
; Jaer the Wind Mage
Spell1=41
Spell2=44
Spell3=0
Spell4=0
HeroMPPerLevel=5
HeroStartingMP=9
HeroRandomAbilities=1
HeroClass=4
Prisonerturn=0
AIPreference=5
AIResurrectPreference=1
AIEquipOrder=10
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Guiding Beacon=1
RequiredRealm=0
[17]
; Marcus the Ranger, starting MP reduce by 5
Spell1=2
Spell2=7
Spell3=0
Spell4=0
HeroMPPerLevel=2
HeroStartingMP=10
HeroRandomAbilities=2
HeroClass=5
Prisonerturn=30
AIPreference=3
AIResurrectPreference=1
AIEquipOrder=9
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Lucky=1
RequiredRealm=0
[18]
; Fang the Draconian, loses 1 random ability due to base stat is high
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=1
HeroClass=0
Prisonerturn=30
AIPreference=5
AIResurrectPreference=3
AIEquipOrder=13
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Might=1
RequiredRealm=0
[19]
; Morgana the Witch, gain +1 MP per level
Spell1=169
Spell2=170
Spell3=172
Spell4=174
HeroMPPerLevel=6
HeroStartingMP=15
HeroRandomAbilities=2
HeroClass=1
Prisonerturn=20
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=79
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Charmed=1
RequiredRealm=0
[20]
; Jin Zhong the Bronze sentinel, could nolonger able to equipped weapon
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=5
HeroStartingMP=10
HeroRandomAbilities=0
HeroClass=5
Prisonerturn=30
AIPreference=4
AIResurrectPreference=2
AIEquipOrder=11
EquipSlot1=6
EquipSlot2=5
EquipSlot3=5
Noble=1
Agility=1
Constitution=1
Arcane Ward=1
RequiredRealm=0
[21]
; Shin Bo the Ninja, gain stealth
; Ninja could nolonger able to equipped armor, armor slot change to accessory slot
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=3
HeroClass=3
Prisonerturn=99
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=16
EquipSlot1=1
EquipSlot2=5
EquipSlot3=5
Blademaster=1
RequiredRealm=0
[22]
; Spyder the Rogue
; Rogue could nolonger able to equipped armor, armor slot change to accessory slot
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=1
HeroClass=2
Prisonerturn=0
AIPreference=2
AIResurrectPreference=0
AIEquipOrder=5
EquipSlot1=1
EquipSlot2=5
EquipSlot3=5
Leadership=1
Legendary=2
RequiredRealm=0
[23]
; Shalla the Amazon, gain more combat skill and emphasis on her role as duelist even more
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=0
Prisonerturn=35
AIPreference=5
AIResurrectPreference=3
AIEquipOrder=15
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Blademaster=1
Constitution=1
Might=1
Charmed=1
RequiredRealm=0
[24]
; Yramrag the Warlock
Spell1=91
Spell2=101
Spell3=104
Spell4=0
HeroMPPerLevel=8
HeroStartingMP=18
HeroRandomAbilities=2
HeroClass=1
Prisonerturn=30
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=76
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Arcane Power=2
RequiredRealm=0
[25]
; Mystic X the Unknown
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=6
HeroStartingMP=9
HeroRandomAbilities=5
HeroClass=6
Prisonerturn=40
AIPreference=4
AIResurrectPreference=2
AIEquipOrder=17
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
RequiredRealm=0
[26]
; Aerie the Illusionist
Spell1=45
Spell2=46
Spell3=67
Spell4=0
HeroMPPerLevel=14
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=1
Prisonerturn=35
AIPreference=8
AIResurrectPreference=4
AIEquipOrder=90
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
RequiredRealm=0
[27]
; Deth Stryke the Swordsman
; Swordsman could nolonger able to equipped accessory, accessory slot change to weapon slot
Spell1=125
Spell2=137
Spell3=0
Spell4=0
HeroMPPerLevel=5
HeroStartingMP=5
HeroRandomAbilities=2
HeroClass=0
Prisonerturn=150
AIPreference=6
AIResurrectPreference=4
AIEquipOrder=84
EquipSlot1=1
EquipSlot2=1
EquipSlot3=6
Blademaster=1
Constitution=1
Agility=1
Armsmaster=1
RequiredRealm=0
[28]
; Elana the Priestess
; The Priestess gains Chosen of Life and now requires Life book
Spell1=134
Spell2=125
Spell3=140
Spell4=150
HeroMPPerLevel=8
HeroStartingMP=16
HeroRandomAbilities=0
HeroClass=4
Prisonerturn=120
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=83
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Divine Barrier=1
Charmed=1
Noble=1
Prayermaster=2
Chosen of Life=1
RequiredRealm=4
[29]
; Roland the Paladin
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=3
Prisonerturn=150
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=81
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Legendary=1
Might=1
Prayermaster=1
Irresistible Charge=1
Righteous Ward=1
RequiredRealm=0
[30]
; Mortu the Black Knight
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=0
Prisonerturn=150
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=82
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Legendary=1
Might=1
Blademaster=1
Constitution=1
Rampage=1
Death Ascension=1
RequiredRealm=0
[31]
; Alorra the Arcane Archer
Spell1=21
Spell2=56
Spell3=68
Spell4=0
HeroMPPerLevel=7
HeroStartingMP=8
HeroRandomAbilities=4
HeroClass=5
Prisonerturn=100
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=20
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Blademaster=1
Capacity=2
RequiredRealm=0
[32]
; Sir Harold the Knight
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=3
Prisonerturn=130
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=6
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Leadership=2
Constitution=2
Noble=1
Armsmaster=2
Logistics=1
Irresistible Charge=2
RequiredRealm=0
[33]
; Ravashack the Necromancer
; The Necromancer loses Soul Linker but gains Chosen of Death and now requires Death book
Spell1=163
Spell2=165
Spell3=195
Spell4=182
HeroMPPerLevel=10
HeroStartingMP=10
HeroRandomAbilities=1
HeroClass=4
Prisonerturn=120
AIPreference=8
AIResurrectPreference=5
AIEquipOrder=100
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Arcane Power=2
Sage=2
Chosen of Death=1
Ritual Master=1
RequiredRealm=5
[34]
; Warrax the Everchosen
; The Everchosen gains Chosen of Chaos and requires Chaos book
Spell1=81
Spell2=89
Spell3=274
Spell4=117
HeroMPPerLevel=7
HeroStartingMP=5
HeroRandomAbilities=1
HeroClass=5
Prisonerturn=100
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=85
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
Constitution=1
Arcane Power=1
Chosen of Chaos=1
Chaos Boon=1
RequiredRealm=3
[35]
; Torin the Avatar
; The Avatar gains Chosen of Life (super)
Spell1=149
Spell2=125
Spell3=124
Spell4=141
HeroMPPerLevel=5
HeroStartingMP=10
HeroRandomAbilities=0
HeroClass=3
Prisonerturn=0
AIPreference=8
AIResurrectPreference=0
AIEquipOrder=82
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
Leadership=1
Constitution=1
Battlemage=2
Prayermaster=1
Guiding Beacon=1
Divine Barrier=1
Might=2
Chosen of Life=2
Righteous Ward=2
RequiredRealm=4
[36]
; Golz the Warmaster
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=1
HeroClass=3
Prisonerturn=110
AIPreference=6
AIResurrectPreference=1
AIEquipOrder=80
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Agility=2
Might=2
Leadership=2
Rampage=1
Irresistible Charge=1
RequiredRealm=0
[37]
; Tobias the Gambler
; Gambler could nolonger able to equipped armor, armor slot change to accessory slot
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=2
Prisonerturn=80
AIPreference=4
AIResurrectPreference=1
AIEquipOrder=80
EquipSlot1=1
EquipSlot2=5
EquipSlot3=5
Charmed=1
Lucky=1
RequiredRealm=0
[38]
; Gwyndolyn the Dreamwalker
Spell1=165
Spell2=255
Spell3=50
Spell4=60
HeroMPPerLevel=6
HeroStartingMP=20
HeroRandomAbilities=3
HeroClass=1
Prisonerturn=150
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=83
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Arcane Power=1
Agility=1
RequiredRealm=0
[39]
; Ludde the Steelbreaker
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=0
Prisonerturn=20
AIPreference=2
AIResurrectPreference=1
AIEquipOrder=80
EquipSlot1=1
EquipSlot2=1
EquipSlot3=6
Constitution=2
RequiredRealm=0
[40]
; Ambrose the Grand Inquisitor
Spell1=131
Spell2=150
Spell3=152
Spell4=239
HeroMPPerLevel=10
HeroStartingMP=10
HeroRandomAbilities=0
HeroClass=4
Prisonerturn=120
AIPreference=8
AIResurrectPreference=4
AIEquipOrder=83
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Divine Barrier=1
Noble=1
Prayermaster=2
Legendary=2
RequiredRealm=0
[41]
; Arachne the Crone
Spell1=167
Spell2=175
Spell3=177
Spell4=244
HeroMPPerLevel=10
HeroStartingMP=10
HeroRandomAbilities=0
HeroClass=1
Prisonerturn=200
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=83
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Arcane Power=1
Capacity=1
Soul Linker=2
RequiredRealm=0
[42]
; Chiron the Sagittarius
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=3
HeroClass=3
Prisonerturn=120
AIPreference=5
AIResurrectPreference=4
AIEquipOrder=83
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Powershot=1
Armsmaster=2
Irresistible Charge=1
RequiredRealm=0
[43]
; Himenoptera the Swarm Queen
Spell1=271
Spell2=130
Spell3=86
Spell4=244
HeroMPPerLevel=5
HeroStartingMP=15
HeroRandomAbilities=1
HeroClass=3
Prisonerturn=200
AIPreference=9
AIResurrectPreference=4
AIEquipOrder=97
EquipSlot1=6
EquipSlot2=5
EquipSlot3=5
Noble=1
Soul Linker=1
Divine Barrier=2
Prayermaster=1
Guiding Beacon=1
Supply Commander=1
Charmed=1
Battlemage=1
RequiredRealm=0
[44]
; Jaladhi the King of the Deep
Spell1=12
Spell2=46
Spell3=230
Spell4=247
HeroMPPerLevel=4
HeroStartingMP=12
HeroRandomAbilities=0
HeroClass=3
Prisonerturn=100
AIPreference=7
AIResurrectPreference=3
AIEquipOrder=94
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Soul Linker=1
Leadership=1
Constitution=1
Noble=1
Legendary=1
RequiredRealm=0
[45]
; Kulu the War Chief
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=3
Prisonerturn=80
AIPreference=7
AIResurrectPreference=2
AIEquipOrder=5
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Might=2
Constitution=2
Leadership=1
Armsmaster=1
RequiredRealm=0
[46]
; Arvad the Planewalker
; the Plane Walker gains Chosen of AEther but now requires Sorcery book
Spell1=168
Spell2=265
Spell3=273
Spell4=77
HeroMPPerLevel=9
HeroStartingMP=9
HeroRandomAbilities=0
HeroClass=4
Prisonerturn=120
AIPreference=6
AIResurrectPreference=3
AIEquipOrder=15
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Guiding Beacon=2
Logistics=2
Supply Commander=1
Agility=1
Chosen of AEther=1
RequiredRealm=2
[47]
; Etna the Elementalist
; Elementalist could nolonger able to equipped wand, wand slot change to accessory slot
Spell1=12
Spell2=30
Spell3=66
Spell4=90
HeroMPPerLevel=10
HeroStartingMP=20
HeroRandomAbilities=2
HeroClass=1
Prisonerturn=200
AIPreference=8
AIResurrectPreference=3
AIEquipOrder=76
EquipSlot1=5
EquipSlot2=5
EquipSlot3=5
Arcane Power=1
Capacity=2
Ritual Master=1
Elemental Master=2
Charmed=1
RequiredRealm=0
[48]
; the Wanderer, puppet of the Channeler wizard.
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=6
Prisonerturn=999
AIPreference=0
AIResurrectPreference=5
AIEquipOrder=99
EquipSlot1=3
EquipSlot2=5
EquipSlot3=5
RequiredRealm=0

