; Individual hero names
[0]
; The Master Engineer
Name1=Brax
Name2=Dolgin
Name3=Gloinn
Name4=Yngvi
Name5=Flynn
Name6=Fafnir
Name7=Sindre
Name8=Durinn
Name9=Otr
Name10=Dvalinn
Name11=Grimr
Name12=Kili
Name13=Ori
Name14=Vegdrasill
[1]
; The Berserker
Name1=Gunther
Name2=Wolfar
Name3=Angus
Name4=Fritz
Name5=Brennus
Name6=Kurt
Name7=Gunnar
Name8=Hartwig
Name9=Igor
Name10=Conor
Name11=Klaus
Name12=Hans
Name13=Morgen
Name14=Arwald
[2]
; The Sage
Name1=Zaldron
Name2=Jesrael
Name3=Sardon
Name4=Tiberius
Name5=Zorin
Name6=Zabrim
Name7=Eratosthenes
Name8=Zeno
Name9=Gautama
Name10=Isidore
Name11=Sardor
Name12=Sargon
Name13=Kidinnu
Name14=Zoltan
[3]
Name1=B'Shan
Name2=Abdul
Name3=Shaza
Name4=Fazeel
Name5=Wizier
Name6=Attar
Name7=Hamza
Name8=Jabir
Name9=Armin
Name10=Aziz
Name11=Hodja
Name12=Faruk
Name13=Said
Name14=Tariq
[4]
; The Beastmaster
Name1=Rakir
Name2=Salkirg
Name3=Wyn
Name4=Reya
Name5=Fleir
Name6=Tvar
Name7=Gaynar
Name8=Smiargon
Name9=Yrkon
Name10=Moongum
Name11=Jangren
Name12=Airir
Name13=Ailean
Name14=Duncan
[5]
; The Bard
Name1=Valana
Name2=Lauren
Name3=Lidia
Name4=Veronica
Name5=Adrianna
Name6=Mischa
Name7=Lou
Name8=Tanja
Name9=Aischa
Name10=Amy
Name11=Cantora
Name12=Grissel
Name13=Skalda
Name14=Matilda
[6]
; The Centurion
Name1=Baghtru
Name2=Erdem
Name3=Oguz
Name4=Maktu
Name5=Orgaak
Name6=Bahadir
Name7=Denk
Name8=Bozkurt
Name9=Deniz
Name10=Belgutei
Name11=Kartal
Name12=Qasar
Name13=Bilge
Name14=Berk
[7]
; The Healer
Name1=Serena
Name2=Shardis
Name3=Sasha
Name4=Karla
Name5=Anastasia
Name6=Theresa
Name7=Celestria
Name8=Althea
Name9=Brigid
Name10=Shaushka
Name11=Alyona
Name12=Ester
Name13=Yulia
Name14=Minerva
[8]
; The Huntress
Name1=Shuri
Name2=Artemis
Name3=Shanna
Name4=Umalla
Name5=Farra
Name6=Devana
Name7=Feronia
Name8=Skadi
Name9=Yuna
Name10=Devana
Name11=Bendis
Name12=Atlantina
Name13=Cyrene
Name14=Fianna
[9]
Name1=Theria
Name2=Shadow
Name3=Misty
Name4=Doria
Name5=Tamara
Name6=Arachne
Name7=Hannah
Name8=Eris
Name9=Faye
Name10=Naria
Name11=Trixie
Name12=Sarka
Name13=Ruse
Name14=Ruby
[10]
; The Druid
Name1=Greyfairer
Name2=Tholin
Name3=Llywarch
Name4=Zalmoxis
Name5=Feylass
Name6=Cathbad
Name7=Amergin
Name8=Tadg
Name9=Mug Ruith
Name10=Divikiakos
Name11=Gwenc'hlan
Name12=Aneirin
Name13=Taliesin
Name14=Kian
[11]
; the War Monk
Name1=Taki
Name2=Quai
Name3=Chang
Name4=Tonaga
Name5=Dao
Name6=Benkei
Name7=Gochiin
Name8=Inei
Name9=Ichirai
Name10=Tsutsui
Name11=Kosa
Name12=Rennyo
Name13=Sessai
Name14=Hyujeong
[12]
; The Warrior Mage
Name1=Reywind
Name2=Stalkaor
Name3=Darius
Name4=Wylas
Name5=Deamond
Name6=Gilmore
Name7=Desmond
Name8=Darian
Name9=Baksis
Name10=Milad
Name11=Norul
Name12=Safan
Name13=Merewald
Name14=Oswin
[13]
; The Magician
Name1=Malleus
Name2=Delian
Name3=Furius
Name4=Karnak
Name5=Landreux
Name6=Brantley
Name7=Cyrus
Name8=Aidan
Name9=Kiran
Name10=Blaise
Name11=Ignatius
Name12=Kenneth
Name13=Aarush
Name13=Uri
Name14=Ignacio
[14]
; The Assassin
Name1=Tumu
Name2=Altahza
Name3=Shaka
Name4=Huracus
Name5=Kaizlar
Name6=Tumo
Name7=Talib
Name8=Sadik
Name9=Obi
Name10=Rafiki
Name11=Hassan
Name12=Siman
Name13=Kafu
Name14=Nisr
[15]
; The Wind Mage
Name1=Jaer
Name2=Graydon
Name3=Aquilon
Name4=Shadowin
Name5=Arcus
Name6=Jael
Name7=Jarlath
Name8=Graham
Name9=Flint
Name10=Favonius
Name11=Brendon
Name12=Elton
Name13=Garrik
Name14=Nodin
[16]
; The Ranger
Name1=Marcus
Name2=Cassius
Name3=Tantris
Name4=Waylish
Name5=Wolf
Name6=Strider
Name7=Aloysius
Name8=Androcles
Name9=Borys
Name10=Valdus
Name11=Titus
Name12=Silvius
Name13=Rufus
Name14=Remus
[17]
; The Draconian
Name1=Fang
Name2=Dreadwing
Name3=Draka
Name4=Druel
Name5=Hiss
Name6=Plon
Name7=Draco
Name8=Ormr
Name9=Zmaj
Name10=Lohe
Name11=Drach
Name12=Azi
Name13=Glaufang
Name14=Smoke
[18]
; The Witch
Name1=Morgana
Name2=Tabatha
Name3=Karlota
Name4=Elicia
Name5=Cassandra
Name6=Astarte
Name7=Bellatrix
Name8=Hecate
Name9=Desdemona
Name10=Medea
Name11=Lucinda
Name12=Esmeralda
Name13=Aradia
Name14=Vivien
[19]
; The Bronze Sentinel
Name1=Jinzhong
Name2=Orlo
Name3=Metallis
Name4=Sheenar
Name5=Balzius
Name6=Aurelius
Name7=Bazi
Name8=Midas
Name9=Abriz
Name10=Kim
Name11=Flavius
Name12=Orlando
Name13=Talos
Name14=Zlatan
[20]
; The Ninja
Name1=Shin Bo
Name2=Omi
Name3=Mongo
Name4=Reyon
Name5=Dakan
Name6=Sasuke
Name7=Fuma
Name8=Hanzo
Name9=Danzo
Name10=Saizo
Name11=Doshun
Name12=Raikei
Name13=Jiraiya
Name14=Kozo
[21]
; The Rogue
Name1=Spyder
Name2=Jester
Name3=Marco
Name4=Dupre
Name5=Eroll
Name6=Anwir
Name7=Buster
Name8=Wily
Name9=Dion
Name10=Fox
Name11=Nestor
Name12=Peter
Name13=Robin
Name14=Sly
[22]
; The Amazon
Name1=Shalla
Name2=Diana
Name3=Lana
Name4=Delilah
Name5=Sonja
Name6=Helga
Name7=Lagertha
Name9=Tomyris
Name10=Arite
Name11=Thalestris
Name12=Amage
Name13=Scathach
Name14=Zarinaya
[23]
; The Warlock
Name1=Yramrag
Name2=Grofzinar
Name3=Malefix
Name4=Farad
Name5=Solnar
Name6=Pailan
Name7=Hadad
Name8=Saar
Name9=Taranis
Name10=Abigar
Name11=Ukko
Name12=Styrmir
Name13=Zyran
Name14=Barak
[24]
; The Unknown
Name1=Mystic X
Name2=Nymos
Name3=Morphis
Name4=Guy
Name5=Misterio
Name6=Bevardis
Name7=Wuming
Name8=Numerius
Name9=Hombre
Name10=Nescio
Name11=Aulus
Name12=Majhul
Name13=Nimeton
Name14=Isimsiz
[25]
Name1=Aerie
Name2=Stella
Name3=Miranda
Name4=Windaria
Name5=Mira
Name6=Glinda
Name7=Maya
Name8=Aleah
Name9=Arien
Name10=Azora
Name11=Phoebe
Name12=Samantha
Name13=Amelia
Name14=Xoara
[26]
; The Swordsman
Name1=Deth Stryke
Name2=Aleron
Name3=Destin
Name4=Nicholas
Name5=Walter
Name6=Ladislau
Name7=Dragomir
Name8=Gore
Name9=Wilhelm
Name10=Owain
Name11=Eugen
Name12=Infestus
Name13=Anvil
Name14=Vegetius
[27]
; The Priestess
Name1=Elana
Name2=Victoria
Name3=Aphena
Name4=Helena
Name5=Justine
Name6=Evelina
Name7=Cosima
Name8=Indira
Name9=Amara
Name10=Almina
Name11=Maliha
Name12=Anwen
Name13=Galatea
Name14=Irene
[28]
; The Paladin
Name1=Roland
Name2=Charles
Name3=Fairley
Name4=Cecil
Name5=Andreas
Name6=Astolpho
Name7=Olivier
Name8=Ogier
Name9=Renaud
Name10=Maugris
Name11=Naimon
Name12=Otuel
Name13=Fierabras
Name14=Percival
[29]
Name1=Mortu
Name2=Blake
Name3=Marek
Name4=Kane
Name5=Garrock
Name6=Hector
Name7=Mordred
Name8=Vytis
Name9=Kazimir
Name10=Dracul
Name11=Zawisza
Name12=Tristan
Name13=Cadogan
Name14=Morien
[30]
; The Arcane Archer
Name1=Alorra
Name2=Gwendolyn
Name3=Darlona
Name4=Demeta
Name5=Lita
Name6=Elwyn
Name7=Gwyneth
Name8=Eluned
Name9=Alwena
Name10=Beccah
Name11=Ceridwen
Name12=Morwen
Name13=Alwina
Name14=Blodwen
[31]
; The Knight
Name1=Sir Harold
Name2=Sir Henry
Name3=Sir Stephan
Name4=Sir Sheldon
Name5=Sir Thomas
Name6=Sir Osenain
Name7=Sir Lionel
Name8=Sir Ector
Name9=Sir Gawain
Name10=Sir William
Name11=Don Rodrigo
Name12=Sir Lanval
Name13=Sir Edward
Name14=Sir Lancelot
[32]
; The Necromancer
Name1=Ravashack
Name2=Exu
Name3=Thanatos
Name4=Lazarus
Name5=Maweth
Name6=Samedi
Name7=Astaroth
Name8=Morte
Name9=Orpheus
Name10=Lestat
Name11=Narlok
Name12=Jarlath
Name13=Ankou
Name14=Aralez
[33]
; The Everchosen
Name1=Warrax
Name2=Kolimak
Name3=Harlak
Name4=Abeloth
Name5=Brabax
Name6=Sopdu
Name7=Falak
Name8=Boryet
Name9=Bandus
Name10=Hadur
Name11=Ogun
Name12=Gurzil
Name13=Nergal
Name14=Maahes
[34]
; The Avatar
Name1=Torin
Name2=Azrael
Name3=Lawrence
Name4=Purseus
Name5=Heuron
Name6=Fionn
Name7=Ascelin
Name8=Amadeus
Name9=Davorin
Name10=Aigil
Name11=Mannus
Name12=Alexander
Name13=Vytautas
Name14=Bahram
[35]
; The Warmaster
Name1=Golz
Name2=Samo
Name3=Efim
Name4=Darijo
Name5=Arman
Name6=Goran
Name7=Branko
Name8=Duje
Name9=Grigor
Name10=Davor
Name11=Kesar
Name12=Marek
Name13=Roko
Name14=Jaka
[36]
; The Gambler
Name1=Tobias
Name2=Tychus
Name3=Felix
Name4=Benedict
Name5=Chance
Name6=Asher
Name7=Winifred
Name8=Septimus
Name9=Boone
Name10=Hazard
Name11=Edmund
Name12=Faust
Name13=Ace
Name14=Madoc
[37]
; The Dreamwalker
Name1=Gwyndolyn
Name2=Alys
Name3=Carys
Name4=Rhiannon
Name5=Eilonwy
Name6=Gorawen
Name7=Heledd
Name8=Arianwen
Name9=Megha
Name10=Bronwen
Name11=Deryn
Name12=Trina
Name13=Meredith
Name14=Vanora
[38]
; The Steelbreaker
Name1=Leppaludi
Name2=Giljagaur
Name3=Stufur
Name4=Oinn
Name5=Berling
Name6=Viggr
Name7=Dainn
Name8=Frar
Name9=Herraudr
Name10=Jari
Name11=Rekkr
Name12=Hugstari
Name13=Grer
Name14=Eggmoinn
[39]
; The Grand Inquisitor
Name1=Ambrose
Name2=Pedro
Name3=Arnaut
Name4=Nicolau
Name5=Heinrich
Name6=Konrad
Name7=Martin
Name8=Jacob
Name9=Hentenius
Name10=Tomas
Name11=Diego
Name12=Adrian
Name13=Andres
Name14=Vidal
[40]
; The Crone
Name1=Arachne
Name2=Elli
Name3=Yaga
Name4=Annis
Name5=Befana
Name6=Ambika
Name7=Beira
Name8=Erinyes
Name9=Holle
Name10=Ngame
Name11=Nehalennia
Name12=Sheela
Name13=Eileithyia
Name14=Orca
[41]
; The Sagittarius
Name1=Chiron
Name2=Agrius
Name3=Ophion
Name4=Pholus
Name5=Teleboas
Name6=Nessus
Name7=Mermerus
Name8=Lycus
Name9=Hylonome
Name10=Hippotion
Name11=Dictys
Name12=Bienor
Name13=Hippasus
Name14=Eurytus
[42]
; The Swarm Queen
Name1=Himenoptera
Name2=Debora
Name3=Jelissa
Name4=Apida
Name5=Bethylida
Name6=Vanessa
Name7=Tarala
Name8=Tyria
Name9=Mariposa
Name10=Mazarine
Name11=Antonia
Name12=Cersei
Name13=Arthrodite
Name14=Antnita
[43]
; The King of the Deep
Name1=Jaladhi
Name2=Magara
Name3=Ananda
Name4=Vasuki
Name5=Kaliya
Name6=Chandaka
Name7=Taksaka
Name8=Sagara
Name9=Rsika
Name10=Iravan
Name11=Gumum
Name12=Nanda
Name13=Abhoga
Name14=Sakha
[44]
; The War Chief
Name1=Kulu
Name2=Nkem
Name3=Shomari
Name4=Zabu
Name5=Issiaka
Name6=Linval
Name7=Asante
Name8=Jomo
Name9=Nnamdi
Name10=Seydouba
Name11=Buti
Name12=Kanye
Name13=Tichafa
Name14=Nonso
[45]
; The Planewalker
Name1=Arvad
Name2=Igashu
Name3=Bahis
Name4=Kevalin
Name5=Zulan
Name6=Mshai
Name7=Vettel
Name8=Faron
Name9=Abir
Name10=Dolen
Name11=Kymani
Name12=Wendel
Name13=Csaba
Name14=Pathik
[46]
; The Elementalist
Name1=Etna
Name2=Pele
Name3=Caldera
Name4=Maar
Name5=Somma
Name6=Hualca
Name7=Rinjani
Name8=Lanin
Name9=Erciyes
Name10=Juana
Name11=Mojanda
Name12=Solimana
Name13=Tacora
Name14=Sara
[47]
; The Marionette
Name1=Rikka
Name2=Tukkata
Name3=Antonette
Name4=Mary Ann
Name5=Bella
Name6=Apsara
Name7=Columbina
Name8=Lele
Name9=Monica
Name10=Bambola
Name11=Wawa
Name12=Nina
Name13=Dumya
Name14=Kukull
