; Highest supported ID is 100.
; Please be aware that 39 is reserved for system use and not available.
; StatIcon 1 is bow icon, 2 is rock icon, 3 is magic attack icon.
[10]
Image=5
StatIcon=2
Sound=15
[11]
Image=5
StatIcon=2
Sound=16
[12]
Image=13
StatIcon=2
Sound=15
[13]
Image=14
StatIcon=2
Sound=20
[14]
Image=15
StatIcon=2
Sound=13
[20]
Image=2
IsMissile=Yes
StatIcon=1
Sound=17
[21]
Image=6
IsMissile=Yes
StatIcon=4
Sound=18
[22]
Image=6
IsMissile=Yes
StatIcon=4
Sound=16
[30]
Image=1
IsMagic=Yes
StatIcon=3
Sound=19
[31]
Image=3
IsMagic=Yes
StatIcon=3
Sound=20
[32]
Image=4
IsMagic=Yes
StatIcon=3
Sound=21
[33]
Image=7
IsMagic=Yes
StatIcon=3
Sound=22
[34]
Image=8
IsMagic=Yes
StatIcon=3
Sound=23
[35]
Image=9
IsMagic=Yes
StatIcon=3
Sound=24
[36]
Image=10
IsMagic=Yes
StatIcon=3
Sound=25
[37]
Image=11
IsMagic=Yes
StatIcon=3
Sound=26
[38]
Image=12
IsMagic=Yes
StatIcon=3
Sound=23
[39]
; This ID can't be used!
[40]
Image=16
IsMagic=Yes
StatIcon=3
Sound=39
