[0]
MaxOptions=87
; first page
; <STARTING SITUATION>
DisplayOrder1=38
; Standardized
DisplayOrder2=22
; Order Please
DisplayOrder3=12
; Tree Mastery
DisplayOrder4=17
; Disconnected
DisplayOrder5=19
; Undeveloped Start
DisplayOrder6=18
; Plane of Earth
DisplayOrder7=9
; Plane of Water
DisplayOrder8=23
; I Am The Boss
DisplayOrder9=21
; Inverted Worlds
DisplayOrder10=24
; World Equalizer
DisplayOrder11=3
; Race to the Unknown
DisplayOrder12=4
; Banned Barbarians
DisplayOrder13=42
; Banned Gnolls
DisplayOrder14=43
; Banned Halflings
DisplayOrder15=44

; second page
; Banned High Elves
DisplayOrder16=45
; Banned High Men
DisplayOrder17=46
; Banned Klackons
DisplayOrder18=47
; Banned Lizardmen
DisplayOrder19=48
; Banned Nomads
DisplayOrder20=49
; Banned Orcs
DisplayOrder21=50
; Banned Hawkmen
DisplayOrder22=51
; Banned Beastmen
DisplayOrder23=52
; Banned Dark Elves
DisplayOrder24=53
; Banned Draconians
DisplayOrder25=54
; Banned Dwarves
DisplayOrder26=55
; Banned Trolls
DisplayOrder27=56
; Banned Xuanyuanese
DisplayOrder28=57
; Banned Rakhshasas
DisplayOrder29=58
; Banned Goblins
DisplayOrder30=59

; third page
; <ACCESSIBILITY OPTIONS>
DisplayOrder31=39
; Automatic Combat
DisplayOrder32=1
; Targeting Aid
DisplayOrder33=8
; Smart Familiar
DisplayOrder34=13
; Sandbox Mode
DisplayOrder35=11
; No Overlap
DisplayOrder36=15
; Leave me Alone
DisplayOrder37=10
; Corrupt Leaders
DisplayOrder38=26
; Everything Nice
DisplayOrder39=20
; Easy Lairs
DisplayOrder40=5
; Dumb Neutrals
DisplayOrder41=6
; Continental Lord
DisplayOrder42=16
; Absolute Fortress
DisplayOrder43=79
; Pleasantville
DisplayOrder44=62
; Zero Book Rule
DisplayOrder45=61

; fourth page
; <Fortress Options>
DisplayOrder46=63
; Fortress on the Hill
DisplayOrder47=64
; Mountain King
DisplayOrder48=65
; Mount Doom
DisplayOrder49=66
; Sand Pit
DisplayOrder50=67
; Everglade
DisplayOrder51=68
; Disney on Ice
DisplayOrder52=69
; Magic Garden
DisplayOrder53=70
; Adamantium Fortress
DisplayOrder54=32
; Orihalcon Fortress
DisplayOrder55=72
; Neo Venezia
DisplayOrder56=73
; Doomsday Bunker
DisplayOrder57=74
; Firework Factory
DisplayOrder58=75
; World Tree
DisplayOrder59=76
; Grand Bazaar
DisplayOrder60=77

; fifth page
; <ADVANCED OPTIONS>
DisplayOrder61=40
; More Than Retort
DisplayOrder62=80
; Desolated Outpost
DisplayOrder63=84
; Treasure Impact
DisplayOrder64=25
; Accelerated Race
DisplayOrder65=87
; Book Collectors
DisplayOrder66=30
; Minor Paranoia
DisplayOrder67=27
; Major Hostility
DisplayOrder68=28
; Against The Worlds
DisplayOrder69=2
; Monsters Gone Wild
DisplayOrder70=7
; Unstoppable Stampede
DisplayOrder71=31
; The Lord of the Magics
DisplayOrder72=86
; Return of the Master
DisplayOrder73=85
; Wizard of Oz
DisplayOrder74=82
; Among Us...
DisplayOrder75=83

; sixth page
; Cosmic Chessboard
DisplayOrder76=34
; Nodeborne Souls
DisplayOrder77=33
; Khan the Conqueror
DisplayOrder78=37
; Gods Play Dices
DisplayOrder79=36
; Uphill Battle
DisplayOrder80=35
; You Too, Orihalcon?
DisplayOrder81=78
; You Too, Adamantium?
DisplayOrder82=41
; Demon King's Castle
DisplayOrder83=71
; Post-catalysm
DisplayOrder84=60
; No Secret in Mastery
DisplayOrder85=81
; No Trading
DisplayOrder86=14
; Final War
DisplayOrder87=29


; It is possible to add a new score modifier with any effect, as long as there is
; a script file where the effect can be implemented. Use the SCORINGOPTION() function to check for the state of options.
; Please note the effect of several default modifiers is hardcoded and thus cannot be removed or replaced.
; Use "DisplayOrder" to move them to a different slot in the selection screen instead.
[1]
Name=Automatic Combat
ScoreMultiplier=100
[2]
Name=Against The Worlds
ScoreMultiplier=200
[3]
Name=World Equalizer
ScoreMultiplier=100
[4]
Name=Race to the Unknown
ScoreMultiplier=80
[5]
Name=Easy Lairs
ScoreMultiplier=90
[6]
Name=Dumb Neutrals
ScoreMultiplier=85
[7]
Name=Monsters Gone Wild
ScoreMultiplier=135
[8]
Name=Targeting Aid
ScoreMultiplier=95
[9]
Name=Plane of Earth
ScoreMultiplier=80
[10]
Name=Leave me Alone
ScoreMultiplier=75
[11]
Name=Sandbox Mode
ScoreMultiplier=50
[12]
Name=Order Please
ScoreMultiplier=100
[13]
Name=Smart Familiar
ScoreMultiplier=95
[14]
Name=No Trading
ScoreMultiplier=125
[15]
Name=No Overlap
ScoreMultiplier=70
[16]
Name=Continental Lord
ScoreMultiplier=85
[17]
Name=Tree Mastery
ScoreMultiplier=100
[18]
Name=Undeveloped Start
ScoreMultiplier=100
[19]
Name=Disconnected
ScoreMultiplier=95
[20]
Name=Everything Nice
ScoreMultiplier=90
[21]
Name=I Am The Boss
ScoreMultiplier=30
[22]
Name=Standardized
ScoreMultiplier=100
[23]
Name=Plane of Water
ScoreMultiplier=115
[24]
Name=Inverted Worlds
ScoreMultiplier=40
[25]
Name=Treasure Impact
ScoreMultiplier=75
[26]
Name=Corrupt Leaders
ScoreMultiplier=94
[27]
Name=Minor Paranoia
ScoreMultiplier=120
[28]
Name=Major Hostility
ScoreMultiplier=150
[29]
Name=Final War
ScoreMultiplier=150
[30]
Name=Book Collectors
ScoreMultiplier=75
[31]
Name=Unstoppable Stampede
ScoreMultiplier=125
[32]
Name=Adamantium Fortress
ScoreMultiplier=60
[33]
Name=Nodeborne Souls
ScoreMultiplier=125
[34]
Name=Cosmic Chessboard
ScoreMultiplier=125
[35]
Name=Uphill Battle
ScoreMultiplier=150
[36]
Name=Gods Play Dices
ScoreMultiplier=150
[37]
Name=Khan the Conqueror
ScoreMultiplier=125
[38]
Name=<Starting Situation>
ScoreMultiplier=100
[39]
Name=<Accessibility Options>
ScoreMultiplier=100
[40]
Name=<Advanced Options>
ScoreMultiplier=100
[41]
Name=You Too, Adamantium?
ScoreMultiplier=125
[42]
Name=Banned Barbarians
ScoreMultiplier=100
[43]
Name=Banned Gnolls
ScoreMultiplier=100
[44]
Name=Banned Halflings
ScoreMultiplier=100
[45]
Name=Banned High Elves
ScoreMultiplier=100
[46]
Name=Banned High Men
ScoreMultiplier=100
[47]
Name=Banned Klackons
ScoreMultiplier=100
[48]
Name=Banned Lizardmen
ScoreMultiplier=100
[49]
Name=Banned Nomads
ScoreMultiplier=100
[50]
Name=Banned Orcs
ScoreMultiplier=100
[51]
Name=Banned Hawkmen
ScoreMultiplier=100
[52]
Name=Banned Beastmen
ScoreMultiplier=100
[53]
Name=Banned Dark Elves
ScoreMultiplier=100
[54]
Name=Banned Draconians
ScoreMultiplier=100
[55]
Name=Banned Dwarves
ScoreMultiplier=100
[56]
Name=Banned Trolls
ScoreMultiplier=100
[57]
Name=Banned Xuanyuanese
ScoreMultiplier=100
[58]
Name=Banned Rakhshasas
ScoreMultiplier=100
[59]
Name=Banned Goblins
ScoreMultiplier=100
[60]
Name=Post-catalysm
ScoreMultiplier=110
[61]
Name=Zero Book Rule
ScoreMultiplier=100
[62]
Name=Pleasantville
ScoreMultiplier=100
[63]
Name=<Fortress Option>
ScoreMultiplier=100
[64]
Name=Fortress on the Hill
ScoreMultiplier=90
[65]
Name=Mountain King
ScoreMultiplier=90
[66]
Name=Mount Doom
ScoreMultiplier=90
[67]
Name=Sand Pit
ScoreMultiplier=90
[68]
Name=Everglade
ScoreMultiplier=90
[69]
Name=Disney on Ice
ScoreMultiplier=90
[70]
Name=Magic Garden
ScoreMultiplier=90
[71]
Name=Demon King's Castle
ScoreMultiplier=125
[72]
Name=Orihalcon Fortress
ScoreMultiplier=60
[73]
Name=Neo Venezia
ScoreMultiplier=50
[74]
Name=Doomsday Bunker
ScoreMultiplier=50
[75]
Name=Firework Factory
ScoreMultiplier=50
[76]
Name=World Tree
ScoreMultiplier=50
[77]
Name=Grand Bazaar
ScoreMultiplier=50
[78]
Name=You Too, Orihalcon?
ScoreMultiplier=125
[79]
Name=Absolute Fortress
ScoreMultiplier=50
[80]
Name=More Than Retort
ScoreMultiplier=100
[81]
Name=No Secret in Mastery
ScoreMultiplier=100
[82]
Name=Wizard of Oz
ScoreMultiplier=120
[83]
Name=Among Us...
ScoreMultiplier=120
[84]
Name=Desolated Outpost
ScoreMultiplier=100
[85]
Name=Return of the Master
ScoreMultiplier=50
[86]
Name=The Lord of the Magics
ScoreMultiplier=200
[87]
Name=Accelerated Race
ScoreMultiplier=120
[88]
Name=-------------
ScoreMultiplier=100
