// --- Ability Definitions ---
// Each ability: { key, label, type: 'bool'|'num'|'select', match, group }

const ABILITY_DEFS = [
  // Abilities — gaze (left col) | touch (right col); the Exorcise/Destruction touch pair is last.
  { key: 'stoningGaze', label: 'Stoning Gaze', type: 'numcheck', match: 'StoningGaze', group: 'Abilities', tooltip: 'Opponents with Stoning Immunity or Magic Immunity are unaffected.\nFor each defender figure: Defender resist at −X or die.\nFires before the melee exchange, on both attack and defense.\nCoM 2 & Warlord: Level does not modify this independent gaze field.' },
  { key: 'stoningTouch', label: 'Stoning Touch', type: 'numcheck', match: 'StoningTouch', group: 'Abilities', tooltip: 'Opponents with Stoning Immunity or Magic Immunity are unaffected.\nFor each attacker figure: Defender resist at −X or die.\nMoM 1.31 & 1.60: Innate/card values fire on every selected attack,\nincluding Gaze; item values follow melee or shared non-melee records.\nCoM 1: Innate/card values fire on every selected attack, including Gaze;\nitem values follow melee or shared non-melee records.\nCoM 2: General values fire on melee, Thrown, both Breaths, and ranged\nattacks; never on Gaze. Channel values fire only in their channel.\nWarlord: General values fire on melee, Thrown, both Breaths, and ranged\nattacks; never on Gaze. Channel values fire only in their channel.\nWarlord: Focus Magic moves it to melee and Thrown only.' },
  { key: 'deathGaze', label: 'Death Gaze', type: 'numcheck', match: 'DeathGaze', group: 'Abilities', tooltip: 'Opponents with Death Immunity, Magic Immunity, or\nRighteousness are unaffected.\nFor each defender figure: Defender resist at −X or die.\nFires before the melee exchange, on both attack and defense.\nCoM 2 & Warlord: Level does not modify this independent gaze field.' },
  { key: 'deathTouch', label: 'Death Touch', type: 'numcheck', match: 'DeathTouch', group: 'Abilities', tooltip: 'Opponents with Death Immunity or Magic Immunity are unaffected.\nRighteousness grants +30 Resistance against this effect.\nFor each attacker figure: Defender resist at −X or die.\nMoM 1.31 & 1.60: Innate/card values fire on every selected attack,\nincluding Gaze; item values follow melee or shared non-melee records.\nCoM 1: Innate/card values fire on every selected attack, including Gaze;\nitem values follow melee or shared non-melee records.\nCoM 2: General values fire on melee, Thrown, both Breaths, and ranged\nattacks; never on Gaze. Channel values fire only in their channel.\nWarlord: General values fire on melee, Thrown, both Breaths, and ranged\nattacks; never on Gaze. Channel values fire only in their channel.\nWarlord: Focus Magic moves it to melee and Thrown only.' },
  { key: 'doomGaze', label: 'Doom Gaze', type: 'num', match: 'DoomGaze', group: 'Abilities', tooltip: 'Deals X damage, ignoring to-hit and defense rolls.\nFires before the melee exchange, on both attack and defense.\nCoM 2 & Warlord: Level does not modify this independent gaze field.' },
  { key: 'lifeSteal', label: 'Life Steal', type: 'numcheck', match: 'LifeSteal', group: 'Abilities', tooltip: 'Opponents with Death Immunity, Magic Immunity, or\nRighteousness are unaffected.\nEach eligible attacker figure returns a raw roll magnitude. Target\ndamage is capped by remaining HP, but the full result immediately\nheals the attacker before later eligible calls. Regular damage is\nrestored before Undeath damage; Irrecoverable damage is not healed.\nDOS: may restore figures and grant temporary Extra Hits, with\nbuild-specific restoration and cap rules.\nCoM 2/Warlord: overheal becomes base bonus HP per living figure.\nMoM 1.31 & 1.60: Fires on every selected attack, including Gaze.\nCoM 1: Fires on every selected attack, including Gaze.\nCoM 2/Warlord: Fires on melee, Thrown, both Breaths, and ranged;\nnever on Gaze.' },
  { key: 'poison', label: 'Poison Touch', type: 'num', match: 'PoisonTouch', group: 'Abilities', tooltip: 'Opponents with Poison Immunity are unaffected.\nX times per attacker figure: Defender resist or take 1 damage.\nMoM 1.31 & 1.60: Fires on every selected attack, including Gaze.\nMoM 1.31 & 1.60: No save modifier.\nCoM 1: Fires on every selected attack, including Gaze.\nCoM 1 & 2 & Warlord: Save modifier −1.\nCoM 2: Fires on melee, Thrown, both Breaths, and ranged attacks;\nnever on Gaze.\nWarlord: Fires on melee, Thrown, both Breaths, and ranged attacks;\nnever on Gaze.' },
  { key: 'holyBonus', label: 'Holy bonus', type: 'num', match: 'HolyBonus', group: 'Abilities', tooltip: '+X to melee attack, defense, and resistance.\nCoM 1 & 2 & Warlord: Also +X to ranged, thrown, and breath attack.' },
  // `match` is the roster token with spaces stripped and case untouched, so the interior
  // "to" stays lowercase — the rosters name this "Resistance to All".
  { key: 'resistanceToAll', label: 'Res. to all', type: 'num', match: 'ResistancetoAll', group: 'Abilities', tooltip: '+X to resistance.' },
  { key: 'exorcise', label: 'Exorcise', type: 'numcheck', match: 'Exorcise', group: 'Abilities', subgroup: '_CoM, CoM2 & Warlord', tooltip: 'Versions: CoM 1 & 2, Warlord\nFantastic targets only.\nOpponents with Magic Immunity are unaffected.\nFor each attacker figure: Defender resist or be banished.\nUndead defenders get an additional −3 resistance modifier.\nCoM 1: Uses a literal −3 modifier; the entered value only records\nthat the common 0x0800 flag is present. Spell Lock blocks it.\nFires on every selected attack, including Gaze.\nCoM 2: Uses the entered −X modifier. Fires on melee, Thrown, both\nBreaths, and ranged attacks; never on Gaze.\nWarlord: Uses the entered −X modifier. Fires on melee, Thrown, both\nBreaths, and ranged attacks; never on Gaze.' },
  // Explicit subgroup, not inherited: defs without one fall under the previous def's header,
  // and Exorcise immediately above is CoM-onward. Destruction exists in all three DOS builds
  // too (0x9A19E, modifier 0), so it must not be gated with it.
  { key: 'destruction', label: 'Destruction', type: 'numcheck', match: 'Destruction', group: 'Abilities', subgroup: '_', tooltip: 'Versions: CoM 2, Warlord\nEach surviving attacker figure makes one Chaos-realm resistance attempt.\nBless adds its resistance bonus.\nMagic Immunity skips every attempt.\nAny failed attempt destroys the whole target unit.\nFires on melee, Thrown, both Breaths, and ranged attacks.\nDoes not fire on Stoning, Death, or Doom Gaze.' },
  // Bool abilities in a headerless grid; '_' prefix suppresses the subgroup header.
  // Keep labels column-major alphabetical: the UI grid flows row-first.
  ...twoColumnMajor([
    { key: 'armorPiercing', label: 'Armor Piercing', type: 'bool', match: 'ArmorPiercing', group: 'Abilities', subgroup: '_', tooltip: "Halves defender's defense (rounded down)." },
    { key: 'caster', label: 'Caster', type: 'bool', match: 'Caster', group: 'Abilities', subgroup: '_', tooltip: 'MoM 1.31 & 1.60: Uses mana for its magical ranged attack.\nCoM 1 & 2 & Warlord: Qualifies unit for Supreme Light bonuses.\nNot modeled: spellcasting, mana consumption.' },
    { key: 'fear', label: 'Cause Fear', type: 'bool', match: 'CauseFear', group: 'Abilities', subgroup: '_', tooltip: "Opponents with Magic Immunity or Righteousness are unaffected.\nFor each opponent figure: Resist or freeze for the melee exchange.\nMoM 1.31 & 1.60: Death Immunity skips the roll;\nno resistance modifier.\nMoM 1.31 bug 1: Defender's Cause Fear never fires — only the\nattacker's does.\nMoM 1.31 bug 2: Each of the defender's failed rolls also fears one\nattacker figure (self-fear), bypassing immunity.\nCoM 1: Death Immunity skips the −3 roll.\nCoM 2: Intrinsic/base Death Immunity skips the −3 roll;\nrecalculation-only Death Immunity still rolls.\nWarlord: Intrinsic/base Death Immunity skips the −3 roll;\nrecalculation-only Death Immunity still rolls." },
    { key: 'charmed', label: 'Charmed', type: 'bool', match: 'Charmed', group: 'Abilities', subgroup: '_', tooltip: 'Hero ability.\nMoM 1.31 & 1.60 & CoM 1: +30 Resistance for resistance rolls.\nCoM 2 & Warlord: Resistance becomes 100 for resistance rolls.\nConditional bonuses such as Bless and Resist Magic are added afterward.\nDoes not change displayed Resistance.' },
    { key: 'coldImmunity', label: 'Cold Immunity', type: 'bool', match: 'ColdImmunity', group: 'Abilities', subgroup: '_', tooltip: 'Immunity to cold attacks.\nNot modeled: freezing prevention.' },
    { key: 'deathImmunity', label: 'Death Immunity', type: 'bool', match: 'DeathImmunity', group: 'Abilities', subgroup: '_', tooltip: 'Immunity to Death Gaze, Death Touch, and Life Steal.\nMoM 1.31 & 1.60: Also skips Cause Fear rolls.\nCoM 1: Also skips Cause Fear rolls.\nCoM 2: Cause Fear checks intrinsic/base Death Immunity;\nrecalculation-only grants do not skip its roll.\nWarlord: Cause Fear checks intrinsic/base Death Immunity;\nrecalculation-only grants do not skip its roll.\nNot modeled: immunity to Death-realm spells.' },
    { key: 'dispelEvil', label: 'Dispel Evil', type: 'bool', match: 'DispelEvil', group: 'Abilities', subgroup: '_MoM only', tooltip: 'Versions: MoM 1.31 & 1.60\nDoes not affect units other than Chaos and Death.\nOpponents with Magic Immunity are unaffected.\nFor each attacker figure: Defender resist at −4 or die.\nUndead defenders resist at −9 instead.\nFires on every selected attack, including Gaze.' },
    { key: 'doom', label: 'Doom Damage', type: 'bool', match: 'Doom', group: 'Abilities', subgroup: '_', tooltip: 'All attacks skip to-hit and defense rolls.\nDamage dealt = floor(attack strength / 2).' },
    { key: 'fireImmunity', label: 'Fire Immunity', type: 'bool', match: 'FireImmunity', group: 'Abilities', subgroup: '_', tooltip: 'Immunity to Fire Breath, Immolation, and Wall of Fire.\nCoM 2 & Warlord: Also qualifies unit for Inner Power bonuses.' },
    { key: 'firstStrike', label: 'First Strike', type: 'bool', match: 'FirstStrike', group: 'Abilities', subgroup: '_', tooltip: "Opponents with Negate First Strike are unaffected.\nAttacker delivers melee and touch attacks before the defender\nretaliates (not when counter-attacking).\nCoM 1: Only triggers if the defender's top figure has ≤ 24 HP." },
    { key: 'illusion', label: 'Illusion', type: 'bool', match: 'Illusion', group: 'Abilities', subgroup: '_', tooltip: "Opponents with Illusion Immunity or True Sight are unaffected.\nDefender's defense drops to 0, overriding all immunities.\nMoM 1.31 & 1.60 & CoM 1: City-wall defense remains.\nWarlord: Under True Light, −10% To Hit." },
    { key: 'illusionImmunity', label: 'Illusion Immunity', type: 'bool', match: 'IllusionImmunity', group: 'Abilities', subgroup: '_', tooltip: 'Immune to Illusion and Invisibility.\nAlso blocks Vertigo and Mind Storm.\nMoM 1.31 bug: For Blur, Illusion Immunity is checked on the\ndefender instead of the attacker.\nNot modeled: Confusion prevention; seeing through Wall of Darkness.' },
    { key: 'immolation', label: 'Immolation', type: 'bool', match: 'Immolation', group: 'Abilities', subgroup: '_', tooltip: 'Opponents with Fire Immunity, Magic Immunity, or\nRighteousness are unaffected.\nFire area attack hitting all opponent figures each melee phase.\nMoM 1.31: Strength 4. Bug: Also fires alongside ranged attacks.\nMoM 1.60: Strength 4.\nCoM 1 & 2 & Warlord: Strength 10.\nNot modeled: web burning, freeze prevention.' },
    { key: 'invisibility', label: 'Invisibility', type: 'bool', match: 'Invisibility', group: 'Abilities', subgroup: '_', tooltip: 'Opponents with Illusion Immunity or True Sight are unaffected.\nRanged attackers cannot target this unit.\nMoM 1.31 & 1.60: Opponent −10% To Hit on all attacks\n(melee, ranged, thrown, breath, gaze).\nCoM 1, CoM2 & Warlord: 20% chance to negate each incoming hit.\nCoM 1 stacks with unit Blur to 30%.\nCoM2 stacks with tactical defender Card B\'s army Blur to 30%;\nWarlord 40%.' },
    { key: 'largeShield', label: 'Large Shield', type: 'bool', match: 'LargeShield', group: 'Abilities', subgroup: '_', tooltip: 'Extra defense vs ranged, thrown, breath, Immolation,\nand Wall of Fire.\nMoM 1.31 & 1.60: +2.\nCoM 1 & 2 & Warlord: +3.' },
    { key: 'lightningResist', label: 'Lightning Resist', type: 'bool', match: 'LightningResist', group: 'Abilities', subgroup: '_', tooltip: 'Negates the Armor Piercing component of incoming Lightning Breath.\nCoM 2 & Warlord: Also qualifies unit for Inner Power bonuses.' },
    { key: 'longRange', label: 'Long Range', type: 'bool', match: 'LongRange', group: 'Abilities', subgroup: '_', tooltip: 'Caps the distance To-Hit penalty on missile and boulder ranged\nattacks at −10%.\nCoM 6.08, CoM2, Warlord: Heroes pay no distance penalty, so this is\nredundant for them.' },
    { key: 'lucky', label: 'Lucky', type: 'bool', match: 'Lucky', group: 'Abilities', subgroup: '_', tooltip: '+10% To Hit, +10% To Block, +1 Resistance.\nMoM 1.31: Also opponent −10% To Hit on melee (and counter-attacks).' },
    { key: 'magicImmunity', label: 'Magic Immunity', type: 'bool', match: 'MagicImmunity', group: 'Abilities', subgroup: '_', tooltip: 'Immunity to magical ranged attacks, Immolation, and Wall of Fire.\nAlso negates Death Gaze, Death Touch, Life Steal, Cause Fear,\nStoning, Dispel Evil, and Exorcise.\nAlso negates the curses Weakness, Black Sleep, Shatter, Vertigo,\nWarp Creature, Mind Storm, Nausea, and Temporal Twist.\nMoM only: Also protects against Fire Breath and Lightning Breath.' },
    { key: 'missileImmunity', label: 'Missile Immunity', type: 'bool', match: 'MissileImmunity', group: 'Abilities', subgroup: '_', tooltip: 'Immunity to missile ranged attacks (not boulder).' },
    { key: 'merging', label: 'Merging', type: 'bool', match: 'Merging', group: 'Abilities', subgroup: '_CoM2 & Warlord', tooltip: 'Versions: CoM 2, Warlord\nCalculated Merging prevents Wall of Fire from firing against this\nunit. Unlike Teleporting, it does not grant Tactician First Strike\nand Temporal Twist does not strip it.' },
    { key: 'negateFirstStrike', label: 'Negate First Strike', type: 'bool', match: 'NegateFirstStrike', group: 'Abilities', subgroup: '_', tooltip: "Negates the opponent's First Strike." },
    { key: 'nonCorporeal', label: 'Non-Corporeal', type: 'bool', match: 'Non-Corporeal', group: 'Abilities', subgroup: '_', tooltip: 'Warlord: Tactician retort grants this unit Negate First Strike.\nNot modeled: terrain/wall movement; immunity to undead conversion.' },
    { key: 'poisonImmunity', label: 'Poison Immunity', type: 'bool', match: 'PoisonImmunity', group: 'Abilities', subgroup: '_', tooltip: 'Immunity to Poison Touch.' },
    { key: 'stoningImmunity', label: 'Stoning Immunity', type: 'bool', match: 'StoningImmunity', group: 'Abilities', subgroup: '_', tooltip: 'Immunity to Stoning Gaze and Stoning Touch.' },
    { key: 'supernatural', label: 'Supernatural', type: 'bool', match: 'Supernatural', group: 'Abilities', subgroup: '_', tooltip: "Versions: CoM 1 & 2, Warlord\nCoM 1: Trait is present, but its executable test is inactive;\nit has no combat effect.\nCoM 2 & Warlord: Each attack's hits deal at least\nRound((hits − start) × ratio / 100), using ties-to-even rounding.\nShipped start 0, ratio 34." },
    { key: 'teleporting', label: 'Teleporting', type: 'bool', match: 'Teleporting', group: 'Abilities', subgroup: '_CoM2 & Warlord', tooltip: 'Versions: CoM 2, Warlord\nCalculated Teleporting prevents Wall of Fire from firing against\nthis unit. Warlord: with Tactician, also grants First Strike;\nTemporal Twist strips Teleporting before Tactician runs.' },
    { key: 'undead', label: 'Undead', type: 'bool', match: 'Undead', group: 'Abilities', subgroup: '_', tooltip: 'Unit becomes a fantastic Death creature.\nMoM 1.31: Grants Death Immunity.\nMoM 1.31 bug: Should also have granted Cold, Poison, and Illusion Immunity.\nMoM 1.60: Grants Death, Cold, Poison, and Illusion Immunity.\nCoM 1 & 2 & Warlord: Grants Death, Cold, and Illusion Immunity.\nNot modeled: natural healing / regeneration prevention.' },
    { key: 'weaponImmunity', label: 'Weapon Immunity', type: 'bool', match: 'WeaponImmunity', group: 'Abilities', subgroup: '_', tooltip: 'Extra defense against attacks not marked magical.\nMoM 1.31 & 1.60: Defense = 10.\nMoM 1.31 bug: Thrown attacks, and generic units (e.g. Catapult,\nWarship), bypass it.\nCoM 1: Defense +8; normal-unit and weapon-quality rules apply.\nCoM 2: Defense +8. Warlord: Defense +10.\nModern bypass: calculated Magic Weapon, magical ranged, Breath,\nor Gaze. Final Fantastic/normal identity is not the direct gate.' },
  ]),
  // Warlord-mod-only unit tags, shown under a 'Warlord' subheader.
  // Keep labels column-major alphabetical: the UI grid flows row-first.
  ...twoColumnMajor([
    { key: 'amplifier', label: 'Amplifier', type: 'bool', match: 'Amplifier', group: 'Abilities', subgroup: 'Warlord', tooltip: 'Versions: Warlord 1.5.12.7\nWhen this opposing unit is present in combat, a positive Wall of\nFire result gains 1 damage. Zero damage stays zero; copies do not\nstack. The broader active-spell damage/healing effect is out of scope.' },
    { key: 'bloodSucker', label: 'Blood Sucker', type: 'bool', match: 'BloodSucker', group: 'Abilities', subgroup: 'Warlord', tooltip: 'Versions: Warlord 1.5.12.7\nAfter all result categories and riders, a positive result triggers once\nper ApplyAttack call. Rider-only damage can trigger it. Adds the shipped\nBloodsuckerDamage (2) before target rendering caps overkill, then passes\nthe independent BloodsuckerHealing (2) to non-overheal regeneration.\nHealing is capped only by attacker recoverable damage, restores ordinary\nthen undead damage, ignores No Healing, and creates no bonus HP.\nFires on melee, Thrown, Breath, ranged, and gaze ApplyAttack calls.\nHaste supplies a separate trigger check for its repeated call.' },
    { key: 'clergy', label: 'Clergy', type: 'bool', match: 'Clergy', group: 'Abilities', subgroup: 'Warlord', tooltip: 'Versions: Warlord\nWith Sanctify, the unit becomes a fantastic Life creature\n(non-clergy units instead become non-fantastic Life).\nNot modeled: improved Exorcise, Sanctify casting-skill bonus.' },
    { key: 'flying', label: 'Flying', type: 'bool', match: 'Flight', group: 'Abilities', subgroup: 'Warlord', tooltip: 'Versions: Warlord\nQualifies a unit with the Explosive reform for Bombs&Grenades.' },
    // Artificer's resistance write is `GetStat(U,SResist,1)+2` (CreateUnit.CAS:43), not the +1
    // this tooltip used to state; the Magic Weapons half is the `SETENCHANTMENTFLAG(U,EncMagic,1,1)`
    // at `:39`, modelled as `artificerMagicWeapon` (stats.js:158). The rank is the F208 ruling:
    // CreateUnit.CAS runs when the city builds the unit, so it cannot see the cast-time flag
    // Rebuild writes (F196).
    { key: 'mechanical', label: 'Mechanical', type: 'bool', match: 'Mechanical', group: 'Abilities', subgroup: 'Warlord', tooltip: 'Versions: Warlord\nBuffed by Artificer (+1 melee, +1 ranged, +1 armor, +2 resistance,\nMagic Weapons) and Mechanical Expert (+20% To Hit, +10% To Block).\nRebuild grants this flag, but too late for Artificer: that buff lands\nwhen the unit is trained.' },
    { key: 'rage', label: 'Rage', type: 'bool', match: 'Rage', group: 'Abilities', subgroup: 'Warlord', tooltip: 'Versions: Warlord\n+1 melee attack per figure the unit has lost.\n+1 ranged attack per figure lost, if the unit has a ranged attack.\nFigures lost counts pre-combat casualties and in-combat losses.' },
    { key: 'sailing', label: 'Sailing', type: 'bool', match: 'Sailing', group: 'Abilities', subgroup: 'Warlord', tooltip: 'Versions: Warlord\nWith Heat Power Engine and Temporal Engineering, gains\nFlying and Illusion Immunity in addition to Haste.' },
    { key: 'sapiens', label: 'Sapiens', type: 'bool', match: 'Sapiens', group: 'Abilities', subgroup: 'Warlord', tooltip: 'Versions: Warlord\nFantastic creature capable of using Outlander technology.\nQualifies for reforms that also affect regular units.' },
  ]),
];

// Lookup by key over the definitions above. Callers that need a def hold only its key, so the
// scan belongs with the array rather than being re-spelled beside each asker.
function abilityDefByKey(key) {
  return ABILITY_DEFS.find(a => a.key === key);
}
