// Numeric presets. Weapon, Missile and Fire Immunity, Cause Fear, Illusion and Invisibility,
// and the modern unit abilities from Doom Damage through Fortification.
definePresets({
  // --- Weapon Immunity (MoM 1.31) ---
  weaponImmunityMelee: {
    desc: 'Weapon Immunity Melee (MoM 1.31): normal melee vs WI (def 0→10), 100% block → all 10 hits blocked',
    version: V_MOM_131,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  weaponImmunityMagicWeapon: {
    desc: 'Weapon Immunity bypassed by magic weapon: 10 hits vs 0 def → full damage',
    a: { atk:10, toHitMod:70, hp:10, weapon: 'magic' },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 10 },
  },
  weaponImmunityFantastic: {
    desc: 'Weapon Immunity bypassed by fantastic unit: 10 hits vs 0 def → full damage',
    a: { atk:10, toHitMod:70, hp:10, unitType: 'fantastic_chaos' },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 10 },
  },
  weaponImmunityHero: {
    desc: 'Weapon Immunity bypassed by hero: 10 hits vs 0 def → full damage',
    a: { atk:10, toHitMod:70, hp:10, unitType: 'hero' },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 10 },
  },
  weaponImmunityCounter: {
    desc: 'Weapon Immunity on attacker: A has WI (def 0→10), B normal counter 10 atk all blocked',
    a: { atk:1, toHitMod:70, def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    b: { atk:10, toHitMod:70, def:0, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 1 },
  },
  weaponImmunityThrown131: {
    desc: 'Weapon Immunity vs Thrown (MoM 1.31): bug — thrown ignores WI → def stays 0, all 10 thrown hits land; melee 1 hit blocked by WI def 10',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:10, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:0, toBlkMod:70, hp:20, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 10 },
  },
  weaponImmunityRangedMissile: {
    desc: 'Weapon Immunity applies to ranged missile: def 0→10, 100% block → all hits blocked',
    a: { rtbType:'missile', rtb:10, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  weaponImmunityRangedMagic: {
    desc: 'Weapon Immunity does not apply to ranged magic: 10 hits vs 0 def → full damage',
    a: { rtbType:'magic_c', rtb:10, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 10 },
  },
  // --- Weapon Immunity (version-specific) ---
  weaponImmunityThrownPatched: {
    desc: 'Weapon Immunity vs Thrown (MoM CP 1.60): fix — thrown triggers WI (def 0→10), 100% block → all thrown + melee blocked',
    version: V_MOM_CP,
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:10, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  weaponImmunityCom2Melee: {
    desc: 'Weapon Immunity Melee (CoM2): normal melee vs WI → def 0+8=8, 100% block → only 8 hits blocked',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 2 },
  },
  weaponImmunityWarlordMelee: {
    desc: 'Weapon Immunity Melee (Warlord): normal melee vs WI → def 0+10=10, 100% block → all 10 hits blocked',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  weaponImmunityAfterMissileImmunityCoM2: {
    desc: 'EffectiveDefense order: Missile Immunity replaces the accumulated defense with 100, then Weapon Immunity adds 8. Modern defense rolls only the first 15 dice at To Block and the rest at 30%, so 108 defense blocks 15 + 93×0.3 = 42.9 of 70 missile hits → 27.1; the 100-final chain blocks 40.5 and leaks 29.5.',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:70, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:70, abilities: { missileImmunity: true, weaponImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 27.100 },
  },
  weaponImmunityGeneric131: {
    desc: 'Weapon Immunity vs Generic unit (MoM 1.31): bug — WI bypassed, def stays 0, 6 atk 30% hit → 1.8 dmg',
    version: V_MOM_131,
    aUnitName: 'Trireme',
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 1.800 },
  },
  weaponImmunityGenericPatched: {
    desc: 'Weapon Immunity vs Generic unit (MoM CP 1.60): fix — WI applies, def 0→10, 100% block → 0 dmg',
    version: V_MOM_CP,
    aUnitName: 'Trireme',
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  weaponImmunityGenericCatapult131: {
    desc: 'Weapon Immunity vs Generic Catapult boulder (MoM 1.31): bug — WI bypassed, def stays 0, 10 boulder 30% hit → 3.0 dmg',
    version: V_MOM_131,
    aUnitName: 'Catapult',
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  weaponImmunityGenericCatapultPatched: {
    desc: 'Weapon Immunity vs Generic Catapult boulder (MoM CP 1.60): fix — WI applies, def 0→10, 100% block → 0 dmg',
    version: V_MOM_CP,
    aUnitName: 'Catapult',
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },

  // --- Missile Immunity ---
  missileImmunityMissile: {
    desc: 'Missile Immunity vs Missile: def 2→50, 3 atk 100% hit → all blocked (50 def × 100% block)',
    a: { rtbType:'missile', rtb:3, toHitRtbMod:70, hp:10 },
    b: { def:2, toBlkMod:70, hp:10, abilities: { missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  missileImmunityBoulder: {
    desc: 'Missile Immunity does NOT apply to boulder: def stays 2, 3 atk 100% hit → 1 dmg',
    a: { rtbType:'boulder', rtb:3, toHitRtbMod:70, hp:10 },
    b: { def:2, toBlkMod:70, hp:10, abilities: { missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  missileImmunityMagic: {
    desc: 'Missile Immunity does NOT apply to magic ranged: def stays 0, 3 atk 100% hit → 3 dmg',
    a: { rtbType:'magic_c', rtb:3, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  missileImmunityMelee: {
    desc: 'Missile Immunity does NOT apply to melee: def stays 0, 3 atk 100% hit → 3 dmg',
    a: { atk:3, toHitMod:70, hp:10, abilities: {} },
    b: { def:0, toBlkMod:70, hp:10, abilities: { missileImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  missileImmunityArmorPiercing: {
    desc: 'Missile Immunity after Armor Piercing: AP halves first, then MI raises to 50 → all blocked',
    a: { rtbType:'missile', rtb:3, toHitRtbMod:70, hp:10, abilities: { armorPiercing: true } },
    b: { def:6, toBlkMod:70, hp:10, abilities: { missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },

  missileImmunityWIOverwrite131: {
    desc: 'WI+MI vs Missile (MoM 1.31): bug — WI overwrites MI, def=10 not 50. 15 hits − 10 blocks = 5',
    version: V_MOM_131,
    a: { rtbType:'missile', rtb:15, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:20, abilities: { weaponImmunity: true, missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  missileImmunityWIOverwriteFixed: {
    desc: 'WI+MI vs Missile (MoM CP 1.60): fix — MI wins, def=50. 15 hits all blocked',
    version: V_MOM_CP,
    a: { rtbType:'missile', rtb:15, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:20, abilities: { weaponImmunity: true, missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  missileImmunityWraithFormOverwrite131: {
    desc: 'Wraith Form WI+MI vs Missile (MoM 1.31): WI overwrites MI, def=10. 15 hits − 10 blocks = 5',
    version: V_MOM_131,
    a: { rtbType:'missile', rtb:15, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:20, abilities: { wraithForm: true, missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  missileImmunityInvulnerabilityOverwrite131: {
    desc: 'Invulnerability WI+MI vs Missile (MoM 1.31): WI overwrites MI, def=10; Invulnerability absorbs 2 of 5 damage',
    version: V_MOM_131,
    a: { rtbType:'missile', rtb:15, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:20, abilities: { invulnerability: true, missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  missileImmunityGenericKeepsMI131: {
    desc: 'WI+MI vs Generic missile (MoM 1.31): Generic bypasses WI, so MI remains def=50 and blocks the shot',
    version: V_MOM_131,
    aUnitName: 'Galley',
    b: { def:0, toBlkMod:70, hp:20, abilities: { weaponImmunity: true, missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  missileImmunityWIMagicWeapon: {
    desc: 'WI+MI vs magic weapon missile → WI bypassed, MI still applies, def=50. All blocked',
    a: { rtbType:'missile', rtb:15, toHitRtbMod:70, hp:10, weapon:'magic' },
    b: { def:0, toBlkMod:70, hp:20, abilities: { weaponImmunity: true, missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },

  // --- Guardian Wind ---
  guardianWindBlocksMissile: {
    desc: 'Guardian Wind grants Missile Immunity: missile 3 vs def 2 + Guardian Wind → def raised to 50, all blocked',
    a: { rtbType:'missile', rtb:3, toHitRtbMod:70, hp:10 },
    b: { def:2, toBlkMod:70, hp:10, abilities: { guardianWind: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },

  // --- Fire Immunity ---
  fireImmunityFireBreath: {
    desc: 'Fire Immunity vs Fire Breath: breath 5 at 100% vs FI def 50 → blocked; melee 5 at 100% vs def 2 → 3 dmg',
    a: { atk:5, rtbType:'fire', rtb:5, toHitMod:70, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:2, toBlkMod:70, hp:10, abilities: { fireImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  fireImmunityNotMelee: {
    desc: 'Fire Immunity does NOT apply to melee: def stays 0, 3 atk 100% hit → 3 dmg',
    a: { atk:3, toHitMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { fireImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  fireImmunityNotThrown: {
    desc: 'Fire Immunity does NOT apply to thrown: def stays 0, 1+3 thrown+melee 100% hit → 4 dmg',
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:3, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { fireImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  fireImmunityNotMissile: {
    desc: 'Fire Immunity does NOT apply to missile ranged: def stays 0, 3 atk 100% hit → 3 dmg',
    a: { rtbType:'missile', rtb:3, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { fireImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  fireImmunityAfterArmorPiercing: {
    desc: 'Fire Immunity after Armor Piercing: AP halves def 6→3, then Fire Immunity assigns 50, so breath 70 deals 20. The assignment is absolute, not a raise — measured, a defender at def 6, 60 or 100 all end at 50 — so removing Armor Piercing leaves 20 as well, and no fixture can make its presence move this number. What the size does prove is the order: Armor Piercing applied *after* Fire Immunity would halve the 50 and the same breath would deal 45, which is what the same shot deals against a plain def 25. The earlier 5-strength breath against a 10 HP defender printed 0 under both orders and could not fail. Armor Piercing is live in the same setup without Fire Immunity: 67 against 64.',
    a: { atk:0, rtbType:'fire', rtb:70, toHitRtbMod:70, hp:10, abilities: { armorPiercing: true } },
    b: { atk:0, def:6, toBlkMod:70, hp:200, abilities: { fireImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 20.000 },
  },
  fireImmunityIllusionOverrides: {
    desc: 'Illusion overrides Fire Immunity: FI sets def to 50, then Illusion sets to 0 → full breath damage',
    a: { atk:1, rtbType:'fire', rtb:5, toHitMod:70, toHitRtbMod:70, hp:10, abilities: { illusion: true } },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { fireImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },

  // --- Cause Fear (v1.31 buggy behavior) ---
  fearBasic: {
    desc: 'Cause Fear Attacker (MoM 1.31): bug — A fears B (50%) + self-fear bug. E[A unfeared]=3.5 → E[dmgB]=10.5, E[B unfeared]=0.5 → E[dmgA]=1.5',
    version: V_MOM_131,
    a: { figs:4, atk:3, toHitMod:70, hp:10, abilities: { fear: true } },
    b: { atk:3, toHitMod:70, hp:20, def:0, res:5 },
    expected: { dmgToA: 1.500, dmgToB: 10.500 },
  },
  fearDefenderNoop: {
    desc: 'Cause Fear Defender (MoM 1.31): bug — defending Fear has no effect. Both do 5 dmg normally',
    version: V_MOM_131,
    a: { atk:5, toHitMod:70, hp:10, res:5 },
    b: { atk:5, toHitMod:70, hp:10, def:0, res:5, abilities: { fear: true } },
    expected: { dmgToA: 5.000, dmgToB: 5.000 },
  },
  fearDeathImmune: {
    desc: 'Cause Fear vs Death Immunity: fear blocked, both do 5 dmg normally',
    a: { atk:5, toHitMod:70, hp:10, abilities: { fear: true } },
    b: { atk:5, toHitMod:70, hp:10, def:0, abilities: { deathImmunity: true } },
    expected: { dmgToA: 5.000, dmgToB: 5.000 },
  },
  fearMagicImmune: {
    desc: 'Cause Fear vs Magic Immunity: fear blocked, both do 5 dmg normally',
    a: { atk:5, toHitMod:70, hp:10, abilities: { fear: true } },
    b: { atk:5, toHitMod:70, hp:10, def:0, abilities: { magicImmunity: true } },
    expected: { dmgToA: 5.000, dmgToB: 5.000 },
  },
  fearNotRanged: {
    desc: 'Cause Fear does not apply to ranged attacks: 5 missile 100% hit → 5 dmg',
    a: { rtbType:'missile', rtb:5, toHitRtbMod:70, hp:10, abilities: { fear: true } },
    b: { def:0, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },

  // --- Illusion ---
  illusionMelee: {
    desc: 'Illusion Melee: 5 atk 30% hit vs def 6 → def becomes 0, E[dmg] = 5×0.3 = 1.5',
    a: { atk:5, hp:10, abilities: { illusion: true } },
    b: { def:6, hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.500 },
  },
  illusionRanged: {
    desc: 'Illusion Ranged: missile 5 atk 30% hit vs def 6 → def becomes 0, E[dmg] = 5×0.3 = 1.5',
    a: { rtbType:'missile', rtb:5, hp:10, abilities: { illusion: true } },
    b: { def:6, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.500 },
  },
  illusionThrown: {
    desc: 'Illusion Thrown: thrown 5 + melee 1, 30% hit vs def 6 → def becomes 0, E[dmg] = 6×0.3 = 1.8',
    a: { atk:1, rtbType:'thrown', rtb:5, hp:10, abilities: { illusion: true } },
    b: { atk:0, def:6, hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.800 },
  },
  illusionCounter: {
    desc: 'Illusion on defender: B counter ignores A def 6. A 1atk all blocked; B 5atk 30% hit → E[counter] = 1.5',
    a: { atk:1, toHitMod:70, def:6, hp:10 },
    b: { atk:5, def:1, toBlkMod:70, hp:10, abilities: { illusion: true } },
    expected: { dmgToA: 1.500, dmgToB: 0 },
  },
  illusionImmunityNegates: {
    desc: 'Illusion Immunity: 5 atk 30% hit vs def 6 + Illusion Immunity → def stays 6, normal damage',
    a: { atk:5, hp:10, abilities: { illusion: true } },
    b: { def:6, hp:10, abilities: { illusionImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0.449 },
  },
  trueSightNegatesIllusion: {
    desc: 'True Sight grants Illusion Immunity: 5 atk 100% hit vs def 6 + True Sight 100% block → def stays 6, 0 dmg (would be 5 if True Sight didn\'t grant immunity)',
    a: { atk:5, toHitMod:70, hp:10, abilities: { illusion: true } },
    b: { def:6, toBlkMod:70, hp:10, abilities: { trueSight: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  trueSightRangedToHitWarlord: {
    desc: 'True Sight (Warlord): ranged 1 at base 30% + True Sight 5% To-Hit vs def 0 → E[dmg] = 0.35 (without True Sight, 0.30)',
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:1, type:'magic' } }, hp:10, abilities: { trueSight: true } },
    b: { atk:0, def:0, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.350 },
  },
  trueSightBreathUnaffectedWarlord: {
    desc: 'True Sight (Warlord) writes SToRanged only: melee 1 and fire breath 1 both stay at 30% → 0.3 + 0.3 = 0.6. If the bonus reached the Breath channel the breath would hit at 35% and give 0.650.',
    version: V_WARLORD,
    a: { atk:1, modernAttacks: { fireBreath: { strength:1, type:'fire' } }, hp:10, abilities: { trueSight: true } },
    b: { hp:10 },
    rangedCheck: false,
    expected: { dmgToA: 0, dmgToB: 0.600 },
  },
  trueSightThrownUnaffectedWarlord: {
    desc: 'True Sight (Warlord) writes SToRanged only: melee 1 and thrown 1 both stay at 30% → 0.3 + 0.3 = 0.6. If the bonus reached the Thrown channel the thrown attack would hit at 35% and give 0.650.',
    version: V_WARLORD,
    a: { atk:1, modernAttacks: { thrown: { strength:1, type:'thrown' } }, hp:10, abilities: { trueSight: true } },
    b: { hp:10 },
    rangedCheck: false,
    expected: { dmgToA: 0, dmgToB: 0.600 },
  },
  eyeOfHeavenNegatesIllusion: {
    desc: 'Eye of Heaven grants Illusion Immunity to its own unit: 5 atk 100% hit vs def 6 + Eye of Heaven 100% block → def stays 6, 0 dmg (would be 5 if illusion still ignored armor)',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10, abilities: { illusion: true } },
    b: { def:6, toBlkMod:70, hp:10, abilities: { eyeOfHeaven: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  eyeOfHeavenDisablesEnemyGaze: {
    desc: 'Eye of Heaven on the defender strips the attacker\'s gaze: Doom Gaze 5 disabled → 0 dmg (would be 5 without Eye of Heaven)',
    version: V_WARLORD,
    a: { atk:0, hp:10, abilities: { doomGaze: 5 } },
    b: { def:0, hp:10, abilities: { eyeOfHeaven: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  eyeOfHeavenTrueSightToHitWarlord: {
    desc: 'Eye of Heaven (Warlord): grants True Sight, so ranged 1 at base 30% + 5% To-Hit vs def 0 → E[dmg] = 0.35 (without Eye of Heaven, 0.30)',
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:1, type:'magic' } }, hp:10, abilities: { eyeOfHeaven: true } },
    b: { atk:0, def:0, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.350 },
  },
  illusionCityWalls: {
    desc: 'Illusion + City Walls: def 3 base + 3 CW = 6, Illusion → only CW survives, def=3',
    a: { atk:5, toHitMod:70, hp:10, abilities: { illusion: true } },
    b: { def:3, toBlkMod:70, hp:10, cityWalls: '3' },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  blazeOfGloryZeroesEnchantmentArmorWarlord: {
    desc: 'Blaze of Glory transfers current Armor and then sets Defense to 0, including enchantment Armor. Iron Skin gives +5 Armor, so defender melee becomes 5 but all 4 incoming hits land. The old surviving-Armor reconstruction blocked every hit.',
    version: V_WARLORD,
    a: { atk:4, def:10, hitChance:70, toBlkMod:70, hp:20 },
    b: { atk:0, def:0, hitChance:70, toBlkMod:70, hp:20,
      abilities: { blazeOfGlory: true, ironSkin: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  illusionCityWallsCoM2: {
    desc: 'EffectiveDefense returns immediately at the Illusion step in CoM2: both base defense and the City Walls extra-defense input are discarded, so all 5 hits land.',
    version: V_COM2,
    a: { atk:5, hitChance:70, hp:10, abilities: { illusion: true } },
    b: { def:3, toBlkMod:70, hp:10, cityWalls: '3' },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  cityWallsAfterWarpDefenseCoM2: {
    desc: 'City Walls is EffectiveDefense extra defense, not a unit stat: Warp Defense first reduces Armor 9 to 3, then intact walls add 3 → 6. Eight hits at 100% block deal 2 (adding walls before Warp would leave 4 and deal 4).',
    version: V_COM2,
    a: { atk:8, hitChance:70, hp:10 },
    b: { def:9, toBlkMod:70, hp:10, cityWalls: '3', abilities: { warpDefense: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  cityWallsAfterBlazeOfGloryWarlord: {
    desc: 'City Walls lands after Blaze of Glory: Blaze transfers base Armor 3 to melee and zeros it, then intact walls add 3 only for the incoming attack. Five hits at 100% block deal 2 (booking walls before Blaze would transfer them and deal 5).',
    version: V_WARLORD,
    a: { atk:5, def:10, hitChance:70, toBlkMod:70, hp:10 },
    b: { atk:0, def:3, toBlkMod:70, hp:10, cityWalls: '3', abilities: { blazeOfGlory: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  cityWallsProtectsInitiatorOnCounterattackCoM2: {
    desc: 'Card A is inside and attacks card B outside. City Walls does not protect outside B from the initial strike, but protects inside A when B counterattacks: 4 hits − 3 blocks = 1.',
    version: V_COM2,
    a: { atk:4, def:0, hitChance:70, toBlkMod:70, hp:20, cityWalls:'3' },
    b: { atk:4, def:0, hitChance:70, toBlkMod:70, hp:20 },
    expected: { dmgToA:1.000, dmgToB:4.000 },
  },
  cityWallsProtectsRecipientAcrossWallCoM2: {
    desc: 'Card A is outside and attacks card B inside. City Walls protects B from the initial strike regardless of army membership: 4 hits − 3 blocks = 1; outside A gets no bonus against the counterattack.',
    version: V_COM2,
    a: { atk:4, def:0, hitChance:70, toBlkMod:70, hp:20 },
    b: { atk:4, def:0, hitChance:70, toBlkMod:70, hp:20, cityWalls:'3' },
    expected: { dmgToA:4.000, dmgToB:1.000 },
  },
  cityWallsNoBonusWhenBothInsideCoM2: {
    desc: 'Both cards are inside the walls, so neither attack crosses inward from outside and neither unit receives the City Walls defense bonus.',
    version: V_COM2,
    a: { atk:4, def:0, hitChance:70, toBlkMod:70, hp:20, cityWalls:'3' },
    b: { atk:4, def:0, hitChance:70, toBlkMod:70, hp:20, cityWalls:'3' },
    expected: { dmgToA:4.000, dmgToB:4.000 },
  },
  illusionOverridesWeaponImmunity: {
    desc: 'Illusion overrides Weapon Immunity: WI sets def to 10, then Illusion sets to 0 → full damage',
    a: { atk:5, toHitMod:70, hp:10, abilities: { illusion: true } },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  illusionDoesNotOverrideImmolationDefense: {
    desc: 'Illusion does not affect Immolation defense: melee ignores def for 1 dmg, but Immolation 4 vs def 4 at 100% block is fully blocked',
    a: { atk:1, toHitMod:70, hp:10, abilities: { illusion: true, immolation: true } },
    b: { def:4, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },

  // --- Invisibility ---
  invisibilityMelee: {
    desc: 'Invisible defender melee: 5 atk 30% hit − 10% invis penalty = 20% hit vs def 0, E[dmg] = 5×0.2 = 1.0',
    a: { atk:5, hp:10 },
    b: { def:0, hp:10, abilities: { invisibility: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  invisibilityRangedBlocked: {
    desc: 'Invisible defender cannot be targeted by ranged: 0 damage regardless of attacker stats',
    a: { rtbType:'missile', rtb:5, hp:10 },
    b: { def:0, hp:10, abilities: { invisibility: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  invisibilityRangedIllusionImmune: {
    desc: 'Illusion Immune attacker can target invisible defender at range with no penalty: E[dmg] = 5×0.3 = 1.5',
    a: { rtbType:'missile', rtb:5, hp:10, abilities: { illusionImmunity: true } },
    b: { def:0, hp:10, abilities: { invisibility: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.500 },
  },
  invisibilityCounter: {
    desc: 'Invisible attacker: B counter gets −10% to hit penalty. A: 1×0.3=0.3; B counter: 5×0.2=1.0',
    a: { atk:1, def:0, hp:10, abilities: { invisibility: true } },
    b: { atk:5, def:0, hp:10 },
    expected: { dmgToA: 1.000, dmgToB: 0.300 },
  },
  invisibilityIllusionImmuneNoPenalty: {
    desc: 'Illusion Immune attacker ignores invisibility: full 30% hit, E[dmg] = 5×0.3 = 1.5',
    a: { atk:5, hp:10, abilities: { illusionImmunity: true } },
    b: { def:0, hp:10, abilities: { invisibility: true } },
    expected: { dmgToA: 0, dmgToB: 1.500 },
  },
  invisibilityDoomIgnores: {
    desc: 'Doom bypasses to-hit so invisibility penalty is irrelevant: floor(5/2) = 2 damage',
    a: { atk:5, hp:10, abilities: { doom: true } },
    b: { def:5, toBlkMod:70, hp:10, abilities: { invisibility: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Doom Damage ---
  doomDamageMelee: {
    desc: 'Doom Damage Melee: 1 fig 5 atk doom vs 5 def — bypasses to-hit and defense, floor(5/2) = 2 damage',
    a: { atk:5, hp:10, abilities: { doom: true } },
    b: { def:5, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  doomDamageMultiFig: {
    desc: 'Doom Damage Multi-fig: 4 figs × floor(2/2)=1 atk doom vs 5 def — exact 4 damage, ignores defense',
    a: { figs:4, atk:2, hp:10, abilities: { doom: true } },
    b: { def:5, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  doomDamageRanged: {
    desc: 'Doom Damage Ranged: 1 fig 5 missile doom vs 5 def — floor(5/2) = 2 damage, no distance penalty',
    a: { rtbType:'missile', rtb:5, hp:10, abilities: { doom: true } },
    b: { def:5, toBlkMod:70, hp:10 },
    rangedCheck: true, rangedDist: 9,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  doomDamageThrownAffected: {
    desc: 'Doom Damage applies to thrown + melee: 2 thrown doom + 4 melee doom vs 5 def, 20 hp — floor(4/2) + floor(2/2) = 2 + 1 = 3',
    a: { atk:4, rtbType:'thrown', rtb:2, hp:10, abilities: { doom: true } },
    b: { def:5, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  doomDamageCounter: {
    desc: 'Doom Damage Counter: defender 5 atk doom vs attacker 5 def — counter is floor(5/2) = 2 damage',
    a: { atk:1, toHitMod:70, def:5, toBlkMod:70, hp:10 },
    b: { atk:5, hp:10, abilities: { doom: true } },
    expected: { dmgToA: 2.000, dmgToB: 1.000 },
  },

  // --- Holy Bonus ---
  holyBonusMeleeAtk: {
    desc: 'Holy Bonus Melee Atk: base 1 atk + HB 2 → effective 3 atk, 100% hit vs 0 def → 3 dmg',
    a: { atk:1, toHitMod:70, hp:10, abilities: { holyBonus: 2 } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  holyBonusDef: {
    desc: 'Holy Bonus Defense: 2 atk 100% hit vs base def 1 + HB 2 → effective 3 def, 100% block → all blocked',
    a: { atk:2, toHitMod:70, hp:10 },
    b: { def:1, toBlkMod:70, hp:10, abilities: { holyBonus: 2 } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  holyBonusRes: {
    desc: 'Holy Bonus Resistance: Poison 4 vs base res 5 + HB 2 → effective res 7, pFail 30%, E[dmg]=1.2',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { holyBonus: 2 } },
    expected: { dmgToA: 0, dmgToB: 1.200 },
  },
  holyBonusRangedMoM: {
    desc: 'Holy Bonus Ranged (MoM 1.31): HB does NOT boost ranged atk. rtb 1 + HB 2 → still 1 hit',
    version: V_MOM_131,
    a: { rtbType:'missile', rtb:1, toHitRtbMod:70, hp:10, abilities: { holyBonus: 2 } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  holyBonusRangedCoM2: {
    desc: 'Holy Bonus Ranged (CoM2): HB boosts ranged atk. rtb 1 + HB 2 → 3 hits, 100% hit vs 0 def → 3 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:1, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { holyBonus: 2 } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },

  // --- Supreme Light ---
  supremeLightLifeCreatureMeleeCoM: {
    desc: 'Supreme Light (CoM): Life creature gains +2 melee. atk 1 → 3, 100% hit vs 0 def → 3 dmg',
    version: V_COM,
    a: { atk:1, toHitMod:70, hp:10, unitType: 'fantastic_life', abilities: { supremeLight: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  supremeLightCasterRangedCoM2: {
    desc: 'Supreme Light (CoM2): Caster unit gains +2 ranged. rtb 1 → 3, 100% hit vs 0 def → 3 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:1, type:'magic' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { supremeLight: true, caster: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  supremeLightDefenseFromResistanceCoM2: {
    desc: 'Supreme Light (CoM2): Life creature with res 8 gains floor(8/3)=2 defense. 6 atk 100% hit vs 2 def → E[dmg]=5.4',
    version: V_COM2,
    a: { atk:6, hitChance:70, hp:10 },
    b: { res:8, hp:10, unitType: 'fantastic_life', abilities: { supremeLight: true } },
    expected: { dmgToA: 0, dmgToB: 5.400 },
  },
  supremeLightNonEligibleNoBonusCoM2: {
    desc: 'Supreme Light (CoM2): normal non-Caster unit gets no bonus. atk 1 stays 1 → 1 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { supremeLight: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },

  // --- Breakthrough ---
  breakthroughMeleeCoM2: {
    desc: 'Breakthrough (CoM2) +1melee: base 1 atk becomes 2, 100% hit vs 0 def → 2.0 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { breakthrough: 'melee' } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  breakthroughMeleeDefAttackCoM2: {
    desc: 'Breakthrough (CoM2) +1melee/+1def still grants the +1 melee attack on offense: base 1 atk becomes 2 → 2.0 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { breakthrough: 'meleeDef' } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  breakthroughLiveFantasticStillNormalCoM2: {
    desc: 'Breakthrough (CoM2) admits the normal package on the permanent record: Chaos Channels makes the attacker live-Fantastic over a non-Fantastic base, and the block tests `not B.Fantastic`, so the +1 melee still lands. atk 1 becomes 2 → 2.0 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { breakthrough: 'melee', ccDefense: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  breakthroughLiveFantasticStillNormalWarlord: {
    desc: 'Breakthrough (Warlord) admits the normal package on the permanent record: Chaos Channels makes the attacker live-Fantastic over a non-Fantastic base, and the block tests `not B.Fantastic`, so the +1 melee still lands. atk 1 becomes 2 → 2.0 dmg',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { breakthrough: 'melee', ccDefense: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  breakthroughMeleeDefDefenseCoM2: {
    desc: 'Breakthrough (CoM2) derives its normal package from identity: the exceptional +def label cannot override a normal unit, so defense stays 0 and 1 hit deals 1 damage.',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10 },
    b: { def:0, hp:10, abilities: { breakthrough: 'meleeDef' } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },

  // --- Combat Discipline / Overland Discipline ---
  combatDisciplineEliteNegatesFirstStrikeCoM2: {
    desc: 'Combat Discipline (CoM2): Elite+ grants Negate First Strike, so the defender cancels First Strike and trades damage normally',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { firstStrike: true, illusion: true } },
    b: { atk:2, hitChance:70, hp:10, level:'elite', abilities: { discipline: 'combat' } },
    expected: { dmgToA: 5.000, dmgToB: 10.000 },
  },
  overlandDisciplineDefenseNormalCoM2: {
    desc: 'Overland Discipline (CoM2): normal unit gets +1 defense. 2 missile atk at 100% vs def 1 at 100% block → 1 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { discipline: 'overland' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  overlandDisciplineDefenseRegularCoM2: {
    desc: 'Overland Discipline (CoM2): Regular+ gets another +1 defense. 3 missile atk at 100% vs def 2 at 100% block → 1 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:3, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, level:'regular', abilities: { discipline: 'overland' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  overlandDisciplineVeteranMeleeCoM2: {
    desc: 'Overland Discipline (CoM2): Veteran+ gets +1 melee attack. base 1 + veteran 2 + discipline 1 = 4 → 4 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, level:'veteran', abilities: { discipline: 'overland' } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  overlandDisciplineVeteranMissileCoM2: {
    desc: 'Overland Discipline (CoM2): Veteran+ gets +1 non-magical ranged. missile 1 + veteran 2 + discipline 1 = 4 → 4 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:1, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, level:'veteran', abilities: { discipline: 'overland' } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  overlandDisciplineVeteranMagicRangedNoBonusCoM2: {
    desc: 'Overland Discipline (CoM2): Veteran+ does not boost magical ranged. magic 1 + veteran 2 = 3, not 4',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:1, type:'magic' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, level:'veteran', abilities: { discipline: 'overland' } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },

  // --- Destiny ---
  destinyDefenseAndHealthCoM2: {
    desc: 'Destiny (CoM2): defender gets +4 defense and doubled HP. 24 atk vs def 4 at 100% block leaves 20 damage, which now fits under the 20 HP cap',
    version: V_COM2,
    a: { atk:24, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { destiny: true } },
    expected: { dmgToA: 0, dmgToB: 20.000 },
  },
  destinyGrantsSupernaturalCoM2: {
    desc: 'Destiny (CoM2): enchanted unit becomes Supernatural. doubled melee 3→6 fully blocked still deals round(6/3) = 2 damage',
    version: V_COM2,
    a: { atk:3, hitChance:70, hp:10, abilities: { destiny: true } },
    b: { def:6, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  destinyMeleeRemovesLevelsCoM2: {
    desc: 'Destiny (CoM2): doubles base melee but removes veterancy. Veteran base 1 becomes 2, not 4',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, level:'veteran', abilities: { destiny: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  destinyRangedDoublesBaseCoM2: {
    desc: 'Destiny (CoM2): doubles base ranged attack strength. missile 2 becomes 4',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { destiny: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  destinyFireBreathDoublesCoM2: {
    desc: 'Destiny (CoM2): the doubling reaches Fire Breath ($0059A51F), which the modern engine keeps in its own channel rather than in the ranged field. Melee 0 isolates the breath: strength 3 doubles to 6 at 100% hit vs def 0; without Destiny the same setup deals 3.0. The 30 HP defender keeps both values clear of the HP pool.',
    version: V_COM2,
    a: { atk:0, modernAttacks: { fireBreath: { strength:3, type:'fire' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { destiny: true } },
    b: { def:0, hp:30 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  destinyLightningBreathDoublesCoM2: {
    desc: 'Destiny (CoM2): the doubling reaches Lightning Breath ($0059A559), a channel independent of both ranged and Fire Breath. Melee 0 isolates the breath: strength 4 doubles to 8 at 100% hit vs def 0; without Destiny 4.0. The 30 HP defender keeps both values clear of the HP pool.',
    version: V_COM2,
    a: { atk:0, modernAttacks: { lightningBreath: { strength:4, type:'lightning' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { destiny: true } },
    b: { def:0, hp:30 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  destinyThrownDoublesCoM2: {
    desc: 'Destiny (CoM2): the doubling reaches Thrown ($0059A593), the last of the six doubled attack/HP fields. Melee 0 isolates the Thrown attack: strength 5 doubles to 10 at 100% hit vs def 0; without Destiny 5.0. The 30 HP defender keeps both values clear of the HP pool.',
    version: V_COM2,
    a: { atk:0, modernAttacks: { thrown: { strength:5, type:'thrown' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { destiny: true } },
    b: { def:0, hp:30 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  destinyResistanceAndHpCoM2: {
    desc: 'Destiny (CoM2): +4 resistance and doubled HP turn Death Gaze vs res 3 / hp 10 into res 7 / hp 20, for 6 damage on average',
    version: V_COM2,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:3, hp:10, abilities: { destiny: true } },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  destinyAfterLuckyStarWarlord: {
    desc: 'Ordered Apotheosis (Warlord): Warlord renames Destiny to Apotheosis, so the Apotheosis control is the one that reaches this version — the CoM2-named Destiny control is hidden here and selecting it would leave Lucky Star running alone. Lucky Star adds +1 melee in UnitCalcPre, then Apotheosis doubles the live 3+1 to 8. At 100% hit vs def 0 → 8.0; without it 4.0, and applying the doubling before the hook would deal 7.0.',
    version: V_WARLORD,
    a: { atk:3, hitChance:70, hp:10, abilities: { luckyStar: true, apotheosis: true } },
    b: { def:0, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },

  // --- Focus Magic ---
  focusMagicMagicRangedCoM2: {
    desc: 'Focus Magic (CoM2): magical ranged gets +3. magic 4 → 7, 100% hit vs 0 def → 7.0',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:4, type:'magic' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { focusMagic: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  focusMagicMagicalRangedIgnoresLiveStrengthWarlord: {
    desc: 'Focus Magic (Warlord): the magical-ranged +3 is the fourth arm of the ranged branch ($0059AAA3), reached on `B.ranged <> 0` and a magical `B.rangedtype` — both permanent-record reads, and the arm makes no live-strength test of its own (Units.RecalculateUnits.pas:874-909). Plague is region `b`, so its −3 has already driven the magic 2 to −1 by the time the branch runs; the arm still adds 3, and the region-`e` clamp settles it at 2. Ranged mode at 100% To Hit → 2.0. Gating the +3 on live strength instead loses the attack outright for 0.0, and removing Focus Magic does exactly that.',
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:2, type:'magic' } }, hitRanged:80, hitThrown:80, hitBreath:80, hp:10,
      abilities: { focusMagic: true, plague: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  focusMagicBreathCoM2: {
    desc: 'Focus Magic (CoM2): breath gets +3. fire breath 2 → 5 plus melee 1 → 6.0',
    version: V_COM2,
    a: { atk:1, hitChance:70, modernAttacks: { fireBreath: { strength:2, type:'fire' } }, hp:10, abilities: { focusMagic: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  focusMagicConvertsMissileCoM2: {
    desc: 'Focus Magic (CoM2): missile 5 converts to magic 5, bypassing Missile Immunity → 5.0',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:5, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { focusMagic: true } },
    b: { hp:10, abilities: { missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  focusMagicPreservesLowMissileCoM2: {
    desc: 'Focus Magic (CoM2): missile 1 converts to magic at the same strength, bypassing Missile Immunity → 1.0. Raising it to the CoM 1 minimum of 3 would deal 3.0; failing to convert it would deal 0.',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:1, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { focusMagic: true } },
    b: { hp:10, abilities: { missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  focusMagicConvertsThrownCoM2: {
    desc: 'Focus Magic (CoM2): thrown 5 converts to magic 5, so ranged mode uses a magical ranged attack and bypasses Missile Immunity → 5.0',
    version: V_COM2,
    a: { modernAttacks: { thrown: { strength:5, type:'thrown' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { focusMagic: true } },
    b: { hp:10, abilities: { missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  focusMagicFollowsLionheartCoM: {
    desc: 'Ordered Focus Magic (CoM 1): Lionheart is com1:0x8F660 and Focus Magic com1:0x8F7E6, so the +3 reads the still-Missile type and lands — missile 2 + 3 = 5 — and the later conversion retypes that 5 to magic_s, which Missile Immunity does not stop: 5.0. Reading the converted type at Lionheart\'s position would leave 2, raised to the branch minimum of 3; without Focus Magic the missile 5 is stopped outright for 0.',
    version: V_COM,
    a: { rtbType:'missile', rtb:2, toHitRtbMod:70, hp:10,
      abilities: { lionheart: true, focusMagic: true } },
    b: { hp:10, abilities: { missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  focusMagicGrantsRangedCoM2: {
    desc: 'Focus Magic (CoM2): no qualifying attack grants strength-3 magic ranged; at base 30% To Hit that averages 0.9 dmg',
    version: V_COM2,
    a: { hp:10, abilities: { focusMagic: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.900 },
  },
  focusMagicCreationAfterLevelCoM2: {
    desc: 'Ordered Focus Magic (CoM2): Champion on an attack-less unit resolves before Focus creates strength-3 magic ranged, so the new field gets no level bonus. At 100% hit → 3.0',
    version: V_COM2,
    a: { atk:0, level:'champion', hitRanged:70, hitThrown:70, hitBreath:70, hp:10,
      abilities: { focusMagic: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  focusMagicDoomGazeBoostCoM2: {
    desc: 'Focus Magic (CoM2): doom gaze gets +3. doom gaze 4 → 7 exact damage',
    version: V_COM2,
    a: { hp:10, abilities: { focusMagic: true, doomGaze: 4 } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  // The two members below are one fixture under two versions, which is what a version-difference
  // pair has to be. A doom gaze is held differently by the two engines — the DOS record keeps its
  // strength in the shared RTB slot while CoM2 keeps it in the ability row — so each half states
  // the same unit in its own engine's notation. Selecting the type-104 slot also arms the stoning
  // and death kill loops in the DOS build, so the defender's Resistance is put out of their reach
  // and only the doom strength is left to measure. Both engines reach `+3` on the gaze, so the
  // difference the pair measures is **what else the block does**, which ranged mode exposes.
  focusMagicDoomGazeCoM: {
    desc: 'Focus Magic (CoM 1): one three-way branch, and a doom-gaze template takes its first arm — the unit type\'s ranged type 104 satisfies `>= 30 and <> 100` (com1:0x8F825/0x8F829) — so the gaze goes 2 → 5 and **no ranged attack is created**. Ranged mode at 100% To Hit therefore falls back to melee and only the gaze lands, for 5.0. The paired focusMagicDoomGazeCoM2 runs the same unit on the engine whose gaze clause and ranged-creation branch are independent tests, so there the created strength-3 magic attack fires and the gaze does not, for 3.0. Removing Focus Magic leaves 2 here; retyping the slot as arm 3 would leaves the gaze at 2 and fires a created 3.',
    version: V_COM,
    a: { rtbType:'gaze_multiple', rtb:2, toHitRtbMod:70, hp:10,
      abilities: { focusMagic: true, doomGaze: 2 } },
    b: { def:0, res:50, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  focusMagicDoomGazeCoM2: {
    desc: 'Focus Magic (CoM2): the doomgaze +3 test ($0059A66D) and the ranged-creation branch ($0059A790) are independent tests that both run (Units.RecalculateUnits.pas:873-910), so a doom-gaze unit gains the strength-3 magic ranged attack as well. Ranged mode at 100% To Hit fires that attack and the gaze does not, for 3.0 — against the 5.0 the CoM 1 member of this pair reports for the same unit, whose single branch spends itself on the gaze and creates nothing. Without Focus Magic there is no ranged attack, the exchange falls back to melee and the bare gaze deals 2.0. The gaze half alone is focusMagicDoomGazeBoostCoM2.',
    version: V_COM2,
    a: { hitRanged:70, hitThrown:70, hitBreath:70, hp:10,
      abilities: { focusMagic: true, doomGaze: 2 } },
    b: { def:0, res:50, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  focusMagicDoomGazeRangedBranchCoM2: {
    desc: 'The other half of the same independence: a doom-gaze-only CoM2 unit still gets Focus Magic\'s created strength-3 magic ranged attack ($0059A790), so the +3 gaze clause does not consume it. Ranged mode at 100% hit → 3.0; without Focus Magic the unit has no ranged attack, the exchange falls back to melee and only the bare gaze lands, for 2.0.',
    version: V_COM2,
    a: { hitRanged:70, hitThrown:70, hitBreath:70, hp:10,
      abilities: { focusMagic: true, doomGaze: 2 } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  // Arm 1 of CoM 1's three-way branch tests the **unit type's** ranged type for
  // `>= RAT_MAGIC_FIRST and <> RAT_THROWN` (com1:0x8F825, com1:0x8F829, both signed), so it admits
  // 101-105 — the two breaths and all three gazes — beside magical ranged, and it makes no
  // strength test. The four presets below hold that reach and the two shapes of arm 3.
  focusMagicStoningGazeCoM: {
    desc: 'Focus Magic (CoM 1): arm 1 admits a gaze template, so a stoning gaze of 2 becomes 5 exact damage. The gaze rides the DOS shared slot, which is the value the +3 lands on (com1:0x8F82D). Removing Focus Magic leaves 2, and so does treating the gaze as arm 3\'s fallback — retyping the slot to a magical ranged attack leaves the gaze itself at 2. Melee mode: gazes do not fire in the ranged sequence. Resistance 50 puts the petrify roll out of reach, so the gaze strength is all that is measured.',
    version: V_COM,
    a: { rtbType:'gaze_stoning', rtb:2, toHitRtbMod:70, hp:10, abilities: { focusMagic: true } },
    b: { def:0, res:50, hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  focusMagicBreathIgnoresLiveStrengthCoM: {
    desc: 'Focus Magic (CoM 1): arm 1 makes no strength test at all (com1:0x8F825 straight to the +3 at com1:0x8F82D), so a fire-breath template standing at strength 0 still takes it. Melee 1 at 100% plus the breath raised 0 → 3 deals 4.0; a fabricated `strength > 0` gate on the arm leaves the breath at 0 for 1.0, which is also what removing Focus Magic gives.',
    version: V_COM,
    a: { atk:1, toHitMod:70, rtbType:'fire', rtb:0, toHitRtbMod:70, hp:10,
      abilities: { focusMagic: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  focusMagicConvertsZeroThrownCoM: {
    desc: 'Focus Magic (CoM 1): a Thrown template is excluded from arm 1 by `base_rt <> RAT_THROWN` (com1:0x8F829) and from arm 2 by `> RAT_THROWN` (com1:0x8F839), so it falls to arm 3 whatever its strength — retyped to shot type 34 and floored at 3 (com1:0x8F840, com1:0x8F84C). Ranged mode at 100% To Hit → 3.0. Gating the conversion on positive Thrown strength leaves the unit with no ranged attack for 0.0, which is also what removing Focus Magic gives.',
    version: V_COM,
    a: { rtbType:'thrown', rtb:0, toHitRtbMod:70, hp:10, abilities: { focusMagic: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  focusMagicFloorsTypelessSlotCoM: {
    desc: 'Focus Magic (CoM 1): arm 3 floors rather than assigns — `if (bu->ranged < 3) bu->ranged = 3` (com1:0x8F845, com1:0x8F84C) — so a typeless slot already carrying 4 keeps 4 after the retype to shot type 34. Ranged mode at 100% To Hit → 4.0; assigning 3 instead cuts it to 3.0, and removing Focus Magic leaves the slot typeless with no ranged attack, for 0.0.',
    version: V_COM,
    a: { rtbType:'none', rtb:4, toHitRtbMod:70, hp:10, abilities: { focusMagic: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Blazing Eyes ---
  blazingEyesChaosCreatureGetsDoomGazeCoM2: {
    desc: 'Blazing Eyes (CoM2): Chaos creature gains Doom Gaze 3 → 3 exact damage',
    version: V_COM2,
    a: { hp:10, unitType:'fantastic_chaos', abilities: { blazingEyes: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  blazingEyesChaosCreatureUpgradesDoomGazeCoM2: {
    desc: 'Blazing Eyes (CoM2): Chaos creature with Doom Gaze 4 gets +1 instead of replacing it, so it deals 5 exact damage',
    version: V_COM2,
    a: { hp:10, unitType:'fantastic_chaos', abilities: { blazingEyes: true, doomGaze: 4 } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  blazingEyesChaosChannelsEligibleCoM2: {
    desc: 'Blazing Eyes (CoM2): a normal unit transformed to fantastic_chaos by Chaos Channels qualifies and gains Doom Gaze 3',
    version: V_COM2,
    a: { hp:10, unitType:'normal', abilities: { blazingEyes: true, ccDefense: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  blazingEyesLandsAfterFocusMagicCoM2: {
    desc: 'Blazing Eyes is a region-c block at $005A1E16, later than Focus Magic\'s doom-gaze clause `if U.doomgaze > 0` at $0059A66D, so a Doom Gaze this block conjures is not one Focus Magic can find: the Chaos creature ends at Doom Gaze 3 and deals 3 exact damage. Melee mode, so Focus Magic\'s separately created magic ranged attack does not fire. Removing Blazing Eyes leaves no gaze and 0; removing Focus Magic leaves the same 3, which is the point. Before F174 the grant was folded into the base seed, Focus Magic saw it there, and the unit dealt 6.',
    version: V_COM2,
    a: { hp:10, unitType:'fantastic_chaos', abilities: { blazingEyes: true, focusMagic: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  chaosEmbraceLandsAfterFocusMagicWarlord: {
    desc: 'The Warlord arm of the same order: Chaos Embrace is Blazing Eyes renamed, writes the same $005A1E16 block, and still lands after Focus Magic ($0059A66D), so the conjured Doom Gaze 3 deals 3 exact damage rather than the 6 a base-seeded grant would have reached.',
    version: V_WARLORD,
    a: { hp:10, unitType:'fantastic_chaos', abilities: { chaosEmbrace: true, focusMagic: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  blazingEyesNonChaosNoUpgradeCoM2: {
    desc: 'Blazing Eyes (CoM2): non-Chaos creature with Doom Gaze 4 does not get the +1 bonus, so it stays at 4 damage',
    version: V_COM2,
    a: { hp:10, unitType:'fantastic_nature', abilities: { blazingEyes: true, doomGaze: 4 } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Inner Power ---
  innerPowerFireImmunityMeleeCoM2: {
    desc: 'Inner Power (CoM2): Fire Immunity unit gets +3 melee, so atk 1 becomes 4 → 4 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { innerPower: true, fireImmunity: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  innerPowerLightningResistRangedCoM2: {
    desc: 'Inner Power (CoM2): Lightning Resist unit gets +3 to magical ranged, so magic 2 becomes 5 → 5 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'magic' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { innerPower: true, lightningResist: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  innerPowerDefenseCoM2: {
    desc: 'Inner Power (CoM2): eligible defender gets +2 defense, so 5 atk 100% hit vs def 2 at 30% block → 4.4 dmg',
    version: V_COM2,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, hp:10, abilities: { innerPower: true, fireImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 4.400 },
  },
  innerPowerResistanceCoM2: {
    desc: 'Inner Power (CoM2): eligible defender gets +2 resistance, so Death Gaze vs res 5 becomes res 7 → 3 dmg',
    version: V_COM2,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, abilities: { innerPower: true, lightningResist: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  innerPowerNoTraitNoBonusCoM2: {
    desc: 'Inner Power (CoM2): unit without Fire Immunity or Lightning Resist gets no bonus, so atk 1 stays 1 → 1 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { innerPower: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  innerPowerBreathNotThrownCoM2: {
    desc: 'Exclusion the engine makes: the block\'s three secondary writes are `U.ranged`, `U.firebreath` and `U.lightningbreath`, each on its own `> 0` test, and its decode note says in as many words that it does not alter Thrown (Units.RecalculateUnits.pas:1877-1884). Fire Breath 5 → 8 while Thrown 3 stays 3, so 3 + 8 = 11.000 at 100% hit vs def 0. A grant reaching every channel, as this block made before F139, gives 6 + 8 = 14.000.',
    version: V_COM2,
    a: { atk:0, modernAttacks: { thrown: { strength: 3, type: 'thrown' },
      fireBreath: { strength: 5, type: 'fire' } },
    hitRanged:70, hitThrown:70, hitBreath:70, hp:10,
    abilities: { innerPower: true, fireImmunity: true } },
    b: { def:0, hp:30 },
    expected: { dmgToA: 0, dmgToB: 11.000 },
  },
  innerPowerDoomGazeUnchangedCoM2: {
    desc: 'Exclusion the engine makes: `U.doomgaze` is an independent record field named by no line of the Inner Power block (Units.RecalculateUnits.pas:1866-1885). Doom Gaze 5 still deals 5.000; the pre-F139 write gave 8.000.',
    version: V_COM2,
    a: { atk:0, hp:10, abilities: { innerPower: true, fireImmunity: true, doomGaze: 5 } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },

  // --- Orihalcon ---
  orihalconMagicRangedBonusCoM2: {
    desc: 'Orihalcon (CoM2): magical ranged gets +2 strength, so magic 2 becomes 4 → 4 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'magic' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, armor:'orihalcon' },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  orihalconResBonusCoM2: {
    desc: 'Orihalcon (CoM2): +1 resistance, so res 5 becomes 6 → death gaze 40% kill chance → 4 expected damage',
    version: V_COM2,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, armor:'orihalcon' },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  orihalconNoMissileBonusCoM2: {
    desc: 'Orihalcon (CoM2): non-magical missile ranged gets no +2 attack bonus, so missile 2 stays 2 → 2 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, armor:'orihalcon' },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  orihalconFocusMagicConvertedCoM2: {
    desc: 'Orihalcon (CoM2): Focus Magic preserves missile strength 2 while converting it to magic, then Orihalcon adds +2 → 4 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, armor:'orihalcon', abilities: { focusMagic: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Reinforce Magic ---
  reinforceMagicResistanceCoM2: {
    desc: 'Reinforce Magic (CoM2): all units gain +2 resistance, so Death Gaze vs res 5 becomes res 7 → 3 dmg',
    version: V_COM2,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, abilities: { reinforceMagic: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  reinforceMagicMagicRangedCoM2: {
    desc: 'Reinforce Magic (CoM2): magical ranged gets +2 strength, so magic 2 becomes 4 → 4 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'magic' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { reinforceMagic: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  reinforceMagicMissileNoBonusCoM2: {
    desc: 'Reinforce Magic (CoM2): non-magical missile ranged gets no +2 attack bonus, so missile 2 stays 2 → 2 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { reinforceMagic: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  reinforceMagicFocusConvertedCoM2: {
    desc: 'Reinforce Magic (CoM2): Focus Magic preserves missile strength 2 while converting it to magic, then Reinforce Magic adds +2 → 4 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { reinforceMagic: true, focusMagic: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Survival Instinct ---
  survivalInstinctFantasticBonusCoM2: {
    desc: 'Survival Instinct (CoM2): fantastic creature gets +10% To Hit, so atk 1 at base 30% becomes 40% → 0.4 dmg',
    version: V_COM2,
    a: { atk:1, hp:10, unitType: 'fantastic_nature', abilities: { survivalInstinct: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  survivalInstinctTransformedEligibleCoM2: {
    desc: 'Survival Instinct (CoM2): a normal unit transformed by Chaos Channels counts as fantastic_chaos and gains the +10% To Hit bonus → 0.4 dmg',
    version: V_COM2,
    a: { atk:1, hp:10, unitType: 'normal', abilities: { survivalInstinct: true, ccDefense: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  survivalInstinctSpiritLinkAssertsFantasticWarlord: {
    desc: 'Survival Instinct (Warlord) on a Spirit-Linked normal unit: the block tests the calculated record, `if U.Fantastic` at $005A1664 (Units.RecalculateUnits.pas), and Spirit Link asserts Fantastic in region b at UnitCalcPre.CAS:30, so the +10% To Hit applies where it stands — atk 1 at base 30% becomes 40% → 0.4 dmg, against the 0.3 the same unit deals without Spirit Link. Reading the pre-pass fixed point instead answered for the region-d clearing write at UnitCalc.CAS:1306, which is past this block, and gave 0.3.',
    version: V_WARLORD,
    a: { atk:1, hp:10, unitType: 'normal', abilities: { survivalInstinct: true, spiritLink: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },

  // --- Guardian ---
  guardianToHitCoM: {
    desc: 'Guardian (CoM): +10% To Hit, so atk 1 at base 30% becomes 40% → 0.4 dmg',
    version: V_COM,
    a: { atk:1, toHitMod:0, hp:10, abilities: { guardian: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  guardianToDefendCoM2: {
    desc: 'Guardian (CoM2): defender gets +10% To Defend, so 5 hits vs 1 shield at 40% block → 4.6 dmg',
    version: V_COM2,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:1, toBlkMod:0, hp:10, abilities: { guardian: true } },
    expected: { dmgToA: 0, dmgToB: 4.600 },
  },
  guardianResistanceCoM2: {
    desc: 'Guardian (CoM2): +1 resistance, so Death Gaze vs res 5 becomes res 6 → 4 dmg',
    version: V_COM2,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, abilities: { guardian: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Tactician ---
  tacticianNormalDefenseCoM: {
    desc: 'Tactician (CoM): non-hero unit gets +1 defense. 5 hits vs 1 shield at 100% block → 4 dmg',
    version: V_COM,
    a: { atk:5, toHitMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { tactician: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  tacticianHeroAttackCoM2: {
    desc: 'Tactician (CoM2): hero gets +2 melee attack. atk 1 becomes 3 → 3 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, unitType: 'hero', abilities: { tactician: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  tacticianHeroRangedCoM2: {
    desc: 'Tactician (CoM2): hero gets +2 to ranged attack strength. missile 1 becomes 3 → 3 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:1, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, unitType: 'hero', abilities: { tactician: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  tacticianHeroThrownUnchangedCoM2: {
    desc: 'Tactician (CoM2) writes only conventional ranged: a hero\'s Thrown 1 stays 1 instead of receiving +2.',
    version: V_COM2,
    a: { atk:0, modernAttacks: { thrown: { strength:1, type:'thrown' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10,
      unitType:'hero', abilities: { tactician: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  tacticianHeroDefenseCoM2: {
    desc: 'Tactician (CoM2): hero gets +2 defense. 5 hits vs 2 shields at 100% block → 3 dmg',
    version: V_COM2,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, unitType: 'hero', abilities: { tactician: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  tacticianHeroResistanceCoM2: {
    desc: 'Tactician (CoM2): hero gets +2 resistance, so Death Gaze vs res 5 becomes res 7 → 3 dmg',
    version: V_COM2,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, unitType: 'hero', abilities: { tactician: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  tacticianHeroDefenseWarlord: {
    desc: 'Tactician (Warlord): hero gets only +1 defense (not +2). 5 hits vs 1 shield at 100% block → 4 dmg',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, unitType: 'hero', abilities: { tactician: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  tacticianTeleportingFirstStrikeWarlord: {
    desc: 'Tactician (Warlord): teleporting unit gains First Strike — kills B before B can counter',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { tactician: true, teleporting: true } },
    b: { atk:5, hitChance:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  tacticianNonCorporealNegateFirstStrikeWarlord: {
    desc: 'Tactician (Warlord): non-corporeal unit gains Negate First Strike — B survives to retaliate (dmgToA=5)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { firstStrike: true } },
    b: { atk:5, hitChance:70, hp:9, toBlkMod:70, abilities: { tactician: true, nonCorporeal: true } },
    expected: { dmgToA: 5.000, dmgToB: 9.000 },
  },
  tacticianWraithFormNegateFirstStrikeWarlord: {
    desc: 'Tactician (Warlord): Wraith Form unit gains Negate First Strike — B survives to retaliate (dmgToA=5)',
    version: V_WARLORD,
    a: { atk:12, hitChance:70, hp:10, abilities: { firstStrike: true } },
    b: { atk:5, hitChance:70, hp:1, toBlkMod:70, abilities: { tactician: true, wraithForm: true } },
    expected: { dmgToA: 5.000, dmgToB: 1.000 },
  },
  tacticianRulerNegateFirstStrikeWarlord: {
    desc: 'Tactician (Warlord): Ruler of Underworld unit gains Negate First Strike — B survives to retaliate (dmgToA=5)',
    version: V_WARLORD,
    a: { atk:12, hitChance:70, hp:10, abilities: { firstStrike: true } },
    b: { atk:5, hitChance:70, hp:1, toBlkMod:70, abilities: { tactician: true, rulerOfUnderworld: true } },
    expected: { dmgToA: 5.000, dmgToB: 1.000 },
  },

  // --- Favored Terrain ---
  favoredTerrainDefenseWarlord: {
    desc: 'Favored Terrain (Warlord): unit on favored tile gets +1 defense. 5 hits vs 1 shield at 100% block → 4 dmg',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { favoredTerrain: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  favoredTerrainToHitWarlord: {
    desc: 'Favored Terrain (Warlord): unit on favored tile gets +5% To Hit. 10 dice at 30%+5%=35% → 3.5 dmg',
    version: V_WARLORD,
    a: { atk:10, hp:10, abilities: { favoredTerrain: true } },
    b: { def:0, atk:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 3.500 },
  },
  favoredTerrainTacticianDefenseWarlord: {
    desc: 'Favored Terrain + Tactician (Warlord): terrain bonus doubled (+2 def) stacks with Tactician +1 def → +3. 5 hits vs 3 shields at 100% block → 2 dmg',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { favoredTerrain: true, tactician: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  favoredTerrainTacticianToHitWarlord: {
    desc: 'Favored Terrain + Tactician (Warlord): To Hit bonus doubled to +10%. 10 dice at 30%+10%=40% → 4.0 dmg',
    version: V_WARLORD,
    a: { atk:10, hp:10, abilities: { favoredTerrain: true, tactician: true } },
    b: { def:0, atk:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  favoredTerrainTacticianFirstStrikeWarlord: {
    desc: 'Favored Terrain + Tactician (Warlord): unit gains First Strike — kills B before B can counter (dmgToA=0)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { favoredTerrain: true, tactician: true } },
    b: { atk:5, hitChance:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  favoredTerrainTacticianNegateFirstStrikeWarlord: {
    desc: 'Favored Terrain + Tactician (Warlord): unit gains Negate First Strike — survives A\'s First Strike to retaliate (dmgToA=5)',
    version: V_WARLORD,
    a: { atk:20, hitChance:70, hp:10, abilities: { firstStrike: true } },
    b: { atk:5, hitChance:70, hp:10, toBlkMod:70, abilities: { favoredTerrain: true, tactician: true } },
    expected: { dmgToA: 5.000, dmgToB: 10.000 },
  },

  // --- Fortification ---
  fortificationRangedWarlord: {
    desc: 'Fortification Ranged (Warlord): missile 4 (100% hit) vs def 1+3=4 (100% block) → 0',
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:4, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp: 10 },
    b: { def: 1, toBlkMod: 70, hp: 10, abilities: { fortification: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  fortificationBreathWarlord: {
    desc: 'Fortification Breath (Warlord): fire breath 4 (100% hit) vs def 1+3=4 (100% block) → 0; melee 1 vs def 1 → 0',
    version: V_WARLORD,
    a: { atk: 1, hitChance:70, modernAttacks: { fireBreath: { strength:4, type:'fire' } }, hp: 10 },
    b: { atk: 0, def: 1, toBlkMod: 70, hp: 10, abilities: { fortification: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },

  fortificationLargeShieldUpgradeWarlord: {
    desc: 'Fortification on a unit that already has Large Shield grants Missile Immunity instead: missile 12 (100% hit) vs def raised to 100 → 0 (would be 12−5=7 with only Large Shield)',
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:12, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp: 10 },
    b: { def: 2, toBlkMod: 70, hp: 20, abilities: { largeShield: true, fortification: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
});
