// Numeric presets. Hillfort through Rage, the race-gated city buildings and their recruitment
// grants, and the mechanical-unit abilities (Artificer, Mechanical Expert, Rebuild).
definePresets({
  // --- Hillfort ---
  hillfortMissileWarlord: {
    desc: 'Hillfort Missile Immunity (Warlord): missile 3 (100% hit) vs def 2 raised to 50 → 0',
    version: V_WARLORD,
    a: { rtbType: 'missile', rtb: 3, hitRanged:70, hitThrown:70, hitBreath:70, hp: 10 },
    b: { def: 2, toBlkMod: 70, hp: 10, abilities: { hillfort: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  hillfortMeleeUnaffectedWarlord: {
    desc: 'Hillfort does NOT protect vs melee: atk 3 (100% hit) vs def 2 (100% block) → 1',
    version: V_WARLORD,
    a: { atk: 3, hitChance:70, hp: 10 },
    b: { atk: 0, def: 2, toBlkMod: 70, hp: 10, abilities: { hillfort: true } },
    expected: { dmgToA: 0, dmgToB: 1 },
  },

  // --- Planewalking ---
  planewalkingTacticianFirstStrikeWarlord: {
    desc: 'Planewalking grants Teleporting: Tactician + Planewalking unit gains First Strike — kills B before B can counter',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { tactician: true, planewalking: true } },
    b: { atk:5, hitChance:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },

  // --- Temporal Twist ---
  temporalTwistStripsFirstStrikeWarlord: {
    desc: 'Temporal Twist strips First Strike: A loses FS, so B retaliates simultaneously (dmgToA=5)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { firstStrike: true, temporalTwist: true } },
    b: { atk:5, hitChance:70, hp:10 },
    expected: { dmgToA: 5.000, dmgToB: 10.000 },
  },
  temporalTwistStripsNegateFirstStrikeWarlord: {
    desc: "Temporal Twist strips Negate First Strike: B loses NFS, so A's First Strike kills B before counter (dmgToA=0)",
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { firstStrike: true } },
    b: { atk:5, hitChance:70, hp:10, abilities: { negateFirstStrike: true, temporalTwist: true } },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  temporalTwistStripsTeleportingWarlord: {
    desc: 'Temporal Twist strips Teleporting: Tactician no longer grants First Strike, so B retaliates. 5 hits vs 1 shield (Tactician +1 def) at 100% block → 4 dmg',
    version: V_WARLORD,
    a: { atk:10, def:0, hitChance:70, toBlkMod:70, hp:10, abilities: { tactician: true, teleporting: true, temporalTwist: true } },
    b: { atk:5, hitChance:70, hp:10 },
    expected: { dmgToA: 4.000, dmgToB: 10.000 },
  },
  temporalTwistTacticianRestoresNonCorporealNegateWarlord: {
    desc: 'Temporal Twist clears Negate First Strike before the later Tactician step restores it from Non-Corporeal, so B survives A\'s First Strike and retaliates for 5. B\'s own Tactician also gives it +1 Defense (Units.RecalculateUnits.pas:2409-2435 grants non-heroes exactly +1), rolled here at 100% block, so A\'s 10 hits deal 9. B\'s 9 HP is load-bearing: at 10 the control that drops Non-Corporeal leaves B alive and countering too, and side A would not move.',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { firstStrike: true } },
    b: { atk:5, hitChance:70, hp:9, toBlkMod:70, abilities: { tactician: true, nonCorporeal: true, temporalTwist: true } },
    expected: { dmgToA: 5.000, dmgToB: 9.000 },
  },
  temporalTwistTacticianRestoresFavoredTerrainStrikesWarlord: {
    desc: 'Temporal Twist clears strike flags before the later Tactician Favored Terrain branch restores both; A kills B by First Strike and takes no counter damage.',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { tactician: true, favoredTerrain: true, temporalTwist: true } },
    b: { atk:5, hitChance:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },

  // --- Zeal ---
  zealGrantsFirstStrikeWarlord: {
    desc: 'Zeal grants First Strike: A kills B (10hp) before B can counter — dmgToA=0',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { zeal: true } },
    b: { atk:5, hitChance:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  zealGrantsNegateFirstStrikeWarlord: {
    desc: "Zeal grants Negate First Strike: B's Zeal cancels A's First Strike → simultaneous trade (dmgToA=5)",
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { firstStrike: true } },
    b: { atk:5, hitChance:70, hp:10, abilities: { zeal: true } },
    expected: { dmgToA: 5.000, dmgToB: 10.000 },
  },
  zealStrippedByTemporalTwistWarlord: {
    desc: 'Temporal Twist strips Zeal-granted First Strike: A loses FS, B retaliates simultaneously (dmgToA=5)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { zeal: true, temporalTwist: true } },
    b: { atk:5, hitChance:70, hp:10 },
    expected: { dmgToA: 5.000, dmgToB: 10.000 },
  },

  // --- Rage ---
  rageMeleePreCombatLossWarlord: {
    desc: 'Rage (Warlord) melee, pre-combat losses: 6-fig unit at 3 dmg (hp 1) → 3 figs alive, 3 lost → +3 melee. atk 1+3=4, 3 figs × 4 at 100% hit vs def 0 → 12 dmg',
    version: V_WARLORD,
    a: { figs:6, atk:1, hitChance:70, hp:1, dmg:3, abilities: { rage: true } },
    b: { atk:0, def:0, hp:30 },
    expected: { dmgToA: 0, dmgToB: 12.000 },
  },
  rageRangedPreCombatLossWarlord: {
    desc: 'Rage (Warlord) ranged, pre-combat losses: 6-fig unit at 3 dmg (hp 1) → 3 figs alive, 3 lost → +3 ranged. rtb 1+3=4, 3 figs × 4 at 100% hit vs def 0 → 12 dmg',
    version: V_WARLORD,
    a: { figs:6, rtbType:'missile', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:1, dmg:3, abilities: { rage: true } },
    b: { atk:0, def:0, hp:30 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 12.000 },
  },
  rageDynamicCounterFirstStrikeWarlord: {
    desc: 'Rage (Warlord) dynamic in-combat loss: A first-strikes for 3 (atk 3, 100% hit, def 0), killing 3 of B’s 6 figs (hp 1). B counters with 3 figs at atk 1 +3 Rage =4 → 12 dmg to A. Counter Rage reflects figures lost this combat.',
    version: V_WARLORD,
    a: { atk:3, hitChance:70, def:0, hp:20, abilities: { firstStrike: true } },
    b: { figs:6, atk:1, hitChance:70, def:0, hp:1, abilities: { rage: true } },
    expected: { dmgToA: 12.000, dmgToB: 3.000 },
  },

  // --- Altar of the Moon ---
  altarOfTheMoonRangedWarlord: {
    desc: 'Altar of the Moon (Warlord): ranged unit gains +2 Ranged Attack. rtb 1+2=3, 100% hit vs def 0 → 3 dmg (single full-health fig → Rage adds 0)',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, race:'Gnoll', abilities: { altarOfTheMoon: true } },
    b: { atk:0, def:0, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  altarOfTheMoonRageWarlord: {
    desc: 'Altar of the Moon (Warlord): grants Rage. 6-fig unit at 3 dmg (hp 1) → 3 figs alive, 3 lost → +3 melee. atk 1+3=4, 3 figs × 4 at 100% hit vs def 0 → 12 dmg',
    version: V_WARLORD,
    a: { figs:6, atk:1, hitChance:70, hp:1, dmg:3, race:'Gnoll', abilities: { altarOfTheMoon: true } },
    b: { atk:0, def:0, hp:30 },
    expected: { dmgToA: 0, dmgToB: 12.000 },
  },
  altarOfTheMoonPoisonImmunityWarlord: {
    desc: 'Altar of the Moon (Warlord): grants Poison Immunity. Defender immune → poison 4 negated; melee atk 1 vs def 1 at 100% block → 0 dmg (without Altar, poison would deal ~2.4)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { poison: 4 } },
    b: { atk:0, def:1, toBlkMod:70, res:5, hp:10, race:'Gnoll', abilities: { altarOfTheMoon: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  altarOfTheMoonResistanceWarlord: {
    desc: 'Altar of the Moon (Warlord): +1 Resistance. Defender res 4 +1 = 5; incoming Life Steal −3 → effective res 2 → E = sum(1..8)/10 = 3.6 (without the +1, res 4 → eff 1 → 4.5)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { lifeSteal: -3 } },
    b: { atk:0, def:1, toBlkMod:70, res:4, hp:30, race:'Gnoll', abilities: { altarOfTheMoon: true } },
    expected: { dmgToA: 0, dmgToB: 3.600 },
  },
  altarOfTheMoonNonGnollWarlord: {
    desc: 'Altar of the Moon (Warlord): a non-Gnoll unit gets no bonus. Ranged rtb 1 (100% hit) vs def 0 → 1 dmg (a Gnoll would gain +2 Ranged → 3)',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { altarOfTheMoon: true } },
    b: { atk:0, def:0, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  altarOfTheMoonHunterPoisonWarlord: {
    desc: 'Altar of the Moon (Warlord): G. Hunters gain Poison 2. Melee atk 1 vs def 1 at 100% block → 0; Poison 2 (1 fig) vs res 5 (CoM2 −1 → eff 4, pFail 0.6) → E = 2 × 0.6 = 1.2 (without the Hunters tag, Altar grants no Poison → 0)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, race:'Gnoll', name:'Gnoll Hunters', abilities: { altarOfTheMoon: true } },
    b: { atk:0, def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.200 },
  },
  altarOfTheMoonWitchdoctorLifeStealWarlord: {
    desc: 'Altar of the Moon (Warlord): G. Witchdoctors gain Life Steal −1 replacing Poison. Base Poison 2 is removed; melee atk 1 vs def 1 at 100% block → 0; Life Steal −1 vs res 5 (eff 4) → E = sum(1..6)/10 = 2.1 (without the interaction, base Poison 2 would deal 1.2 instead)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, race:'Gnoll', name:'Witchdoctors', abilities: { altarOfTheMoon: true, poison: 2 } },
    b: { atk:0, def:1, toBlkMod:70, res:5, hp:20 },
    expected: { dmgToA: 0, dmgToB: 2.100 },
  },

  // --- Altar of the Sun ---
  altarOfTheSunFigureWarlord: {
    desc: 'Altar of the Sun (Warlord): a Hawkman gains +1 Figure. 2-fig attacker → 3 figs; atk 2 × 3 figs at 100% hit vs def 0 → 6 dmg (without the Altar, 2 figs → 4)',
    version: V_WARLORD,
    a: { figs:2, atk:2, hitChance:70, hp:5, race:'Hawkmen', abilities: { altarOfTheSun: true } },
    b: { atk:0, def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  altarOfTheSunNonHawkmanWarlord: {
    desc: 'Altar of the Sun (Warlord): no Hawkman tag → no figure bonus. 2-fig attacker stays at 2 figs; atk 2 × 2 figs at 100% hit vs def 0 → 4 dmg (a Hawkman would get 6)',
    version: V_WARLORD,
    a: { figs:2, atk:2, hitChance:70, hp:5, abilities: { altarOfTheSun: true } },
    b: { atk:0, def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  altarOfTheSunHolyMotherMeleeWarlord: {
    desc: 'Altar of the Sun (Warlord): Holy Mother gains +1 Melee instead of a figure. 1-fig attacker stays at 1 fig; atk 2+1 × 1 fig at 100% hit vs def 0 → 3 dmg (without the Altar, atk 2 → 2)',
    version: V_WARLORD,
    a: { figs:1, atk:2, hitChance:70, hp:5, race:'Hawkmen', name:'Holy Mother', abilities: { altarOfTheSun: true } },
    b: { atk:0, def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  altarOfTheSunHeroExcludedWarlord: {
    desc: 'Altar of the Sun (Warlord): a Hawkman hero is excluded → no figure bonus. 1-fig attacker stays at 1 fig; atk 2 × 1 fig at 100% hit vs def 0 → 2 dmg (a non-hero Hawkman would gain +1 Figure → 4)',
    version: V_WARLORD,
    a: { figs:1, atk:2, hitChance:70, hp:5, unitType:'hero', race:'Hawkmen', abilities: { altarOfTheSun: true } },
    b: { atk:0, def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Alumni of Academy ---
  alumniOfAcademyMagicRangedWarlord: {
    desc: 'Academy (Warlord): a 6-figure Halfling magical-ranged unit gains a flat +2 figures. 1 ranged × 8 figs at 100% hit vs def 0 → 8 dmg (without Academy, 6)',
    version: V_WARLORD,
    a: { figs:6, rtbType:'magic', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:2, race:'Halfling', name:'Halfling Shamans', abilities: { alumniOfAcademy: true } },
    b: { atk:0, def:0, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  alumniOfAcademyMechanicalExcludedWarlord: {
    desc: 'Academy (Warlord): Mechanical excludes the magical-ranged branch. 1 ranged × 6 figs at 100% hit vs def 0 → 6 dmg (a non-Mechanical unit would deal 8)',
    version: V_WARLORD,
    a: { figs:6, rtbType:'magic', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:2, race:'Halfling', name:'Mechanical Shamans', abilities: { alumniOfAcademy: true, mechanical: true } },
    b: { atk:0, def:0, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  alumniOfAcademyLightningBoltWarlord: {
    desc: 'Academy (Warlord): the gate is `GetStat(U,SRangedType,1)>29` (CreateUnit.CAS:462-464) — the whole magical band, not an enumeration of realms — so the id-30 lightning-bolt projectile is inside it exactly as any other magical id is. 1 ranged × 8 figs at 100% hit vs def 0 → 8 dmg (without Academy, 6). Missile Immunity on the target is the control that the projectile is classed magical rather than physical: it blocks nothing here.',
    version: V_WARLORD,
    a: { figs:6, rtbType:'magic_lightning', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:2, race:'Halfling', name:'Halfling Stormcallers', abilities: { alumniOfAcademy: true } },
    b: { atk:0, def:0, hp:20, abilities: { missileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  alumniOfAcademyRocsWarlord: {
    desc: 'Academy (Warlord): Halfling Rocs qualify as the Fantastic Stable unit. 1 melee × (2+2) figs at 100% hit vs def 0 → 4 dmg (without Academy, 2)',
    version: V_WARLORD,
    a: { figs:2, atk:1, hitChance:70, hp:5, race:'Halfling', name:'Halfling Rocs', abilities: { alumniOfAcademy: true } },
    b: { atk:0, def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  alumniOfAcademyNonHalflingExcludedWarlord: {
    desc: 'Academy (Warlord): non-Halfling magical-ranged units cannot use the racial building. 1 ranged × 4 figs at 100% hit vs def 0 → 4 dmg (a Halfling would deal 6)',
    version: V_WARLORD,
    a: { figs:4, rtbType:'magic', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:2, race:'High Men', name:'High Men Magicians', abilities: { alumniOfAcademy: true } },
    b: { atk:0, def:0, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Dragon Mound ---
  dragonMoundFireBreathWarlord: {
    desc: 'Dragon Mound (Warlord): a Draconian unit with Fire Breath gains +2. Melee 1 vs def 1 (100% block) → 0; breath 2+2=4 (100% hit) vs def 1 (100% block) → 4−1 = 3 (without Dragon Mound, breath 2 → 2−1 = 1)',
    version: V_WARLORD,
    a: { figs:1, atk:1, hitChance:70, rtbType:'fire', rtb:2, hp:10, race:'Draconian', abilities: { dragonMound: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  dragonMoundArmorWarlord: {
    desc: 'Dragon Mound (Warlord): a Draconian unit gains +1 Armor. atk 5 (100% hit) vs def 0 + Dragon Mound → 1 shield at 100% block → 4 dmg (without Dragon Mound, def 0 → 5)',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, race:'Draconian', abilities: { dragonMound: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  dragonMoundHeroExcludedWarlord: {
    desc: 'Dragon Mound (Warlord): a Draconian hero is excluded — no +1 Armor. atk 5 (100% hit) vs def 0 → 5 dmg (a non-hero Draconian would gain +1 Armor → 1 shield at 100% block → 4 dmg)',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, unitType:'hero', race:'Draconian', abilities: { dragonMound: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  dragonMoundNonDraconianWarlord: {
    desc: 'Dragon Mound (Warlord): no Draconian tag → no bonus. Breath 2 (100% hit) vs def 0 → 2; melee 1 vs def 0 → 1; total 3 (a Draconian would get +2 breath and +1 armor → breath 4, but here def 0 means armor is moot; the point is breath stays 2)',
    version: V_WARLORD,
    a: { figs:1, atk:1, hitChance:70, rtbType:'fire', rtb:2, hp:10, abilities: { dragonMound: true } },
    b: { atk:0, def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  dragonMoundThrownNotBoostedWarlord: {
    desc: 'Dragon Mound (Warlord): the +2 creates Fire Breath and does not boost existing Thrown. Melee 1 vs def 1 (100% block) → 0; unboosted Thrown 2 and created Fire Breath 2 each deal 1 → total 2',
    version: V_WARLORD,
    a: { figs:1, atk:1, hitChance:70, rtbType:'thrown', rtb:2, hp:10, race:'Draconian', abilities: { dragonMound: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Lava Smelter ---
  // Each mineral pair records an independent permanent grant carried by a new Dwarf unit or by
  // an existing non-fantastic unit after Upgrade & Retrain.
  lavaSmelterWeaponImmunityWarlord: {
    desc: 'Lava Smelter (Warlord): a Dwarf unit gains Weapon Immunity. Normal melee atk 10 (100% hit) vs def 0 → WI +10 = 10, 100% block → all blocked → 0 (without the grant, def 0 → 10 dmg)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, race:'Dwarf', abilities: { lavaSmelterWeaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  lavaSmelterMissileImmunityWarlord: {
    desc: 'Lava Smelter (Warlord): a Dwarf unit gains Missile Immunity. Missile rtb 10 (100% hit) vs def 0 → MI raises def to 100, 100% block → all blocked → 0 (without the grant, def 0 → 10 dmg)',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, race:'Dwarf', abilities: { lavaSmelterMissileImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  lavaSmelterResistElemWarlord: {
    desc: 'Lava Smelter (Warlord): a Dwarf unit gains Resist Elements. Magic ranged rtb 6 (100% hit) vs def 0 → +4 = 4, 100% block → 2 dmg (without the grant, def 0 → 6 dmg)',
    version: V_WARLORD,
    a: { rtbType:'magic', rtb:6, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, race:'Dwarf', abilities: { lavaSmelterResistElements: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  lavaSmelterElementalArmorWarlord: {
    desc: 'Lava Smelter (Warlord): a Dwarf unit gains Elemental Armor. Magic ranged rtb 10 (100% hit) vs def 0 → +12 = 12, 100% block → all blocked → 0 (without the grant, def 0 → 10 dmg)',
    version: V_WARLORD,
    a: { rtbType:'magic', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, race:'Dwarf', abilities: { lavaSmelterElementalArmor: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  lavaSmelterFlameBladeWarlord: {
    desc: 'Lava Smelter (Warlord): a Dwarf unit gains Fiery Blade. Melee 1+3 = 4, weapon upgraded to magic so it bypasses the target Weapon Immunity → def 0, 100% block of 0 shields → 4 dmg (without the grant, melee 1 vs WI def 10 → 0 dmg)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, race:'Dwarf', abilities: { lavaSmelterFieryBlade: true } },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  lavaSmelterUpgradeRetrainNonDwarfWarlord: {
    desc: 'Lava Smelter + Upgrade & Retrain (Warlord): an existing non-Dwarf unit can carry Weapon Immunity. Normal melee atk 10 (100% hit) vs WI +10 defense, 100% block → 0 dmg',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { lavaSmelterWeaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  lavaSmelterUpgradeRetrainHeroWarlord: {
    desc: 'Lava Smelter + Upgrade & Retrain (Warlord): an existing hero can carry Weapon Immunity. Normal melee atk 10 (100% hit) vs WI +10 defense, 100% block → 0 dmg',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, unitType:'hero', abilities: { lavaSmelterWeaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  lavaSmelterFantasticExcludedWarlord: {
    desc: 'Lava Smelter + Upgrade & Retrain (Warlord): fantastic creatures are excluded. Normal melee atk 10 (100% hit) vs def 0 → 10 dmg',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, unitType:'fantastic_chaos', abilities: { lavaSmelterWeaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  lavaSmelterProtectionsStackWarlord: {
    desc: 'Lava Smelter (Warlord): Resist Elements and Elemental Armor stack as two independent Inc writes (Combat.ResolutionHelpers.pas:191-195). Magic ranged 20 meets 4 + 12 = 16 Defense, but DefenseRoll (:159-171) rolls only dice 1-15 at the rolled chance and caps the rest at 30% (ToDefendCap 15, ToDefendCappedValue 30), so 15 × 1.0 + 1 × 0.3 = 15.3 is blocked → 4.7. The cap makes a cap-free re-size impossible here, since 4 + 12 always exceeds 15. Elemental Armor alone deals 8.0, Resist Elements alone 16.0.',
    version: V_WARLORD,
    a: { rtbType:'magic', rtb:20, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:30, abilities: {
      lavaSmelterResistElements: true,
      lavaSmelterElementalArmor: true,
    } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.700 },
  },

  // --- Lightning Blade ---
  lightningBladeConvertsThrownWarlord: {
    desc: 'Lightning Blade (Warlord): innate Thrown 4 becomes Lightning Breath 5 (Thrown +1, Armor Piercing). Melee atk 1 vs def 4 (100% block) → 0; breath 5 with AP halves def 4→2 → 5−2 = 3 (without conversion, plain thrown 4 vs def 4 → 0)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, rtbType:'thrown', rtb:4, hp:10, abilities: { lightningBlade: true } },
    b: { atk:0, def:4, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  lightningBladeGrantsBreathWarlord: {
    desc: 'Lightning Blade (Warlord): melee-only unit gains a strength-1 Lightning Breath (Armor Piercing). Melee atk 2 vs def 1 (100% block) → 1; granted breath 1 with AP halves def 1→0 → 1; total 2 (without the grant, only melee → 1)',
    version: V_WARLORD,
    a: { atk:2, hitChance:70, hp:10, abilities: { lightningBlade: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Ludus Agoge ---
  // Orc-race building. Trained Orc units gain +1 Attack, +1 existing ranged,
  // +1 Resistance, and +1 HP.
  // Legionaries gain +1 Movement instead (not modelled) and heroes are excluded.
  ludusAgogeAttackWarlord: {
    desc: 'Ludus Agoge (Warlord): an Orc unit gains +1 Attack. Melee 4+1 = 5 (100% hit) vs def 1 (100% block) → 5−1 = 4 (without the grant, melee 4 → 3)',
    version: V_WARLORD,
    a: { atk:4, hitChance:70, hp:10, race:'Orc', abilities: { ludusAgoge: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  ludusAgogeResistanceWarlord: {
    desc: 'Ludus Agoge (Warlord): an Orc unit gains +1 Resistance. Death Gaze vs res 9+1 = 10 → P(die) = 0 → 0 dmg (without the grant, res 9 → P = 0.1 × 10 HP = 1.0 dmg). The resistance grant is isolated here: at P = 0 no figure dies, so the +1 HP grant cannot affect the result. The grant also writes +1 melee at ABase, so the Orc counterattacks for 1 at 30% To Hit → dmgToA 0.3 (F133)',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:9, hp:10, race:'Orc', abilities: { ludusAgoge: true } },
    expected: { dmgToA: 0.300, dmgToB: 0 },
  },
  ludusAgogeHpWarlord: {
    desc: 'Ludus Agoge (Warlord): an Orc unit gains +1 HP. Melee 10 (100% hit) vs def 0 → 10 raw, capped at the defender total HP 5+1 = 6 → 6 dmg (without the grant, HP 5 caps it at 5). The grant also writes +1 melee at ABase, so the Orc counterattacks for 1 at 30% To Hit → dmgToA 0.3 (F133)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:30 },
    b: { atk:0, def:0, toBlkMod:70, hp:5, race:'Orc', abilities: { ludusAgoge: true } },
    expected: { dmgToA: 0.300, dmgToB: 6.000 },
  },
  ludusAgogeNonOrcWarlord: {
    desc: 'Ludus Agoge (Warlord): a non-Orc unit gets no bonus. Melee 4 (100% hit) vs def 1 (100% block) → 3 (an Orc would gain +1 Attack → 4)',
    version: V_WARLORD,
    a: { atk:4, hitChance:70, hp:10, abilities: { ludusAgoge: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  ludusAgogeLegionaryExcludedWarlord: {
    desc: 'Ludus Agoge (Warlord): a Legionary gains +1 Movement instead (not modelled), so no stat bonus. Melee 4 (100% hit) vs def 1 (100% block) → 3 (a non-Legionary Orc would gain +1 Attack → 4)',
    version: V_WARLORD,
    a: { atk:4, hitChance:70, hp:10, race:'Orc', name:'Orc Legionary', abilities: { ludusAgoge: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  ludusAgogeHeroExcludedWarlord: {
    desc: 'Ludus Agoge (Warlord): an Orc hero is excluded — no bonus. Melee 4 (100% hit) vs def 1 (100% block) → 3 (a non-hero Orc would gain +1 Attack → 4)',
    version: V_WARLORD,
    a: { atk:4, hitChance:70, unitType:'hero', hp:10, race:'Orc', abilities: { ludusAgoge: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },

  // --- Mother Fungus ---
  // Goblin building. Trained Goblin units gain +2 Attack, +2 existing ranged,
  // +10% To Defend, and Poison 1
  // (heroes excluded; the ×2 Spellcharge bonus is not modelled). Attack and To-Defend cases
  // give the defender Poison Immunity so the always-on Poison 1 grant does not contaminate the
  // effect under test.
  motherFungusAttackWarlord: {
    desc: 'Mother Fungus (Warlord): a Goblin unit gains +2 Attack. Melee 4+2 = 6 (100% hit) vs def 1 (100% block) → 6−1 = 5 (without the grant, melee 4 → 3). Defender is Poison-Immune to isolate from the +1 Poison grant',
    version: V_WARLORD,
    a: { atk:4, hitChance:70, hp:10, race:'Goblin', abilities: { motherFungus: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30, abilities: { poisonImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  motherFungusToDefendWarlord: {
    desc: 'Mother Fungus (Warlord): a Goblin unit gains +10% To Defend. Boulder 10 (100% hit) vs a Goblin defender, def 5, base 30%+10% = 40% block → 10 − 5×0.4 = 8.0 (without the grant, 30% block → 10 − 5×0.3 = 8.5). Ranged so no melee counter; the defender Attack/Poison grants only affect the (absent) counterattack',
    version: V_WARLORD,
    a: { rtbType:'boulder', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:20 },
    b: { atk:0, def:5, toBlkMod:0, res:20, hp:20, race:'Goblin', abilities: { motherFungus: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  motherFungusPoisonWarlord: {
    desc: 'Mother Fungus (Warlord): a melee-only Goblin unit with no poison gains Poison 1. Melee 1+2 = 3 (100% hit) vs def 3 (100% block) → 0 physical, but Poison 1 lands (res 1, CoM2 fail = (11−1)/10 = 1.0) → 1.0 poison damage (without the grant, melee 1 vs def 3 → 0 physical and no poison → 0). The +2 Attack is fully absorbed by the 100%-block def 3 so only the poison grant surfaces',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, race:'Goblin', abilities: { motherFungus: true } },
    b: { atk:0, def:3, toBlkMod:70, res:1, hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  motherFungusNonGoblinWarlord: {
    desc: 'Mother Fungus (Warlord): a non-Goblin unit gets no bonus. Melee 4 (100% hit) vs def 1 (100% block) → 3 (a Goblin would gain +2 Attack → 5). No poison grant applies, so the defender needs no Poison Immunity',
    version: V_WARLORD,
    a: { atk:4, hitChance:70, hp:10, abilities: { motherFungus: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  motherFungusHeroExcludedWarlord: {
    desc: 'Mother Fungus (Warlord): a Goblin hero is excluded — no Attack and no Poison grant. Melee 4 (100% hit) vs def 1 (100% block) → 3 (a non-hero Goblin would deal 5 plus poison). No Poison Immunity on the defender, so an erroneous poison grant would also surface',
    version: V_WARLORD,
    a: { atk:4, hitChance:70, unitType:'hero', hp:10, race:'Goblin', abilities: { motherFungus: true } },
    b: { atk:0, def:1, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },

  // --- Pool of Repentance ---
  // Rakhshasa building. Units trained here gain +1 Armor and +1 Resistance. Race-gated to
  // Rakhshasa; heroes excluded.
  poolOfRepentanceArmorWarlord: {
    desc: 'Pool of Repentance (Warlord): a Rakhshasa unit gains +1 Armor. atk 5 (100% hit) vs def 0 + Pool → 1 shield at 100% block → 4 dmg (without the grant, def 0 → 5)',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, race:'Rakhshasa', abilities: { poolOfRepentance: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  poolOfRepentanceResistanceWarlord: {
    desc: 'Pool of Repentance (Warlord): a Rakhshasa unit gains +1 Resistance. Death Gaze vs res 9+1 = 10 → P(die) = 0 → 0 dmg (without the grant, res 9 → P = 0.1 × 10 HP = 1.0 dmg)',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:9, hp:10, race:'Rakhshasa', abilities: { poolOfRepentance: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  poolOfRepentanceNonRakhshasaWarlord: {
    desc: 'Pool of Repentance (Warlord): a non-Rakhshasa unit gets no bonus. atk 5 (100% hit) vs def 0 → 5 dmg (a Rakhshasa would gain +1 Armor → 1 shield at 100% block → 4 dmg)',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { poolOfRepentance: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  poolOfRepentanceHeroExcludedWarlord: {
    desc: 'Pool of Repentance (Warlord): a Rakhshasa hero is excluded — no +1 Armor. atk 5 (100% hit) vs def 0 → 5 dmg (a non-hero Rakhshasa would gain +1 Armor → 4 dmg)',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, unitType:'hero', race:'Rakhshasa', abilities: { poolOfRepentance: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },

  // --- Sancta Basilica ---
  // High Men building. Every High Men unit trained gains +3 Resistance. Clergy (unit tag),
  // Crusaders, and Paladins (by name) also gain Sanctify; Crusaders also gain Lucky; Paladins
  // also gain Magic Immunity. Improved Exorcise and the defending-city True Light are not modelled.
  // Race-gated to High Men; heroes excluded.
  sanctaBasilicaResistanceWarlord: {
    desc: 'Sancta Basilica (Warlord): a plain High Men unit gains +3 Resistance. Death Gaze vs res 7+3 = 10 → P(die) = 0 → 0 dmg (without the grant, res 7 → P = 0.3 × 10 HP = 3.0 dmg). No name/Clergy match, so no Sanctify/Lucky/Magic Immunity contaminates the Death Gaze',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:7, hp:10, race:'High Men', abilities: { sanctaBasilica: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  sanctaBasilicaCrusaderLuckyWarlord: {
    desc: 'Sancta Basilica (Warlord): a High Men Crusader gains Lucky (+10% To Block). Boulder 10 (100% hit) vs def 5, base 30%+10% = 40% block → 10 − 5×0.4 = 8.0 (without Lucky, 30% block → 8.5). Ranged so no melee counter',
    version: V_WARLORD,
    a: { rtbType:'boulder', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:20 },
    b: { atk:0, def:5, toBlkMod:0, hp:20, race:'High Men', name:'Crusaders', abilities: { sanctaBasilica: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  sanctaBasilicaPaladinMagicImmunityWarlord: {
    desc: 'Sancta Basilica (Warlord): a High Men Paladin gains Magic Immunity, which blocks Death Gaze entirely → 0 dmg (without the grant, res 1+3 = 4 → P = 0.6 × 10 HP = 6.0 dmg)',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:1, hp:10, race:'High Men', name:'Paladins', abilities: { sanctaBasilica: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  sanctaBasilicaClergySanctifyWarlord: {
    desc: 'Sancta Basilica (Warlord): a High Men Clergy attacker gains Sanctify and becomes Life FANTASTIC, so the defender\'s Weapon Immunity does not apply (attacker not normal). atk 6 (100% hit) vs def 2 (100% block) → 6−2 = 4 (without Sanctify the attacker stays normal, Weapon Immunity adds +10 def → 12 → 0 dmg)',
    version: V_WARLORD,
    a: { figs:1, atk:6, hp:10, hitChance:70, weapon:'normal', unitType:'normal', race:'High Men', name:'High Men Monks', abilities: { sanctaBasilica: true, clergy: true } },
    b: { figs:1, atk:0, def:2, hp:10, toBlkMod:70, unitType:'normal', abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  sanctaBasilicaNonHighMenWarlord: {
    desc: 'Sancta Basilica (Warlord): a non-High Men unit gets no bonus. Death Gaze vs res 7 → P = 0.3 × 10 HP = 3.0 dmg (a High Men unit would gain +3 Resistance → res 10 → 0 dmg)',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:7, hp:10, abilities: { sanctaBasilica: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  sanctaBasilicaHeroExcludedWarlord: {
    desc: 'Sancta Basilica (Warlord): a High Men hero is excluded — no +3 Resistance. Death Gaze vs res 7 → P = 0.3 × 10 HP = 3.0 dmg (a non-hero High Men unit would reach res 10 → 0 dmg)',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:7, hp:10, unitType:'hero', race:'High Men', abilities: { sanctaBasilica: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },

  // --- Military Workshop ---
  // XuanYuan building. Upgrades any normal unit (heroes/fantastic excluded), not race-gated.
  // Physical ranged/thrown → Armor Piercing (or +2 strength if Doom); Fire Breath +4; small
  // physical projectiles → heavy (boulder, bypassing Missile Immunity); +1 Poison.
  // The non-poison cases give the defender Poison Immunity so the always-on +1 Poison grant
  // does not contaminate the effect under test.
  militaryWorkshopArmorPiercingWarlord: {
    desc: 'Military Workshop (Warlord): a physical-ranged unit gains Armor Piercing. Boulder 10 (100% hit) vs def 8 (100% block) → AP halves def to 4 → 10−4 = 6 (without the grant, def 8 → 2). Defender is Poison-Immune to isolate from the +1 Poison grant',
    version: V_WARLORD,
    a: { rtbType:'boulder', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:20, abilities: { militaryWorkshop: true } },
    b: { atk:0, def:8, toBlkMod:70, hp:20, abilities: { poisonImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  militaryWorkshopDoomGetsStrengthNotAPWarlord: {
    desc: 'Military Workshop (Warlord): a Doom-attack unit gets +2 strength instead of Armor Piercing (Doom already ignores armor). Boulder Doom 5+2 = 7 strength → CoM Doom deals floor(7/2) = 3, def 8 ignored (without the grant, floor(5/2) = 2). Defender Poison-Immune',
    version: V_WARLORD,
    a: { rtbType:'boulder', rtb:5, hitRanged:70, hitThrown:70, hitBreath:70, hp:20, abilities: { doom: true, militaryWorkshop: true } },
    b: { atk:0, def:8, toBlkMod:70, hp:20, abilities: { poisonImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  militaryWorkshopFireBreathWarlord: {
    desc: 'Military Workshop (Warlord): a Fire Breath unit gains +4 breath strength. Fire breath 6+4 = 10 (100% hit) vs def 3 (100% block) → 10−3 = 7 (without the grant, 6 → 3). Defender Poison-Immune to isolate the breath bonus',
    version: V_WARLORD,
    a: { atk:1, rtbType:'fire', rtb:6, hitRanged:70, hitThrown:70, hitBreath:70, hp:20, abilities: { militaryWorkshop: true } },
    b: { atk:0, def:3, toBlkMod:70, hp:20, abilities: { poisonImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  militaryWorkshopProjectileUpgradeWarlord: {
    desc: 'Military Workshop (Warlord): a small physical (missile) projectile upgrades to heavy (boulder), bypassing Missile Immunity. Missile 10 vs a Missile-Immune defender → without the grant, def raised to 100 → all blocked → 0. With the grant the boulder ignores Missile Immunity → def 0 → 10 damage. Defender also Poison-Immune',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:20, abilities: { militaryWorkshop: true } },
    b: { atk:0, def:0, toBlkMod:70, hp:20, abilities: { missileImmunity: true, poisonImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  militaryWorkshopMeleeOnlyExcludedWarlord: {
    desc: 'Military Workshop (Warlord): a melee-only unit is ineligible for Blackpowder. Melee 1 is fully blocked and no Poison is granted → 0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { militaryWorkshop: true } },
    b: { atk:0, def:1, toBlkMod:70, res:1, hp:10 },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  militaryWorkshopHeroExcludedWarlord: {
    desc: 'Military Workshop (Warlord): a hero is excluded — no Armor Piercing and no +1 Poison. Boulder 10 (100% hit) vs def 8 (100% block) → 10−8 = 2 (a normal unit would deal 6 plus poison). No Poison Immunity on the defender, so an erroneous poison grant would also surface',
    version: V_WARLORD,
    a: { rtbType:'boulder', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, unitType:'hero', hp:20, abilities: { militaryWorkshop: true } },
    b: { atk:0, def:8, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Venom (Warlord enchantment) ---
  venomGrantsPoisonWarlord: {
    desc: 'Venom (Warlord): a unit with no poison gains Poison 1. Melee 1 (100% hit) vs def 1 (100% block) → 0 physical, but Poison 1 lands (res 1, CoM2 fail = (11−1)/10 = 1.0) → 1.0 poison damage (without the grant, no poison → 0)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { venom: true } },
    b: { atk:0, def:1, toBlkMod:70, res:1, hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  venomBoostsExistingPoisonWarlord: {
    desc: 'Venom (Warlord): +1 Poison boosts an existing attack. Poison 2 → 3 vs res 5 (CoM2 fail = (11−5)/10 = 0.6) → 3 × 0.6 = 1.8 poison. Melee 1 vs def 1 (100% block) → 0 physical (without the grant, Poison 2 → 1.2)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { venom: true, poison: 2 } },
    b: { atk:0, def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.800 },
  },
  venomGrantsPoisonImmunityWarlord: {
    desc: 'Venom (Warlord): grants Poison Immunity. A Venom defender is immune → attacker Poison 4 negated → 0; melee 1 vs def 1 (100% block) → 0 (without immunity, Poison 4 vs res 5 → 4 × 0.6 = 2.4)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { poison: 4 } },
    b: { atk:0, def:1, toBlkMod:70, res:5, hp:10, abilities: { venom: true } },
    expected: { dmgToA: 0, dmgToB: 0.000 },
  },

  // --- Artificer ---
  artificerMechanicalMeleeWarlord: {
    desc: 'Artificer (Warlord): mechanical unit gets +1 melee. atk 1 → 2, 100% hit vs 0 def → 2 dmg',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { artificer: true, mechanical: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  artificerMechanicalRangedWarlord: {
    desc: 'Artificer (Warlord): mechanical unit gets +1 ranged. missile 1 → 2, 100% hit → 2 dmg',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { artificer: true, mechanical: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  artificerMechanicalDefenseWarlord: {
    desc: 'Artificer (Warlord): mechanical unit gets +1 armor. 5 atk vs 0 def + Artificer → 1 shield at 100% block → 4 dmg',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { artificer: true, mechanical: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  artificerMechanicalResistanceWarlord: {
    desc: 'Artificer (Warlord): mechanical unit gets +2 resistance — CreateUnit.CAS:43, matching manual changelog 1.4.22; the helptext still says +1 (Source discrepancies.md §6). Death Gaze vs res 5 → res 7 → pFail (10−7)/10 = 0.3 → 1 fig × 10 hp × 0.3 = 3 dmg (at the helptext +1 it would be res 6 → 4 dmg)',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, abilities: { artificer: true, mechanical: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  artificerMagicWeaponBypassesWIWarlord: {
    desc: 'Artificer (Warlord): mechanical attacker gets Magic Weapons → bypasses defender Weapon Immunity. atk 5 (+1 Artificer = 6, +10% to-hit from magic) vs 0 def + WI → WI bypassed, 6 dmg',
    version: V_WARLORD,
    a: { atk:5, hitChance:60, hp:10, abilities: { artificer: true, mechanical: true } },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  artificerNoBonusForNonMechanicalWarlord: {
    desc: 'Artificer (Warlord): non-mechanical unit gets no bonus. atk 1, 100% hit vs 0 def → 1 dmg (not 2)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { artificer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },

  // --- Mechanical Expert ---
  mechanicalExpertToHitWarlord: {
    desc: 'Mechanical Expert (Warlord): mechanical attacker gets +20% To Hit. 10 atk at 30%+20%=50% vs 0 def → 5 dmg (not 3)',
    version: V_WARLORD,
    a: { atk:10, hp:10, abilities: { mechanicalExpert: true, mechanical: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  mechanicalExpertToDefendWarlord: {
    desc: 'Mechanical Expert (Warlord): mechanical defender gets +10% To Defend. 10 hits vs 10 def at 30%+10%=40% block → 4 blocks → 6 dmg (not 7)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:20 },
    b: { def:10, hp:20, abilities: { mechanicalExpert: true, mechanical: true } },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  mechanicalExpertNoBonusForNonMechanicalWarlord: {
    desc: 'Mechanical Expert (Warlord): non-mechanical unit gets no bonus. 10 atk at base 30% vs 0 def → 3 dmg (not 5)',
    version: V_WARLORD,
    a: { atk:10, hp:10, abilities: { mechanicalExpert: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  mechanicalExpertRebuildMakesMechanicalWarlord: {
    desc: 'Rebuild + Mechanical Expert (Warlord): Rebuild makes the unit mechanical, so +20% To Hit applies. atk 10 + Rebuild(+2) = 12 at 50% vs 0 def → 6 dmg',
    version: V_WARLORD,
    a: { atk:10, hp:10, abilities: { rebuild: true, mechanicalExpert: true } },
    b: { def:0, hp:30 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },

  // --- Rebuild ---
  rebuildMeleeWarlord: {
    desc: 'Rebuild (Warlord): +2 melee. atk 1 → 3, 100% hit vs 0 def → 3 dmg',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { rebuild: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  rebuildArmorWarlord: {
    desc: 'Rebuild (Warlord): +2 armor. 5 atk vs 0 def + Rebuild → 2 shields at 100% block → 3 dmg',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { rebuild: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  rebuildArmorPiercingWarlord: {
    desc: 'Rebuild (Warlord): grants Armor Piercing. Missile rtb 2 100% hit vs def 3 100% block → AP halves def to 1 → 1 dmg (Rebuild +2 melee does not affect ranged attack)',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:2, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { rebuild: true } },
    b: { def:3, toBlkMod:70, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  colossalStrengthMeleeWarlord: {
    desc: 'Colossal Strength (Warlord): +1 + 40% of base melee. Base atk 10 → +1+floor(0.4×10)=+5 → 15. 1 fig, 100% hit, def 2 fully blocks 2 → E[dmg] = 13 (without Colossal Strength, 10 − 2 = 8)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { colossalStrength: true } },
    b: { def:2, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 13 },
  },
  colossalStrengthPhysicalRangedWarlord: {
    desc: 'Colossal Strength (Warlord): physical ranged gains +1 + 40% of base. Base missile 10 → 15. 100% hit, def 2 blocks 2 → E[dmg] = 13 (without Colossal Strength, 10 − 2 = 8)',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { colossalStrength: true } },
    b: { def:2, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 13 },
  },
  colossalStrengthThrownWarlord: {
    desc: 'Colossal Strength (Warlord): thrown gains +1 + 40% of base. Base thrown 10 → 15. 100% hit, def 2 blocks 2 → E[dmg] = 13 (without Colossal Strength, 10 − 2 = 8)',
    version: V_WARLORD,
    a: { atk:1, rtbType:'thrown', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { colossalStrength: true } },
    b: { def:2, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 13 },
  },
  colossalStrengthMagicRangedNoBonusWarlord: {
    desc: 'Colossal Strength (Warlord): magic ranged is not physical ranged, so it gets no bonus. Base magic 10, 100% hit, def 2 blocks 2 → E[dmg] = 8 (unchanged by Colossal Strength)',
    version: V_WARLORD,
    a: { rtbType:'magic', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { colossalStrength: true } },
    b: { def:2, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 8 },
  },
  colossalStrengthScalesBuffedMeleeWarlord: {
    desc: 'Colossal Strength (Warlord) scales CURRENT melee, not base (UnitCalc.CAS:1227-1243 reads GetStat(U,SAttack,0) in phase d). Base atk 10 + Lionheart +3 = 13 → +1+floor(0.4×13)=+6 → 19. 100% hit, def 2 blocks 2 → E[dmg] = 17 (if it scaled base instead: 10+3+5 = 18 → 16)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { colossalStrength: true, lionheart: true } },
    b: { def:2, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 17 },
  },
  colossalStrengthScalesAfterRustWarlord: {
    desc: 'Colossal Strength (Warlord) is applied after Rust within phase d — Rust is UnitCalc.CAS:492-504, Colossal :1227, so Colossal scales the already-reduced melee. Base atk 10 − 3 = 7 → +1+floor(0.4×7)=+3 → 10. 100% hit, def 2 blocks 2 → E[dmg] = 8 (if Colossal scaled base instead: 10−3+5 = 12 → 10)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { colossalStrength: true, rust: true } },
    b: { def:2, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 8 },
  },
  colossalStrengthScalesBuffedRangedWarlord: {
    desc: 'Colossal Strength (Warlord) scales current physical ranged, not base. Base missile 10 + Lionheart +3 (non-magic ranged) = 13 → +1+floor(0.4×13)=+6 → 19. 100% hit, def 2 blocks 2 → E[dmg] = 17 (if it scaled base instead: 10+3+5 = 18 → 16)',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { colossalStrength: true, lionheart: true } },
    b: { def:2, toBlkMod:70, hp:30 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 17 },
  },
  rustMeleePenaltyWarlord: {
    desc: 'Rust (Warlord): −3 melee attack. Base atk 10 → 7, 1 fig, 100% hit, def 0 → E[dmg] = 7 (without Rust, 10)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { rust: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 7 },
  },
  rustPhysicalRangedPenaltyWarlord: {
    desc: 'Rust (Warlord): −3 to physical ranged (missile). Missile 10 → 7, 100% hit, def 0 → E[dmg] = 7 (without Rust, 10)',
    version: V_WARLORD,
    a: { atk:0, rtbType:'missile', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { rust: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 7 },
  },
  rustBoulderRangedPenaltyWarlord: {
    desc: 'Rust (Warlord): −3 to physical ranged (boulder). Boulder 10 → 7, 100% hit, def 0 → E[dmg] = 7 (without Rust, 10)',
    version: V_WARLORD,
    a: { atk:0, rtbType:'boulder', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { rust: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 7 },
  },
  rustStripsMagicWeaponWarlord: {
    desc: 'Rust (Warlord): strips magic weapon → reverts to regular, so Weapon Immunity is no longer bypassed. Magic atk 10 vs WI (def 0→10), with Rust melee 10−3=7 fully blocked → E[dmg] = 0 (without Rust, magic bypasses WI → 10)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, weapon: 'magic', abilities: { rust: true } },
    b: { def:0, toBlkMod:70, hp:20, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  rustEliminatesThrownWarlord: {
    desc: 'Rust (Warlord): thrown attack eliminated. Thrown 10 (no melee), 100% hit, def 0 → with Rust no thrown phase → E[dmg] = 0 (without Rust, thrown lands → 10)',
    version: V_WARLORD,
    a: { atk:0, rtbType:'thrown', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { rust: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  rustEliminatesLargeShieldWarlord: {
    desc: 'Rust (Warlord): Large Shield eliminated on the cursed defender. Missile 10 vs def 0; Large Shield would add +2 vs ranged → with Rust shield gone, def 0 → E[dmg] = 10 (without Rust, def 2 → 8)',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:10, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:20, abilities: { rust: true, largeShield: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 10 },
  },
  rustFantasticUnaffectedWarlord: {
    desc: 'Rust targets a regular (non-fantastic) unit, so a fantastic creature is unaffected: no −3 melee. Fantastic atk 10 → stays 10, 1 fig, 100% hit, def 0 → 10 (if wrongly applied, 7).',
    version: V_WARLORD,
    a: { unitType:'fantastic_chaos', atk:10, hitChance:70, hp:10, abilities: { rust: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10 },
  },
  divineProtectionLuckyToHitWarlord: {
    desc: 'Divine Protection (Warlord): grants Lucky. 1 atk, base 30% + Lucky +10% = 40% hit vs 0 def → E[dmg] = 0.4 (without Divine Protection, 30% → 0.3)',
    version: V_WARLORD,
    a: { atk:1, hp:10, abilities: { divineProtection: true } },
    b: { def:0, hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.4 },
  },
  divineProtectionLuckyResistanceWarlord: {
    desc: 'Divine Protection (Warlord): grants Lucky +1 Resistance. Poison 6 vs base res 5 + Lucky +1 = res 6, CoM −1 poison penalty → effective 5, pFail 50%, E[dmg] = 3.0 (without grant, res 5 −1 = 4 → pFail 60% → 3.6)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { poison: 6 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { divineProtection: true } },
    expected: { dmgToA: 0, dmgToB: 3.0 },
  },
  divineProtectionDeathImmunityWarlord: {
    desc: 'Divine Protection (Warlord): grants Death Immunity. Death Gaze vs res 5 + Death Immunity → fully blocked, 0 dmg (without grant, res 5 → P(die) 0.3 × 10 HP = 3.0)',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, abilities: { divineProtection: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  luckyStarAuraMeleeWarlord: {
    desc: 'Lucky Star aura (Warlord): +1 melee to a friendly unit that is not itself enchanted, and no Lucky. (1+1) atk at base 30% To-Hit vs def 0 → E[dmg] = 0.6 (without the aura, 0.3; if it also granted Lucky, 0.8)',
    version: V_WARLORD,
    a: { atk:1, hp:10, abilities: { luckyStar: true } },
    b: { def:0, hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.6 },
  },
  luckyStarEnchantedUnitWarlord: {
    desc: 'Lucky Star (Warlord) on its enchanted unit: the aura plus the Lucky grant, which is the separate Lucky control. (1+1) atk at base 30% + Lucky 10% To-Hit vs def 0 → E[dmg] = 0.8',
    version: V_WARLORD,
    a: { atk:1, hp:10, abilities: { luckyStar: true, lucky: true } },
    b: { def:0, hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.8 },
  },
  luckyStarAuraResistanceWarlord: {
    desc: 'Lucky Star aura (Warlord): +1 Resistance without Lucky. Poison 6 vs base res 5+1 = 6, CoM −1 poison penalty → effective 5, pFail 50%, E[dmg] = 3.0 (with Lucky as well it would be res 7 → 2.4)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { poison: 6 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { luckyStar: true } },
    expected: { dmgToA: 0, dmgToB: 3.0 },
  },
  luckyStarAuraArmorWarlord: {
    desc: 'Lucky Star aura (Warlord): defender gains +1 Armor. 3 atk at 100% hit vs base def 1+1 at 100% block → 1 dmg (without the aura bonus, 2)',
    version: V_WARLORD,
    a: { atk:3, hitChance:70, hp:10 },
    b: { atk:0, def:1, toBlkMod:70, hp:10, abilities: { luckyStar: true } },
    expected: { dmgToA: 0, dmgToB: 1.0 },
  },
  rallyResistanceWarlord: {
    desc: 'Rally (Warlord): grants +2 Resistance. Poison 7 vs base res 5 + Rally +2 = res 7, CoM −1 poison penalty → effective 6, pFail 40%, E[dmg] = 2.8 (without Rally, res 5 −1 = 4 → pFail 60% → 4.2)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { poison: 7 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { rally: true } },
    expected: { dmgToA: 0, dmgToB: 2.8 },
  },
  disheartenProphecyResistanceWarlord: {
    desc: 'Dishearten Prophesy (Warlord): garrison suffers −2 Resistance. Poison 7 vs base res 7 − Dishearten 2 = res 5, CoM −1 poison penalty → effective 4, pFail 60%, E[dmg] = 4.2 (without Dishearten, res 7 −1 = 6 → pFail 40% → 2.8)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { poison: 7 } },
    b: { def:1, toBlkMod:70, res:7, hp:10, abilities: { disheartenProphecy: true } },
    expected: { dmgToA: 0, dmgToB: 4.2 },
  },
  insulationFireImmunityWarlord: {
    desc: 'Insulation (Warlord): grants Fire Immunity. Fire Breath 5 (100% hit) vs Insulation def → blocked (FI def 50); melee 5 (100% hit) vs def 2 → 3 dmg (without Insulation, breath 5 vs def 2 = 3 + melee 3 = 6)',
    version: V_WARLORD,
    a: { atk:5, rtbType:'fire', rtb:5, hitChance:70, hp:10 },
    b: { atk:0, def:2, toBlkMod:70, hp:10, abilities: { insulation: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  insulationLightningResistWarlord: {
    desc: 'Insulation (Warlord): grants Lightning Resist, cancelling Lightning Breath AP. Breath 2 (100% hit) vs def 2 (100% block) → AP cancelled, 2−2 = 0 (without Insulation, lightning is AP → def 2 halved to 1, 2−1 = 1)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, rtbType:'lightning', rtb:2, hp:10 },
    b: { atk:0, def:2, toBlkMod:70, hp:10, abilities: { insulation: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  rebuildDeathImmunityWarlord: {
    desc: 'Rebuild (Warlord): grants Death Immunity. Death Gaze vs res 5 + Death Immunity → fully blocked, 0 dmg',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, abilities: { rebuild: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  rebuildIllusionImmunityWarlord: {
    desc: 'Rebuild (Warlord): grants Illusion Immunity. Illusion attack vs def 6 + Rebuild → def stays 6 (not 0), 0 dmg',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10, abilities: { illusion: true } },
    b: { def:6, toBlkMod:70, hp:10, abilities: { rebuild: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  rebuildMakesMechanicalForArtificerWarlord: {
    desc: 'Rebuild + Artificer (Warlord): Rebuild makes the unit mechanical, so Artificer also applies. atk 1 + Rebuild(+2) + Artificer(+1) = 4, 100% hit vs 0 def → 4 dmg',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { rebuild: true, artificer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
});
