// Numeric presets. Berserk, the Warlord combat enchantments and curses (Blood Lust through
// Blaze of Glory), the Warlord globals granted by city resources and buildings, and Black Channels.
definePresets({
  // --- Berserk ---
  berserkDoublesMelee: {
    desc: 'Berserk doubles melee attack: base 3 atk × 2 = 6, 100% hit vs 0 def → E[dmg]=6.0',
    a: { atk:3, toHitMod:70, hp:10, abilities: { berserk: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  berserkDoublesBeforeHighPrayer: {
    desc: 'Berserk is the last unit-enchantment block (131:0x8F860), so it doubles before the combat-enchantment blocks: atk 3 × 2 = 6, then High Prayer +2 (131:0x902CF) → E[dmg]=8.0 (without Berserk: 5.0)',
    a: { atk:3, toHitMod:70, hp:10, abilities: { berserk: true, highPrayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  berserkSetsDefToZero: {
    desc: 'Berserk sets own def to 0: Berserked unit has def=5 but effective def=0 → all atk hits land, E[dmg]=4.0',
    a: { atk:4, toHitMod:70, hp:10 },
    b: { def:5, hp:10, abilities: { berserk: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  berserkIronSkinOverridden: {
    desc: 'Berserk overrides Iron Skin: Iron Skin would give +5 def, but Berserk forces def=0 → all hits land, E[dmg]=4.0',
    a: { atk:4, toHitMod:70, hp:10 },
    b: { def:0, hp:10, abilities: { berserk: true, ironSkin: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Warlord Berserk: +15% To Hit, -10% To Block, no atk doubling, no def-zero ---
  // --- Beat of Swiftness (Warlord) ---
  beatOfSwiftnessArmorPenaltyWarlord: {
    desc: 'Beat of Swiftness: def 10 loses round-to-even(10/10)=1, leaving 9. atk 10 @100% hit, 100% block → 10−9=1 dmg (without it: 10−10=0)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:10, toBlkMod:70, hp:20, abilities: { beatOfSwiftness: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  berserkWarlordPlus15ToHit: {
    desc: 'Warlord Berserk grants +15% To Hit, no atk doubling: 4 atk @ 30%+15%=45% vs def=0 → E[dmg]=1.8',
    version: V_WARLORD,
    a: { atk:4, hp:10, abilities: { berserkWarlord: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 1.800 },
  },
  berserkWarlordMinus10ToBlock: {
    desc: 'Warlord Berserk on defender: -10% To Block, def NOT zeroed. 1 atk @100% hit; def=1 @ 100%-10%=90% block → E[dmg]=0.1',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10 },
    b: { def:1, toBlkMod:70, hp:20, abilities: { berserkWarlord: true } },
    expected: { dmgToA: 0, dmgToB: 0.100 },
  },

  // --- Conjuring Pact nausea (Warlord) ---
  nauseaMinus10ToHit: {
    desc: 'Nausea on attacker: -10% To Hit. atk=10 @ 100%-10%=90% hit vs def=0 → E[dmg]=9.0 (without it: 10.0)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { nausea: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 9.000 },
  },
  nauseaMinus10ToDefend: {
    desc: 'Nausea on defender: -10% To Defend. atk=1 @100% hit; def=1 @ 100%-10%=90% block → E[dmg]=0.1 (without it: 0)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10 },
    b: { def:1, toBlkMod:70, hp:20, abilities: { nausea: true } },
    expected: { dmgToA: 0, dmgToB: 0.100 },
  },

  // --- Magic Immunity curse gating ---
  // Magic Immunity (and, for Mind Storm, Illusion Immunity) hard-blocks these
  // magic-based curses: the gated attacker keeps its full strength / to-hit.
  // Each test diverges from the ungated result, so removing the gate fails it.
  magicImmunityGatesWeakness: {
    desc: 'Magic Immunity blocks Weakness: melee stays 10 (ungated −3 → 7). 100% hit vs def 0 → 10',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { magicImmunity: true, weakness: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  magicImmunityGatesBlackSleep: {
    desc: 'Magic Immunity blocks Black Sleep: defender rolls normally (ungated = max damage). atk 10 @ 30% hit vs def 0 → 3.0 (ungated 10)',
    version: V_COM2,
    a: { atk:10, hp:10 },
    b: { def:0, hp:20, abilities: { magicImmunity: true, blackSleep: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  magicImmunityGatesShatter: {
    desc: 'Magic Immunity blocks Shatter: melee stays 10 (ungated → 1). 100% hit vs def 0 → 10',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { magicImmunity: true, shatter: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  magicImmunityGatesVertigo: {
    desc: 'Magic Immunity blocks Vertigo: To Hit stays 100% (ungated −25% → 75%). atk 10 vs def 0 → 10 (ungated 7.5)',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { magicImmunity: true, vertigo: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  magicImmunityGatesWarpAttack: {
    desc: 'Magic Immunity blocks Warp Creature (attack): melee stays 10 (ungated halved → 5). 100% hit vs def 0 → 10',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { magicImmunity: true, warpAttack: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  magicImmunityGatesMindStorm: {
    desc: 'Magic Immunity blocks Mind Storm: melee stays 10 (ungated −3 → 7). 100% hit vs def 0 → 10',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { magicImmunity: true, mindStorm: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  illusionImmunityGatesMindStorm: {
    desc: 'Illusion Immunity blocks Mind Storm: melee stays 10 (ungated −3 → 7). 100% hit vs def 0 → 10',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { illusionImmunity: true, mindStorm: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  illusionImmunityGatesVertigo: {
    desc: 'Illusion Immunity blocks Vertigo: To Hit stays 100% (ungated −25% → 75%). atk 10 vs def 0 → 10 (ungated 7.5)',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { illusionImmunity: true, vertigo: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  magicImmunityGatesNausea: {
    desc: 'Magic Immunity blocks Nausea: To Hit stays 100% (ungated −10% → 90%). atk 10 vs def 0 → 10 (ungated 9)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { magicImmunity: true, nausea: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  magicImmunityGatesTemporalTwist: {
    desc: 'Magic Immunity blocks Temporal Twist: First Strike preserved, so A kills B before retaliation (ungated dmgToA=5)',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, abilities: { magicImmunity: true, firstStrike: true, temporalTwist: true } },
    b: { atk:5, hitChance:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  blackPrayerBypassesMagicImmunity: {
    desc: 'Black Prayer is NOT gated by Magic Immunity (on the MoM bypass list): melee 10 still −1 → 9 vs def 0 at 100% hit',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { magicImmunity: true, blackPrayer: true } },
    b: { def:0, hp:20 },
    expected: { dmgToA: 0, dmgToB: 9.000 },
  },

  // --- Blood Lust ---
  bloodLustDoublesVsNormalCoM: {
    desc: 'Blood Lust doubles melee vs normal units in CoM: 3 atk → 6, 100% hit vs 0 def → 6.0',
    version: V_COM,
    a: { atk:3, toHitMod:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { hp:10, unitType:'normal' },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  bloodLustHeroTargetCoM2: {
    desc: 'Blood Lust treats heroes as normal targets in CoM2: 3 atk → 6 vs hero → 6.0',
    version: V_COM2,
    a: { atk:3, hitChance:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { hp:10, unitType:'hero' },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  bloodLustDoublesThrownCoM2: {
    desc: 'Blood Lust (CoM2): Thrown 3 doubles to 6 vs a normal 6-HP target and kills it before melee. Without the Thrown doubling, Thrown 3 + doubled melee 2 would deal only 5',
    version: V_COM2,
    a: { atk:1, hitChance:70, rtbType:'thrown', rtb:3, hp:10, abilities: { bloodLust: true } },
    b: { def:0, toBlkMod:70, hp:6, unitType:'normal' },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  bloodLustDoesNotDoubleFireBreathCoM2: {
    desc: 'Blood Lust (CoM2): Fire Breath 3 remains 3 against a normal target; only melee and Thrown enter the doubling block',
    version: V_COM2,
    a: { atk:0, rtbType:'fire', rtb:3, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { bloodLust: true } },
    b: { def:0, toBlkMod:70, hp:10, unitType:'normal' },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  bloodLustThrownCoM1MeleeOnly: {
    desc: 'CoM 1 Blood Lust remains melee-only: melee 1 doubles to 2 while Thrown 3 stays 3, for 5 total damage',
    version: V_COM,
    a: { atk:1, rtbType:'thrown', rtb:3, toHitMod:70, toHitRtbMod:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { def:0, hp:20, unitType:'normal' },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  bloodLustThrownCoM2: {
    desc: 'CoM2 Blood Lust doubles melee 1 and Thrown 3 against a non-Fantastic target, for 8 total damage',
    version: V_COM2,
    a: { atk:1, rtbType:'thrown', rtb:3, hitChance:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { def:0, hp:20, unitType:'normal' },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  bloodLustThrownFantasticTargetCoM2: {
    desc: 'CoM2 Blood Lust does not double melee 1 or Thrown 3 against a Fantastic target, for 4 total damage',
    version: V_COM2,
    a: { atk:1, rtbType:'thrown', rtb:3, hitChance:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { def:0, hp:20, unitType:'fantastic_nature' },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  bloodLustThrownWarlord: {
    desc: 'Warlord Blood Lust doubles melee 1 and Thrown 3 against a non-Fantastic target, for 8 total damage',
    version: V_WARLORD,
    a: { atk:1, rtbType:'thrown', rtb:3, hitChance:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { def:0, hp:20, unitType:'normal' },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  bloodLustLightningBreathUndoubledWarlord: {
    desc: 'Warlord Blood Lust leaves Lightning Breath undoubled: breath 3 + doubled melee 1 to 2 = 5.0',
    version: V_WARLORD,
    a: { atk:1, rtbType:'lightning', rtb:3, hitChance:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { hp:10, unitType:'normal' },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  bloodLustPhysicalRangedUndoubledCoM2: {
    desc: 'CoM2 Blood Lust leaves physical ranged undoubled: missile 3 = 3.0',
    version: V_COM2,
    a: { rtbType:'missile', rtb:3, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { hp:10, unitType:'normal' },
    rangedCheck: true,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  bloodLustMagicalRangedUndoubledWarlord: {
    desc: 'Warlord Blood Lust leaves magical ranged undoubled: a magical shot of 3 stays 3.0 where the doubling would make it 6.0. The attack type token is the modern `magic` — the spelled-out magic_sorcery this preset used before is in no type list, so the unit had no attack at all and the preset could never fail.',
    version: V_WARLORD,
    a: { rtbType:'magic', rtb:3, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { hp:10, unitType:'normal' },
    rangedCheck: true,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  bloodLustDoomGazeUndoubledCoM2: {
    desc: 'CoM2 Blood Lust leaves Doom Gaze undoubled: gaze 3 + doubled melee 1 to 2 = 5.0',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, unitType:'normal', abilities: { bloodLust: true, doomGaze: 3 } },
    b: { hp:10, unitType:'normal' },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  bloodLustNoDoubleVsFantasticCoM: {
    desc: 'Blood Lust does not double against fantastic units: 3 atk stays 3 vs fantastic target → 3.0',
    version: V_COM,
    a: { atk:3, toHitMod:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { hp:10, unitType:'fantastic_nature' },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  bloodLustFantasticBecomesDeathRealmCoM2: {
    desc: 'Blood Lust converts a fantastic_chaos unit into Death realm in CoM2: Darkness gives +1 atk to Death units, so atk 1 → 2, doubled to 4 vs normal → 4.0',
    version: V_COM2,
    darkness: true,
    a: { atk:1, hitChance:70, hp:10, unitType:'fantastic_chaos', abilities: { bloodLust: true } },
    b: { hp:10, unitType:'normal' },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  bloodLustBypassesWeaponImmunityCoM2: {
    desc: 'Blood Lust makes a normal attacker undead/Fantastic before CoM2 derives EncMagic, so Weapon Immunity is bypassed; the normal target still takes doubled melee: 5 atk → 10 vs def 2 → 9.4',
    version: V_COM2,
    a: { atk:5, hitChance:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { def:2, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 9.400 },
  },
  bloodLustVulnerableToExorciseCoM2: {
    desc: 'Blood Lust makes a normal unit a created-undead fantastic Death unit in CoM2, so Exorcise can target it: −6 plus the created-undead −3 leaves res 12 at effective 3, so pFail=0.7 and 1 attacking figure vs a 2-figure target gives E[banish]=7 plus 1 physical → 8.0',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { exorcise: -6 } },
    b: { figs:2, def:0, res:12, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  bloodLustNotUndeadWarlord: {
    desc: 'Warlord: Bloodlust no longer turns the unit undead, so it stays non-fantastic and Exorcise cannot target it. Same setup as the CoM2 pair (1 fig Exorcise −6 vs 2-fig res 12 normal w/ bloodLust); only the 1 physical melee hit lands → 1.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { exorcise: -6 } },
    b: { figs:2, def:0, res:12, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  bloodLustDoesNotBypassWeaponImmunityWarlord: {
    desc: 'Warlord: Bloodlust attacker stays normal, so Weapon Immunity DOES apply (+10 def). atk 5 doubled to 10 vs effective def 12 (2+10), 100% hit, 30% block → 10 - 12*0.3 = 6.4',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10, unitType:'normal', abilities: { bloodLust: true } },
    b: { def:2, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 6.400 },
  },

  // --- Bloodsucker (Warlord) ---
  // Per-phase trigger: if base attack deals ≥1 dmg through armor, +2 dmg / +2 heal.
  // Cap: 1 trigger per phase regardless of attacker figure count.
  bloodsuckerBasicMeleeWarlord: {
    desc: 'Bloodsucker melee: 1 fig atk 5, 100% hit vs def 0 → 5 base + 2 BS = 7.0',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10, abilities: { bloodSucker: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  bloodsuckerMultiFigCapWarlord: {
    desc: 'Bloodsucker cap: 4 figs each atk 1 (100% hit, def 0) = 4 base dmg, +2 BS once (not 4×2). Total 6.0.',
    version: V_WARLORD,
    a: { figs:4, atk:1, hitChance:70, hp:3, abilities: { bloodSucker: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  bloodsuckerArmorBlocksAllNoTriggerWarlord: {
    desc: 'Bloodsucker requires ≥1 dmg through armor: 1 fig atk 1 (100% hit) vs def 5 (100% block) → 0 base dmg, no trigger. Total 0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { bloodSucker: true } },
    b: { def:5, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  bloodsuckerThrownMeleeDoubleTriggerWarlord: {
    desc: 'Bloodsucker fires per phase: 1 fig thrown 1 + melee 1 (both 100% hit, def 0) → thrown 1+2 + melee 1+2 = 6.0.',
    version: V_WARLORD,
    a: { atk:1, rtbType:'thrown', rtb:1, hitChance:70, hp:10, abilities: { bloodSucker: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  bloodsuckerHasteDoublesWarlord: {
    desc: 'Bloodsucker with Haste: each of two melee strikes is a separate trigger. 1 fig atk 1, def 0, hasted: (1+2) + (1+2) = 6.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { bloodSucker: true, haste: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  bloodsuckerRangedWarlord: {
    desc: 'Bloodsucker fires on ranged: 1 fig missile 1 (100% hit, def 0) → 1+2 = 3.0.',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { bloodSucker: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  bloodsuckerCapAtRemHPWarlord: {
    desc: 'Bloodsucker +2 capped at target remaining HP: atk 5 vs hp 6 (no figs lost) → base 5 capped to 5; BS would push to 7 but capped to 6.',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10, abilities: { bloodSucker: true } },
    b: { def:0, toBlkMod:70, hp:6 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  bloodsuckerCounterAttackWarlord: {
    desc: 'Bloodsucker fires on counter-attack: defender (BS) counters with atk 3 → 3 base + 2 BS = 5 to attacker. Attacker atk 1 deals 1 to defender (no BS).',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, def:0, toBlkMod:70 },
    b: { atk:3, hitChance:70, def:0, toBlkMod:70, hp:20, abilities: { bloodSucker: true } },
    expected: { dmgToA: 5.000, dmgToB: 1.000 },
  },

  // --- Vampirism (Warlord enchantment: grants undead + Blood Sucker, thrown/breath → melee) ---
  vampirismGrantsBloodSuckerWarlord: {
    desc: 'Vampirism grants Blood Sucker: 1 fig atk 5, 100% hit vs def 0 → 5 base + 2 BS = 7.0. (Without the granted BS it would be 5.0.)',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10, abilities: { vampirism: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  vampirismGrantsUndeadImmunityWarlord: {
    desc: 'Vampirism makes defender undead → Life Steal immune. Atk 1 (100% blocked by def 1) + attacker Life Steal -3 vs res 5 → 0 (immune). Without undead it would be 3.6.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { lifeSteal: -3 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { vampirism: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  vampirismThrownToMeleeTransferWarlord: {
    desc: 'Vampirism script transfer: thrown 5, melee 2 vs def 2 (100% hit/block). Melee becomes 2+trunc(5/2)=4 → 2 through +2 Blood Sucker = 4; thrown drops to 1 → 0. Total 4.0. Without transfer: thrown 5→3 +2 Blood Sucker = 5, melee 2→0 = 5.0.',
    version: V_WARLORD,
    a: { atk:2, rtbType:'thrown', rtb:5, hitChance:70, hp:10, abilities: { vampirism: true } },
    b: { def:2, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  // --- Revenant (Warlord enchantment: grants undead + melee Death Touch 0) ---
  revenantGrantsDeathTouchWarlord: {
    desc: 'Revenant grants Death Touch 0: atk 1 (100% blocked by def 1) + granted Death Touch 0 vs Res 5 — pFail (10−5)/10 = 0.5, E[dmg] = 0.5 × 10 = 5.0. Without Revenant it would be 0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { revenant: true } },
    b: { def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  revenantDeathTouchOnThrownWarlord: {
    desc: 'Revenant writes Death Touch 0 to melee flags, which Caster.exe also uses for Thrown: thrown 1 is fully '
        + 'blocked by def 1, and the Thrown call and the unconditional melee call each make one Death 0 attempt '
        + 'vs Res 5, so 1 - 0.5^2 = 0.75 x 10 hp = 7.5. Without the Thrown record sharing only melee would roll, '
        + 'for 5.0.',
    version: V_WARLORD,
    a: { atk:0, rtbType:'thrown', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { revenant: true } },
    b: { def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 7.500 },
  },
  revenantDeathTouchNotRangedWarlord: {
    desc: 'Revenant clears the general/ranged Death Touch records: magic 1 fully blocked by def 1 and the melee-only Death Touch does not join the ranged attack → 0.',
    version: V_WARLORD,
    a: { rtbType:'magic', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { revenant: true } },
    b: { def:1, toBlkMod:70, res:5, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.000 },
  },
  revenantOverwritesStrongerDeathTouchWarlord: {
    desc: 'Revenant unconditionally replaces intrinsic Death Touch -3 with melee Death Touch 0: fully blocked melee averages 5.0, not the intrinsic 8.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { revenant: true, deathTouch: -3 } },
    b: { def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  revenantGrantsUndeadImmunityWarlord: {
    desc: 'Revenant makes defender undead → Death Touch immune. Atk 1 (100% blocked by def 1) + attacker Death Touch -3 vs Res 5 → 0 (immune). Without undead it would be (10−5−3)/10 × 10 = 2.0. '
        + 'The subject is that dmgToB stays 0; dmgToA is the defender\'s own Revenant Death Touch 0, which rides '
        + 'its unconditional counterattack at melee 0 against Res 0 and kills the attacking figure for 10.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { deathTouch: -3 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { revenant: true } },
    expected: { dmgToA: 10.000, dmgToB: 0 },
  },
  // --- Exorcise (Warlord touch: resist-or-banish vs fantastic units) ---
  exorciseFantasticWarlord: {
    desc: 'Exorcise -3 vs fantastic Res 5: atk 1 (100% blocked by def 1) + Exorcise touch, effRes 5-3=2 → pFail 0.8 × 10 hp = 8.0. Non-fantastic defender would be immune (0).',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { exorcise: -3 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, unitType:'fantastic_nature' },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  exorciseNonFantasticImmuneWarlord: {
    desc: 'Exorcise only affects fantastic units: same Exorcise -3 vs a NORMAL defender → 0. (As fantastic it would be 8.0.)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { exorcise: -3 } },
    b: { def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  exorciseUndeadExtraPenaltyWarlord: {
    desc: 'Exorcise (like Dispel Evil) hits created-undead with an additional -3: Exorcise 0 vs an undead (fantastic_death) defender Res 5 → effRes 5-3=2 → pFail 0.8 × 10 = 8.0. A non-undead fantastic defender would be effRes 5 → 0.5 × 10 = 5.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { exorcise: 0 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { undead: true } },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  // --- Destruction (CoM2/Warlord touch: one roll per attacking figure, whole-unit outcome) ---
  // Defenders are 4 figures x 10 hp = 40 total so a whole-unit kill is distinguishable from
  // the per-figure kill that Stoning/Death Touch would produce (which would be 10 per fail).
  destructionWholeUnitCoM2: {
    desc: 'Destruction 0 vs Res 5: one attacker figure makes one attempt. Melee atk 1 is fully blocked; pFail 0.5 destroys the whole 4x10 unit → 0.5 x 40 = 20.0.',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 20.000 },
  },
  destructionPerAttackerFigureCoM2: {
    desc: 'Destruction rolls once per surviving attacker figure: 4 figures each fail independently with p=0.5, so P(any failure)=1-0.5^4=0.9375. The whole 4x10 target is destroyed for E[dmg]=37.5; one whole-call roll would deal 20.0.',
    version: V_COM2,
    a: { figs:4, atk:1, hitChance:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 37.500 },
  },
  destructionSaveModifierCoM2: {
    desc: 'Destruction -3 vs Res 5: effRes 5-3=2 → pFail 0.8 x 40 = 32.0 (vs 20.0 at modifier 0).',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { destruction: -3 } },
    b: { figs:4, def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 32.000 },
  },
  destructionMagicImmunityCoM2: {
    desc: 'Magic Immunity blocks Destruction: same setup as destructionWholeUnitCoM2 but the defender has Magic Immunity → 0 (would be 20.0 without it).',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:5, hp:10, abilities: { magicImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  destructionHighResistanceCoM2: {
    desc: 'Destruction 0 vs Res 10: effRes 10 is never failed → 0 (Res 5 would give 20.0).',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:10, hp:10 },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  destructionRangedMagicCoM2: {
    desc: 'Destruction fires on magical ranged (CoM2): one attacker figure makes one attempt at effRes 5, so pFail 0.5 x the 40-HP target = 20.0.',
    version: V_COM2,
    a: { rtbType:'magic', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:5, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 20.000 },
  },
  destructionRangedMagicWarlord: {
    desc: 'Destruction still fires on magical ranged in Warlord — unlike Stoning/Death Touch, it has no ranged exclusion (Energy Cannon triggers it from its beam projectile, and the Magician only attacks at range) → 0.5 x 40 = 20.0.',
    version: V_WARLORD,
    a: { rtbType:'magic', rtb:1, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:5, hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 20.000 },
  },
  destructionBlessCoM2: {
    desc: 'Destruction is Chaos-realm, so Bless protects: Res 2 + Bless 5 = 7 → pFail 0.3 x 40 = 12.0. Without Bless it would be pFail 0.8 x 40 = 32.0.',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:2, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 12.000 },
  },
  destructionBlessWarlord: {
    desc: "Warlord's Bless resistance bonus is 4, not CoM2's 5: Res 2 + 4 = 6 → pFail 0.4 x 40 = 16.0 (12.0 in CoM2).",
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:2, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 16.000 },
  },
  destructionDeathImmunityNoProtectionCoM2: {
    desc: 'Death Immunity does NOT stop Destruction — the realm is Chaos, not Death: still 0.5 x 40 = 20.0 (a Death-realm touch would be 0).',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:5, hp:10, abilities: { deathImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 20.000 },
  },
  destructionNotInMoM: {
    desc: 'Destruction does not exist in MoM: same setup as destructionWholeUnitCoM2 under MoM 1.31 → 0 (20.0 in CoM2).',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, hp:10, abilities: { destruction: 0 } },
    b: { figs:4, def:1, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  // --- Angelic Guardians (Warlord global: grants/improves Exorcise on friendly units) ---
  angelicGuardiansGrantsExorciseRegularWarlord: {
    desc: 'Angelic Guardians on a regular unit grants Exorcise -0: vs fantastic Res 5, effRes 5 → pFail 0.5 × 10 = 5.0. Without the enchantment it would be 0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { angelicGuardians: true } },
    b: { def:1, toBlkMod:70, res:5, hp:10, unitType:'fantastic_nature' },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  angelicGuardiansLifeTierWarlord: {
    desc: 'Angelic Guardians on a Sanctified (life-realm) unit grants Exorcise -1: vs fantastic Res 5, effRes 4 → pFail 0.6 × 10 = 6.0. A regular unit would only get -0 → 5.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { angelicGuardians: true, sanctify: true } },
    b: { def:1, toBlkMod:70, res:5, hp:10, unitType:'fantastic_nature' },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  angelicGuardiansImprovesExistingExorciseWarlord: {
    desc: 'Angelic Guardians on a regular unit that already has Exorcise -1 adds -2 → -3: vs fantastic Res 5, effRes 2 → pFail 0.8 × 10 = 8.0. Without the enchantment, Exorcise -1 → effRes 4 → 0.6 × 10 = 6.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { angelicGuardians: true, exorcise: -1 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, unitType:'fantastic_nature' },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  angelicGuardiansFantasticChaosNotBuffedWarlord: {
    desc: 'Angelic Guardians does not buff non-Life fantastic creatures: a fantastic Chaos attacker gains no Exorcise → 0 (atk 1 fully blocked). A realm-less/Life unit would have gained Exorcise -0 → 5.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, unitType:'fantastic_chaos', abilities: { angelicGuardians: true } },
    b: { def:1, toBlkMod:70, res:5, hp:10, unitType:'fantastic_nature' },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  angelicGuardiansImprovesExistingExorciseOnChaosWarlord: {
    desc: 'Angelic Guardians improves an existing Exorcise even on a non-Life fantastic unit: Chaos Exorcise -1 becomes -3, so Res 5 fails 80% of the time for 8.0 expected damage. Without the improvement it would deal 6.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, unitType:'fantastic_chaos', abilities: { angelicGuardians: true, exorcise: -1 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, unitType:'fantastic_nature' },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  angelicGuardiansUsesBaseFantasticGateWarlord: {
    desc: 'Angelic Guardians uses BASEFANTASTIC: a base regular unit made Fantastic by Combat Summoned still gains Exorcise 0, dealing 5.0 expected damage. A live-Fantastic gate would incorrectly deal 0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { angelicGuardians: true, combatSummoned: true } },
    b: { def:1, toBlkMod:70, res:5, hp:10, unitType:'fantastic_nature' },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  shadowStrikeGrantsThrownWarlord: {
    desc: 'Shadow Strike (Warlord): melee-only unit gains a thrown attack at 1 + 1/3 of melee. Melee 9 → thrown 1+floor(9/3)=4. Both 100% hit vs def 0 → 9 + 4 = 13.0 (without Shadow Strike, melee 9 only → 9.0)',
    version: V_WARLORD,
    a: { atk:9, hitChance:70, hp:10, abilities: { shadowStrike: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 13.000 },
  },
  shadowStrikeBoostsExistingThrownWarlord: {
    desc: 'Shadow Strike (Warlord): a unit with existing thrown gains 1 + 1/3 of melee as added thrown. Melee 9, thrown 4 → thrown 4+1+floor(9/3)=8. Both 100% hit vs def 0 → 9 + 8 = 17.0 (without Shadow Strike, 9 + 4 = 13.0)',
    version: V_WARLORD,
    a: { atk:9, rtbType:'thrown', rtb:4, hitChance:70, hp:10, abilities: { shadowStrike: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 17.000 },
  },
  shadowStrikeAfterColossalWarlord: {
    desc: 'Ordered Shadow Strike (Warlord): Colossal Strength raises melee 9 → 13, then Shadow Strike creates thrown 1+floor(13/3)=5. Both hit at 100% vs def 0 → 18.0; using pre-Colossal melee would deal 17.0',
    version: V_WARLORD,
    a: { atk:9, hitChance:70, hp:10, abilities: { colossalStrength: true, shadowStrike: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 18.000 },
  },
  shadowStrikeGrantPrecedesNoBlazingMarchWarlord: {
    desc: 'Ordered Shadow Strike (Warlord): Blazing March adds +3 melee in region c, so the grant reads melee 12 and creates thrown 1+floor(12/3)=5 in region d. Its +3 Thrown bonus is written in region c, where the Thrown field does not exist yet, so the created attack does not carry it: 12 + 5 = 17.0, not the 20.0 a pre-sequence grant would take',
    version: V_WARLORD,
    a: { atk:9, hitChance:70, hp:10, abilities: { blazingMarch: true, shadowStrike: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 17.000 },
  },
  shadowStrikeFillsThrownFocusMagicVacatedWarlord: {
    desc: 'Focus Magic moves the Thrown field rather than retyping it (Units.RecalculateUnits.pas:885-891), so `SThrown` stands empty when Shadow Strike reaches `UnitCalc.CAS:1262` and the grant is the whole of it. Melee 9, thrown 4: the 4 leaves for the Ranged field, the grant makes thrown 1+floor(9/3)=4, and melee mode fires melee plus thrown for 9 + 4 = 13.0. Without Focus Magic the grant lands on the untouched 4 for 9 + 8 = 17.0; without Shadow Strike the vacated field stays empty for 9.0.',
    version: V_WARLORD,
    a: { atk:9, rtbType:'thrown', rtb:4, hitChance:70, hp:10,
      abilities: { focusMagic: true, shadowStrike: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 13.000 },
  },
  shadowStrikeDoublePoisonWarlord: {
    desc: 'Shadow Strike (Warlord): the granted thrown is a separate phase, so Poison fires on both thrown and melee. Melee 9 grants thrown 4, both 100% hit vs def 0 → 13 physical; Poison 3 vs res 5 (CoM2 fail = (11−5)/10 = 0.6) → 1.8 per phase × 2 = 3.6, total 16.6 (without Shadow Strike, melee 9 + single poison 1.8 = 10.8)',
    version: V_WARLORD,
    a: { atk:9, hitChance:70, hp:10, abilities: { shadowStrike: true, poison: 3 } },
    b: { def:0, toBlkMod:70, res:5, hp:30 },
    expected: { dmgToA: 0, dmgToB: 16.600 },
  },

  // --- Soul Flay (Warlord Death curse: −1 melee / −1 ranged / −2 armor / −2 resistance per experience level; Recruit counts as level 1) ---
  soulFlayMeleeRecruitWarlord: {
    desc: 'Soul Flay (Warlord) on a Recruit (normal level = level 1): melee 5 − 1 = 4, 100% hit vs def 0 → 4.0 (without Soul Flay it would be 5.0)',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10, abilities: { soulFlay: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  soulFlayMeleeScalesEliteWarlord: {
    desc: 'Soul Flay (Warlord) scales with level: Elite (level 4) melee 10 + 2 (Elite level bonus) − 4 = 8, 100% hit vs def 0 → 8.0 (a flat −1 penalty would give 11.0)',
    version: V_WARLORD,
    a: { atk:10, level:'elite', hitChance:70, hp:10, abilities: { soulFlay: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  soulFlayRangedRecruitWarlord: {
    desc: 'Soul Flay (Warlord) on a Recruit missile attacker: SRanged 5 − 1 = 4, 100% hit vs def 0 → 4.0. Without the ranged write it would be 5.0; without Soul Flay entirely, also 5.0.',
    version: V_WARLORD,
    a: { atk:0, rtbType:'missile', rtb:5, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { soulFlay: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  soulFlayArmorRecruitWarlord: {
    desc: 'Soul Flay (Warlord) on a Recruit defender: armor 2 − 2 = 0, so atk 2 (100% hit/block) passes a defenseless target → 2.0 (without Soul Flay, def 2 blocks all → 0.0)',
    version: V_WARLORD,
    a: { atk:2, hitChance:70, hp:10 },
    b: { def:2, toBlkMod:70, hp:10, abilities: { soulFlay: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  soulFlayResistanceRecruitWarlord: {
    desc: 'Soul Flay (Warlord) on a Recruit defender: resistance 5 − 2 = 3. Death Touch 0 vs res 3 → pFail (10−3)/10 = 0.7 × 10 hp = 7.0. Melee atk 1 fully blocked by armor 3−2=1. (Without Soul Flay, res 5 → pFail 0.5 → 5.0)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { deathTouch: 0 } },
    b: { def:3, toBlkMod:70, res:5, hp:10, abilities: { soulFlay: true } },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },

  // --- Plague (Warlord combat curse: −3 melee / −3 ranged / −3 armor / −6 resistance / −10% To Hit) ---
  plagueMeleeWarlord: {
    desc: 'Plague (Warlord) on the attacker: melee 8 − 3 = 5, 100% base hit − 10% Plague = 90% vs def 0 → 5 × 0.9 = 4.5 (without Plague it would be 8.0)',
    version: V_WARLORD,
    a: { atk:8, hitChance:70, hp:10, abilities: { plague: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 4.500 },
  },
  plagueRangedWarlord: {
    desc: 'Plague (Warlord) on a missile attacker: SRanged 8 − 3 = 5, 100% base hit − 10% Plague = 90% vs def 0 → 5 × 0.9 = 4.5. Without the ranged write it would be 8 × 0.9 = 7.2; without Plague entirely, 8.0.',
    version: V_WARLORD,
    a: { atk:0, rtbType:'missile', rtb:8, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { plague: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.500 },
  },
  plagueArmorWarlord: {
    desc: 'Plague (Warlord) on the defender: armor 3 − 3 = 0, so atk 3 (100% hit/block) passes a defenseless target → 3.0 (without Plague, def 3 blocks all → 0.0)',
    version: V_WARLORD,
    a: { atk:3, hitChance:70, hp:10 },
    b: { def:3, toBlkMod:70, hp:10, abilities: { plague: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  plagueResistanceWarlord: {
    desc: 'Plague (Warlord) on the defender: resistance 8 − 6 = 2. Death Touch 0 vs res 2 → pFail (10−2)/10 = 0.8 × 10 hp = 8.0. Melee atk 1 fully blocked by armor 4−3=1. (Without Plague, res 8 → pFail 0.2 → 2.0)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { deathTouch: 0 } },
    b: { def:4, toBlkMod:70, res:8, hp:10, abilities: { plague: true } },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  plagueToHitWarlord: {
    desc: 'Plague (Warlord) −10% To Hit: melee 13 − 3 = 10, 100% base hit − 10% = 90% vs def 0 → 10 × 0.9 = 9.0 (without Plague, 13 × 100% = 13.0)',
    version: V_WARLORD,
    a: { atk:13, hitChance:70, hp:10, abilities: { plague: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 9.000 },
  },

  // --- Pox Host / Goblin Pox (Warlord global combat debuff, race-dependent) ---
  // Non-Goblin: −3 melee / −3 ranged / −3 armor / −1 resistance, no To Hit. Goblin: −1 melee / −1 ranged / −1 armor (no resistance penalty).
  goblinPoxNonGoblinMeleeWarlord: {
    desc: 'Pox Host (Warlord) on a non-Goblin attacker: melee 8 − 3 = 5, 100% hit vs def 0 → 5.0 (no To Hit penalty, unlike Plague). Without Pox Host it would be 8.0',
    version: V_WARLORD,
    poxHost: true,
    a: { atk:8, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  goblinPoxNonGoblinArmorWarlord: {
    desc: 'Pox Host (Warlord) on a non-Goblin defender: armor 3 − 3 = 0, so thrown 3 (100% hit/block) passes a defenseless target → 3.0 (without Pox Host, def 3 blocks all → 0.0). Pox Host is a global, so both sides take it; the attack uses Thrown, the one channel the script leaves alone, which keeps the attack strength at 3 and isolates the armor rule. A conventional missile would be reduced to 0 and print 0.0.',
    version: V_WARLORD,
    poxHost: true,
    a: { atk:0, rtbType:'thrown', rtb:3, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:3, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  goblinPoxNonGoblinRangedWarlord: {
    desc: 'Pox Host (Warlord) on a non-Goblin missile attacker: SRanged 8 − 3 = 5, 100% hit vs def 0 → 5.0 (no To Hit penalty, unlike Plague). Without the ranged write it would be 8.0.',
    version: V_WARLORD,
    poxHost: true,
    a: { atk:0, rtbType:'missile', rtb:8, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  goblinPoxNonGoblinResistanceWarlord: {
    desc: 'Pox Host (Warlord) on a non-Goblin defender: resistance 5 − 1 = 4 (helptext: non-Goblins take −1 resistance). Death Touch 0 vs res 4 → pFail (10−4)/10 = 0.6 × 10 hp = 6.0. Melee atk 1 fully blocked by armor 4−3=1. (Without Pox Host, res 5 → pFail 0.5 → 5.0; the manual −3 would give res 2 → 8.0)',
    version: V_WARLORD,
    poxHost: true,
    a: { atk:1, hitChance:70, hp:10, abilities: { deathTouch: 0 } },
    b: { def:4, toBlkMod:70, res:5, hp:10 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  goblinPoxGoblinMilderWarlord: {
    desc: 'Pox Host (Warlord) on a GOBLIN attacker: only −1 melee (not −3). melee 8 − 1 = 7, 100% hit vs def 0 → 7.0 (without Pox Host, 8.0; if it wrongly used the non-Goblin −3 it would be 5.0)',
    version: V_WARLORD,
    poxHost: true,
    a: { atk:8, hitChance:70, hp:10, race: 'Goblin' },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  goblinPoxGoblinRangedMilderWarlord: {
    desc: 'Pox Host (Warlord) on a GOBLIN missile attacker: only −1 ranged (not −3). SRanged 8 − 1 = 7, 100% hit vs def 0 → 7.0 (without Pox Host, 8.0; if it wrongly used the non-Goblin −3 it would be 5.0)',
    version: V_WARLORD,
    poxHost: true,
    a: { atk:0, rtbType:'missile', rtb:8, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, race: 'Goblin' },
    b: { def:0, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  goblinPoxGoblinResistanceWarlord: {
    desc: 'Pox Host (Warlord) on a GOBLIN defender: resistance is NOT penalized (helptext: Goblins take only −1 melee / −1 armor). res stays 5 → Death Touch 0 vs res 5 → pFail (10−5)/10 = 0.5 × 10 = 5.0. Melee atk 1 fully blocked by armor 4−1=3. (If the Goblin branch wrongly applied a −1 resistance, res 4 → 6.0; a non-Goblin −1 also → res 4 → 6.0)',
    version: V_WARLORD,
    poxHost: true,
    a: { atk:1, hitChance:70, hp:10, abilities: { deathTouch: 0 } },
    b: { def:4, toBlkMod:70, res:5, hp:10, race: 'Goblin' },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },

  // --- Great Unbinding (Warlord Sorcery global: −20% To Hit / −20% To Defend / −2 Resistance on opponent fantastic creatures) ---
  greatUnbindingToHitWarlord: {
    desc: 'Great Unbinding (Warlord) on a fantastic attacker: To Hit 100% − 20% = 80%. melee 10 (1 fig) vs def 0 → 10 × 0.8 = 8.0 (without Great Unbinding, 100% → 10.0)',
    version: V_WARLORD,
    a: { figs:1, atk:10, hitChance:70, hp:10, unitType:'fantastic_chaos', abilities: { greatUnbinding: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  greatUnbindingToBlockWarlord: {
    desc: 'Great Unbinding (Warlord) on a fantastic defender: To Block 100% − 20% = 80%. atk 10 (100% hit) vs def 10 blocking at 80% → ~2 leak through (without Great Unbinding, def 10 at 100% blocks all → 0.0)',
    version: V_WARLORD,
    a: { figs:1, atk:10, hitChance:70, hp:20 },
    b: { def:10, toBlkMod:70, hp:20, unitType:'fantastic_chaos', abilities: { greatUnbinding: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  greatUnbindingResistanceWarlord: {
    desc: 'Great Unbinding (Warlord) on a fantastic defender: resistance 5 − 2 = 3. Death Touch 0 vs res 3 → pFail (10−3)/10 = 0.7 × 10 hp = 7.0 (without Great Unbinding, res 5 → 0.5 → 5.0)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { deathTouch: 0 } },
    b: { def:4, toBlkMod:70, res:5, hp:10, unitType:'fantastic_chaos', abilities: { greatUnbinding: true } },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  greatUnbindingNonFantasticUnaffectedWarlord: {
    desc: 'Great Unbinding (Warlord) on a non-fantastic attacker: no effect. melee 10 (1 fig, 100% hit) vs def 0 → 10.0 (the fantastic-only gating means a normal unit keeps full To Hit)',
    version: V_WARLORD,
    a: { figs:1, atk:10, hitChance:70, hp:10, unitType:'normal', abilities: { greatUnbinding: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },

  // --- Natural Selection (Warlord Nature global: recruitment bonuses from city resources) ---
  naturalSelectionCoalWarlord: {
    desc: 'Natural Selection Coal (Warlord): +1 melee. melee 5 + 1 = 6 (1 fig, 100% hit) vs def 0 → 6.0 (without Coal → 5.0)',
    version: V_WARLORD,
    a: { figs:1, atk:5, hitChance:70, hp:10, abilities: { coal: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  naturalSelectionCoalCreatesMeleeWarlord: {
    desc: 'Natural Selection Coal (Warlord) on a melee-less defender: CreateUnit.CAS writes SAttack at ABase ungated, so BaseUnits.attack becomes 1 and the melee slot is open. The counterattack is melee 0 + 1 = 1 (1 fig, 100% hit) vs def 0 → dmgToA 1.0 (reading the card input instead of the permanent record discards it → 0.0)',
    version: V_WARLORD,
    a: { figs:1, atk:5, hitChance:70, hp:30 },
    b: { figs:1, atk:0, def:0, toBlkMod:70, hitChance:70, hp:20, abilities: { coal: true } },
    expected: { dmgToA: 1.000, dmgToB: 5.000 },
  },
  naturalSelectionCoalOpensHolyBonusWarlord: {
    desc: 'Holy Bonus reads the permanent record (`if B.attack > 0`, Units.RecalculateUnits.pas:2530), which Coal has raised: the counterattack is 0 + 1 (Coal) + 2 (Holy Bonus) = 3 (1 fig, 100% hit) vs def 0 → dmgToA 3.0 (without Coal the permanent record stays 0 and the aura skips melee → 0.0). Holy Bonus also gives the defender +2 armor, blocking 2 of the incoming 5 at 100% To Block → dmgToB 3.0',
    version: V_WARLORD,
    a: { figs:1, atk:5, hitChance:70, hp:30 },
    b: { figs:1, atk:0, def:0, toBlkMod:70, hitChance:70, hp:20, abilities: { coal: true, holyBonus: 2 } },
    expected: { dmgToA: 3.000, dmgToB: 3.000 },
  },
  naturalSelectionCoalOpensNodeAuraWarlord: {
    desc: '`applynodeaura` gates melee on the permanent record (Units.RecalculateUnits.pas:466), which Coal has raised: the counterattack is 0 + 1 (Coal) + 2 (node aura) = 3 (1 fig, 100% hit) vs def 0 → dmgToA 3.0 (without Coal the node aura skips melee → 0.0). The node aura also gives the Nature defender +2 armor, blocking 2 of the incoming 5 at 100% To Block → dmgToB 3.0',
    version: V_WARLORD,
    a: { figs:1, atk:5, hitChance:70, hp:30 },
    b: { figs:1, atk:0, def:0, toBlkMod:70, hitChance:70, hp:20, race:'Nature', abilities: { coal: true } },
    nodeAura: 'nature',
    expected: { dmgToA: 3.000, dmgToB: 3.000 },
  },
  naturalSelectionCoalAttacksWarlord: {
    desc: 'The same Coal-created melee on the *attacking* card, which no melee-initiation guard may refuse: the exchange is admitted regardless of attack strength, so melee 0 + 1 = 1 (1 fig, 100% hit) vs def 0 → dmgToB 1.0, and the defender still counterattacks for 5 (without Coal the attacker deals 0.0 and only the counterattack lands)',
    version: V_WARLORD,
    a: { figs:1, atk:0, def:0, toBlkMod:70, hitChance:70, hp:20, abilities: { coal: true } },
    b: { figs:1, atk:5, hitChance:70, hp:30 },
    expected: { dmgToA: 5.000, dmgToB: 1.000 },
  },
  naturalSelectionIronWarlord: {
    desc: 'Natural Selection Iron (Warlord): +1 armor on defender. armor 4 + 1 = 5 (100% block) fully blocks atk 5 → 0.0 (without Iron, def 4 lets 1 leak → 1.0)',
    version: V_WARLORD,
    a: { figs:1, atk:5, hitChance:70, hp:20 },
    b: { def:4, toBlkMod:70, hp:20, abilities: { iron: true } },
    expected: { dmgToA: 0, dmgToB: 0.000 },
  },
  naturalSelectionWildGameWarlord: {
    desc: 'Natural Selection Wild game (Warlord): +1 ranged attack. missile 5 + 1 = 6 (1 fig, 100% hit) vs def 0 → 6.0 (without Wild game → 5.0)',
    version: V_WARLORD,
    a: { figs:1, rtbType:'missile', rtb:5, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { wildGame: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  naturalSelectionWildGameMagicRangedWarlord: {
    desc: 'Natural Selection Wild game (Warlord): +1 also applies to magic ranged. magic 5 + 1 = 6 (1 fig, 100% hit) vs def 0 → 6.0 (without Wild game → 5.0)',
    version: V_WARLORD,
    a: { figs:1, rtbType:'magic', rtb:5, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { wildGame: true } },
    b: { def:0, toBlkMod:70, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  naturalSelectionWildGameThrownNoBonusWarlord: {
    desc: 'Natural Selection Wild game (Warlord): thrown is NOT a "ranged attack" for this bonus. Base thrown 7, 100% hit, def 2 blocks 2 → 5.0 (melee atk 1 fully blocked by def 2). With the bonus wrongly applied → 8 − 2 = 6.',
    version: V_WARLORD,
    a: { atk:1, rtbType:'thrown', rtb:7, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { wildGame: true } },
    b: { def:2, toBlkMod:70, hp:20 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  naturalSelectionNightshadeWarlord: {
    desc: 'Natural Selection Nightshade (Warlord): +1 Resistance on defender. res 4 + 1 = 5. Death Touch 0 vs res 5 → pFail (10−5)/10 = 0.5 × 10 hp = 5.0 (without Nightshade, res 4 → 0.6 → 6.0). Melee atk 1 fully blocked by armor 4.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { deathTouch: 0 } },
    b: { def:4, toBlkMod:70, res:4, hp:10, abilities: { nightshade: 1 } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  naturalSelectionPowerMineralsWarlord: {
    desc: 'Natural Selection Power minerals (Warlord): +N Resistance directly; 2 → +2. res 3 + 2 = 5. Death Touch 0 vs res 5 → 0.5 × 10 hp = 5.0 (without Power minerals, res 3 → 0.7 → 7.0). Melee atk 1 fully blocked by armor 4.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { deathTouch: 0 } },
    b: { def:4, toBlkMod:70, res:3, hp:10, abilities: { powerMinerals: 2 } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },

  // --- Survival Instinct +To Block (Warlord recruitment bonus: +N% To Defend on normal units) ---
  survivalInstinctToBlockNormalWarlord: {
    desc: 'Survival Instinct +To Block (Warlord) on a normal defender: +40% raises To Block from 30% base to 70%. atk 10 (100% hit, 1 fig) vs def 10 → 10 × (1 − 0.70) = 3.0 (without the bonus, 30% block → 7.0)',
    version: V_WARLORD,
    a: { figs:1, atk:10, hitChance:70, hp:20 },
    b: { def:10, hp:20, unitType:'normal', abilities: { survivalInstinctToBlock: 40 } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  survivalInstinctToBlockFantasticUnaffectedWarlord: {
    desc: 'Survival Instinct +To Block (Warlord): no effect on fantastic creatures (normal-unit recruitment bonus). def 10 at 30% base block: atk 10 (100% hit) → 10 × 0.70 = 7.0 (same as without the bonus)',
    version: V_WARLORD,
    a: { figs:1, atk:10, hitChance:70, hp:20 },
    b: { def:10, hp:20, unitType:'fantastic_chaos', abilities: { survivalInstinctToBlock: 40 } },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },

  // --- Hierophany (Warlord Life curse: halves Defense, strips all immunities / Lightning Resist / Negate First Strike) ---
  hierophanyHalvesDefenseWarlord: {
    desc: 'Hierophany (Warlord) halves the cursed unit\'s Defense: def 8 → 4. atk 8 (100% hit/block): 8 − 4 = 4.0 (without Hierophany, def 8 blocks all → 0.0)',
    version: V_WARLORD,
    a: { atk:8, hitChance:70, hp:10 },
    b: { def:8, toBlkMod:70, hp:20, abilities: { hierophany: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  hierophanyStripsWeaponImmunityWarlord: {
    desc: 'Hierophany (Warlord) strips Weapon Immunity from the cursed unit: a normal melee attacker is no longer blocked. atk 8 (100% hit/block) vs def 0 → 8.0 (with Weapon Immunity intact, Warlord raises def to 10 → 0.0)',
    version: V_WARLORD,
    a: { atk:8, hitChance:70, hp:10, unitType:'normal', weapon:'normal' },
    b: { def:0, toBlkMod:70, hp:20, unitType:'normal', abilities: { weaponImmunity: true, hierophany: true } },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  hierophanyStripsMagicImmunityWarlord: {
    desc: 'Hierophany (Warlord) strips Magic Immunity: sorcery magic ranged is no longer blocked. rtb 3 (100% hit/block) vs def 0 → 3.0 (with Magic Immunity intact, def is raised to 50 → 0.0)',
    version: V_WARLORD,
    a: { rtbType:'magic', rtb:3, hitRanged:70, hitThrown:70, hitBreath:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { magicImmunity: true, hierophany: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },

  // --- Pillar of Faith (Warlord Life city enchantment: 20% Lucky grant, +1 Resistance per Religious Building) ---
  pillarOfFaithLuckyResistanceWarlord: {
    desc: 'Pillar of Faith Lucky grants +1 Resistance: Poison 4 (CoM −1) vs res 5+1=6 → pFail (11−6)/10=0.5, E[dmg]=2.0 (without Lucky, res 5 → pFail 0.6 → 2.4)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { pillarOfFaithLucky: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  pillarOfFaithResistanceWarlord: {
    desc: 'Pillar of Faith grants +1 Resistance per Religious Building: 3 buildings → +3 res. Poison 4 (CoM −1) vs res 5+3=8 → pFail (11−8)/10=0.3, E[dmg]=1.2 (without the bonus, res 5 → 2.4)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { pillarOfFaithRes: 3 } },
    expected: { dmgToA: 0, dmgToB: 1.200 },
  },
  pillarOfFaithResistanceUncappedWarlord: {
    desc: 'Pillar of Faith has no script-side cap: 12 qualifying buildings → +12 res. Poison 10 (CoM −1) vs res 0+12=12 → immune → 0.0 (an artificial +8 cap would produce 3.0 damage)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { poison: 10 } },
    b: { def:1, toBlkMod:70, res:0, hp:20, abilities: { pillarOfFaithRes: 12 } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },

  // --- Blaze of Glory (Warlord Chaos enchantment: Armor→Melee, Defense→0, Ranged→Thrown, +Armor Piercing, −First Strike) ---
  blazeOfGloryArmorToMeleeWarlord: {
    desc: 'Blaze of Glory: Melee gains the unit\'s full Armor. Melee 2, Armor 6 → melee 2+6=8, 100% hit vs def 0 → 8.0. (Without Blaze, melee 2 → 2.0.)',
    version: V_WARLORD,
    a: { atk:2, def:6, hitChance:70, hp:10, abilities: { blazeOfGlory: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  blazeOfGloryArmorPiercingWarlord: {
    desc: 'Blaze of Glory grants Armor Piercing. Attacker base armor 0 (melee stays 4), AP halves defender def 4 → 2, 100% hit/block → 4−2 = 2.0. (Without the granted AP, 4−4 = 0.)',
    version: V_WARLORD,
    a: { atk:4, def:0, hitChance:70, hp:10, abilities: { blazeOfGlory: true } },
    b: { def:4, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  blazeOfGloryRangedToThrownWarlord: {
    desc: 'Blaze of Glory turns the Ranged attack into a Thrown attack of the same strength, so it fires in the melee engagement. Melee 1, missile 6 (rangedCheck off → missile would not fire) → thrown 6 + melee 1 = 7.0. (Without Blaze, only melee 1 fires → 1.0.)',
    version: V_WARLORD,
    a: { atk:1, def:0, rtbType:'missile', rtb:6, hitChance:70, hp:10, abilities: { blazeOfGlory: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  blazeOfGloryFollowsRustWarlord: {
    desc: 'Rust (UnitCalc.CAS:493) runs before Blaze of Glory (:1490), so Rust still sees a missile attack and takes its −3 before the transfer. Melee 1−3 → 0, missile 6−3=3 → thrown 3 → 3.0. (Without Rust, thrown 6 + melee 1 → 7.0; with the transfer applied first, Rust would find no missile and the thrown would be 6.)',
    version: V_WARLORD,
    a: { atk:1, def:0, rtbType:'missile', rtb:6, hitChance:70, hp:10, abilities: { blazeOfGlory: true, rust: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  blazeOfGloryCarriesRangedlessLionheartWarlord: {
    desc: 'Lionheart\'s ranged +3 is gated on not Ismagicalranged(U.rangedtype) (Units.RecalculateUnits.pas:1730), which is True for a zero ranged type (:2968-2975), so it lands on the Ranged field of a unit with no ranged attack; Blaze of Glory then moves that whole field into Thrown (UnitCalc.CAS:1494-1500). Melee 1+3 = 4 plus a new thrown 3 → 7.0. (Without Blaze, melee 4 only → 4.0; without Lionheart, melee 1 and nothing to transfer → 1.0.)',
    version: V_WARLORD,
    a: { atk:1, def:0, hitChance:70, hp:10, abilities: { blazeOfGlory: true, lionheart: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  blazeOfGloryCarriesWeaknessThrownPenaltyWarlord: {
    desc: 'Weakness writes Dec(U.ranged, 3) and Dec(U.thrown, 3) with no positivity and no type gate (Units.RecalculateUnits.pas:2273-2279), so both record fields carry the penalty before Blaze of Glory adds Ranged into Thrown (UnitCalc.CAS:1494-1500): missile 7-3 = 4 arrives on a Thrown field already standing at -3 → thrown 1, beside melee 5-3 = 2 → 3.0. (Without Weakness, melee 5 plus thrown 7 → 12.0; without Blaze of Glory the missile attack does not fire in melee, leaving melee 2 → 2.0.)',
    version: V_WARLORD,
    a: { atk:5, rtb:7, rtbType:'missile', def:0, hitChance:70, hp:10, abilities: { blazeOfGlory: true, weakness: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  blazeOfGloryCarriesWeaknessRangedPenaltyWarlord: {
    desc: 'Dec(U.ranged, 3) has no type gate either (Units.RecalculateUnits.pas:2273-2279), so it reaches a typeless Ranged field: Lionheart\'s own ungated +3 (:1730) puts 3 there, Weakness takes it back to 0, and Blaze of Glory transfers that 0 into Thrown (UnitCalc.CAS:1494-1500). Melee 5+3-3 = 5 plus thrown 4-3 = 1 → 6.0. (Without Weakness, melee 8 plus thrown 4+3 = 7 → 15.0; reading the ranged arm as a type predicate leaves SRanged at 3 and gives thrown 4 → 9.0.)',
    version: V_WARLORD,
    a: { atk:5, rtb:4, rtbType:'thrown', def:0, hitChance:70, hp:10,
      abilities: { blazeOfGlory: true, weakness: true, lionheart: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  blazeOfGloryCarriesMindStormRangedPenaltyWarlord: {
    desc: 'Mind Storm\'s Dec(U.ranged, 5) is ungated in the same way (Units.RecalculateUnits.pas:2281-2295), so an empty typeless Ranged field stands at -5 when Blaze of Glory adds it into Thrown (UnitCalc.CAS:1494-1500). Melee 9-3 = 6 with an armor of 5-5 = 0 to carry, plus thrown 12-5 = 7 taking the -5 → 2 → 8.0. (Without Mind Storm, melee 9+5 = 14 plus thrown 12 → 26.0; gating the ranged arm on a live slot leaves the transfer nothing to carry and gives thrown 7 → 13.0.)',
    version: V_WARLORD,
    a: { atk:9, rtb:12, rtbType:'thrown', def:5, hitChance:70, hp:10,
      abilities: { blazeOfGlory: true, mindStorm: true } },
    b: { def:0, toBlkMod:70, hp:40 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  blazeOfGloryCarriesNoBombsGrenadesGrantWarlord: {
    desc: 'SETSTAT(U,SThrown,0,GETSTAT(U,SThrown,0)+%I(8-SFigures/2)) (UnitCalcPre.CAS:1071) is one '
      + 'write to one field, so the Ranged field Blaze of Glory needs standing by for its transfer '
      + '(UnitCalc.CAS:1494-1500) never takes a copy of the grant merely because it is empty and '
      + 'typeless when the block runs. 1-figure melee 5 with Armor 2: Blaze moves the armor into '
      + 'melee for 7, Bombs&Grenades grants Thrown floor(8 - 1/2) = 7, and there is nothing in the '
      + 'Ranged field for the transfer to carry, so 100% hit vs def 0 gives 7 + 7 = 14.0. (Letting '
      + 'the grant fire on every empty typeless slot puts 7 in the Ranged field too and Blaze adds '
      + 'it in for Thrown 14 and 21.0; dropping Explosive Reform leaves melee 7 alone → 7.0, and '
      + 'dropping Blaze of Glory leaves melee 5 beside the same Thrown 7 → 12.0.)',
    version: V_WARLORD,
    a: { figs:1, atk:5, def:2, hitChance:70, hp:10,
      abilities: { outlanderWizard: true, explosive: true, blazeOfGlory: true } },
    b: { def:0, toBlkMod:70, hp:40 },
    expected: { dmgToA: 0, dmgToB: 14.000 },
  },
  blazeOfGloryThrownReadsHolyWeaponToHitWarlord: {
    desc: 'Inc(U.hitchancethrown, 10) is unconditional (Units.RecalculateUnits.pas:1803-1809), so Holy Weapon\'s +10 already stands on the record\'s Thrown threshold when Blaze of Glory puts an attack there (UnitCalc.CAS:1494-1500). Melee 5 at 30+10 = 40% plus the transferred thrown 7 at the same 40% → 2.0 + 2.8 = 4.8. (Without Holy Weapon both read 30% → 3.6; without Blaze of Glory the missile does not fire in melee, leaving melee 5 at 40% → 2.0.)',
    version: V_WARLORD,
    a: { atk:5, rtb:7, rtbType:'missile', def:0, hp:10, abilities: { blazeOfGlory: true, holyWeapon: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 4.800 },
  },
  blazeOfGloryThrownTakesNoDistancePenaltyWarlord: {
    desc: 'The ranged distance penalty is a resolution-time read of the finished record, so it '
      + 'follows the attack Blaze of Glory leaves behind. Lightning Blade has already spent the '
      + 'Thrown field (CreateUnit.CAS:294-299), so the transfer at UnitCalc.CAS:1494-1500 retypes '
      + 'the Ranged slot in place: missile 6 becomes Thrown 6 and fires in the melee engagement, '
      + 'where there is no range. Melee 1 + thrown 6 + the granted Lightning Breath 1, all at '
      + '30+70 = 100% → 8.0. (Reading the pre-sequence missile type instead applies CoM2\'s '
      + '−10−3×(6−4) = −16% to the thrown attack, giving 1 + 5.04 + 1 = 7.04; without Blaze of '
      + 'Glory the attack is still a missile, fires at range 6 and does take the −16% → 5.04.)',
    version: V_WARLORD,
    a: { atk:1, def:0, rtbType:'missile', rtb:6, hitChance:70, hp:10,
      abilities: { blazeOfGlory: true, lightningBlade: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    rangedCheck: true, rangedDist: 6,
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  blazeOfGloryHeroUnaffectedWarlord: {
    desc: 'Blaze of Glory targets a non-hero unit, so a hero is unaffected: no Armor→Melee transfer. Hero melee 2, Armor 6 → melee stays 2 vs def 0 → 2.0. (If wrongly applied, melee 2+6 = 8.)',
    version: V_WARLORD,
    a: { unitType:'hero', atk:2, def:6, hitChance:70, hp:10, abilities: { blazeOfGlory: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Black Channels ---
  blackChannelsMeleeBonus: {
    desc: 'Black Channels +2 melee: base 3 atk + BC = 5, 100% hit vs 0 def → E[dmg]=5.0',
    a: { atk:3, toHitMod:70, hp:10, abilities: { blackChannels: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  blackChannelsRangedBonus: {
    desc: 'Black Channels +1 ranged: base 2 rtb + BC = 3, 100% hit vs 0 def → E[dmg]=3.0',
    a: { rtbType:'missile', rtb:2, toHitRtbMod:70, hp:10, abilities: { blackChannels: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  blackChannelsDefBonus: {
    desc: 'Black Channels +1 def: 4 atk 100% hit vs def 0+1=1 (30% block) → E[dmg]=3.7',
    a: { atk:4, toHitMod:70, hp:10 },
    b: { hp:10, abilities: { blackChannels: true } },
    expected: { dmgToA: 0, dmgToB: 3.700 },
  },
  blackChannelsResBonus: {
    desc: 'Black Channels +1 res: Stoning -1 vs res 5+1=6; effectiveRes=5, pFail=0.5; hp=10+1=11 → E[dmg]=0.5×11=5.5; melee blocked',
    a: { atk:1, toHitMod:70, hp:10, abilities: { stoningTouch: -1 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { blackChannels: true } },
    expected: { dmgToA: 0, dmgToB: 5.500 },
  },
  blackChannelsHpBonus: {
    desc: 'Black Channels +1 HP: 1-fig unit hp=1+1=2; 3 atk 100% hit 0 def → damage capped at remHP=2',
    a: { atk:3, toHitMod:70, hp:10 },
    b: { hp:1, abilities: { blackChannels: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  blackChannelsPoisonImmune: {
    desc: 'Black Channels grants Poison Immunity: poison 4 and melee both blocked → 0 damage',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { blackChannels: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  blackChannelsDeathImmune: {
    desc: 'Black Channels grants Death Immunity: Cause Fear does not affect BC unit → 3 atk land (minus BC +1 def at 30% block → E[dmg]=2.7)',
    a: { atk:3, toHitMod:70, hp:10, abilities: { fear: true } },
    b: { res:0, hp:10, abilities: { blackChannels: true } },
    expected: { dmgToA: 0, dmgToB: 2.700 },
  },
  blackChannelsFantasticDeath: {
    desc: 'Black Channels → fantastic_death: triggers opponent Bless (+3 def at 100% block vs death) → 0 damage',
    a: { atk:1, toHitMod:70, hp:10, abilities: { blackChannels: true } },
    b: { def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  blackChannelsThrownBonus: {
    desc: 'Black Channels +1 thrown: atk 1+2=3, thrown 1+1=2, 100% hit vs 0 def → E[dmg]=5.0 (thrown+melee)',
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:1, toHitRtbMod:70, hp:10, abilities: { blackChannels: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
});
