// Numeric presets. The predefined-unit matchups, the fire effects (Immolation, Wall of Fire,
// Warp Reality), Bless and the elemental protections, and the prayers.
definePresets({
  // --- Predefined-unit Tests ---
  predefBarbSwordsVsSpears: {
    desc: 'Barbarian Swordsmen vs Barbarian Spearmen: basic normal-vs-normal melee',
    aUnitName: 'Barbarian Swordsmen',
    bUnitName: 'Barbarian Spearmen',
    expected: { dmgToA: 1.046, dmgToB: 3.760 },
  },
  predefLongbowmenVsOrcSpears: {
    desc: 'Longbowmen vs Orc Spearmen: ranged missile matchup at range 1',
    aUnitName: 'Longbowmen',
    bUnitName: 'Orc Spearmen',
    rangedCheck: true,
    rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.929 },
  },
  predefWarBearsVsDwarvenHalberdiers: {
    desc: 'War Bears vs Dwarven Halberdiers: Nature fantastic vs tough normal infantry',
    aUnitName: 'War Bears',
    bUnitName: 'Dwarven Halberdiers',
    expected: { dmgToA: 3.740, dmgToB: 2.606 },
  },
  predefGreatDrakeVsHydra: {
    desc: 'Great Drake vs Hydra: fantastic vs fantastic, breath and multi-attack',
    aUnitName: 'Great Drake',
    bUnitName: 'Hydra',
    expected: { dmgToA: 3.726, dmgToB: 31.170 },
  },
  predefDeathKnightsVsPaladins: {
    desc: 'Death Knights vs Ultra Elite Paladins: Death fantastic (life steal) vs strong normal unit',
    aUnitName: 'Death Knights',
    bUnitName: 'Paladins',
    b: { level: 'ultra_elite', weapon: 'adamantium' },
    expected: { dmgToA: 7.649, dmgToB: 14.842 },
  },
  predefChaosSpawnVsUnicorns: {
    desc: 'Chaos Spawn vs Unicorns (MoM 1.60): multi-gaze + poison vs resistance-to-all, poison immunity',
    version: V_MOM_CP,
    aUnitName: 'Chaos Spawn',
    bUnitName: 'Unicorns',
    // F45: the Unicorns' Resistance to All never matched its def, so this preset was scored
    // with 0 instead of +2 despite naming the ability. At resistance 9 rather than 7, against
    // the gaze's −4, the destroyed share falls from 68.6% to 31.6% and the surviving figures
    // retaliate. Unticking the Res. to all consumer still reproduces the old 0.260 / 23.129.
    expected: { dmgToA: 0.929, dmgToB: 20.805 },
  },

  // F47: roster-wiring coverage. These assert that the roster's Illusion token reaches the
  // ability, which F46 showed nothing else tested — the mechanic itself already worked, so a
  // custom-stat preset would pass with the token broken. Only dmgToB is asserted: Illusion
  // zeroes the defender's defense, so every landed hit lands in full and the mean is exactly
  // figures x melee x to-hit, independent of the defender's stats. Retaliation is not part of
  // the mechanic and is deliberately left unasserted.
  predefPhantomWarriorsVsPaladins: {
    desc: 'Phantom Warriors vs Paladins (MoM 1.31): roster Illusion zeroes defense → 6 figs x 3 melee x 30% = 5.400 (1.129 if the roster token fails to match)',
    aUnitName: 'Phantom Warriors',
    bUnitName: 'Paladins',
    expected: { dmgToB: 5.400 },
  },
  predefPhantomWarriorsVsGreatDrakeCoM: {
    desc: 'Phantom Warriors vs Great Drake (CoM): roster Illusion zeroes defense 11 → 7 figs x 3 melee x 30% = 6.300 (0.321 if the roster token fails to match)',
    version: V_COM,
    aUnitName: 'Phantom Warriors',
    bUnitName: 'Great Drake',
    expected: { dmgToB: 6.300 },
  },

  // --- Immolation ---
  immolationMelee: {
    desc: 'Immolation melee: 1atk 100% hit + immolation(4) 30% hit vs 1fig 0def 10HP → 1 + 1.2 = 2.2',
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:10 },
    expected: { dmgToB: 2.200 },
  },
  immolationMoMStrength: {
    desc: 'Immolation Strength (MoM 1.31): strength 4 — 1atk 100% + imm(4)@30% vs 0def 20HP → 1 + 1.2 = 2.2',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:20 },
    expected: { dmgToB: 2.200 },
  },
  immolationAreaMultiFig: {
    desc: 'Immolation area vs 4fig 1HP 0def: imm(4)@30% per fig capped at 1HP each + melee 1',
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true } },
    b: { figs:4, def:0, hp:1 },
    expected: { dmgToB: 3.706 },
  },
  immolationNoOverflow: {
    desc: 'Immolation no overflow: vs 2fig 2HP 0def, imm(4)@30% per fig capped at 2HP + melee 1',
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true } },
    b: { figs:2, def:0, hp:2 },
    expected: { dmgToB: 3.095 },
  },
  immolationMagicImmunity: {
    desc: 'Immolation blocked by Magic Immunity: melee 1 only, immolation does 0',
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:10, abilities: { magicImmunity: true } },
    expected: { dmgToB: 1.000 },
  },
  immolationRighteousness: {
    desc: 'Immolation vs Righteousness: def→50, str 4 @30% all blocked → melee 1 only',
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:10, abilities: { righteousness: true } },
    expected: { dmgToB: 1.000 },
  },
  immolationFireImmunity: {
    desc: 'Immolation vs Fire Immunity: def raised to 50, str 4 @ 30% all blocked → melee only',
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:10, abilities: { fireImmunity: true } },
    expected: { dmgToB: 1.000 },
  },
  immolationArmorPiercingIgnored: {
    desc: 'Armor Piercing does NOT halve immolation defense: LS gives imm def 2 (not 1). '
        + 'Melee 1@100% (melee def 0) + imm(4)@30% vs def 2 (LS), 100% block → 1 + 0.0918 = 1.0918',
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true, armorPiercing: true } },
    b: { def:0, toBlkMod:70, hp:20, abilities: { largeShield: true } },
    expected: { dmgToB: 1.0918 },
  },
  immolationBothSides: {
    desc: 'Both have immolation: A(1fig 1atk) + imm@30% vs B(4fig 1atk 0def 2HP) + imm@30%',
    a: { atk:1, toHitMod:70, def:0, hp:10, abilities: { immolation: true } },
    b: { figs:4, atk:1, toHitMod:70, def:0, hp:2, abilities: { immolation: true } },
    expected: { dmgToA: 5.200, dmgToB: 5.418 },
  },
  immolationNotRangedCoM: {
    desc: 'Immolation + Ranged (CoM): does NOT fire with ranged → missile only (5 100% hit, 0 def = 5 dmg)',
    version: V_COM,
    a: { rtbType:'missile', rtb:5, toHitRtbMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToB: 5.000 },
  },
  immolationRangedMoM: {
    desc: 'Immolation + Ranged (MoM 1.31): fires with ranged → missile 5@100% + imm(4)@30% vs 0def = 5 + 1.2 = 6.2',
    version: V_MOM_131,
    a: { rtbType:'missile', rtb:5, toHitRtbMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToB: 6.200 },
  },
  immolationWithThrown: {
    desc: 'Immolation + Thrown (MoM 1.31): fires in thrown+melee → thrown 3@100% + imm@30% + melee 1@100% + imm@30% = 6.4',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:3, toHitRtbMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:20 },
    expected: { dmgToB: 6.400 },
  },
  immolationCoMStrength10: {
    desc: 'Immolation Strength (CoM): strength 10 — 1atk 100% + imm(10)@30% vs 0def 20HP → 1 + 3 = 4',
    version: V_COM,
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:20 },
    expected: { dmgToB: 4.000 },
  },
  elemArmorImmolationCoM: {
    desc: 'CoM 1 Elemental Armor covers Immolation: melee 1 is blocked by base def 1; immolation str 10 is fully blocked by def 1+12 at 100% To Block → 0',
    version: V_COM,
    a: { atk:1, toHitMod:70, hp:10, abilities: { immolation: true } },
    b: { def:1, toBlkMod:70, hp:20, abilities: { elemArmor: 'elementalArmor' } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  immolationAtkZeroNoFire: {
    desc: 'Immolation does not fire when melee atk=0 (touchAttackFires check)',
    a: { atk:0, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:10 },
    expected: { dmgToB: 0 },
  },
  immolationNotRangedPatched: {
    desc: 'Immolation + Ranged (MoM CP 1.60): fix — does NOT fire with ranged → missile only (5@100%, 0def = 5)',
    version: V_MOM_CP,
    a: { rtbType:'missile', rtb:5, toHitRtbMod:70, hp:10, abilities: { immolation: true } },
    b: { def:0, hp:20 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToB: 5.000 },
  },


  // --- Wall of Fire ---
  wallOfFireBasic: {
    desc: 'Wall of Fire basic (MoM str 5): 1 atk 100% hit vs 0 def — melee 1, WoF 5@30% vs 0def → 1.5 dmg to A',
    a: { atk:1, toHitMod:70, def:0, hp:10 },
    b: { atk:0, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 1.500, dmgToB: 1.000 },
  },
  wallOfFireMultiFig: {
    desc: 'Wall of Fire area: 4 figs 1hp — each fig binomial(5,0.3) capped at 1hp → 4×(1-0.7^5) = 3.3277',
    a: { figs:4, atk:1, toHitMod:70, def:0, hp:1 },
    b: { atk:0, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 3.3277, dmgToB: 0.6723 },
  },
  wallOfFireMagicImmunity: {
    desc: 'Wall of Fire blocked by Magic Immunity: melee 1 to B, WoF does 0 to A',
    a: { atk:1, toHitMod:70, def:0, hp:10, abilities: { magicImmunity: true } },
    b: { atk:0, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  wallOfFireRighteousness: {
    desc: 'Wall of Fire vs Righteousness: def→50, str 5 @30% all blocked → 0 to A, melee 1 to B',
    a: { atk:1, toHitMod:70, def:0, hp:10, abilities: { righteousness: true } },
    b: { atk:0, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  wallOfFireFireImmunity: {
    desc: 'Wall of Fire vs Fire Immunity: def raised to 50, str 5 @ 30% all blocked → 0 to A',
    a: { atk:1, toHitMod:70, def:0, hp:10, abilities: { fireImmunity: true } },
    b: { atk:0, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  wallOfFireNotRanged: {
    desc: 'Wall of Fire does NOT fire during ranged attack (attacker does not pass through)',
    a: { rtbType:'missile', rtb:1, toHitRtbMod:70, def:0, hp:10 },
    b: { atk:0, def:0, hp:10 },
    rangedCheck: true, rangedDist: 1,
    wallOfFire: true,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  wallOfFireCoM2Strength: {
    desc: 'Wall of Fire CoM2 strength 10: str 10 @ 30% vs 0 def → mean 3.0 dmg to A',
    version: V_COM2,
    a: { atk:1, toHitMod:70, def:0, hp:20 },
    b: { atk:0, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 3.000, dmgToB: 1.000 },
  },
  wallOfFireCoMStrength: {
    desc: 'Wall of Fire CoM 6.08 strength 10: str 10 @ 30% vs 0 def → mean 3.0 dmg to A',
    version: V_COM,
    a: { atk:1, toHitMod:70, def:0, hp:20 },
    b: { atk:0, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 3.000, dmgToB: 1.000 },
  },
  resistElementsWallOfFireCoM: {
    desc: 'CoM 1 Resist Elements covers Wall of Fire: str 10 is fully blocked by def 6+4 at 100% To Block; melee 1 is blocked by defender def 1 → 0',
    version: V_COM,
    a: { atk:1, toHitMod:70, def:6, toBlkMod:70, hp:20, abilities: { elemArmor: 'resistElements' } },
    b: { atk:0, def:1, toBlkMod:70, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  wallOfFireWarlordStrength: {
    desc: 'Wall of Fire Warlord: single figure str 12 @ 60% vs 0 def → mean 7.2 dmg to A',
    version: V_WARLORD,
    a: { atk:1, toHitMod:70, def:0, hp:20 },
    b: { atk:0, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 7.200, dmgToB: 1.000 },
  },
  wallOfFireWarlordSingleFigure: {
    desc: 'Wall of Fire Warlord strikes ONE figure: 4 figs hp20 — str 12 @ 60% on a single fig → 7.2 to A (not 4×). Melee 4×1 to B.',
    version: V_WARLORD,
    a: { figs:4, atk:1, toHitMod:70, def:0, hp:20 },
    b: { atk:0, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 7.200, dmgToB: 4.000 },
  },
  wallOfFireWarlordDefenderMetalFires: {
    desc: 'Wall of Fire garrison boost grants defender +1 non-magic attack (Metal Fires): B melee counter 5→6 vs 0 def; WoF fire 7.2 + counter 6 = 13.2 to A',
    version: V_WARLORD,
    a: { atk:1, toHitMod:70, def:0, hp:100 },
    b: { atk:5, toHitMod:70, def:0, hp:10, abilities: { wallOfFireBoost: true } },
    wallOfFire: true,
    expected: { dmgToA: 13.200, dmgToB: 1.000 },
  },
  wallOfFireWarlordDefenderMagicWeapon: {
    desc: 'Wall of Fire garrison boost grants defender magic weapons (Metal Fires): B counter (atk 5+1) bypasses A Weapon Immunity (def 0+10 → 0). WoF fire 7.2 + counter 6 = 13.2 to A (0 without bypass)',
    version: V_WARLORD,
    a: { atk:1, toHitMod:70, def:0, toBlkMod:70, hp:100, abilities: { weaponImmunity: true } },
    b: { atk:5, toHitMod:70, def:0, hp:10, abilities: { wallOfFireBoost: true } },
    wallOfFire: true,
    expected: { dmgToA: 13.200, dmgToB: 1.000 },
  },
  wallOfFireWarlordBoostOnAttacker: {
    desc: 'Garrison boost is per-unit and side-independent: boost on attacker A (no fire line). A melee 5→6 vs B def 0 → 6.0 to B (5.0 without the boost)',
    version: V_WARLORD,
    a: { atk:5, toHitMod:70, def:0, hp:10, abilities: { wallOfFireBoost: true } },
    b: { atk:0, toBlkMod:70, def:0, hp:20 },
    expected: { dmgToA: 0.000, dmgToB: 6.000 },
  },
  wallOfFireWarlordBoostBoulder: {
    desc: 'Garrison boost now covers boulder physical ranged: A boulder 5→6 @100% vs B def 0 → 6.0 to B (5.0 without boulder coverage)',
    version: V_WARLORD,
    rangedCheck: true, rangedDist: 1,
    a: { rtbType:'boulder', rtb:5, toHitRtbMod:70, def:0, hp:10, abilities: { wallOfFireBoost: true } },
    b: { atk:0, toBlkMod:70, def:0, hp:20 },
    expected: { dmgToA: 0.000, dmgToB: 6.000 },
  },
  wallOfFireWarlordFireLineNoBoost: {
    desc: 'Split: fire-line global alone does NOT grant the garrison boost. B has no boost → counter stays 5; WoF fire 7.2 + counter 5 = 12.2 to A (13.2 if the fire line still boosted)',
    version: V_WARLORD,
    a: { atk:1, toHitMod:70, def:0, hp:100 },
    b: { atk:5, toHitMod:70, def:0, hp:10 },
    wallOfFire: true,
    expected: { dmgToA: 12.200, dmgToB: 1.000 },
  },
  // --- Magic Immunity vs Breath (version difference) ---
  magicImmunityFireBreathMoM: {
    desc: 'Magic Immunity vs Fire Breath (MoM): MI sets def to 50 — fire breath 4 blocked; melee atk 1 vs def 0 = 1 dmg',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, rtbType:'fire', rtb:4, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { magicImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  magicImmunityFireBreathCoM: {
    desc: 'Magic Immunity vs Fire Breath (CoM): MI no longer blocks breath (CoM v2.3) — fire breath 4 + melee 1 = 5 dmg',
    version: V_COM,
    a: { atk:1, toHitMod:70, rtbType:'fire', rtb:4, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { magicImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },

  wallOfFireAfterThrown: {
    desc: 'WoF sequence: thrown fires at full A count (4×1=4), then WoF kills ~3.33 A figs, melee uses survivors (~0.67) → 4.672',
    a: { figs:4, atk:1, toHitMod:70, rtbType:'thrown', rtb:1, toHitRtbMod:70, def:0, hp:1 },
    b: { atk:0, def:0, hp:20 },
    wallOfFire: true,
    expected: { dmgToA: 3.328, dmgToB: 4.672 },
  },
  wallOfFireAfterGazeCounter: {
    desc: 'WoF sequence: B gaze 3 overflow kills 1 of 2 A figs (2hp each), WoF targets 1 survivor (1hp) → 3.832 to A, 0.168 to B',
    a: { figs:2, atk:1, toHitMod:70, def:0, hp:2, abilities: { stoningImmunity: true } },
    b: { rtbType:'gaze_stoning', rtb:3, atk:0, def:0, hp:20, toHitRtbMod:70, abilities: {  } },
    wallOfFire: true,
    expected: { dmgToA: 3.832, dmgToB: 0.168 },
  },
  wallOfFireAfterThrownAndGaze: {
    desc: 'WoF sequence: thrown (2×1=2 to B), B gaze overflow (3 kills 1 A fig), WoF on 1 survivor, melee → 3.832 to A, 2.168 to B',
    a: { figs:2, atk:1, toHitMod:70, rtbType:'thrown', rtb:1, toHitRtbMod:70, def:0, hp:2, abilities: { stoningImmunity: true } },
    b: { rtbType:'gaze_stoning', rtb:3, atk:0, def:0, hp:20, toHitRtbMod:70, abilities: {  } },
    wallOfFire: true,
    expected: { dmgToA: 3.832, dmgToB: 2.168 },
  },
  wallOfFireBilateralGaze: {
    desc: 'WoF with bilateral gaze: A gaze (2 to B) → B gaze (2 to A) → WoF (1.5 to A) → melee 1 + counter 1',
    a: { rtbType:'gaze_stoning', rtb:2, atk:1, toHitMod:70, def:0, hp:10, toHitRtbMod:70, abilities: { stoningImmunity: true } },
    b: { rtbType:'gaze_stoning', rtb:2, atk:1, toHitMod:70, def:0, hp:10, toHitRtbMod:70, abilities: { stoningImmunity: true } },
    wallOfFire: true,
    expected: { dmgToA: 4.500, dmgToB: 3.000 },
  },

  // --- Warp Reality ---
  warpRealityBasic: {
    desc: 'Warp Reality: non-chaos A gets -20% to hit (30%→10%), 1 atk vs 0 def → 0.1 dmg',
    a: { atk:1, hp:10 },
    b: { hp:10 },
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.100 },
  },
  warpRealityChaosExempt: {
    desc: 'Warp Reality: Chaos Fantastic A is exempt (30% to hit unchanged), 1 atk vs 0 def → 0.3 dmg',
    a: { atk:1, hp:10, unitType:'fantastic_chaos' },
    b: { hp:10 },
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.300 },
  },
  warpRealityChaosChannelsExempt: {
    desc: 'Warp Reality: Chaos Channels unit is exempt (counts as Chaos), 1 atk vs 0 def → 0.3 dmg',
    a: { atk:1, hp:10, abilities: { ccDefense: true } },
    b: { hp:10 },
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.300 },
  },
  warpRealityMagicImmunityNotExempt: {
    desc: 'Warp Reality bypasses Magic Immunity: non-chaos A with MagicImm still gets -20% to hit → 0.1 dmg',
    a: { atk:1, hp:10, abilities: { magicImmunity: true } },
    b: { hp:10 },
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.100 },
  },
  warpRealityBothSides: {
    desc: 'Warp Reality penalizes both sides: A 1 atk 10%, B 1 atk 10% → 0.1 dmg each',
    a: { atk:1, hp:10 },
    b: { atk:1, hp:10 },
    warpReality: true,
    expected: { dmgToA: 0.100, dmgToB: 0.100 },
  },
  warpRealityFloorAt10: {
    desc: 'Warp Reality floors at 10%: A starts at 10% (toHitMod -20), WR -20% → still 10% → 0.1 dmg',
    a: { atk:1, toHitMod:-20, hp:10 },
    b: { hp:10 },
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.100 },
  },
  warpRealityRanged: {
    desc: 'Warp Reality vs ranged: missile 1 atk, 30%→10% to hit vs 0 def → 0.1 dmg',
    a: { rtbType:'missile', rtb:1, hp:10 },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.100 },
  },

  hurricaneRanged: {
    desc: 'Hurricane: missile 1 atk gets -20% to hit (30%→10%) vs 0 def → 0.1 dmg',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:1, hp:10 },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    hurricane: true,
    expected: { dmgToA: 0, dmgToB: 0.100 },
  },
  hurricaneBreath: {
    desc: 'Hurricane: fire breath 1 atk gets -30% to hit (30%→10%, floored) vs 0 def → 0.1 dmg. Without Hurricane breath would hit at 30% → 0.3, so the breath-specific penalty is exercised.',
    version: V_WARLORD,
    a: { atk:1, rtbType:'fire', rtb:1, hp:10 },
    b: { hp:10 },
    rangedCheck: false,
    hurricane: true,
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  hurricaneMeleeUnaffected: {
    desc: 'Hurricane does not touch melee: 1 atk stays at 30% to hit vs 0 def → 0.3 dmg',
    version: V_WARLORD,
    a: { atk:1, hp:10 },
    b: { hp:10 },
    hurricane: true,
    expected: { dmgToA: 0, dmgToB: 0.300 },
  },
  hurricanePenaltySizeRanged: {
    desc: 'Hurricane’s ranged penalty is 20 points, not 30: missile 2 at 100% to hit drops to 80% → 1.6 dmg. Paired with hurricanePenaltySizeBreath, which starts from the same 100% and lands on 70%. The 30%-base presets above cannot tell the two penalties apart because both floor at 10%. Without Hurricane this is 2.0.',
    version: V_WARLORD,
    a: { rtbType:'missile', rtb:2, toHitRtbMod:70, hp:10 },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    hurricane: true,
    expected: { dmgToA: 0, dmgToB: 1.600 },
  },
  hurricanePenaltySizeBreath: {
    desc: 'Hurricane’s breath penalty is 30 points: fire breath 2 at 100% to hit drops to 70% → 1.4, plus 1 melee at an untouched 30% → 1.7 dmg. Paired with hurricanePenaltySizeRanged: same base, 10 points further down because Fire and Lightning Breath read the separate breath modifier. Without Hurricane this is 2.3.',
    version: V_WARLORD,
    a: { atk:1, rtbType:'fire', rtb:2, toHitRtbMod:70, hp:10 },
    b: { hp:10 },
    rangedCheck: false,
    hurricane: true,
    expected: { dmgToA: 0, dmgToB: 1.700 },
  },

  destinyOverridesCCFireBreathCoM2: {
    desc: 'Type precedence (CoM2): Chaos Channels Fire Breath is applied before Destiny, so the final type is Life and Warp Reality penalizes both channels. Destiny doubles more than melee and HP — it also doubles fire breath ($0059A51F), lightning breath ($0059A559) and thrown ($0059A593) — so the Chaos Channels breath 4 doubles to 8 and its Supernatural minimum rides alongside the doubled melee → 0.387 dmg. Dropping Destiny gives 0.300; reversing the type precedence would give 1.403.',
    version: V_COM2,
    a: { atk:1, hp:10, abilities: { destiny: true, ccFireBreath: true } },
    b: { hp:10, abilities: { fireImmunity: true } },
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.387 },
  },
  ccDefenseOverridesDestinyCoM2: {
    desc: 'Type precedence (CoM2): Chaos Channels Defense is applied after Destiny, so final type is Chaos. Destiny still doubles melee to 2, and Warp Reality is ignored → 0.6 dmg',
    version: V_COM2,
    a: { atk:1, hp:10, abilities: { destiny: true, ccDefense: true } },
    b: { hp:10 },
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.600 },
  },
  ccFlightOverridesDestinyCoM2: {
    desc: 'Type precedence (CoM2): Chaos Channels Flight is applied after Destiny, so final type is Chaos. Destiny still doubles melee to 2, and Warp Reality is ignored → 0.6 dmg',
    version: V_COM2,
    a: { atk:1, hp:10, abilities: { destiny: true, ccFlight: true } },
    b: { hp:10 },
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.600 },
  },
  bloodLustOverridesCCDefenseCoM2: {
    desc: 'Type precedence (CoM2): Chaos Channels Armor/Defense is applied before Blood Lust, so final type is Death; Blood Lust still doubles melee against the normal target, and Warp Reality penalizes that doubled attack → 0.2 dmg',
    version: V_COM2,
    a: { atk:1, hp:10, abilities: { bloodLust: true, ccDefense: true } },
    b: { hp:10 },
    warpReality: true,
    expected: { dmgToA: 0, dmgToB: 0.200 },
  },
  raiseDeadOverridesUndeadCoM2: {
    desc: 'Type precedence (CoM2): Raise Dead makes the unit unaligned fantastic, overriding Undead, so Exorcise −4 still reaches it but loses the created-undead −3: res 7 stays at effective 3, pFail=0.7, E[banish]=7 plus 1 physical → 8.0 (11.0 without Raise Dead)',
    version: V_COM2,
    a: { atk:1, toHitMod:70, hp:10, abilities: { exorcise: -4 } },
    b: { figs:2, def:0, res:7, hp:10, abilities: { undead: true, raiseDead: true } },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  raiseDeadDoesNotOverrideUndeadMoM: {
    desc: 'Type precedence (MoM): Raise Dead does not make the unit unaligned fantastic, so Undead still gives Dispel Evil the -9 penalty → 11.0 damage',
    version: V_MOM_CP,
    a: { atk:1, toHitMod:70, hp:10, abilities: { dispelEvil: true } },
    b: { figs:2, def:0, res:7, hp:10, abilities: { undead: true, raiseDead: true } },
    expected: { dmgToA: 0, dmgToB: 11.000 },
  },
  mysticSurgeOverridesUndeadCoM2: {
    desc: 'Type precedence (CoM2): Mystic Surge makes the unit unaligned fantastic, overriding Undead, so Exorcise −4 loses the created-undead −3; its own −2 resistance leaves res 7 at effective 1, pFail=0.9, and its +2 defense cuts the physical hit to 0.49 → 9.49 (11.0 without Mystic Surge)',
    version: V_COM2,
    a: { atk:1, toHitMod:70, hp:10, abilities: { exorcise: -4 } },
    b: { figs:2, def:0, res:7, hp:10, abilities: { undead: true, mysticSurge: true } },
    expected: { dmgToA: 0, dmgToB: 9.490 },
  },

  // --- Bless ---
  blessMeleeFromDeath: {
    desc: 'Bless +3 def vs Death Fantastic melee: 5 atk 100% hit, def 0+3=3, 100% block → 5−3=2 dmg',
    a: { atk:5, toHitMod:70, hp:10, unitType:'fantastic_death' },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  blessMeleeFromChaos: {
    desc: 'Bless +3 def vs Chaos Fantastic melee: 5 atk 100% hit, def 0+3=3, 100% block → 5−3=2 dmg',
    a: { atk:5, toHitMod:70, hp:10, unitType:'fantastic_chaos' },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  blessMeleeFromDeathCoM2: {
    desc: 'CoM2 Bless does NOT apply vs Death Fantastic melee: 5 atk 100% hit, def 0, 100% block → 5 dmg',
    version: V_COM2,
    a: { atk:5, toHitMod:70, hp:10, unitType:'fantastic_death' },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  blessMeleeFromChaosCoM2: {
    desc: 'CoM2 Bless does NOT apply vs Chaos Fantastic melee: 5 atk 100% hit, def 0, 100% block → 5 dmg',
    version: V_COM2,
    a: { atk:5, toHitMod:70, hp:10, unitType:'fantastic_chaos' },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  blessMeleeFromNormal: {
    desc: 'Bless does NOT apply vs Normal unit melee: 5 atk 100% hit, def 0, 100% block → 5 dmg',
    a: { atk:5, toHitMod:70, hp:10 },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  blessFireBreathAlwaysChaos: {
    desc: 'Bless +3 def vs Fire Breath (always Chaos) even from Normal unit: breath 5−3=2, melee 1−0=1 (bless n/a) → 3 dmg',
    a: { atk:1, rtbType:'fire', rtb:5, toHitMod:70, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  blessLightningBreathAlwaysChaos: {
    desc: 'Bless +3 def vs Lightning Breath (always Chaos) — intrinsic AP halves bless: breath def floor((0+3)/2)=1, 5−1=4, melee 1−0=1 → 5 dmg',
    a: { atk:1, rtbType:'lightning', rtb:5, toHitMod:70, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  blessMagicChaosRanged: {
    desc: 'Bless +3 def vs Chaos Magic ranged (always Chaos): 5 hits vs def 0+3=3 → 2 dmg',
    a: { rtbType:'magic_c', rtb:5, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  blessMissileFromDeathNoBonus: {
    desc: 'Bless does NOT apply vs Missile from a Death Fantastic: a missile is realm-less (ranged_type 20−29), so it never inherits the attacker\'s Death realm. 5 hits vs def 0 → 5 dmg (would be 2 if the realm carried over)',
    a: { rtbType:'missile', rtb:5, toHitRtbMod:70, hp:10, unitType:'fantastic_death' },
    b: { def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  blessThrownFromChaosNoBonus: {
    desc: 'Bless does NOT apply vs plain Thrown from a Chaos Fantastic: Thrown is realm-less (ranged_type 100), unlike the attacker\'s melee. Thrown 5 − 0 = 5; melee 1 vs def 0+3=3 → 0. Total 5 dmg (would be 2 if the realm carried over)',
    a: { atk:1, rtbType:'thrown', rtb:5, toHitMod:70, toHitRtbMod:70, hp:10, unitType:'fantastic_chaos' },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  blessArmorPiercingHalves: {
    desc: 'Bless + Armor Piercing: pre-AP def 3+3=6, AP halves to 3, 7 atk → 7−3=4 dmg (without bless would be 6)',
    a: { atk:7, toHitMod:70, hp:10, unitType:'fantastic_chaos', abilities: { armorPiercing: true } },
    b: { atk:0, def:3, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  blessCauseFear: {
    desc: 'Bless +3 res vs Cause Fear (v1.31 self-fear bug fires even for immune A): B res 5+3=8, pFear=0.2; bug: E[A self-feared]=0.2 → E[A figs]=3.8 → dmgToB=11.4; E[B unfeared]=0.8 → dmgToA=2.4',
    a: { figs:4, atk:3, toHitMod:70, hp:10, abilities: { fear: true, deathImmunity: true } },
    b: { atk:3, toHitMod:70, hp:100, def:0, res:5, abilities: { bless: true } },
    expected: { dmgToA: 2.400, dmgToB: 11.400 },
  },
  blessCauseFearImmune: {
    desc: 'Bless +3 res → effective res 10 immune to Fear (no self-fear bug: bPFear=0): B res 7+3=10, not feared, full counter 1×3=3',
    a: { figs:4, atk:3, toHitMod:70, hp:10, abilities: { fear: true, deathImmunity: true } },
    b: { atk:3, toHitMod:70, hp:100, def:0, res:7, abilities: { bless: true } },
    expected: { dmgToA: 3.000, dmgToB: 12.000 },
  },
  blessLifeSteal: {
    desc: 'Bless +3 res vs Life Steal −3: effRes=5+3−3=5, E[dmg]=sum(1..5)/10=1.5',
    a: { atk:1, toHitMod:70, hp:10, abilities: { lifeSteal: -3 } },
    b: { atk:0, def:1, toBlkMod:70, res:5, hp:20, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 1.500 },
  },
  blessDeathGaze: {
    desc: 'Bless vs Death Gaze −3 (hidden ranged 1 so gaze fires in v1.31): +3 res → effRes=5+3−3=5, fail=0.5 → 5.0 death. Bless also grants +3 def against the gaze itself, since a Death Gaze is Death-realm regardless of the attacker\'s unit type, so the hidden 1 adds 0.5×0.3×0.7³=0.051',
    a: { rtbType:'gaze_death', rtb:1, hp:10, abilities: { deathGaze: -3 } },
    b: { atk:0, def:0, res:5, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 5.051 },
  },
  blessBreathBonusMoM: {
    desc: 'MoM Bless +3 def vs Chaos magic ranged: 7 hits − 3 bless = 4 dmg',
    version: V_MOM_131,
    a: { rtbType:'magic_c', rtb:7, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  blessBreathBonusCoM: {
    desc: 'CoM 1 Bless gives NO def bonus vs Chaos magical ranged: its defense half needs ranged_type > 39, which excludes every conventional ranged type. 7 hits − 0 = 7 dmg (4 in MoM)',
    version: V_COM,
    a: { rtbType:'magic_c', rtb:7, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  blessBreathBonusCoM2: {
    desc: 'CoM2 Bless gives NO def bonus vs a Chaos magical ranged unit attack: its defense half is gated on a positive spell ID and ApplyAttack passes 0 for every unit channel. 7 hits − 0 = 7 dmg (MoM blocks 3, and a +5 here would leave 2)',
    version: V_COM2,
    a: { rtbType:'magic_c', rtb:7, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  blessResistBonusMoM: {
    desc: 'MoM Bless vs Death Gaze −3: +3 res → effRes=5+3−3=5, pFail=0.5 → 5.0 death; +3 def vs the Death-realm gaze → physical 0.5×0.3×0.7³=0.051 = 5.051',
    version: V_MOM_131,
    a: { rtbType:'gaze_death', rtb:1, hp:10, abilities: { deathGaze: -3 } },
    b: { atk:0, def:0, res:5, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 5.051 },
  },
  blessResistBonusCoM2: {
    desc: 'CoM2 Bless +5 res vs Death Gaze −3: effRes=5+5−3=7, pFail=0.3 → 3.0. No hidden gaze strength: CoM2 stores stoning/death/doom gaze as three independent stats with no attack-strength slot, and the gaze fires without one.',
    version: V_COM2,
    a: { hp:10, abilities: { deathGaze: -3 } },
    b: { atk:0, def:0, res:5, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  blessBreathBonusWarlord: {
    desc: 'Warlord Bless gives NO def bonus vs a Chaos magical ranged unit attack: the same positive-spell-ID gate excludes every ApplyAttack unit channel. 7 hits − 0 = 7 dmg (a +7 here would leave 0)',
    version: V_WARLORD,
    a: { rtbType:'magic_c', rtb:7, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  blessFireBreathDefMoM: {
    desc: 'MoM Bless +3 def vs Fire Breath from a Normal unit: breath 7 − 3 = 4, melee 1 − 0 = 1 (bless n/a) → 5 dmg',
    version: V_MOM_131,
    a: { atk:1, rtbType:'fire', rtb:7, toHitMod:70, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  blessFireBreathDefCoM: {
    desc: 'CoM 1 Bless +5 def vs Fire Breath: breath is ranged_type 101, the one attack class its defense half still covers. Breath 7 − 5 = 2, melee 1 − 0 = 1 → 3 dmg (5 in MoM)',
    version: V_COM,
    a: { atk:1, rtbType:'fire', rtb:7, toHitMod:70, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:0, toBlkMod:70, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  blessResistBonusWarlord: {
    desc: 'Warlord Bless +4 res vs Death Gaze −3: effRes=5+4−3=6, pFail=0.4 → 4.0. Bless\'s +7 Defense half does not touch gaze (HELP.TXT: fire/lightning and Chaos/Death damage spells only), and Warlord has no hidden gaze strength stat.',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: -3 } },
    b: { atk:0, def:0, res:5, hp:10, abilities: { bless: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Elemental Armor / Resist Elements ---
  elemArmorMagicCRanged: {
    desc: 'Elemental Armor +10 def vs Chaos magic ranged: 10 hits vs def 0+10=10, 100% block → 0 dmg',
    a: { rtbType:'magic_c', rtb:10, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'elementalArmor' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  elemArmorMagicNRanged: {
    desc: 'Elemental Armor +10 def vs Nature magic ranged: 10 hits vs def 0+10=10, 100% block → 0 dmg',
    a: { rtbType:'magic_n', rtb:10, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'elementalArmor' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  elemArmorNotVsMagicS: {
    desc: 'Elemental Armor does NOT apply to Sorcery ranged: 5 hits vs def 0, 0 blocks → 5 dmg',
    a: { rtbType:'magic_s', rtb:5, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'elementalArmor' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  elemArmorNotMelee: {
    desc: 'Elemental Armor does NOT apply to melee: 10 hits vs def 0, no bonus → 10 dmg',
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'elementalArmor' } },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  elemArmorFireBreath: {
    desc: 'Elemental Armor +10 def vs Fire Breath: 5 breath hits vs 10 def 100% block = 0; melee 1 hit vs 0 def = 1 total',
    a: { atk:1, rtbType:'fire', rtb:5, toHitMod:70, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'elementalArmor' } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  elemArmorLightningBreath: {
    desc: 'Elemental Armor +10 def vs Lightning Breath (intrinsic AP halves): floor((0+10)/2)=5 def, 10 hits − 5 blocks = 5 breath; melee 1 = 6 total',
    a: { atk:1, rtbType:'lightning', rtb:10, toHitMod:70, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:20, abilities: { elemArmor: 'elementalArmor' } },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  resistElementsMagicC: {
    desc: 'Resist Elements +3 def vs Chaos magic ranged: 5 hits vs def 0+3=3, 100% block → 2 dmg',
    a: { rtbType:'magic_c', rtb:5, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'resistElements' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  elemArmorNotCumulative: {
    desc: 'Elemental Armor supersedes Resist Elements: 15 hits vs def max(10,3)=10 → 5 dmg (not 2 if they stacked to 13)',
    a: { rtbType:'magic_c', rtb:15, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:20, abilities: { elemArmor: 'elementalArmor' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  resistElementsNotVsMagicSMoM: {
    desc: 'MoM Resist Elements does NOT apply to Sorcery ranged: 5 hits vs def 0 → 5 dmg',
    a: { rtbType:'magic_s', rtb:5, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'resistElements' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  resistElementsVsMagicSCoM2: {
    desc: 'CoM2 Resist Elements +4 def vs ALL magic ranged incl. Sorcery: 5 hits vs def 4 → 1 dmg',
    version: V_COM2,
    a: { rtbType:'magic_s', rtb:5, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'resistElements' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  resistElementsFireBreathMoM: {
    desc: 'MoM Resist Elements +3 def vs Fire Breath: 5 breath vs def 3 → 2 dmg + 1 melee = 3 total',
    a: { atk:1, rtbType:'fire', rtb:5, toHitMod:70, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'resistElements' } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  resistElementsFireBreathCoM2: {
    desc: 'CoM2 Resist Elements +4 def vs Fire Breath: 5 breath vs def 4 → 1 dmg + 1 melee = 2 total',
    version: V_COM2,
    a: { atk:1, rtbType:'fire', rtb:5, toHitMod:70, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'resistElements' } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  resistElementsMagicCCoM2: {
    desc: 'CoM2 Resist Elements +4 def vs Chaos magic ranged: 5 hits vs def 4 → 1 dmg (not 2 in MoM)',
    version: V_COM2,
    a: { rtbType:'magic_c', rtb:5, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'resistElements' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  elemArmorVsMagicSCoM2: {
    desc: 'CoM2 Elemental Armor +12 def vs ALL magic ranged incl. Sorcery: 5 hits vs def 12 → 0 dmg',
    version: V_COM2,
    a: { rtbType:'magic_s', rtb:5, toHitRtbMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { elemArmor: 'elementalArmor' } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  // --- Eldritch Weapon ---
  eldritchWeaponMelee: {
    desc: 'Eldritch Weapon melee: toBlock 30% → 20% (1 shield, 20% block) → E[dmg]=0.800',
    a: { atk:1, toHitMod:70, hp:10, abilities: { eldritchWeapon: true } },
    b: { def:1, hp:10 },
    version: V_MOM_131,
    expected: { dmgToA: 0, dmgToB: 0.800 },
  },
  eldritchWeaponRangedMissile: {
    desc: 'Eldritch Weapon missile ranged: toBlock 30% → 20% (1 shield, 20% block) → E[dmg]=0.800',
    a: { rtbType:'missile', rtb:1, toHitRtbMod:70, hp:10, abilities: { eldritchWeapon: true } },
    b: { def:1, hp:10 },
    version: V_MOM_131,
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.800 },
  },
  eldritchWeaponWeaponUpgrade: {
    desc: 'Eldritch Weapon upgrades normal→magic: bypasses WI (def stays 5 not 10) + toBlock 20% → E[dmg]=4.000',
    a: { atk:5, toHitMod:70, hp:10, abilities: { eldritchWeapon: true } },
    b: { def:5, hp:10, abilities: { weaponImmunity: true } },
    version: V_MOM_131,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  eldritchWeaponRangedKeepsWI: {
    // Eldritch's magic-weapon upgrade is melee-only (MoM Eldritch Weapon page), so a bow
    // attack does NOT bypass Weapon Immunity: defense is raised 5→10. The -10% To Block
    // still applies (30%→20%). 5 hits vs 10 shields @20% block → E[dmg]≈3.007.
    // If Eldritch wrongly upgraded the ranged weapon (the old bug), WI would be bypassed
    // (def stays 5) and E[dmg] would be 4.000 instead.
    desc: 'Eldritch Weapon ranged does NOT bypass WI: def 5→10 (WI applies) + toBlock 20% → E[dmg]≈3.007',
    a: { rtbType:'missile', rtb:5, toHitRtbMod:70, hp:10, abilities: { eldritchWeapon: true } },
    b: { def:5, hp:10, abilities: { weaponImmunity: true } },
    version: V_MOM_131,
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.007 },
  },

  // --- Giant Strength ---
  giantStrengthMelee: {
    desc: 'Giant Strength +1 melee: base 1 atk + GS → 2 atk, 100% hit vs 0 def → E[dmg]=2.0',
    a: { atk:1, toHitMod:70, hp:10, abilities: { giantStrength: true } },
    b: { hp:10 },
    version: V_MOM_131,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  giantStrengthThrown: {
    desc: 'Giant Strength +1 thrown: atk 1+1=2, thrown 1+1=2, 100% hit vs 0 def → E[dmg]=4.0 (thrown+melee)',
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:1, toHitRtbMod:70, hp:10, abilities: { giantStrength: true } },
    b: { hp:10 },
    version: V_MOM_131,
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  giantStrengthNotMissile: {
    desc: 'Giant Strength does NOT boost missile ranged: base 1 + GS → still 1 rtb → E[dmg]=1.0',
    a: { rtbType:'missile', rtb:1, toHitRtbMod:70, hp:10, abilities: { giantStrength: true } },
    b: { hp:10 },
    version: V_MOM_131,
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },

  // --- Prayer ---
  prayerToHit: {
    desc: 'Prayer To Hit: 1 atk, base 30% + Prayer +10% = 40% hit vs 0 def → 0.4',
    a: { atk:1, hp:10, abilities: { prayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  prayerToHitRanged: {
    desc: 'Prayer To Hit Ranged: missile 1 atk, base 30% + Prayer +10% = 40% hit vs 0 def → 0.4',
    a: { rtbType:'missile', rtb:1, hp:10, abilities: { prayer: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  prayerToBlock: {
    desc: 'Prayer To Block: 1 atk 90% hit (v1.31 Prayer penalty) vs def 1, 40% block → 0.9×0.6 = 0.54',
    a: { atk:1, toHitMod:70, hp:10 },
    b: { def:1, hp:10, abilities: { prayer: true } },
    expected: { dmgToA: 0, dmgToB: 0.540 },
  },
  prayerResistance: {
    desc: 'Prayer Resistance: Poison 4 vs base res 5 + Prayer +1 = res 6, pFail 40%, E[dmg] = 1.6',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { prayer: true } },
    expected: { dmgToA: 0, dmgToB: 1.600 },
  },
  prayerEnemyMeleePenalty131: {
    desc: 'Prayer Enemy Melee Penalty (MoM 1.31): bug — B Prayer, A melee 30% → 20%. 1 atk vs 0 def → 0.2',
    version: V_MOM_131,
    a: { atk:1, hp:10 },
    b: { hp:10, abilities: { prayer: true } },
    expected: { dmgToA: 0, dmgToB: 0.200 },
  },
  prayerEnemyPenaltyNotRanged131: {
    desc: 'Prayer Enemy Ranged Penalty (MoM 1.31): enemy penalty does NOT apply to ranged. Missile 1 atk 30% → still 0.3',
    version: V_MOM_131,
    a: { rtbType:'missile', rtb:1, hp:10 },
    b: { hp:10, abilities: { prayer: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.300 },
  },
  prayerEnemyPenaltyRemovedPatched: {
    desc: 'Prayer Enemy Melee Penalty (MoM CP 1.60): fix — enemy penalty removed. 1 atk 30% vs Prayer → still 0.3',
    version: V_MOM_CP,
    a: { atk:1, hp:10 },
    b: { hp:10, abilities: { prayer: true } },
    expected: { dmgToA: 0, dmgToB: 0.300 },
  },

  // --- High Prayer ---
  highPrayerMeleeAtk: {
    desc: 'High Prayer Melee Atk: base 1 atk + HP +2 = 3 atk, 100% hit vs 0 def → 3 dmg',
    a: { atk:1, toHitMod:70, hp:10, abilities: { highPrayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  highPrayerDefense: {
    desc: 'High Prayer Defense: missile 4 100% hit vs base def 1 + HP +2 = 3, 100% block → 4−3 = 1 (def 2 would give 2)',
    a: { rtbType:'missile', rtb:4, toHitRtbMod:70, hp:10 },
    b: { def:1, toBlkMod:70, hp:10, abilities: { highPrayer: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  highPrayerResistance: {
    desc: 'High Prayer Resistance: Poison 4 vs base res 5 + HP +3 = res 8, pFail 20%, E[dmg] = 0.8',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { highPrayer: true } },
    expected: { dmgToA: 0, dmgToB: 0.800 },
  },
  highPrayerToHit: {
    desc: 'High Prayer To Hit: missile 1, base 30% + HP +10% = 40% hit vs 0 def → 0.4 (ranged isolates from +2 melee)',
    a: { rtbType:'missile', rtb:1, hp:10, abilities: { highPrayer: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  highPrayerToBlock: {
    desc: 'High Prayer To Block: missile 10 100% hit vs def 8 + HP +2 = 10, 40% block → 10−4 = 6.0 (30% would give 7.0)',
    a: { rtbType:'missile', rtb:10, toHitRtbMod:70, hp:10 },
    b: { def:8, hp:20, abilities: { highPrayer: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  highPrayerMeleeNotRanged: {
    desc: 'High Prayer +2 melee does NOT boost ranged: missile 3, 100% hit, HP → still 3 (not 5)',
    a: { rtbType:'missile', rtb:3, toHitRtbMod:70, hp:10, abilities: { highPrayer: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  highPrayerCombined: {
    desc: 'High Prayer combined: atk 3+2=5 at 40% (30+10) vs 0 def → 5×0.4 = 2.0',
    a: { atk:3, hp:10, abilities: { highPrayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Warlord: Prayer + High Prayer stacking ---
  warlordPrayerStackAtk: {
    desc: 'Warlord Prayer+HP stack: atk 1 + HP +2 + Prayer +1 = 4, 100% hit vs 0 def → 4.0 (CoM2 would be 3.0)',
    version: V_WARLORD,
    a: { atk:1, toHitMod:70, hp:10, abilities: { prayer: true, highPrayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  warlordPrayerStackDef: {
    desc: 'Warlord Prayer+HP stack: atk 5 100% hit vs def 1 + HP +2 + Prayer +1 = 4, 100% block → 5−4 = 1.0 (CoM2 def 3 → 2.0)',
    version: V_WARLORD,
    a: { atk:5, toHitMod:70, hp:10 },
    b: { def:1, toBlkMod:70, hp:20, abilities: { prayer: true, highPrayer: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  warlordPrayerStackRes: {
    desc: 'Warlord Prayer+HP stack: Poison 5 vs base res 5 + HP +3 + Prayer +1 = res 9 (CoM2 −1 mod → eff 8), pFail 20%, poison E[dmg] = 1.0. Melee dmg = 0 (atk 1 vs def 10, all blocked). (CoM2 no stack: res 8 → eff 7 → pFail 30% → 1.5)',
    version: V_WARLORD,
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 5 } },
    b: { def:10, toBlkMod:70, res:5, hp:10, abilities: { prayer: true, highPrayer: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  warlordPrayerStackToHitNoStack: {
    desc: 'Warlord Prayer+HP stack: To Hit does NOT stack. atk 1 + HP+2 + Prayer+1 = 4, base 30% + 10% (single bonus) = 40% vs 0 def → 4×0.4 = 1.6 (stacked 50% would give 2.0)',
    version: V_WARLORD,
    a: { atk:1, hp:10, abilities: { prayer: true, highPrayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.600 },
  },
  warlordPrayerStackToBlockNoStack: {
    desc: 'Warlord Prayer+HP stack: To Block does NOT stack. atk 10 100% hit vs def 0 + HP +2 + Prayer +1 = 3, base 30% + 10% (single bonus) = 40% block → 10 − 3×0.4 = 8.80 (stacked 50% would be 8.50)',
    version: V_WARLORD,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, hp:20, abilities: { prayer: true, highPrayer: true } },
    expected: { dmgToA: 0, dmgToB: 8.800 },
  },
  com2PrayerHpSupersedes: {
    desc: 'CoM2 Prayer+HP: HP supersedes (no stack). atk 1 + HP +2 = 3 (Prayer adds nothing), 40% hit vs 0 def → 1.2',
    version: V_COM2,
    a: { atk:1, hp:10, abilities: { prayer: true, highPrayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.200 },
  },
  prayerHpStackPairCoM2: {
    desc: 'Prayer+HP atk pair (CoM2): HP supersedes, atk 1 + 2 = 3, 100% hit vs 0 def → 3.0',
    version: V_COM2,
    a: { atk:1, toHitMod:70, hp:10, abilities: { prayer: true, highPrayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  prayerHpStackPairWarlord: {
    desc: 'Prayer+HP atk pair (Warlord): stack, atk 1 + HP+2 + Prayer+1 = 4, 100% hit vs 0 def → 4.0',
    version: V_WARLORD,
    a: { atk:1, toHitMod:70, hp:10, abilities: { prayer: true, highPrayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Black Prayer ---
  blackPrayerAtkPenalty: {
    desc: 'Black Prayer Atk: base 2 atk − 1 = 1, 100% hit vs 0 def → 1 dmg',
    a: { atk:2, toHitMod:70, hp:10, abilities: { blackPrayer: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  blackPrayerDefPenalty: {
    desc: 'Black Prayer Def: 2 atk 100% hit vs base def 2 − 1 = 1, 100% block → 1 dmg',
    a: { atk:2, toHitMod:70, hp:10 },
    b: { def:2, toBlkMod:70, hp:10, abilities: { blackPrayer: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  blackPrayerResPenalty: {
    desc: 'Black Prayer Res: 1 atk (100% blocked: def 2−1=1 at 100%) + Poison 4 vs res 5−2=3, pFail 70%, E[dmg] = 2.8',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:2, toBlkMod:70, res:5, hp:10, abilities: { blackPrayer: true } },
    expected: { dmgToA: 0, dmgToB: 2.800 },
  },
  blackPrayerRangedAtk: {
    desc: 'Black Prayer Ranged Atk: base 2 missile − 1 = 1, 100% hit vs 0 def → 1 dmg',
    a: { rtbType:'missile', rtb:2, toHitRtbMod:70, hp:10, abilities: { blackPrayer: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  blackPrayerThrownAtk: {
    desc: 'Black Prayer Thrown Atk: base thrown 2 − 1 = 1, 100% hit vs 0 def → 1 thrown + base melee 2 − 1 = 1 at 100% hit → 2 total',
    a: { atk:2, rtbType:'thrown', rtb:2, toHitMod:70, toHitRtbMod:70, hp:10, abilities: { blackPrayer: true } },
    b: { atk:0, hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  blackPrayerDoomGazeUnchangedCoM2: {
    desc: 'Black Prayer (CoM2) does not write the independent Doom Gaze field: Doom Gaze 5 still deals 5 damage.',
    version: V_COM2,
    a: { atk:0, hp:10, abilities: { blackPrayer: true, doomGaze: 5 } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  fieryFuryUsesBaseFantasticForFirstStrikeWarlord: {
    desc: 'Fiery Fury uses BASEFANTASTIC: a base regular Combat Summoned unit receives the +3 regular-unit melee package but not First Strike, so B still counters for 5. A live-Fantastic gate would incorrectly prevent the counter.',
    version: V_WARLORD,
    a: { atk:5, toHitMod:70, hp:10, abilities: { fieryFury: true, combatSummoned: true } },
    b: { atk:5, toHitMod:70, def:0, hp:8 },
    expected: { dmgToA: 5.000, dmgToB: 8.000 },
  },
});
