// Numeric presets. Protective enchantments (Endurance through Wraith Form), the weapon
// enchantments (Metal Fires, Flame Blade, Fiery Blade, Chaos Channels), Lucky, Large Shield,
// and Blur.
definePresets({
  // --- Destroy Mechanical (Clockwork Tinmen) ---
  destroyMechanicalMeleeOneShotWarlord: {
    desc: 'Destroy Mechanical (Warlord): melee attack vs a mechanical defender deals damage = defender HP regardless of attack strength. atk 1 → 10 dmg (not 1)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { destroyMechanical: true } },
    b: { hp:10, abilities: { mechanical: true } },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  destroyMechanicalCounterAttackWarlord: {
    desc: 'Destroy Mechanical (Warlord): defender Tinmen counter-attack one-shots a mechanical attacker. a atk 1 → 1 dmg to Tinmen; b counter atk 1 normally → 1 dmg, but Destroy Mechanical → 10 dmg to a',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { mechanical: true } },
    b: { atk:1, hitChance:70, toBlkMod:70, hp:10, abilities: { destroyMechanical: true } },
    expected: { dmgToA: 10.000, dmgToB: 1.000 },
  },
  destroyMechanicalNoEffectOnNonMechanicalWarlord: {
    desc: 'Destroy Mechanical (Warlord): no effect when defender is not mechanical. atk 1, 100% hit vs 0 def → 1 dmg (not 10)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { destroyMechanical: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  destroyMechanicalRebuildTargetWarlord: {
    desc: 'Destroy Mechanical (Warlord): Rebuild makes defender mechanical, triggering the one-shot. Without feature: atk 1 vs Rebuild (+2 armor) → 0–1 dmg. With feature: 10 dmg. B\'s 0.6 counterattack is the F142 rule: OLSpell.CAS:280 gates its `SAttack` write on nothing, so B\'s permanent melee 0 becomes 2, at the base 30%',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { destroyMechanical: true } },
    b: { hp:10, abilities: { rebuild: true } },
    expected: { dmgToA: 0.600, dmgToB: 10.000 },
  },

  // --- Land Linking ---
  landLinkingBeforeMysticSurgeRealmCoM: {
    desc: 'Land Linking (CoM 1): the block tests the running `bu->race` at com1:0x8F765, and Mystic Surge writes the unaligned-fantastic realm below it at com1:0x8F79E, so a unit made fantastic only by Mystic Surge gets no +2 melee. atk 1 stays 1. The exclusion is the rule under test',
    version: V_COM,
    a: { atk:1, toHitMod:70, hp:10, abilities: { landLinking: true, mysticSurge: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  landLinkingFantasticMeleeCoM2: {
    desc: 'Land Linking (CoM2): fantastic creature gets +2 melee. atk 1 to 3, 100% hit vs 0 def gives 3 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, unitType: 'fantastic_nature', abilities: { landLinking: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  landLinkingFantasticBreathCoM2: {
    desc: 'Land Linking (CoM2): fantastic creature gets +2 breath and melee. fire breath 2 to 4, melee 1 to 3, for 7 damage',
    version: V_COM2,
    a: { atk:1, hitChance:70, modernAttacks: { fireBreath: { strength:2, type:'fire' } }, hp:10, unitType: 'fantastic_nature', abilities: { landLinking: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  landLinkingFantasticDefenseCoM2: {
    desc: 'Land Linking (CoM2): fantastic creature gets +2 defense. 5 atk at 100% vs def 2 at 100% block gives 3 dmg',
    version: V_COM2,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, unitType: 'fantastic_nature', abilities: { landLinking: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  landLinkingNormalNoBonusCoM2: {
    desc: 'Land Linking (CoM2): normal unit only gets Pathfinding, so combat stats are unchanged. atk 1 stays 1',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { landLinking: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  landLinkingRangedCoM: {
    desc: 'Land Linking (CoM): fantastic creature does not get +2 ranged attack. missile 2 stays 2',
    version: V_COM,
    a: { rtbType:'missile', rtb:2, toHitRtbMod:70, hp:10, unitType: 'fantastic_nature', abilities: { landLinking: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  landLinkingRangedCoM2: {
    desc: 'Land Linking (CoM2): fantastic creature does not get +2 ranged attack. missile 2 stays 2',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, unitType: 'fantastic_nature', abilities: { landLinking: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Nature Link (Warlord rename of Land Linking) ---
  natureLinkBeforeSpiritLinkClearWarlord: {
    desc: 'Nature Link (Warlord): the region-c block tests `U.Fantastic`, and Spirit Link clears it only in the late hook (UnitCalc.CAS:1306, region d), so a Mystic-Surged unit still gets the +2 melee there. atk 1 to 3 for 3 dmg',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { natureLink: true, mysticSurge: true, spiritLink: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  natureLinkSpiritLinkAssertsFantasticWarlord: {
    desc: 'Spirit Link on an otherwise non-fantastic unit: `SETSTAT(U,AFantastic,0,1)` at UnitCalcPre.CAS:30 asserts Fantastic in region b, and the region-c Nature Link block reads that record, so the +2 melee applies. atk 1 to 3 for 3 dmg, against the 1 the same unit deals without Spirit Link. The clearing write at UnitCalc.CAS:1306 is region d, past both blocks.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { natureLink: true, spiritLink: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  natureLinkFantasticMeleeWarlord: {
    desc: 'Nature Link (Warlord): fantastic creature still gets the Land Linking +2 melee. atk 1 to 3, 100% hit vs 0 def gives 3 dmg',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, unitType: 'fantastic_nature', abilities: { natureLink: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  natureLinkNormalResistanceWarlord: {
    desc: 'Nature Link (Warlord): normal unit gains only +1 resistance (Land Linking gives normal units nothing). Death Gaze 0 vs res 5 to 6 drops P(die) from 0.5 to 0.4, so 10 HP yields 4.0 dmg',
    version: V_WARLORD,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, abilities: { natureLink: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Endurance ---
  enduranceDefenseCoM: {
    desc: 'Endurance (CoM): defender gains +2 defense, so 5 atk at 100% hit vs 2 def blocks 0.6 on average → 4.4 dmg',
    version: V_COM,
    a: { atk:5, toHitMod:70, hp:10 },
    b: { def:0, hp:10, abilities: { endurance: true } },
    expected: { dmgToA: 0, dmgToB: 4.400 },
  },
  enduranceHpBonusCoM2: {
    desc: 'Endurance (CoM2): 2-figure unit gets floor(4/2)=2 HP per figure, so stoning kill deals 4 plus 1 physical → 5.0 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { stoningTouch: -7 } },
    b: { figs:2, def:0, res:0, hp:2, abilities: { endurance: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  enduranceHpMinimumCoM2: {
    desc: 'Endurance (CoM2): minimum +1 HP per figure still applies above 4 figures, so 9 figs at hp 1 become hp 2 and one stoning kill deals 2 plus 1 physical → 3.0 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { stoningTouch: -7 } },
    b: { figs:9, def:0, res:0, hp:1, abilities: { endurance: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  enduranceEffectCoM: {
    desc: 'Endurance (CoM): same 2-figure target keeps hp 2 but gains +2 defense, so damage is 2 from stoning plus 0.49 physical → 2.49',
    version: V_COM,
    a: { atk:1, toHitMod:70, hp:10, abilities: { stoningTouch: -7 } },
    b: { figs:2, def:0, res:0, hp:2, abilities: { endurance: true } },
    expected: { dmgToA: 0, dmgToB: 2.490 },
  },
  enduranceEffectCoM2: {
    desc: 'Endurance (CoM2): same 2-figure target gets hp 4 per figure and no defense bonus, so damage is 4 from stoning plus 1 physical → 5.0',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { stoningTouch: -7 } },
    b: { figs:2, def:0, res:0, hp:2, abilities: { endurance: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },

  // --- Malnourished ---
  malnourishedMeleePenaltyWarlord: {
    desc: 'Malnourished (Warlord): −1 melee, so atk 5 → 4, 100% hit vs 0 def → 4 dmg',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10, abilities: { malnourished: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  malnourishedDefensePenaltyWarlord: {
    desc: 'Malnourished (Warlord): −2 def, so def 3 → 1, 5 atk 100% hit, 1 of 5 blocked → 4 dmg',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:3, toBlkMod:70, hp:10, abilities: { malnourished: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  malnourishedClosesMeleeSlotWarlord: {
    desc: 'Malnourished (Warlord) writes −1 melee at ABase, so a 1-melee unit enters the recalculation with BaseUnits.attack 0 and every later melee-presence gate is shut — the exclusion is the rule under test. Holy Bonus\'s `if B.attack > 0` therefore skips melee: 0 dmg (reading the card\'s atk instead would leave 1 − 1 + 2 = 2 → 2.0)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { malnourished: true, holyBonus: 2 } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.000 },
  },

  // --- Mislead / Misfortune ---
  misleadMisfortuneNormalMeleeCoM2: {
    desc: 'Mislead/Misfortune (CoM2): affected normal unit loses 1 melee attack, so base 1 atk becomes 0 → 0 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { mislead: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.000 },
  },
  misleadMisfortuneNormalRangedCoM2: {
    desc: 'Mislead/Misfortune (CoM2): affected normal unit loses 1 ranged attack, so missile 2 becomes 1 → 1 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { mislead: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  misleadMisfortuneNormalDefenseCoM2: {
    desc: 'Mislead/Misfortune (CoM2): affected normal defender loses 1 defense, so 2 atk 100% hit vs base def 1 drops to def 0 → 2 dmg',
    version: V_COM2,
    a: { atk:2, hitChance:70, hp:10 },
    b: { def:1, toBlkMod:70, hp:10, abilities: { mislead: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  misleadMisfortuneNormalResistanceCoM2: {
    desc: 'Mislead/Misfortune (CoM2): affected normal defender loses 1 resistance, so Death Gaze vs res 5 becomes res 4 → 6 dmg',
    version: V_COM2,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { res:5, hp:10, abilities: { mislead: true } },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  misleadMisfortuneHeroAffectedCoM2: {
    desc: 'Mislead/Misfortune (CoM2): heroes count as normal-unit targets here, so atk 1 drops to 0 → 0 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, unitType:'hero', abilities: { mislead: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.000 },
  },

  // --- Mystic Surge ---
  mysticSurgeDefenseBonusCoM2: {
    desc: 'Mystic Surge (CoM2): surged defender gets +2 defense. 5 atk 100% hit vs 2 def at 30% block → 4.4 dmg',
    version: V_COM2,
    a: { atk:5, hitChance:70, hp:10 },
    b: { def:0, hp:10, abilities: { mysticSurge: true } },
    expected: { dmgToA: 0, dmgToB: 4.400 },
  },
  mysticSurgeResistPenaltyCoM2: {
    desc: 'Mystic Surge (CoM2): surged unit loses 2 resistance. Death Gaze vs 2-figure res 5 stack becomes res 3 → pFail=0.7 per figure → 14.0 dmg',
    version: V_COM2,
    a: { hp:10, abilities: { deathGaze: 0 } },
    b: { figs:2, res:5, hp:10, abilities: { mysticSurge: true } },
    expected: { dmgToA: 0, dmgToB: 14.000 },
  },
  mysticSurgeFantasticAndToDefendCoM2: {
    desc: 'Mystic Surge (CoM2): directly grants EncMagic and makes the attacker unaligned Fantastic; Weapon Immunity is bypassed, and its -10% To Defend gives 5 atk vs 1 def at 20% block → 4.8 dmg',
    version: V_COM2,
    a: { atk:5, hitChance:70, hp:10, unitType:'normal', abilities: { mysticSurge: true } },
    b: { def:1, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 4.800 },
  },

  // --- Supernatural ---
  supernaturalFormulaCoM: {
    desc: 'Supernatural (CoM): the roster trait has no combat effect; 9 melee fully blocked deals 0 damage',
    version: V_COM,
    a: { atk:9, toHitMod:70, hp:10, abilities: { supernatural: true } },
    b: { def:9, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.000 },
  },
  supernaturalFormulaCoM2: {
    desc: 'Supernatural (CoM2): the blocked-attack minimum is Round(hits × 34 / 100), not round(hits/3). Magic Immunity sets effectiveDefense to 100, so all 28 magic ranged hits are blocked and only the minimum lands: Round(28 × 34/100) = 10, where round(28/3) would give 9. A fully-blocked melee probe can no longer discriminate the two: F32/F34\'s defense-dice cap (Combat.ResolutionHelpers.pas:159-171) holds blocked hits to 15 or fewer, where the formulas agree, and the Defense input is UI-capped at 50. Without Supernatural the same attack deals ~0.',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:28, type:'magic' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { supernatural: true } },
    b: { toBlkMod:70, hp:20, abilities: { magicImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  supernaturalMagicImmunityRangedCoM2: {
    desc: 'Supernatural (CoM2): magic ranged 6 reduced by Magic Immunity still deals the 1/3 minimum = 2 dmg',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:6, type:'magic' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { supernatural: true } },
    b: { toBlkMod:70, hp:10, abilities: { magicImmunity: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  supernaturalFireBreathFireImmunityCoM2: {
    desc: 'Supernatural (CoM2): fire breath 6 reduced by Fire Immunity still deals the 1/3 minimum = 2 dmg',
    version: V_COM2,
    a: { atk:1, modernAttacks: { fireBreath: { strength:6, type:'fire' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { supernatural: true } },
    b: { def:1, toBlkMod:70, hp:10, abilities: { fireImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Resistance to All ---
  resistanceToAllBasic: {
    desc: 'Resistance to All: Poison 4 vs base res 5 + RTA 2 → effective res 7, pFail 30%, E[dmg]=1.2',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { resistanceToAll: 2 } },
    expected: { dmgToA: 0, dmgToB: 1.200 },
  },
  resistanceToAllCap: {
    desc: 'Resistance to All caps immunity: Poison 4 vs res 8 + RTA 2 → effective res 10, pFail 0% → immune',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:8, hp:10, abilities: { resistanceToAll: 2 } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  holyBonusPlusResistanceToAll: {
    desc: 'HB + RTA stacking: Poison 4 vs res 4 + HB 1 + RTA 1 → effective res 6, pFail 40%, E[dmg]=1.6',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:4, hp:10, abilities: { holyBonus: 1, resistanceToAll: 1 } },
    expected: { dmgToA: 0, dmgToB: 1.600 },
  },

  // --- Resist Magic ---
  resistMagicBlocks: {
    desc: 'Resist Magic +5 res vs stoning: res 5+5=10, stoningTouch -3 → effectiveRes 7, pFail 30% → E[stoning dmg]=3.0. Without RM pFail=80% → 8.0.',
    a: { atk:1, toHitMod:70, hp:10, abilities: { stoningTouch: -3 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { resistMagic: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  resistMagicNotPoison: {
    desc: 'Resist Magic does not apply to poison: res 5+0=5, poison 4 → pFail 50% → E[poison dmg]=2.0 (would be 0 if RM applied).',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { resistMagic: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Stone Skin / Iron Skin ---
  stoneSkinDef: {
    desc: 'Stone Skin: +1 Def. 1 atk 100% hit vs def 0 + Stone Skin → def 1, 30% block → E[dmg]=0.7',
    a: { atk:1, toHitMod:70, hp:10 },
    b: { hp:10, abilities: { stoneSkin: true } },
    expected: { dmgToA: 0, dmgToB: 0.700 },
  },
  ironSkinDef: {
    desc: 'Iron Skin: +5 Def. 5 atk 100% hit vs def 0 + Iron Skin → def 5, E[blocks]=1.5 → E[dmg]=3.5',
    a: { atk:5, toHitMod:70, hp:10 },
    b: { hp:10, abilities: { ironSkin: true } },
    expected: { dmgToA: 0, dmgToB: 3.500 },
  },
  ironSkinStoneSkinNoStack: {
    desc: 'Iron Skin + Stone Skin do not stack: only +5 Def applies (not +6). 5 atk 100% hit vs def 5 → E[blocks]=1.5 → E[dmg]=3.5',
    a: { atk:5, toHitMod:70, hp:10 },
    b: { hp:10, abilities: { ironSkin: true, stoneSkin: true } },
    expected: { dmgToA: 0, dmgToB: 3.500 },
  },

  // --- Invulnerability ---
  invulnerabilityMelee: {
    desc: 'Invulnerability: -2 damage per defense roll. 5 atk 100% hit vs def 0 + invuln → net 5-0-2=3 dmg (magic weapon bypasses granted WI)',
    a: { atk:5, toHitMod:70, hp:10, weapon:'magic' },
    b: { hp:10, abilities: { invulnerability: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  invulnerabilityFloorsAtZero: {
    desc: 'Invulnerability: reduction cannot go negative. 1 atk 100% hit vs def 0 + invuln → max(0, 1-2) = 0 dmg',
    a: { atk:1, toHitMod:70, hp:10, weapon:'magic' },
    b: { hp:10, abilities: { invulnerability: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  invulnerabilityGrantsWeaponImmunity: {
    desc: 'Invulnerability grants Weapon Immunity (def→10 vs normal weapons): 10 atk 100% hit 100% block → all blocked',
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { invulnerability: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  invulnerabilityRanged: {
    desc: 'Invulnerability vs ranged missile: 5 rtb 100% hit vs def 0, magic weapon bypasses WI → net 5-2=3',
    a: { rtbType:'missile', rtb:5, toHitRtbMod:70, hp:10, weapon:'magic' },
    b: { hp:10, abilities: { invulnerability: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  invulnerabilityImmolation: {
    desc: 'Invulnerability reduces immolation damage by 2 per defense roll',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, hp:10, weapon:'magic', abilities: { immolation: true } },
    b: { figs:1, def:0, toBlkMod:70, hp:10, abilities: { invulnerability: true } },
    expected: { dmgToA: 0, dmgToB: 0.0918 },
  },
  invulnerabilityNotDoom: {
    desc: 'Invulnerability does not reduce doom damage: 6 atk doom → floor(6/2)=3 lands in full vs invuln',
    a: { atk:6, hp:10, abilities: { doom: true } },
    b: { hp:10, abilities: { invulnerability: true } },
    expected: { dmgToA: 0, dmgToB: 3 },
  },
  invulnerabilityMultiFigOverflow: {
    desc: 'Invulnerability -2 fires on each fresh defense roll during overflow. 5 atk 100% hit vs 3-fig hp=2: fig1 takes 2 (5-2=3, dies, excess 1), fig2 takes max(0,1-2)=0 → total 2 (vs 5 without invuln)',
    a: { atk:5, toHitMod:70, hp:10, weapon:'magic' },
    b: { figs:3, hp:2, abilities: { invulnerability: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Holy Armor ---
  holyArmorDef: {
    desc: 'Holy Armor: +2 Def. 2 atk 100% hit vs def 0 + Holy Armor → def 2, 30% block → E[dmg]=1.4',
    a: { atk:2, toHitMod:70, hp:10 },
    b: { hp:10, abilities: { holyArmor: true } },
    expected: { dmgToA: 0, dmgToB: 1.400 },
  },
  holyArmorVsRanged: {
    desc: 'Holy Armor applies vs ranged too: 2 rtb 100% hit vs def 0 + Holy Armor → def 2 → E[dmg]=1.4',
    a: { rtbType:'missile', rtb:2, toHitRtbMod:70, hp:10 },
    b: { hp:10, abilities: { holyArmor: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.400 },
  },
  holyArmorStacksWithStoneSkin: {
    desc: 'Holy Armor (+2) stacks with Stone Skin (+1): 3 atk 100% hit vs def 0 → def 3, E[blocks]=0.9 → E[dmg]=2.1',
    a: { atk:3, toHitMod:70, hp:10 },
    b: { hp:10, abilities: { holyArmor: true, stoneSkin: true } },
    expected: { dmgToA: 0, dmgToB: 2.100 },
  },
  holyArmorHighDefMoM: {
    desc: 'Holy Armor (MoM): always +2 def regardless of base def. 15 atk 100% hit vs def 8+2=10, 30% block → E[blocks]=3.0 → E[dmg]=12.0',
    version: V_MOM_131,
    a: { atk:15, toHitMod:70, hp:30 },
    b: { def:8, hp:30, abilities: { holyArmor: true } },
    expected: { dmgToA: 0, dmgToB: 12.000 },
  },
  holyArmorLowDefCoM2: {
    desc: 'Holy Armor (CoM2): def 5 ≤ 5 → +2 defense. 10 atk 100% hit vs def 5+2=7, 30% block → E[blocks]=2.1 → E[dmg]=7.9',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:20 },
    b: { def:5, hp:20, abilities: { holyArmor: true } },
    expected: { dmgToA: 0, dmgToB: 7.900 },
  },
  holyArmorHighDefCoM2: {
    desc: 'Holy Armor (CoM2): def 8 > 5 → +10% To Defend instead of +2 def. 15 atk 100% hit vs def 8, toBlock 40% → E[blocks]=3.2 → E[dmg]=11.8',
    version: V_COM2,
    a: { atk:15, hitChance:70, hp:30 },
    b: { def:8, hp:30, abilities: { holyArmor: true } },
    expected: { dmgToA: 0, dmgToB: 11.800 },
  },

  // --- Holy Weapon ---
  holyWeaponMelee: {
    desc: 'Holy Weapon melee: atk 1 @ base 30% + HW +10% = 40% vs def 0 → E[dmg]=0.4',
    a: { atk:1, hp:10, abilities: { holyWeapon: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  holyWeaponMissile: {
    desc: 'Holy Weapon missile: rtb 1 @ base 30% + HW +10% = 40% vs def 0 → E[dmg]=0.4',
    a: { rtbType:'missile', rtb:1, hp:10, abilities: { holyWeapon: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  holyWeaponBoulder: {
    desc: 'Holy Weapon boulder: rtb 1 @ base 30% + HW +10% = 40% vs def 0 → E[dmg]=0.4',
    a: { rtbType:'boulder', rtb:1, hp:10, abilities: { holyWeapon: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  holyWeaponNotMagicRanged: {
    desc: 'Holy Weapon does NOT boost magic ranged: rtb 1 magic_c @ 30% (no HW bonus) → E[dmg]=0.3',
    a: { rtbType:'magic_c', rtb:1, hp:10, abilities: { holyWeapon: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.300 },
  },
  holyWeaponNotFireBreath: {
    desc: 'Holy Weapon does NOT boost fire breath: melee 1 @ 40% + fire rtb 1 @ 30% = 0.4+0.3=0.7',
    a: { atk:1, rtbType:'fire', rtb:1, hp:10, abilities: { holyWeapon: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.700 },
  },
  holyWeaponThrownMoM: {
    desc: 'Holy Weapon vs Thrown (MoM 1.31): bug — no HW bonus on thrown. melee 1 @ 40% + thrown 1 @ 30% = 0.7',
    version: V_MOM_131,
    a: { atk:1, rtbType:'thrown', rtb:1, hp:10, abilities: { holyWeapon: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.700 },
  },
  holyWeaponThrownPatched: {
    desc: 'Holy Weapon vs Thrown (MoM CP 1.60+): fix — HW boosts thrown. melee 1 @ 40% + thrown 1 @ 40% = 0.8',
    version: V_MOM_CP,
    a: { atk:1, rtbType:'thrown', rtb:1, hp:10, abilities: { holyWeapon: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.800 },
  },
  holyWeaponBypassesWI: {
    desc: 'Holy Weapon bypasses Weapon Immunity: 10 atk normal weapon + HW vs WI def 0 → weapon treated as magic, WI does not trigger, 40% hit = E[dmg]=4.0',
    version: V_MOM_131,
    a: { atk:10, hp:10, abilities: { holyWeapon: true } },
    b: { def:0, toBlkMod:70, hp:20, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },

  // --- Heavenly Light ---
  heavenlyLightRangedCoM2: {
    desc: 'Heavenly Light (CoM 2) on an eligible normal unit: +1 conventional ranged strength and +10% Ranged To Hit → missile 3 at 40% = 1.200. Without the enchantment this is missile 2 at 30% = 0.600.',
    version: V_COM2,
    a: { modernAttacks: { ranged: { strength:2, type:'missile' } }, hp:10, abilities: { heavenlyLight: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.200 },
  },
  heavenlyLightNotBreathCoM2: {
    desc: 'Channel boundary: Units.RecalculateUnits.pas:1451-1454 writes Ranged and Thrown only, and the strength bonus reads the conventional Ranged field, so a Fire Breath unit gains neither — breath 2 at 30% = 0.600, the same as without the enchantment. A leak into the Breath To Hit modifier gives 0.800; one into the Breath strength gives 0.900. Paired with heavenlyLightRangedCoM2, which is the same unit with a missile attack.',
    version: V_COM2,
    a: { modernAttacks: { fireBreath: { strength:2, type:'fire' } }, hp:10, abilities: { heavenlyLight: true } },
    b: { hp:10 },
    rangedCheck: false,
    expected: { dmgToA: 0, dmgToB: 0.600 },
  },
  heavenlyLightMeleeCoM: {
    desc: 'Heavenly Light (CoM 1), the defender-side city block at com1:0x905BB: a positive melee attack gains +1, and a unit carrying no weapon material also gains +10% melee To Hit → 3 at 40% = 1.200. Without the enchantment this is 2 at 30% = 0.600.',
    version: V_COM,
    a: { atk:2, toHitMod:0, hp:10, abilities: { heavenlyLight: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.200 },
  },
  heavenlyLightToHitNeedsBareWeaponCoM: {
    desc: 'Material boundary: com1:0x90600 grants the melee threshold only where `mutations & UM_WEAPON_QUALITY_MASK` is clear, so a mithril unit takes the +1 strength and none of the To Hit. Mithril alone is 3 at 40% = 1.200; with Heavenly Light it is 4 at 40% = 1.600, not the 4 at 50% = 2.000 an unconditional threshold gives. Paired with heavenlyLightMeleeCoM, the same unit with a bare weapon.',
    version: V_COM,
    a: { atk:2, toHitMod:0, weapon:'mithril', hp:10, abilities: { heavenlyLight: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.600 },
  },
  heavenlyLightMissileCoM: {
    desc: 'The shared-slot half: com1:0x90610 raises a positive ranged strength and com1:0x9062B adds the threshold for Thrown, Missile and Boulder types → missile 3 at 40% = 1.200. Without the enchantment this is missile 2 at 30% = 0.600.',
    version: V_COM,
    a: { atk:0, rtbType:'missile', rtb:2, hp:10, abilities: { heavenlyLight: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.200 },
  },
  heavenlyLightBreathStrengthNoToHitCoM: {
    desc: 'Type boundary inside one slot: the CoM 1 strength write carries no `ranged_type` test, so the DOS shared slot takes +1 whatever stands in it, while the threshold at com1:0x90618 admits only Thrown and types below RAT_MAGIC_FIRST. A Fire Breath unit is therefore breath 3 at 30% = 0.900, not the 2 at 30% = 0.600 it is without the enchantment and not the 3 at 40% = 1.200 a leaking threshold gives. Paired with heavenlyLightMissileCoM, the same unit with a missile attack.',
    version: V_COM,
    a: { atk:0, rtbType:'fire', rtb:2, hp:10, abilities: { heavenlyLight: true } },
    b: { hp:10 },
    rangedCheck: false,
    expected: { dmgToA: 0, dmgToB: 0.900 },
  },
  heavenlyLightMagicWeaponCoM: {
    desc: 'The minimum weapon quality: com1:0x9063F raises `Weapon_Plus1` to 1 where it was 0, so a bare-weapon unit bypasses Weapon Immunity. atk 10 at a forced 100% To Hit against a Weapon-Immune defender: 11 (the block\'s own +1) all land for 11.000. Without the enchantment Weapon Immunity holds the defense up and only 2.000 gets through; a plain magic weapon and no enchantment gives 10.000, which is the same bypass without the strength bonus.',
    version: V_COM,
    a: { atk:10, toHitMod:70, hp:10, abilities: { heavenlyLight: true } },
    b: { def:0, toBlkMod:70, hp:20, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 11.000 },
  },

  // --- Channel fields on the modern record (F80) ---
  ccFireBreathSeparatesThrownWarlord: {
    desc: 'Record fields: `Caster.exe` $00599F3E adds 4 to the Fire Breath field and writes no other attack, so a Thrown unit finishes with two attacks rather than one boosted one. Hurricane separates them by channel — UnitCalc.CAS:558,569-571 takes 20 points off Thrown and 30 off Breath — so from a 100% base the Thrown 2 fires at 80% and the granted Fire Breath 4 at 70%: 1.6 + 2.8 = 4.400. A grant landing on the Thrown field instead leaves one attack of 6 (4.200 as Breath, 4.800 as Thrown), and a lost Breath field leaves the Thrown alone at 1.600.',
    version: V_WARLORD,
    a: { atk:0, modernAttacks: { thrown: { strength:2, type:'thrown' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    hurricane: true,
    expected: { dmgToA: 0, dmgToB: 4.400 },
  },
  weaponToHitReadsOwnRangedChannelWarlord: {
    desc: 'ApplyMagicWeapons (Units.RecalculateUnits.pas:639-662) gates `hitchanceranged` on the record\'s own `rangedtype` and `hitchancethrown` on the record\'s Thrown field, so the Ranged modifier is decided by the Ranged channel even while the unit also carries the Thrown attack Bombs & Grenades creates. Magic weapon on missile 3: 3 at 40% = 1.200. Without the material this is 0.900. Paired with weaponToHitSkipsMagicRangedChannelWarlord, the same unit with a magical ranged type.',
    version: V_WARLORD,
    a: { atk:1, weapon:'magic', modernAttacks: { ranged: { strength:3, type:'missile' } }, hp:10,
      abilities: { outlanderWizard: true, explosive: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.200 },
  },
  weaponToHitSkipsMagicRangedChannelWarlord: {
    desc: 'Channel boundary: the same unit with a magical ranged attack. `Ismagicalranged` holds, so ApplyMagicWeapons withholds the material To Hit modifier from the Ranged channel and the attack stays at 30% — 3 at 30% = 0.900, the same as with no weapon material at all. That inertness is the rule under test, and it is not general: its missile pair reaches 1.200 from the same material, and reading this gate from the Thrown channel Bombs & Grenades created, whose own material gate passes, would reach 1.200 here too.',
    version: V_WARLORD,
    a: { atk:1, weapon:'magic', modernAttacks: { ranged: { strength:3, type:'magic' } }, hp:10,
      abilities: { outlanderWizard: true, explosive: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.900 },
  },
  weaponMaterialRangedHasNoStrengthGateWarlord: {
    desc: 'ApplyMagicWeapons writes `Inc(Units[i].ranged, j)` inside `if not Ismagicalranged(Units[i].rangedtype)` with no positive-strength gate at all (Units.RecalculateUnits.pas:648-656), and `Ismagicalranged` is False for a zero ranged type (:2968-2975), so the adamantium +2 lands on the `SRanged` field of a unit that owns no ranged attack. Blaze of Glory then moves that whole field into Thrown (UnitCalc.CAS:1494-1500): melee 3 + 2 material + 2 for the Armor the material gave = 7, beside a new Thrown 2 → 9.0. (Gating that write on the slot\'s input strength leaves nothing to transfer, for 7.0; without Blaze of Glory melee 5 and Armor 2 stay where they are, for 5.0; without the material, melee 3 → 3.0.)',
    version: V_WARLORD,
    a: { atk:3, def:0, hitChance:70, hp:10, weapon:'adamantium',
      abilities: { blazeOfGlory: true } },
    b: { def:0, toBlkMod:70, hp:30 },
    expected: { dmgToA: 0, dmgToB: 9.000 },
  },
  weaponMaterialThrownReadsCalculatedFieldWarlord: {
    desc: 'The Thrown half of the same block is gated on `if Units[i].thrown > 0` — the *calculated* Thrown field at ApplyMagicWeapons\' own position (Units.RecalculateUnits.pas:658-662), which region `b` has already written. Bombs & Grenades creates Thrown floor(8 − 4/2) = 6 at `UnitCalcPre.CAS:1071` on a card with no Thrown input at all, so the adamantium +2 reaches it: 4 figures at melee 1+2 = 3 and Thrown 6+2 = 8 deal (3 + 8) × 4 = 44.0. (Reading the slot\'s input strength instead withholds the material from the created attack, leaving Thrown 6 for 36.0; the sibling bombsGrenadesWarlord fixture without the material is 28.0.)',
    version: V_WARLORD,
    a: { figs:4, atk:1, hitChance:70, hp:10, weapon:'adamantium',
      abilities: { outlanderWizard: true, explosive: true } },
    b: { def:0, toBlkMod:70, hp:50 },
    expected: { dmgToA: 0, dmgToB: 44.000 },
  },
  weaponMaterialDosThrownHasNoStrengthGateMoM: {
    desc: 'The DOS material body admits the shared slot by type alone — `RAT_CLASS(bu->ranged_type) == RAT_CLASS_MISSILE || RAT_CLASS_BOULDER || bu->ranged_type == RAT_THROWN` (`unitcalc.c`, 131:0x8F089/0x8F09C/0x8F0A4) — and the `bu->ranged += quality - 1` inside it (131:0x8F0BA) makes no strength test, so adamantium\'s +2 lands on a Thrown slot whose input strength is 0. One figure at 100%: the Thrown phase deals 0 + 2 and the melee 3 + 2, for 7.0. (Gating the write on the slot\'s input strength, as the calculator did before F109, leaves the Thrown attack at 0 for 5.0; mithril is quality 2 and reaches 5.0; a magic weapon is quality 1 and adds nothing, 3.0; no material at all is 3.0.)',
    version: V_MOM_131,
    a: { figs:1, atk:3, def:0, hp:20, rtbType:'thrown', rtb:0, weapon:'adamantium',
      toHitMod:70, toHitRtbMod:70 },
    b: { atk:0, def:0, toBlkMod:70, hp:40 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  weaponMaterialDosMissileHasNoStrengthGateMoM: {
    desc: 'The Missile half of the same type-only gate (`unitcalc.c`, 131:0x8F089): a Missile slot at input strength 0 takes adamantium\'s +2 and becomes a real ranged attack of 2, fired at range 1 with no counter-attack, for 2.0. (With the fabricated input-strength gate the slot stays at 0, the card offers no ranged attack at all and the exchange silently resolves as melee 3 + 2 = 5.0; without the material it is melee 3.0.) Paired with weaponMaterialDosThrownHasNoStrengthGateMoM, the Thrown half of the same gate.',
    version: V_MOM_131,
    a: { figs:1, atk:3, def:0, hp:20, rtbType:'missile', rtb:0, weapon:'adamantium',
      toHitMod:70, toHitRtbMod:70 },
    b: { atk:0, def:0, toBlkMod:70, hp:40 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  weaponMaterialDosThrownHasNoStrengthGateCoM1: {
    desc: 'CoM 1 compiles the same type-only gate at com1:0x8F070/0x8F083/0x8F08B and the same three writes at com1:0x8F0A1/0x8F0A5/0x8F0AF, so the MoM 1.31 result repeats: Thrown 0 + 2 beside melee 3 + 2 = 7.0, against 5.0 with the input-strength gate. It is also the control for weaponMaterialDosSecondarySkippedByFocusMagicCoM1, which is this fixture plus Focus Magic.',
    version: V_COM,
    a: { figs:1, atk:3, def:0, hp:20, rtbType:'thrown', rtb:0, weapon:'adamantium',
      toHitMod:70, toHitRtbMod:70 },
    b: { atk:0, def:0, toBlkMod:70, hp:40 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  weaponMaterialDosMeleeGateIsLiveRecordCoM1: {
    desc: 'The DOS material block gates its melee half on the *calculated* record in front of it: `if (bu->melee > 0)` wraps `bu->melee += quality - 1`, `Gold_Melee` and `melee_tohit++` (`unitcalc.c`, com1:0x8F03A). This unit has melee 0, so adamantium adds nothing to it and only CoM 1\'s Supreme Light does — melee 0 + 2 = 2 for 2.0. (Without the gate the material also lands, for melee 4 and 4.0; Supreme Light is what makes it visible at all, because it is the one CoM 1 effect that widens the terminal slot clamp for a melee-less unit.) Defense stays outside the gate in both engines: 2 from Supreme Light\'s trunc(6/3) plus adamantium\'s 2. The magical ranged 5 + 2 is Supreme Light\'s and moves either way — the DOS material body admits Missile, Boulder and Thrown only.',
    version: V_COM,
    a: { figs:1, atk:0, def:0, res:6, hp:20, rtbType:'magic_s', rtb:5, weapon:'adamantium',
      toHitMod:70, toHitRtbMod:70, abilities: { supremeLight: true } },
    b: { atk:0, def:0, toBlkMod:70, hp:40 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  weaponMaterialMeleeGateReadsPermanentRecordWarlord: {
    desc: 'The modern engine makes the same melee-presence test on the *permanent* record instead: `if BaseUnits[i].attack > 0` wraps `hitchancemelee`, `attack` and `attackbonus` (Units.RecalculateUnits.pas:637-642). Malnourished writes its −1 melee into ABase at `CreateUnit.CAS:614-618`, so this card\'s melee 1 enters ApplyMagicWeapons as a permanent 0 and adamantium is withheld: melee 1 − 1 = 0, then Blaze of Glory moves the whole armour — 4 − 2 Malnourished + 2 adamantium = 4 — onto it, for 4.0. This fixture separates all three readings of the gate: no gate at all, or a gate on the card\'s own melee input, both leave the +2 in place for 6.0. (Without the material, armour 2 alone gives 2.0.) The Ranged record is typed magical at strength 0 so `Ismagicalranged` withholds the material\'s secondary write, leaving Blaze of Glory nothing to transfer — otherwise this fixture would also carry weaponMaterialRangedHasNoStrengthGateWarlord\'s Thrown 2 and state two rules at once.',
    version: V_WARLORD,
    a: { figs:1, atk:1, def:4, hp:20, weapon:'adamantium', hitChance:70,
      modernAttacks: { ranged: { strength: 0, type: 'magic' } },
      abilities: { blazeOfGlory: true, malnourished: true } },
    b: { atk:0, def:0, toBlkMod:70, hp:60 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  weaponMaterialDosSecondarySkippedByFocusMagicCoM1: {
    desc: 'Negative claim — the exclusion is the rule under test. CoM 1 alone wraps the whole secondary half of the material block in `if (!(ench_lo & UE_FOCUS_MAGIC))` (`unitcalc.c`, com1:0x8F095), so a Focus Magic unit takes none of its strength, display bonus or threshold even though the block runs before the conversion at com1:0x8F7E6 and the slot still carries its Thrown type. Only the melee half lands: 3 + 2 = 5.0. Its control is weaponMaterialDosThrownHasNoStrengthGateCoM1, the identical fixture without Focus Magic, which reaches 7.0; removing the exclusion from the calculator raises this fixture to 7.0 too, so the inertness is the engine\'s and not the fixture\'s.',
    version: V_COM,
    a: { figs:1, atk:3, def:0, hp:20, rtbType:'thrown', rtb:0, weapon:'adamantium',
      toHitMod:70, toHitRtbMod:70, abilities: { focusMagic: true } },
    b: { atk:0, def:0, toBlkMod:70, hp:40 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },

  // --- Wraith Form ---
  wraithFormGrantsWeaponImmunity: {
    desc: 'Wraith Form grants Weapon Immunity: normal melee vs WF unit gets blocked by WI defense',
    version: V_MOM_131,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, toBlkMod:70, hp:10, abilities: { wraithForm: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  wraithFormBypassesWIMoM: {
    desc: 'Wraith Form offense in MoM: no WI bypass yet, so normal unit + WF still gets blocked by enemy WI',
    version: V_MOM_131,
    a: { atk:10, toHitMod:70, hp:10, abilities: { wraithForm: true } },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 0 },
  },
  wraithFormBypassesWICoM2: {
    desc: 'Wraith Form offense in CoM2: unit attacks as though it had magic weapons, bypassing enemy WI',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { wraithForm: true } },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  rulerOfUnderworldBypassesWICoM2: {
    desc: 'Ruler of Underworld (CoM2): attacks count as magical for Weapon Immunity bypass, so 10 atk vs enemy WI deals full 10.0',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, abilities: { rulerOfUnderworld: true } },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  rulerOfUnderworldPreservesMagicWICoM2: {
    desc: 'Ruler of Underworld (CoM2): a material-only Magic Weapon grant no longer bypasses the granted Weapon Immunity, so 10 magic atk vs def 0 still faces WI +8 → 2.0 dmg',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10, weapon: 'magic' },
    b: { def:0, toBlkMod:70, hp:20, abilities: { rulerOfUnderworld: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },

  // --- Metal Fires / Flame Blade / Fiery Blade ---
  metalFiresMelee: {
    desc: 'Metal Fires +1 melee: base 1 atk + MF → 2 atk, 100% hit vs 0 def → E[dmg]=2.0',
    a: { atk:1, toHitMod:70, hp:10, abilities: { metalFires: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  metalFiresFantasticUnaffected: {
    desc: 'Metal Fires is non-Fantastic-only: a Fantastic Chaos unit keeps melee 1 instead of receiving +1.',
    a: { atk:1, toHitMod:70, hp:10, unitType:'fantastic_chaos', abilities: { metalFires: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  metalFiresFantasticMissileUnaffected: {
    desc: 'Metal Fires does not boost a Fantastic unit\'s missile attack: strength 1 stays 1.',
    a: { rtbType:'missile', rtb:1, toHitRtbMod:70, hp:10,
      unitType:'fantastic_chaos', abilities: { metalFires: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  metalFiresFantasticThrownUnaffected: {
    desc: 'Metal Fires does not boost a Fantastic unit\'s melee or Thrown attacks: strength 1 + 1 deals 2.',
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:1, toHitRtbMod:70, hp:10,
      unitType:'fantastic_chaos', abilities: { metalFires: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  metalFiresMissile: {
    desc: 'Metal Fires +1 missile: base 1 + MF → 2 rtb, 100% hit vs 0 def → E[dmg]=2.0',
    a: { rtbType:'missile', rtb:1, toHitRtbMod:70, hp:10, abilities: { metalFires: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  metalFiresNotBoulder: {
    desc: 'Metal Fires does NOT boost boulder: base 1 boulder + MF → still 1 rtb → E[dmg]=1.0',
    a: { rtbType:'boulder', rtb:1, toHitRtbMod:70, hp:10, abilities: { metalFires: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  metalFiresThrown: {
    desc: 'Metal Fires +1 thrown: atk 1+1=2, thrown 1+1=2, 100% hit vs 0 def → E[dmg]=4.0 (thrown+melee)',
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:1, toHitRtbMod:70, hp:10, abilities: { metalFires: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  metalFiresWeaponUpgrade: {
    desc: 'Metal Fires upgrades weapon to magic, bypassing WI: 2+1=3 atk vs WI def=1 100% block → WI skipped, E[dmg]=2.0',
    a: { atk:2, toHitMod:70, hp:10, abilities: { metalFires: true } },
    b: { def:1, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  flameBladeMelee: {
    desc: 'Flame Blade +2 melee: base 1 atk + FB → 3 atk, 100% hit vs 0 def → E[dmg]=3.0',
    a: { atk:1, toHitMod:70, hp:10, abilities: { flameBlade: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  flameBladeMissile: {
    desc: 'Flame Blade +2 missile: base 1 + FB → 3 rtb, 100% hit vs 0 def → E[dmg]=3.0',
    a: { rtbType:'missile', rtb:1, toHitRtbMod:70, hp:10, abilities: { flameBlade: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  flameBladeThrown: {
    desc: 'Flame Blade +2 thrown: atk 1+2=3, thrown 1+2=3, 100% hit vs 0 def → E[dmg]=6.0 (thrown+melee)',
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:1, toHitRtbMod:70, hp:10, abilities: { flameBlade: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  flameBladeMetalFiresNoStack: {
    desc: 'Flame Blade + Metal Fires do not stack: only +2 melee applies (not +3). base 1 atk + FB → 3 atk, 100% hit vs 0 def → E[dmg]=3.0',
    a: { atk:1, toHitMod:70, hp:10, abilities: { flameBlade: true, metalFires: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  flameBladeMeleeCoM2: {
    desc: 'CoM2 Flame Blade +3 melee: 1 atk + FB → 4 atk, 100% hit vs 0 def → E[dmg]=4.0',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { flameBlade: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  flameBladeThrownNotBoostedCoM2: {
    desc: 'CoM2 Flame Blade does NOT boost thrown (helptext: missile only): melee 1+3=4, thrown 1 (unchanged), 100% hit vs 0 def → E[dmg]=5.0',
    version: V_COM2,
    a: { atk:1, hitChance:70, modernAttacks: { thrown: { strength:1, type:'thrown' } }, hp:10, abilities: { flameBlade: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  flameBladeMeleeWarlord: {
    desc: 'Warlord Flame Blade +3 melee: 1 atk + FB → 4 atk at 100% hit vs 0 def. Combat-cast Flame Blade also does an unconditional SFireBreath += 1 (UnitCalc.CAS:330-333), creating a strength-1 fire breath on a unit that had none; at the default 30% breath To Hit that adds 0.3 → E[dmg]=4.3. Without the ability the same unit deals 1.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hitRanged:-70, hitThrown:-70, hitBreath:-70, hp:10,
      abilities: { flameBladeWarlord: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.300 },
  },
  flameBladeMissileWarlord: {
    desc: 'Warlord Flame Blade +2 missile: 1 rtb + FB → 3 rtb, 100% hit vs 0 def → E[dmg]=3.0',
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:1, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { flameBladeWarlord: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  flameBladeBoulderWarlord: {
    desc: 'Warlord Flame Blade does NOT boost boulder (helptext: rock bonus belongs to Fiery Fury): 1 rtb, 100% hit vs 0 def → E[dmg]=1.0',
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:1, type:'boulder' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { flameBladeWarlord: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  flameBladeThrownWarlord: {
    desc: 'Warlord Flame Blade: +3 melee and +2 thrown, plus the unconditional SFireBreath += 1 at UnitCalc.CAS:330-333 that creates a strength-1 fire breath from the empty breath field. atk 1+3=4, thrown 1+2=3, created breath 1, all at 100% hit → E[dmg]=8.0. Without the ability the same unit deals 2.0.',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, modernAttacks: { thrown: { strength:1, type:'thrown' } }, hp:10, abilities: { flameBladeWarlord: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  flameBladeFireBreathWarlord: {
    desc: 'Warlord Flame Blade +1 fire breath: 1 + FB → 2 breath, 100% hit + melee atk 1+3=4 → E[dmg]=6.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, modernAttacks: { fireBreath: { strength:1, type:'fire' } }, hp:10, abilities: { flameBladeWarlord: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  flameBladeCreatesFireBreathWarlord: {
    desc: 'Warlord combat Flame Blade creates Fire Breath 1 from an empty field: melee 1+3=4 plus breath 1 at 100% hit → E[dmg]=5.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { flameBladeWarlord: true } },
    b: { def:0, toBlkMod:70, hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  fieryBladeMeleeWarlord: {
    desc: 'Warlord Lava Smelter Fiery Blade +3 melee: 1 atk + Fiery Blade → 4 atk, 100% hit vs 0 def → E[dmg]=4.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, race:'Dwarf', abilities: { lavaSmelterFieryBlade: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  fieryBladeNoFireBreathWarlord: {
    desc: 'Warlord Lava Smelter Fiery Blade does NOT add fire breath: breath stays 1 while melee is 1+3=4 → E[dmg]=5.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, modernAttacks: { fireBreath: { strength:1, type:'fire' } }, hp:10, race:'Dwarf', abilities: { lavaSmelterFieryBlade: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  fieryFuryMeleeWarlord: {
    desc: 'Warlord Fiery Fury +3 melee (regular unit): 1 atk + FF → 4 atk, 100% hit vs 0 def → E[dmg]=4.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { fieryFury: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  fieryFuryMissileWarlord: {
    desc: 'Warlord Fiery Fury +2 missile (regular unit): 1 rtb + FF → 3 rtb, 100% hit vs 0 def → E[dmg]=3.0',
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:1, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { fieryFury: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  fieryFuryBoulderWarlord: {
    desc: 'Warlord Fiery Fury +2 boulder (regular unit): 1 rtb + FF → 3 rtb, 100% hit vs 0 def → E[dmg]=3.0',
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:1, type:'boulder' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, abilities: { fieryFury: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  fieryFuryThrownWarlord: {
    desc: 'Warlord Fiery Fury: +3 melee + +2 thrown (regular). atk 1+3=4, thrown 1+2=3 → E[dmg]=7.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, modernAttacks: { thrown: { strength:1, type:'thrown' } }, hp:10, abilities: { fieryFury: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  fieryFuryNoBreathBonusWarlord: {
    desc: 'Warlord Fiery Fury does NOT boost fire breath (elemental). breath 1 + 0 = 1, melee 1+3=4 → E[dmg]=5.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, modernAttacks: { fireBreath: { strength:1, type:'fire' } }, hp:10, abilities: { fieryFury: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  fieryFuryFantasticNoStatBonus: {
    desc: 'Warlord Fiery Fury on a fantastic creature: no stat bonuses (only First Strike + Chaos conversion). atk stays 1 → E[dmg]=1.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, unitType:'fantastic_nature', abilities: { fieryFury: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  fieryFuryFantasticFirstStrike: {
    desc: 'Warlord Fiery Fury on fantastic gives First Strike: A kills B before B can swing. atk 5 + FS, B atk 5 no FS, B has 5 HP → A wins unscathed → dmgToA=0, dmgToB=5.0',
    version: V_WARLORD,
    a: { atk:5, hitChance:70, hp:10, figs:1, unitType:'fantastic_nature', abilities: { fieryFury: true } },
    b: { atk:5, hitChance:70, def:0, hp:5, figs:1 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  fieryFuryFantasticChaosConversion: {
    desc: 'Warlord Fiery Fury on a fantastic non-undead creature converts it to Chaos: Chaos Surge (count 1, Warlord) then grants +3 melee. atk 1 + ChaosSurge(3) = 4 → E[dmg]=4.0',
    version: V_WARLORD,
    chaosSurge: 1,
    a: { atk:1, hitChance:70, hp:10, unitType:'fantastic_nature', abilities: { fieryFury: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  fieryFuryUndeadNoChaosConversion: {
    desc: 'Fiery Fury\'s Chaos write applies to every base-fantastic unit and carries no undead test (UnitCalcPre.CAS:832-838); the undead exclusion comes later, from the compiled aggregate Undead normalization that forces race := 20 (Units.RecalculateUnits.pas, $0059FBD0..$0059FD93). So the Undead flag, not the Death realm, is what keeps this unit off the Chaos realm and out of Chaos Surge: atk stays 1 → E[dmg]=1.0. Dropping only the Undead flag gives 4.0, matching the sibling fieryFuryFantasticChaosConversion, so the pair brackets the rule.',
    version: V_WARLORD,
    chaosSurge: 1,
    a: { atk:1, hitChance:70, hp:10, unitType:'fantastic_death', abilities: { fieryFury: true, undead: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  fieryFurySanctifyNoChaosConversionWarlord: {
    desc: 'Sanctify overrides Fiery Fury\'s Chaos write from a different source line (UnitCalcPre.CAS:1249) than the Undead normalization does: the unit ends Life rather than Chaos, so Chaos Surge does not reach it and atk stays 1 → E[dmg]=1.0. Dropping Sanctify gives 4.0.',
    version: V_WARLORD,
    chaosSurge: 1,
    a: { atk:1, hitChance:70, hp:10, unitType:'fantastic_nature', abilities: { fieryFury: true, sanctify: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  fieryFuryFieryBladeNoStack: {
    desc: 'Warlord Fiery Fury + Fiery Blade: shared bonuses do NOT stack (melee stays +3, missile +2). atk 1+3=4 → E[dmg]=4.0',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, race:'Dwarf', abilities: { fieryFury: true, lavaSmelterFieryBlade: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  fieryFuryWeaponImmunityBypass: {
    desc: 'Warlord Fiery Fury bypasses Weapon Immunity (effective weapon → magic). atk 4+3=7 hits WI 10 def 0+10=10 normally but bypass leaves def 0 → E[dmg]=7.0',
    version: V_WARLORD,
    a: { atk:4, hitChance:70, hp:10, abilities: { fieryFury: true } },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },

  // --- Spirit Link (Warlord, Conjurer signature) ---
  spiritLinkExorciseImmuneWarlord: {
    desc: 'Spirit Link: spirit-linked fantastic_death is no longer fantastic for targeting, so Exorcise −4 cannot affect it — only physical 1 atk lands → 1.0 (vs 10.0 without Spirit Link)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, abilities: { exorcise: -4 } },
    b: { figs:2, def:0, res:5, hp:10, unitType: 'fantastic_death', abilities: { spiritLink: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  spiritLinkWeaponImmunityBypassWarlord: {
    desc: 'Spirit Link: phase c grants magical attacks while the unit is still fantastic; phase d then clears Fantastic without clearing EncMagic. The spirit-linked attacker therefore still bypasses Weapon Immunity and deals 10.0.',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10, unitType: 'fantastic_chaos', abilities: { spiritLink: true } },
    b: { def:0, toBlkMod:70, hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  spiritLinkBlessNoBonusWarlord: {
    desc: "Spirit Link: spirit-linked fantastic_chaos missile attacker grants the enemy no anti-Chaos Bless bonus. missile 10 vs def 0 → 10.0 (vs 3.0 with Bless's +7)",
    version: V_WARLORD,
    a: { modernAttacks: { ranged: { strength:10, type:'missile' } }, hitRanged:70, hitThrown:70, hitBreath:70, hp:10, unitType: 'fantastic_chaos', abilities: { spiritLink: true } },
    b: { def:0, toBlkMod:70, res:5, hp:10, abilities: { bless: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  spiritLinkResistanceWarlord: {
    // F44 re-derivation: Spirit Link gives Res 5+2=7, Stoning Gaze −3 → effRes 4, pFail 0.6.
    // One defending figure at 10 HP → 6.000. The earlier 6.120 added a 0.12 physical component,
    // but SPEC (*Gaze attacks*) has that hidden component as MoM-only: CoM2 and Warlord carry
    // gazes as save-modifier stats with no attack-strength slot, so there is nothing to roll.
    desc: 'Spirit Link: +2 Resistance. Stoning Gaze −3 vs Res 5+2=7 → effRes 4, pFail 0.6 → 6.0 damage; Warlord has no hidden gaze component',
    version: V_WARLORD,
    a: { hp:10, abilities: { stoningGaze: -3 } },
    b: { res:5, hp:10, unitType: 'fantastic_nature', abilities: { spiritLink: true } },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  spiritLinkGrantsLevelBonusWarlord: {
    desc: 'Spirit Link lets a fantastic creature earn levels: an Elite fantastic_nature attacker gains the Warlord Elite +2 melee. atk 1+2=3, 100% hit vs def 0 → 3.0 (vs 1.0 without Spirit Link, where the level dropdown is ignored for fantastic units)',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, hp:10, level:'elite', unitType: 'fantastic_nature', abilities: { spiritLink: true } },
    b: { def:0, hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },

  // --- Chaos Channels ---
  ccDefense131: {
    desc: 'Chaos Channels Defense (MoM 1.31): +6 def bug → 7 atk 100% hit, def 0+6=6, 100% block → 1 dmg',
    version: V_MOM_131,
    a: { atk:7, toHitMod:70, hp:10 },
    b: { toBlkMod:70, hp:10, abilities: { ccDefense: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  ccDefenseFixed: {
    desc: 'Chaos Channels Defense (CP 1.60): +3 def (Insecticide fix) → 7 atk 100% hit, def 0+3=3, 100% block → 4 dmg',
    version: V_MOM_CP,
    a: { atk:7, toHitMod:70, hp:10 },
    b: { toBlkMod:70, hp:10, abilities: { ccDefense: true } },
    expected: { dmgToA: 0, dmgToB: 4.000 },
  },
  ccFireBreathBasic: {
    desc: 'Chaos Channels Fire Breath 2: atk 1 melee + breath 2 (forced), 100% hit → 3 dmg',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, toHitRtbMod:70, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  ccFireBreathAfterLevelMoM: {
    desc: 'Chaos Channels Fire Breath (MoM 1.31) is written inside BU_Apply_Specials at 0x8F720, after the level bonus, and it assigns the shared slot rather than adding to it — so an elite unit breathes 2, not 2 + the elite ranged bonus. Elite melee 1 + 2 = 3 plus breath 2 → 5 dmg (7 if the assignment ran before the level bonus; a normal-level unit deals 3).',
    version: V_MOM_131,
    a: { atk:1, level:'elite', toHitMod:70, toHitRtbMod:70, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  ccFireBreathCoM: {
    desc: 'Chaos Channels Fire Breath 4 in CoM: atk 1 melee + breath 4 → 5 dmg',
    version: V_COM,
    a: { atk:1, toHitMod:70, toHitRtbMod:70, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  ccFireBreathReplacesThrown: {
    desc: 'Chaos Channels Fire Breath (MoM 1.31): base Thrown 3 is admitted at the signed ceiling and replaced by Fire Breath 2, so melee 1 + breath 2 = 3 dmg',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:3, toHitRtbMod:70, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  ccFireBreathRejectsPositiveThrownCP: {
    desc: 'Chaos Channels Fire Breath (CP 1.60): positive base Thrown 3 exceeds the patched ceiling of 0, so the shared slot stays Thrown; Chaos identity still admits the +2 node aura, making melee 3 + Thrown 5 = 8 (7 if wrongly replaced, 4 without Chaos Channels)',
    version: V_MOM_CP,
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:3, toHitRtbMod:70, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    nodeAura: 'chaos',
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  ccFireBreathRepeatsAtRecompute131: {
    desc: 'MoM 1.31 passes the mutations byte whole to the recompute\'s second BU_Apply_Specials call (131:0x90A1D), so the fire-breath block assigns the shared slot a second time, after the Chaos node aura has already raised it. Melee 1 + 2 (aura, on the Chaos identity Chaos Channels grants) = 3, plus breath 2 → 5 dmg; 7 if the second assignment is missing and the aura keeps its +2 on the slot, which is what CP 1.60 does once its zeroed mutations byte stops the repeat.',
    version: V_MOM_131,
    nodeAura: 'chaos',
    a: { atk:1, toHitMod:70, toHitRtbMod:70, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  ccFireBreathRecomputeFixedCP: {
    desc: 'The same fixture on CP 1.60, which zeroes the mutations byte at the second call so the fire-breath block runs once: the Chaos node aura keeps its +2 on the shared slot, giving melee 3 + breath 4 = 7 dmg against 1.31\'s 5.',
    version: V_MOM_CP,
    nodeAura: 'chaos',
    a: { atk:1, toHitMod:70, toHitRtbMod:70, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  ccFireBreathCoexistsWithLightningCoM2: {
    // F44: this asserted 5.000 on the assumption that CC overwrites the lightning breath. No
    // source supports that. `Caster.exe` $00599EE8 does `firebreath += 4` and writes no other
    // attack field, and the CoM2 manual says CC "can still add Fire Breath to units that have
    // Thrown, Gaze or Lightning Breath". CoM2's channels are independent, so both fire.
    desc: 'Chaos Channels in CoM2 adds Fire Breath alongside an existing Lightning Breath: melee 1 + lightning 5 + fire 4 = 10',
    version: V_COM2,
    a: { atk:1, hitChance:70, modernAttacks: { lightningBreath: { strength:5, type:'lightning' } }, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  ccFireBreathCoexistsWithGazeCoM2: {
    // F44's replacement for `ccFireBreathReplacesGazeCoM2`, which asserted that the gaze
    // suppressed the breath. Nothing supports that; the fabricated overwrite is gone. Defender
    // Resistance 20 against a −3 gaze puts the kill roll out of reach, so this isolates the
    // grant: melee 1 + fire breath 4 = 5.000, where the old suppression gave melee 1 alone.
    desc: 'Chaos Channels in CoM2 adds Fire Breath to a unit that already has a Stoning Gaze: melee 1 + breath 4 = 5 (1 if the gaze wrongly suppresses the grant)',
    version: V_COM2,
    a: { atk:1, hitChance:70, hp:10, abilities: { ccFireBreath: true, stoningGaze: -3 } },
    b: { res:20, hp:10 },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  ccFireBreathVsFireImmunity: {
    desc: 'CC Fire Breath vs Fire Immunity: breath blocked (def 50) → melee 1 only',
    a: { atk:1, toHitMod:70, toHitRtbMod:70, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10, abilities: { fireImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  ccBypassWeaponImmunity: {
    desc: 'CC unit attacks Weapon Immune: CC makes unit fantastic_chaos, so WI does not apply → 3 dmg',
    a: { atk:3, toHitMod:70, hp:10, abilities: { ccDefense: true } },
    b: { hp:10, abilities: { weaponImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  ccNodeAuraChaos: {
    desc: 'CC unit benefits from Chaos Node aura: +2 atk. 1 atk + CC (fantastic_chaos) + chaos node aura → 3 atk, 100% hit → 3 dmg',
    nodeAura: 'chaos',
    a: { atk:1, toHitMod:70, hp:10, abilities: { ccDefense: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  // This pair is kept although both sides now agree: CoM2 was modelled as replacing an
  // existing fire breath and Warlord as stacking, but `Caster.exe` $00599F3E is one `add`
  // routine serving both, so the split was invented. Keeping the pair locks the agreement —
  // a regression that re-splits them fails exactly one side.
  ccFireBreathAddsToExistingCoM2: {
    desc: 'CC Fire Breath vs existing fire breath (CoM2): adds. melee 1 + fire breath (3+4) = 8 dmg',
    version: V_COM2,
    a: { atk:1, hitChance:70, modernAttacks: { fireBreath: { strength:3, type:'fire' } }, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  ccFireBreathAddsToExistingWarlord: {
    desc: 'CC Fire Breath vs existing fire breath (Warlord): adds, identically to CoM2. melee 1 + fire breath (3+4) = 8 dmg',
    version: V_WARLORD,
    a: { atk:1, hitChance:70, modernAttacks: { fireBreath: { strength:3, type:'fire' } }, hp:10, abilities: { ccFireBreath: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },

  // --- Lucky ---
  luckyToHit: {
    desc: 'Lucky To Hit: 1 atk, base 30% + Lucky +10% = 40% hit vs 0 def → E[dmg] = 0.4',
    a: { atk:1, hp:10, abilities: { lucky: true } },
    b: { hp:10 },
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  luckyToHitRanged: {
    desc: 'Lucky To Hit Ranged: missile 1 atk, base 30% + Lucky +10% = 40% hit vs 0 def → 0.4',
    a: { rtbType:'missile', rtb:1, hp:10, abilities: { lucky: true } },
    b: { hp:10 },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.400 },
  },
  luckyToBlock: {
    desc: 'Lucky To Block: 1 atk 90% hit (v1.31 Lucky penalty) vs def 1, 40% block → 0.9×0.6 = 0.54',
    a: { atk:1, toHitMod:70, hp:10 },
    b: { def:1, hp:10, abilities: { lucky: true } },
    expected: { dmgToA: 0, dmgToB: 0.540 },
  },
  luckyResistance: {
    desc: 'Lucky Resistance: Poison 4 vs base res 5 + Lucky +1 = res 6, pFail 40%, E[dmg] = 1.6',
    a: { atk:1, toHitMod:70, hp:10, abilities: { poison: 4 } },
    b: { def:1, toBlkMod:70, res:5, hp:10, abilities: { lucky: true } },
    expected: { dmgToA: 0, dmgToB: 1.600 },
  },
  luckyEnemyMeleePenalty131: {
    desc: 'Lucky Enemy Melee Penalty (MoM 1.31): bug — B Lucky, A melee 30% → 20%. 1 atk vs 0 def → E[dmg] = 0.2',
    version: V_MOM_131,
    a: { atk:1, hp:10 },
    b: { hp:10, abilities: { lucky: true } },
    expected: { dmgToA: 0, dmgToB: 0.200 },
  },
  luckyEnemyPenaltyNotRanged131: {
    desc: 'Lucky Enemy Ranged Penalty (MoM 1.31): enemy penalty does NOT apply to ranged. Missile 1 atk 30% → still 0.3',
    version: V_MOM_131,
    a: { rtbType:'missile', rtb:1, hp:10 },
    b: { hp:10, abilities: { lucky: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 0.300 },
  },
  luckyEnemyPenaltyRemovedPatched: {
    desc: 'Lucky Enemy Melee Penalty (MoM CP 1.60): fix — enemy penalty removed. 1 atk 30% vs Lucky → still 0.3',
    version: V_MOM_CP,
    a: { atk:1, hp:10 },
    b: { hp:10, abilities: { lucky: true } },
    expected: { dmgToA: 0, dmgToB: 0.300 },
  },

  // --- Defense Rollover (wounded top figure) ---
  defRolloverWoundedCoM: {
    desc: 'MoM/CoM: top fig wounded (1/2 HP); rollover at fullHP=2, net 2 hits fullHP threshold → no fresh roll → E=2.000',
    version: V_COM,
    a: { figs: 1, atk: 3, toHitMod: 70, def: 0, hp: 20 },
    b: { figs: 2, hp: 2, dmg: 1, def: 1, toBlkMod: 70, atk: 0 },
    expected: { dmgToA: 0, dmgToB: 2.000 },
  },
  defRolloverWoundedCoM2: {
    desc: 'CoM2: top fig wounded (1/2 HP); rollover at topFigHP=1, excess hits fresh defense roll → blocked → E=1.000',
    version: V_COM2,
    a: { figs: 1, atk: 3, hitChance:70, def: 0, hp: 20 },
    b: { figs: 2, hp: 2, dmg: 1, def: 1, toBlkMod: 70, atk: 0 },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },

  // --- Predefined unit matchups (MoM 1.31) ---
  // --- Large Shield ---
  largeShieldRangedMissile: {
    desc: 'Large Shield Ranged (MoM 1.31): missile 4 (100% hit) vs def 1+2=3 (100% block) → 4−3=1',
    version: V_MOM_131,
    a: { rtbType:'missile', rtb:4, toHitRtbMod:70, hp:10 },
    b: { def:1, toBlkMod:70, hp:10, abilities: { largeShield: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  largeShieldMeleeNoEffect: {
    desc: 'Large Shield Melee: LS does NOT apply — atk 4 (100% hit) vs def 1 (100% block) → 4−1=3',
    a: { atk:4, toHitMod:70, hp:10 },
    b: { atk:0, def:1, toBlkMod:70, hp:10, abilities: { largeShield: true } },
    expected: { dmgToA: 0, dmgToB: 3.000 },
  },
  largeShieldThrown: {
    desc: 'Large Shield Thrown: thrown 4 (100% hit) vs def 1+2=3 (100% block) → 4−3=1; melee 1 vs def 1 (no LS) → 0',
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:4, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:1, toBlkMod:70, hp:10, abilities: { largeShield: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  largeShieldArmorPiercing: {
    desc: 'Large Shield + AP Ranged: def 4+2=6 halved to 3 — missile 4 (100% hit) vs 3 (100% block) → 1',
    a: { rtbType:'missile', rtb:4, toHitRtbMod:70, hp:10, abilities: { armorPiercing: true } },
    b: { def:4, toBlkMod:70, hp:10, abilities: { largeShield: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },
  largeShieldFireBreath: {
    desc: 'Large Shield Breath: fire breath 4 (100% hit) vs def 1+2=3 (100% block) → 4−3=1; melee 1 vs def 1 (no LS) → 0',
    a: { atk:1, toHitMod:70, rtbType:'fire', rtb:4, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:1, toBlkMod:70, hp:10, abilities: { largeShield: true } },
    expected: { dmgToA: 0, dmgToB: 1.000 },
  },

  // --- Large Shield (CoM/CoM2: +3) ---
  largeShieldCom2Ranged: {
    desc: 'Large Shield Ranged (CoM): missile 4 (100% hit) vs def 1+3=4 (100% block) → 0',
    a: { rtbType:'missile', rtb:4, toHitRtbMod:70, hp:10 },
    b: { def:1, toBlkMod:70, hp:10, abilities: { largeShield: true } },
    rangedCheck: true, rangedDist: 1,
    version: V_COM,
    expected: { dmgToA: 0, dmgToB: 0 },
  },

  // --- Blur ---
  // blurBasicMoM131: 10 atk, 100% to hit, def 0, hp 100 (no overflow). Buggy v1.31: skip-on-success.
  // E[negated] per DP recurrence = 0.9174, E[surviving] = 9.083.
  blurBasicMoM131: {
    desc: 'Blur v1.31 (buggy, 10%): 10 atk 100% hit, B has blur — skip-on-success bug, E[dmg]≈9.083',
    version: V_MOM_131,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true } },
    expected: { dmgToA: 0, dmgToB: 9.083 },
  },
  blurFixedMoM160: {
    desc: 'Blur v1.60 (fixed, 10%): 10 atk 100% hit, B has blur — no skip bug, E[dmg]=9.0',
    version: V_MOM_CP,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true } },
    expected: { dmgToA: 0, dmgToB: 9.000 },
  },
  blurCoM2: {
    desc: 'Blur CoM2 (20%): tactical defender Card B\'s army has Blur; E[dmg]=8.0',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true } },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  blurCoM2CounterOwnSide: {
    desc: 'CoM2 Card B army Blur reduces both the initiating strike and Card B\'s counterattack; E[dmg]=8 each',
    version: V_COM2,
    a: { atk:10, def:0, hitChance:70, hp:100 },
    b: { atk:10, def:0, hitChance:70, hp:100, abilities: { blur: true } },
    expected: { dmgToA: 8.000, dmgToB: 8.000 },
  },
  blurIllImmBugV131: {
    desc: 'Blur v1.31 bug: defender illusionImmunity disables their own blur — E[dmg]=10 (no protection)',
    version: V_MOM_131,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true, illusionImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  blurIllImmAtkBugV131: {
    desc: 'Blur v1.31 bug: attacker illusionImmunity does NOT disable blur (checked on wrong unit) — E[dmg]≈9.083',
    version: V_MOM_131,
    a: { atk:10, toHitMod:70, hp:10, abilities: { illusionImmunity: true } },
    b: { def:0, hp:100, abilities: { blur: true } },
    expected: { dmgToA: 0, dmgToB: 9.083 },
  },
  blurIllImmFixed: {
    desc: 'Blur v1.60 fixed: attacker illusionImmunity disables blur — E[dmg]=10',
    version: V_MOM_CP,
    a: { atk:10, toHitMod:70, hp:10, abilities: { illusionImmunity: true } },
    b: { def:0, hp:100, abilities: { blur: true } },
    expected: { dmgToA: 0, dmgToB: 10.000 },
  },
  blurIllImmDefenderFixed: {
    desc: 'Blur v1.60 fixed: defender illusionImmunity does NOT disable their own blur (correct unit checked) — E[dmg]=9.0',
    version: V_MOM_CP,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true, illusionImmunity: true } },
    expected: { dmgToA: 0, dmgToB: 9.000 },
  },
  blurVsDoom: {
    desc: 'Blur does not apply to Doom damage: 10 atk doom → floor(10/2)=5, B has blur — doom bypasses blur, E[dmg]=5',
    version: V_MOM_131,
    a: { atk:10, toHitMod:70, hp:10, abilities: { doom: true } },
    b: { def:0, hp:100, abilities: { blur: true } },
    expected: { dmgToA: 0, dmgToB: 5.000 },
  },
  invisToHitMoM: {
    desc: 'Invisibility in MoM: −10% to-hit penalty (no blur-equivalent): 10 atk 90% hit, def 0 → E[dmg]=9.0',
    version: V_MOM_CP,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { invisibility: true } },
    expected: { dmgToA: 0, dmgToB: 9.000 },
  },
  blurInvisCoM2: {
    desc: 'Invisibility grants Blur-equivalent in CoM (20%, no to-hit penalty): 10 atk 100% hit → E[dmg]=8.0',
    version: V_COM,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { invisibility: true } },
    expected: { dmgToA: 0, dmgToB: 8.000 },
  },
  blurPlusInvisCoM2: {
    desc: 'Blur + Invisibility CoM combined 30% (no to-hit penalty): 10 atk 100% hit → E[dmg]=7.0',
    version: V_COM,
    a: { atk:10, toHitMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true, invisibility: true } },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  blurPlusInvisCoM2v2: {
    desc: 'Card B army Blur + Card B Invisibility CoM2 combined 30%: 10 atk 100% hit → E[dmg]=7.0',
    version: V_COM2,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true, invisibility: true } },
    expected: { dmgToA: 0, dmgToB: 7.000 },
  },
  blurPlusInvisWarlord: {
    desc: 'Card B army Blur + Card B Invisibility Warlord combined 40% → E[dmg]=6.0',
    version: V_WARLORD,
    a: { atk:10, hitChance:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true, invisibility: true } },
    expected: { dmgToA: 0, dmgToB: 6.000 },
  },
  // Blur applies to missile, boulder, magic ranged, thrown, fire breath, gaze ranged (v1.31 buggy 10%)
  blurRangedMissile131: {
    desc: 'Blur applies to ranged missile (v1.31 buggy 10%): rtb=10 100% hit → E[dmg]≈9.083',
    version: V_MOM_131,
    a: { rtbType:'missile', rtb:10, toHitRtbMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 9.083 },
  },
  blurBoulder131: {
    desc: 'Blur applies to boulder (v1.31 buggy 10%): rtb=10 100% hit → E[dmg]≈9.083',
    version: V_MOM_131,
    a: { rtbType:'boulder', rtb:10, toHitRtbMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 9.083 },
  },
  blurMagicRanged131: {
    desc: 'Blur applies to magic ranged (v1.31 buggy 10%): rtb=10 100% hit → E[dmg]≈9.083',
    version: V_MOM_131,
    a: { rtbType:'magic_c', rtb:10, toHitRtbMod:70, hp:10 },
    b: { def:0, hp:100, abilities: { blur: true } },
    rangedCheck: true, rangedDist: 1,
    expected: { dmgToA: 0, dmgToB: 9.083 },
  },
  // Thrown/fire breath require atk>0 to trigger, so melee fires too: E = thrown blur (9.083) + melee blur (0.9) = 9.983
  blurThrown131: {
    desc: 'Blur applies to thrown (v1.31 buggy 10%): rtb=10 + atk=1 both 100% hit → E[dmg]≈9.983',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, rtbType:'thrown', rtb:10, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:0, hp:100, abilities: { blur: true } },
    expected: { dmgToA: 0, dmgToB: 9.983 },
  },
  blurFireBreath131: {
    desc: 'Blur applies to fire breath (v1.31 buggy 10%): rtb=10 + atk=1 both 100% hit → E[dmg]≈9.983',
    version: V_MOM_131,
    a: { atk:1, toHitMod:70, rtbType:'fire', rtb:10, toHitRtbMod:70, hp:10 },
    b: { atk:0, def:0, hp:100, abilities: { blur: true } },
    expected: { dmgToA: 0, dmgToB: 9.983 },
  },
  blurGazeRanged131: {
    desc: 'Blur applies to hidden gaze ranged component (v1.31 buggy 10%): shared gaze strength 10 100% hit → E[dmg]≈9.083',
    version: V_MOM_131,
    a: { rtbType:'gaze_stoning', rtb:10, toHitRtbMod:70, hp:10, abilities: {  } },
    b: { def:0, hp:100, abilities: { stoningImmunity: true, blur: true } },
    expected: { dmgToA: 0, dmgToB: 9.083 },
  },

  // --- Cause Fear (v1.60 fixed behavior) ---
  fearAttackerFixed: {
    desc: 'Cause Fear Attacker (MoM CP 1.60): fix — A fears B normally, no self-fear bug. E[dmgB]=12 (all 4 figs), E[dmgA]=1.5',
    version: V_MOM_CP,
    a: { figs:4, atk:3, toHitMod:70, hp:10, abilities: { fear: true } },
    b: { atk:3, toHitMod:70, hp:20, def:0, res:5 },
    expected: { dmgToA: 1.500, dmgToB: 12.000 },
  },
  fearDefenderFixed: {
    desc: 'Cause Fear Defender (MoM CP 1.60): fix — B defending Fear now works, fears A (50%). E[dmgB]=2.5, E[dmgA]=5',
    version: V_MOM_CP,
    a: { atk:5, toHitMod:70, hp:10, res:5 },
    b: { atk:5, toHitMod:70, hp:10, def:0, res:5, abilities: { fear: true } },
    expected: { dmgToA: 5.000, dmgToB: 2.500 },
  },
  fearDefenderPenaltyCoM: {
    desc: 'Cause Fear Defender (CoM): B defending Fear works with -3 resistance. A res 5 becomes 2, so only 20% attack → E[dmgB]=1',
    version: V_COM,
    a: { atk:5, toHitMod:70, hp:10, res:5 },
    b: { atk:5, toHitMod:70, hp:10, def:0, res:5, abilities: { fear: true } },
    expected: { dmgToA: 5.000, dmgToB: 1.000 },
  },
  fearDefenderPenaltyCoM2: {
    desc: 'Cause Fear Defender (CoM2): B defending Fear works with -3 resistance. A res 5 becomes 2, so only 20% attack → E[dmgB]=1',
    version: V_COM2,
    a: { atk:5, hitChance:70, hp:10, res:5 },
    b: { atk:5, hitChance:70, hp:10, def:0, res:5, abilities: { fear: true } },
    expected: { dmgToA: 5.000, dmgToB: 1.000 },
  },
  fearDefenderFixedFirstStrike: {
    desc: 'Cause Fear bilateral + First Strike (MoM CP 1.60): B fears A before FS; A fears B after FS before counter',
    version: V_MOM_CP,
    a: { atk:10, toHitMod:70, hp:10, res:5, abilities: { firstStrike: true, fear: true } },
    b: { atk:10, toHitMod:70, hp:10, def:0, res:5, abilities: { fear: true } },
    expected: { dmgToA: 2.500, dmgToB: 5.000 },
  },
});
