const COM_UNITS_DATA = {
  "1": {
    "id": 1,
    "templateId": 0,
    "heroTypeId": 0,
    "isHero": true,
    "baseRace": "Dwarven",
    "baseFantastic": false,
    "name": "Dwarf",
    "race": "Dwarven",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 10,
    "hp": 15,
    "melee": 9,
    "moves": 3,
    "abilities": [
      "Hero"
    ],
    "cost": 100,
    "upkeep": 2
  },
  "2": {
    "id": 2,
    "templateId": 1,
    "heroTypeId": 1,
    "isHero": true,
    "baseRace": "Barbarian",
    "baseFantastic": false,
    "name": "Barbarian",
    "race": "Barbarian",
    "category": "Heroes",
    "figures": 1,
    "defense": 4,
    "resist": 5,
    "hp": 14,
    "melee": 8,
    "moves": 3,
    "thrown_breath_type": "thrown",
    "thrown_breath": 5,
    "abilities": [
      "Hero",
      "Cold Immunity"
    ],
    "cost": 100,
    "upkeep": 2
  },
  "3": {
    "id": 3,
    "templateId": 2,
    "heroTypeId": 2,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Sage",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 4,
    "resist": 6,
    "hp": 10,
    "melee": 1,
    "ranged": 10,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(S)",
    "abilities": [
      "Hero"
    ],
    "cost": 200,
    "upkeep": 3
  },
  "4": {
    "id": 4,
    "templateId": 3,
    "heroTypeId": 3,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Dervish",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 5,
    "hp": 11,
    "melee": 8,
    "ranged": 8,
    "moves": 3,
    "ammo": 8,
    "ranged_type": "Missile",
    "abilities": [
      "Hero"
    ],
    "cost": 200,
    "upkeep": 2
  },
  "5": {
    "id": 5,
    "templateId": 4,
    "heroTypeId": 4,
    "isHero": true,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Beastmaster",
    "race": "Beastmen",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 6,
    "hp": 12,
    "melee": 7,
    "ranged": 9,
    "moves": 3,
    "ammo": 8,
    "ranged_type": "Missile",
    "abilities": [
      "Hero"
    ],
    "cost": 200,
    "upkeep": 4
  },
  "6": {
    "id": 6,
    "templateId": 5,
    "heroTypeId": 5,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Bard",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 6,
    "hp": 11,
    "melee": 8,
    "moves": 3,
    "spec_att_attrib": 1,
    "abilities": [
      "Hero",
      "Holy Bonus"
    ],
    "cost": 200,
    "upkeep": 4
  },
  "7": {
    "id": 7,
    "templateId": 6,
    "heroTypeId": 6,
    "isHero": true,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Orc Archer",
    "race": "Orc",
    "category": "Heroes",
    "figures": 1,
    "defense": 6,
    "resist": 7,
    "hp": 12,
    "melee": 7,
    "ranged": 7,
    "moves": 3,
    "ammo": 8,
    "ranged_type": "Missile",
    "abilities": [
      "Hero"
    ],
    "cost": 200,
    "upkeep": 4
  },
  "8": {
    "id": 8,
    "templateId": 7,
    "heroTypeId": 7,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Healer",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 6,
    "resist": 8,
    "hp": 10,
    "melee": 3,
    "ranged": 10,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Hero",
      "Healer"
    ],
    "cost": 200,
    "upkeep": 4
  },
  "9": {
    "id": 9,
    "templateId": 8,
    "heroTypeId": 8,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Huntress",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 5,
    "hp": 12,
    "melee": 4,
    "ranged": 12,
    "moves": 3,
    "ammo": 8,
    "ranged_type": "Missile",
    "abilities": [
      "Hero"
    ],
    "cost": 200,
    "upkeep": 2
  },
  "10": {
    "id": 10,
    "templateId": 9,
    "heroTypeId": 9,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Thief",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 4,
    "resist": 5,
    "hp": 12,
    "melee": 9,
    "moves": 4,
    "abilities": [
      "Hero"
    ],
    "cost": 500,
    "upkeep": 8
  },
  "11": {
    "id": 11,
    "templateId": 10,
    "heroTypeId": 10,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Druid",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 5,
    "hp": 10,
    "melee": 1,
    "ranged": 10,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Hero",
      "Purify"
    ],
    "cost": 200,
    "upkeep": 2
  },
  "12": {
    "id": 12,
    "templateId": 11,
    "heroTypeId": 11,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "War Monk",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 6,
    "resist": 5,
    "hp": 11,
    "melee": 10,
    "moves": 3,
    "abilities": [
      "Hero"
    ],
    "cost": 400,
    "upkeep": 6
  },
  "13": {
    "id": 13,
    "templateId": 12,
    "heroTypeId": 12,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Warrior Mage",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 6,
    "resist": 5,
    "hp": 12,
    "melee": 8,
    "ranged": 8,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Hero"
    ],
    "cost": 200,
    "upkeep": 4
  },
  "14": {
    "id": 14,
    "templateId": 13,
    "heroTypeId": 13,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Magician",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 8,
    "hp": 10,
    "melee": 1,
    "ranged": 12,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Hero",
      "Missile Immunity",
      "Destruction"
    ],
    "cost": 600,
    "upkeep": 10
  },
  "15": {
    "id": 15,
    "templateId": 14,
    "heroTypeId": 14,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Assassin",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 5,
    "hp": 12,
    "melee": 10,
    "moves": 4,
    "spec_att_attrib": 9,
    "abilities": [
      "Hero",
      "First Strike",
      "Poison Touch"
    ],
    "cost": 400,
    "upkeep": 6
  },
  "16": {
    "id": 16,
    "templateId": 15,
    "heroTypeId": 15,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Wind Mage",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 5,
    "hp": 10,
    "melee": 1,
    "ranged": 10,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(S)",
    "abilities": [
      "Hero",
      "Wind Walking",
      "Missile Immunity"
    ],
    "cost": 500,
    "upkeep": 10
  },
  "17": {
    "id": 17,
    "templateId": 16,
    "heroTypeId": 16,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Ranger",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 6,
    "hp": 13,
    "melee": 8,
    "ranged": 9,
    "moves": 3,
    "ammo": 8,
    "ranged_type": "Missile",
    "abilities": [
      "Hero",
      "Poison Immunity"
    ],
    "cost": 400,
    "upkeep": 6
  },
  "18": {
    "id": 18,
    "templateId": 17,
    "heroTypeId": 17,
    "isHero": true,
    "baseRace": "Draconian",
    "baseFantastic": false,
    "name": "Draconian",
    "race": "Draconian",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 6,
    "hp": 13,
    "melee": 10,
    "moves": 3,
    "thrown_breath_type": "fire",
    "thrown_breath": 5,
    "abilities": [
      "Hero",
      "Flight"
    ],
    "cost": 400,
    "upkeep": 8
  },
  "19": {
    "id": 19,
    "templateId": 18,
    "heroTypeId": 18,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Witch",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 5,
    "hp": 10,
    "melee": 1,
    "ranged": 12,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Hero",
      "Missile Immunity"
    ],
    "cost": 500,
    "upkeep": 8
  },
  "20": {
    "id": 20,
    "templateId": 19,
    "heroTypeId": 19,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Golden One",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 7,
    "resist": 9,
    "hp": 11,
    "melee": 10,
    "ranged": 10,
    "moves": 3,
    "ammo": 8,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Hero"
    ],
    "cost": 400,
    "upkeep": 10
  },
  "21": {
    "id": 21,
    "templateId": 20,
    "heroTypeId": 20,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Ninja",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 6,
    "resist": 5,
    "hp": 12,
    "melee": 10,
    "moves": 3,
    "abilities": [
      "Hero",
      "Invisibility"
    ],
    "cost": 600,
    "upkeep": 10
  },
  "22": {
    "id": 22,
    "templateId": 21,
    "heroTypeId": 21,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Rogue",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 6,
    "resist": 5,
    "hp": 13,
    "melee": 11,
    "moves": 3,
    "abilities": [
      "Hero"
    ],
    "cost": 250,
    "upkeep": 6
  },
  "23": {
    "id": 23,
    "templateId": 22,
    "heroTypeId": 22,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Amazon",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 5,
    "hp": 12,
    "melee": 10,
    "moves": 3,
    "thrown_breath_type": "thrown",
    "thrown_breath": 4,
    "abilities": [
      "Hero"
    ],
    "cost": 600,
    "upkeep": 10
  },
  "24": {
    "id": 24,
    "templateId": 23,
    "heroTypeId": 23,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Warlock",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 5,
    "resist": 8,
    "hp": 10,
    "melee": 1,
    "ranged": 12,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Hero",
      "Missile Immunity"
    ],
    "cost": 600,
    "upkeep": 10
  },
  "25": {
    "id": 25,
    "templateId": 24,
    "heroTypeId": 24,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Unknown",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 6,
    "resist": 8,
    "hp": 13,
    "melee": 9,
    "ranged": 9,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Hero"
    ],
    "cost": 600,
    "upkeep": 10
  },
  "26": {
    "id": 26,
    "templateId": 25,
    "heroTypeId": 25,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Illusionist",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 6,
    "resist": 6,
    "hp": 10,
    "melee": 1,
    "ranged": 9,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(S)",
    "abilities": [
      "Hero",
      "Land Corruption",
      "Missile Immunity",
      "Illusion"
    ],
    "cost": 999,
    "upkeep": 12
  },
  "27": {
    "id": 27,
    "templateId": 26,
    "heroTypeId": 26,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Swordsman",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 7,
    "resist": 6,
    "hp": 15,
    "melee": 10,
    "moves": 3,
    "abilities": [
      "Hero"
    ],
    "cost": 999,
    "upkeep": 12
  },
  "28": {
    "id": 28,
    "templateId": 27,
    "heroTypeId": 27,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Priestess",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 7,
    "resist": 8,
    "hp": 10,
    "melee": 2,
    "ranged": 12,
    "moves": 3,
    "ammo": 9,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Hero",
      "Healer",
      "Purify"
    ],
    "cost": 999,
    "upkeep": 12
  },
  "29": {
    "id": 29,
    "templateId": 28,
    "heroTypeId": 28,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Paladin",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 7,
    "resist": 6,
    "hp": 13,
    "melee": 11,
    "moves": 3,
    "abilities": [
      "Hero",
      "Healer",
      "Illusion Immunity",
      "Armor Piercing",
      "First Strike"
    ],
    "cost": 999,
    "upkeep": 12
  },
  "30": {
    "id": 30,
    "templateId": 29,
    "heroTypeId": 29,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Black Knight",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 7,
    "resist": 6,
    "hp": 15,
    "melee": 11,
    "moves": 3,
    "abilities": [
      "Hero",
      "Death Immunity",
      "Armor Piercing",
      "First Strike"
    ],
    "cost": 999,
    "upkeep": 12
  },
  "31": {
    "id": 31,
    "templateId": 30,
    "heroTypeId": 30,
    "isHero": true,
    "baseRace": "High Elf",
    "baseFantastic": false,
    "name": "Elven Archer",
    "race": "High Elf",
    "category": "Heroes",
    "figures": 1,
    "defense": 8,
    "resist": 8,
    "hp": 11,
    "melee": 5,
    "ranged": 12,
    "to_hit": 10,
    "moves": 3,
    "ammo": 8,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Hero"
    ],
    "cost": 999,
    "upkeep": 12
  },
  "32": {
    "id": 32,
    "templateId": 31,
    "heroTypeId": 31,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Knight",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 7,
    "resist": 6,
    "hp": 18,
    "melee": 12,
    "moves": 3,
    "abilities": [
      "Hero",
      "Negate First Strike"
    ],
    "cost": 999,
    "upkeep": 12
  },
  "33": {
    "id": 33,
    "templateId": 32,
    "heroTypeId": 32,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Necromancer",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 7,
    "resist": 8,
    "hp": 10,
    "melee": 1,
    "ranged": 11,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(C)",
    "spec_att_attrib": 3,
    "abilities": [
      "Hero",
      "Missile Immunity",
      "Illusion Immunity",
      "Death Immunity",
      "Life Steal"
    ],
    "cost": 999,
    "upkeep": 12
  },
  "34": {
    "id": 34,
    "templateId": 33,
    "heroTypeId": 33,
    "isHero": true,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Chaos Warrior",
    "race": "High Men",
    "category": "Heroes",
    "figures": 1,
    "defense": 7,
    "resist": 7,
    "hp": 13,
    "melee": 12,
    "ranged": 12,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Hero",
      "Armor Piercing"
    ],
    "cost": 999,
    "upkeep": 12
  },
  "35": {
    "id": 35,
    "templateId": 34,
    "heroTypeId": 34,
    "isHero": true,
    "baseRace": "Life",
    "baseFantastic": false,
    "name": "Chosen",
    "race": "Life",
    "category": "Heroes",
    "figures": 1,
    "defense": 8,
    "resist": 12,
    "hp": 13,
    "melee": 12,
    "moves": 4,
    "spec_att_attrib": 1,
    "abilities": [
      "Hero",
      "Holy Bonus"
    ],
    "cost": 230,
    "upkeep": 12
  },
  "36": {
    "id": 36,
    "templateId": 35,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Generic",
    "baseFantastic": false,
    "name": "Trireme",
    "race": "Generic",
    "category": "Generic",
    "figures": 1,
    "defense": 4,
    "resist": 6,
    "hp": 15,
    "melee": 12,
    "moves": 3,
    "cost": 60
  },
  "37": {
    "id": 37,
    "templateId": 36,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Generic",
    "baseFantastic": false,
    "name": "Galley",
    "race": "Generic",
    "category": "Generic",
    "figures": 1,
    "defense": 4,
    "resist": 7,
    "hp": 20,
    "melee": 14,
    "ranged": 10,
    "moves": 3,
    "ammo": 8,
    "ranged_type": "Missile",
    "cost": 100
  },
  "38": {
    "id": 38,
    "templateId": 37,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Generic",
    "baseFantastic": false,
    "name": "Catapult",
    "race": "Generic",
    "category": "Generic",
    "figures": 1,
    "defense": 2,
    "resist": 3,
    "hp": 10,
    "melee": 0,
    "ranged": 9,
    "to_hit": 20,
    "moves": 1,
    "ammo": 10,
    "ranged_type": "Boulder",
    "abilities": [
      "Wall Crusher",
      "Long Range"
    ],
    "cost": 62,
    "upkeep": 1
  },
  "39": {
    "id": 39,
    "templateId": 38,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Generic",
    "baseFantastic": false,
    "name": "Warship",
    "race": "Generic",
    "category": "Generic",
    "figures": 1,
    "defense": 5,
    "resist": 7,
    "hp": 25,
    "melee": 16,
    "ranged": 14,
    "moves": 4,
    "ammo": 10,
    "ranged_type": "Boulder",
    "abilities": [
      "Long Range"
    ],
    "cost": 140
  },
  "40": {
    "id": 40,
    "templateId": 39,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Lizardman",
    "baseFantastic": false,
    "name": "Carrack",
    "race": "Lizardman",
    "category": "Lizardman",
    "figures": 1,
    "defense": 4,
    "resist": 6,
    "hp": 15,
    "melee": 14,
    "ranged": 8,
    "moves": 4,
    "ammo": 6,
    "ranged_type": "Missile",
    "cost": 80
  },
  "41": {
    "id": 41,
    "templateId": 40,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Barbarian",
    "baseFantastic": false,
    "name": "Barbarian Swordsmen",
    "race": "Barbarian",
    "category": "Barbarian",
    "figures": 6,
    "defense": 3,
    "resist": 3,
    "hp": 1,
    "melee": 3,
    "to_hit": 10,
    "moves": 2,
    "thrown_breath_type": "thrown",
    "thrown_breath": 2,
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "42": {
    "id": 42,
    "templateId": 41,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Barbarian",
    "baseFantastic": false,
    "name": "Barbarian Bowmen",
    "race": "Barbarian",
    "category": "Barbarian",
    "figures": 6,
    "defense": 1,
    "resist": 3,
    "hp": 1,
    "melee": 1,
    "ranged": 3,
    "to_hit": 10,
    "moves": 2,
    "ammo": 8,
    "ranged_type": "Missile",
    "cost": 30,
    "upkeep": 1
  },
  "43": {
    "id": 43,
    "templateId": 42,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Barbarian",
    "baseFantastic": false,
    "name": "Barbarian Cavalry",
    "race": "Barbarian",
    "category": "Barbarian",
    "figures": 4,
    "defense": 2,
    "resist": 3,
    "hp": 3,
    "melee": 5,
    "to_hit": 10,
    "moves": 5,
    "thrown_breath_type": "thrown",
    "thrown_breath": 3,
    "abilities": [
      "First Strike"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "44": {
    "id": 44,
    "templateId": 43,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Barbarian",
    "baseFantastic": false,
    "name": "Barbarian Shaman",
    "race": "Barbarian",
    "category": "Barbarian",
    "figures": 4,
    "defense": 3,
    "resist": 5,
    "hp": 1,
    "melee": 2,
    "ranged": 3,
    "to_hit": 10,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Healing Spell",
      "Healer",
      "Purify"
    ],
    "cost": 50,
    "upkeep": 2
  },
  "45": {
    "id": 45,
    "templateId": 45,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Barbarian",
    "baseFantastic": false,
    "name": "Berserkers",
    "race": "Barbarian",
    "category": "Barbarian",
    "figures": 6,
    "defense": 3,
    "resist": 3,
    "hp": 3,
    "melee": 7,
    "to_hit": 10,
    "moves": 3,
    "thrown_breath_type": "thrown",
    "thrown_breath": 3,
    "cost": 100,
    "upkeep": 2
  },
  "46": {
    "id": 46,
    "templateId": 46,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Beastmen Spearmen",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 6,
    "defense": 1,
    "resist": 3,
    "hp": 2,
    "melee": 3,
    "moves": 2,
    "cost": 10
  },
  "47": {
    "id": 47,
    "templateId": 47,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Beastmen Swordsmen",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 6,
    "defense": 3,
    "resist": 4,
    "hp": 2,
    "melee": 4,
    "moves": 2,
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "48": {
    "id": 48,
    "templateId": 48,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Beastmen Halberdiers",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 6,
    "defense": 4,
    "resist": 5,
    "hp": 3,
    "melee": 6,
    "moves": 2,
    "abilities": [
      "Negate First Strike"
    ],
    "cost": 60,
    "upkeep": 2
  },
  "49": {
    "id": 49,
    "templateId": 49,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Beastmen Bowmen",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 6,
    "defense": 1,
    "resist": 4,
    "hp": 2,
    "melee": 2,
    "ranged": 3,
    "moves": 2,
    "ammo": 8,
    "ranged_type": "Missile",
    "cost": 30,
    "upkeep": 1
  },
  "50": {
    "id": 50,
    "templateId": 50,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Beastmen Priests",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 4,
    "defense": 4,
    "resist": 8,
    "hp": 3,
    "melee": 4,
    "ranged": 5,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Healing Spell",
      "Healer",
      "Purify"
    ],
    "cost": 100,
    "upkeep": 3
  },
  "51": {
    "id": 51,
    "templateId": 51,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Beastmen Magicians",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 4,
    "defense": 3,
    "resist": 8,
    "hp": 2,
    "melee": 2,
    "ranged": 7,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Caster 20 MP",
      "Missile Immunity"
    ],
    "cost": 120,
    "upkeep": 3
  },
  "52": {
    "id": 52,
    "templateId": 52,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Beastmen Engineers",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 6,
    "defense": 1,
    "resist": 4,
    "hp": 2,
    "melee": 2,
    "moves": 1,
    "abilities": [
      "Wall Crusher"
    ],
    "cost": 30,
    "upkeep": 1
  },
  "53": {
    "id": 53,
    "templateId": 54,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Centaurs",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 4,
    "defense": 3,
    "resist": 5,
    "hp": 4,
    "melee": 5,
    "ranged": 5,
    "moves": 4,
    "ammo": 6,
    "ranged_type": "Missile",
    "cost": 90,
    "upkeep": 2
  },
  "54": {
    "id": 54,
    "templateId": 55,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Manticores",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 3,
    "defense": 3,
    "resist": 8,
    "hp": 6,
    "melee": 7,
    "ranged": 1,
    "to_hit": 10,
    "moves": 3,
    "ammo": 2,
    "ranged_type": "Missile",
    "spec_att_attrib": 4,
    "abilities": [
      "Weapon Immunity",
      "Flight",
      "Poison Touch"
    ],
    "cost": 160,
    "upkeep": 2
  },
  "55": {
    "id": 55,
    "templateId": 56,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Beastmen",
    "baseFantastic": false,
    "name": "Minotaurs",
    "race": "Beastmen",
    "category": "Beastmen",
    "figures": 2,
    "defense": 5,
    "resist": 7,
    "hp": 12,
    "melee": 12,
    "to_hit": 20,
    "moves": 3,
    "abilities": [
      "Large Shield"
    ],
    "cost": 200,
    "upkeep": 5
  },
  "56": {
    "id": 56,
    "templateId": 57,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dark Elf",
    "baseFantastic": false,
    "name": "Dark Elf Spearmen",
    "race": "Dark Elf",
    "category": "Dark Elf",
    "figures": 6,
    "defense": 1,
    "resist": 5,
    "hp": 1,
    "melee": 2,
    "ranged": 1,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "cost": 10
  },
  "57": {
    "id": 57,
    "templateId": 58,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dark Elf",
    "baseFantastic": false,
    "name": "Dark Elf Swordsmen",
    "race": "Dark Elf",
    "category": "Dark Elf",
    "figures": 6,
    "defense": 3,
    "resist": 6,
    "hp": 1,
    "melee": 3,
    "ranged": 2,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "58": {
    "id": 58,
    "templateId": 59,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dark Elf",
    "baseFantastic": false,
    "name": "Dark Elf Halberdiers",
    "race": "Dark Elf",
    "category": "Dark Elf",
    "figures": 6,
    "defense": 4,
    "resist": 7,
    "hp": 2,
    "melee": 5,
    "ranged": 3,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "cost": 60,
    "upkeep": 2
  },
  "59": {
    "id": 59,
    "templateId": 60,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dark Elf",
    "baseFantastic": false,
    "name": "Dark Elf Cavalry",
    "race": "Dark Elf",
    "category": "Dark Elf",
    "figures": 4,
    "defense": 2,
    "resist": 6,
    "hp": 3,
    "melee": 5,
    "ranged": 3,
    "moves": 5,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "First Strike"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "60": {
    "id": 60,
    "templateId": 61,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dark Elf",
    "baseFantastic": false,
    "name": "Dark Elf Priests",
    "race": "Dark Elf",
    "category": "Dark Elf",
    "figures": 4,
    "defense": 4,
    "resist": 10,
    "hp": 2,
    "melee": 3,
    "ranged": 7,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Healing Spell",
      "Healer",
      "Purify"
    ],
    "cost": 120,
    "upkeep": 3
  },
  "61": {
    "id": 61,
    "templateId": 62,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dark Elf",
    "baseFantastic": false,
    "name": "Apprentices",
    "race": "Dark Elf",
    "category": "Dark Elf",
    "figures": 6,
    "defense": 2,
    "resist": 6,
    "hp": 1,
    "melee": 2,
    "ranged": 3,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Caster 20 MP",
      "Caster 40 MP",
      "Large Shield"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "62": {
    "id": 62,
    "templateId": 63,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dark Elf",
    "baseFantastic": false,
    "name": "Nightblades",
    "race": "Dark Elf",
    "category": "Dark Elf",
    "figures": 6,
    "defense": 4,
    "resist": 7,
    "hp": 3,
    "melee": 5,
    "moves": 2,
    "spec_att_attrib": 2,
    "abilities": [
      "Invisibility",
      "Poison Touch"
    ],
    "cost": 150,
    "upkeep": 4
  },
  "63": {
    "id": 63,
    "templateId": 64,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dark Elf",
    "baseFantastic": false,
    "name": "Warlocks",
    "race": "Dark Elf",
    "category": "Dark Elf",
    "figures": 4,
    "defense": 4,
    "resist": 9,
    "hp": 1,
    "melee": 1,
    "ranged": 9,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Doombolt Spell",
      "Missile Immunity"
    ],
    "cost": 160,
    "upkeep": 3
  },
  "64": {
    "id": 64,
    "templateId": 65,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dark Elf",
    "baseFantastic": false,
    "name": "Nightmares",
    "race": "Dark Elf",
    "category": "Dark Elf",
    "figures": 2,
    "defense": 4,
    "resist": 12,
    "hp": 8,
    "melee": 8,
    "ranged": 8,
    "to_hit": 20,
    "moves": 4,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Flight"
    ],
    "cost": 200,
    "upkeep": 5
  },
  "65": {
    "id": 65,
    "templateId": 66,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Draconian",
    "baseFantastic": false,
    "name": "Draconian Spearmen",
    "race": "Draconian",
    "category": "Draconian",
    "figures": 6,
    "defense": 2,
    "resist": 4,
    "hp": 1,
    "melee": 2,
    "moves": 2,
    "thrown_breath_type": "fire",
    "thrown_breath": 1,
    "abilities": [
      "Flight"
    ],
    "cost": 10
  },
  "66": {
    "id": 66,
    "templateId": 67,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Draconian",
    "baseFantastic": false,
    "name": "Draconian Swordsmen",
    "race": "Draconian",
    "category": "Draconian",
    "figures": 6,
    "defense": 4,
    "resist": 5,
    "hp": 1,
    "melee": 3,
    "moves": 2,
    "thrown_breath_type": "fire",
    "thrown_breath": 2,
    "abilities": [
      "Flight",
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "67": {
    "id": 67,
    "templateId": 68,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Draconian",
    "baseFantastic": false,
    "name": "Draconian Halberdiers",
    "race": "Draconian",
    "category": "Draconian",
    "figures": 6,
    "defense": 5,
    "resist": 6,
    "hp": 2,
    "melee": 5,
    "moves": 2,
    "thrown_breath_type": "fire",
    "thrown_breath": 3,
    "abilities": [
      "Flight"
    ],
    "cost": 60,
    "upkeep": 2
  },
  "68": {
    "id": 68,
    "templateId": 69,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Draconian",
    "baseFantastic": false,
    "name": "Draconian Bowmen",
    "race": "Draconian",
    "category": "Draconian",
    "figures": 5,
    "defense": 1,
    "resist": 5,
    "hp": 1,
    "melee": 1,
    "ranged": 3,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Missile",
    "abilities": [
      "Flight"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "69": {
    "id": 69,
    "templateId": 70,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Draconian",
    "baseFantastic": false,
    "name": "Saints",
    "race": "Draconian",
    "category": "Draconian",
    "figures": 5,
    "defense": 5,
    "resist": 7,
    "hp": 2,
    "melee": 2,
    "ranged": 4,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Flight",
      "Healing Spell",
      "Healer",
      "Purify"
    ],
    "cost": 100,
    "upkeep": 2
  },
  "70": {
    "id": 70,
    "templateId": 71,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Draconian",
    "baseFantastic": false,
    "name": "Draconian Magicians",
    "race": "Draconian",
    "category": "Draconian",
    "figures": 4,
    "defense": 4,
    "resist": 9,
    "hp": 1,
    "melee": 1,
    "ranged": 7,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Flight",
      "Caster 20 MP",
      "Missile Immunity"
    ],
    "cost": 120,
    "upkeep": 3
  },
  "71": {
    "id": 71,
    "templateId": 72,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Horde",
    "race": "Orc",
    "category": "Orc",
    "figures": 8,
    "defense": 5,
    "resist": 5,
    "hp": 2,
    "melee": 6,
    "moves": 2,
    "abilities": [
      "Large Shield",
      "Negate First Strike"
    ],
    "cost": 75,
    "upkeep": 1
  },
  "72": {
    "id": 72,
    "templateId": 74,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Draconian",
    "baseFantastic": false,
    "name": "Doom Drakes",
    "race": "Draconian",
    "category": "Draconian",
    "figures": 2,
    "defense": 5,
    "resist": 7,
    "hp": 10,
    "melee": 10,
    "moves": 5,
    "thrown_breath_type": "fire",
    "thrown_breath": 7,
    "abilities": [
      "Flight",
      "Cause Fear"
    ],
    "cost": 210,
    "upkeep": 5
  },
  "73": {
    "id": 73,
    "templateId": 75,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Draconian",
    "baseFantastic": false,
    "name": "Air Ship",
    "race": "Draconian",
    "category": "Draconian",
    "figures": 1,
    "defense": 5,
    "resist": 8,
    "hp": 20,
    "melee": 5,
    "ranged": 15,
    "moves": 4,
    "ammo": 10,
    "ranged_type": "Boulder",
    "abilities": [
      "Flight",
      "Wall Crusher",
      "Wind Walking"
    ],
    "cost": 200,
    "upkeep": 4
  },
  "74": {
    "id": 74,
    "templateId": 76,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dwarven",
    "baseFantastic": false,
    "name": "Dwarven Swordsmen",
    "race": "Dwarven",
    "category": "Dwarven",
    "figures": 6,
    "defense": 3,
    "resist": 6,
    "hp": 2,
    "melee": 3,
    "moves": 2,
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "75": {
    "id": 75,
    "templateId": 77,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dwarven",
    "baseFantastic": false,
    "name": "Dwarven Halberdiers",
    "race": "Dwarven",
    "category": "Dwarven",
    "figures": 6,
    "defense": 4,
    "resist": 7,
    "hp": 3,
    "melee": 5,
    "moves": 2,
    "abilities": [
      "Negate First Strike"
    ],
    "cost": 60,
    "upkeep": 2
  },
  "76": {
    "id": 76,
    "templateId": 78,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dwarven",
    "baseFantastic": false,
    "name": "Dwarven Engineers",
    "race": "Dwarven",
    "category": "Dwarven",
    "figures": 6,
    "defense": 1,
    "resist": 8,
    "hp": 2,
    "melee": 1,
    "moves": 1,
    "abilities": [
      "Wall Crusher"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "77": {
    "id": 77,
    "templateId": 79,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dwarven",
    "baseFantastic": false,
    "name": "Hammerhands",
    "race": "Dwarven",
    "category": "Dwarven",
    "figures": 6,
    "defense": 4,
    "resist": 10,
    "hp": 4,
    "melee": 8,
    "moves": 2,
    "cost": 140,
    "upkeep": 4
  },
  "78": {
    "id": 78,
    "templateId": 80,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dwarven",
    "baseFantastic": false,
    "name": "Steam Cannon",
    "race": "Dwarven",
    "category": "Dwarven",
    "figures": 1,
    "defense": 5,
    "resist": 9,
    "hp": 12,
    "melee": 0,
    "ranged": 15,
    "moves": 1,
    "ammo": 10,
    "ranged_type": "Boulder",
    "abilities": [
      "Wall Crusher",
      "Long Range",
      "Poison Immunity"
    ],
    "cost": 100,
    "upkeep": 2
  },
  "79": {
    "id": 79,
    "templateId": 81,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Dwarven",
    "baseFantastic": false,
    "name": "Golem",
    "race": "Dwarven",
    "category": "Dwarven",
    "figures": 1,
    "defense": 7,
    "resist": 15,
    "hp": 20,
    "melee": 14,
    "moves": 3,
    "abilities": [
      "Wall Crusher",
      "Fire Immunity",
      "Stoning Immunity",
      "Cold Immunity",
      "Death Immunity",
      "Poison Immunity"
    ],
    "cost": 180,
    "upkeep": 5
  },
  "80": {
    "id": 80,
    "templateId": 82,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Barbarian",
    "baseFantastic": false,
    "name": "Barbarian Spearmen",
    "race": "Barbarian",
    "category": "Barbarian",
    "figures": 6,
    "defense": 1,
    "resist": 2,
    "hp": 1,
    "melee": 2,
    "to_hit": 10,
    "moves": 2,
    "thrown_breath_type": "thrown",
    "thrown_breath": 1,
    "cost": 10
  },
  "81": {
    "id": 81,
    "templateId": 83,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Gnoll",
    "baseFantastic": false,
    "name": "Gnoll Spearmen",
    "race": "Gnoll",
    "category": "Gnoll",
    "figures": 6,
    "defense": 1,
    "resist": 3,
    "hp": 1,
    "melee": 4,
    "moves": 3,
    "cost": 10
  },
  "82": {
    "id": 82,
    "templateId": 84,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Gnoll",
    "baseFantastic": false,
    "name": "Gnoll Swordsmen",
    "race": "Gnoll",
    "category": "Gnoll",
    "figures": 6,
    "defense": 3,
    "resist": 4,
    "hp": 1,
    "melee": 5,
    "moves": 3,
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "83": {
    "id": 83,
    "templateId": 85,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Gnoll",
    "baseFantastic": false,
    "name": "Gnoll Halberdiers",
    "race": "Gnoll",
    "category": "Gnoll",
    "figures": 6,
    "defense": 4,
    "resist": 5,
    "hp": 2,
    "melee": 7,
    "moves": 3,
    "abilities": [
      "Negate First Strike"
    ],
    "cost": 60,
    "upkeep": 2
  },
  "84": {
    "id": 84,
    "templateId": 86,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Gnoll",
    "baseFantastic": false,
    "name": "Jackal Riders",
    "race": "Gnoll",
    "category": "Gnoll",
    "figures": 8,
    "defense": 3,
    "resist": 5,
    "hp": 3,
    "melee": 6,
    "moves": 4,
    "abilities": [
      "Cause Fear"
    ],
    "cost": 150,
    "upkeep": 2
  },
  "85": {
    "id": 85,
    "templateId": 87,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Barbarian",
    "baseFantastic": false,
    "name": "Gladiators",
    "race": "Barbarian",
    "category": "Barbarian",
    "figures": 3,
    "defense": 6,
    "resist": 5,
    "hp": 6,
    "melee": 5,
    "to_hit": 20,
    "moves": 3,
    "thrown_breath_type": "thrown",
    "thrown_breath": 4,
    "abilities": [
      "Large Shield"
    ],
    "cost": 120,
    "upkeep": 3
  },
  "86": {
    "id": 86,
    "templateId": 88,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Gnoll",
    "baseFantastic": false,
    "name": "Wolf Riders",
    "race": "Gnoll",
    "category": "Gnoll",
    "figures": 4,
    "defense": 3,
    "resist": 5,
    "hp": 5,
    "melee": 7,
    "moves": 5,
    "cost": 80,
    "upkeep": 2
  },
  "87": {
    "id": 87,
    "templateId": 89,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Halfling",
    "baseFantastic": false,
    "name": "Halfling Spearmen",
    "race": "Halfling",
    "category": "Halfling",
    "figures": 8,
    "defense": 1,
    "resist": 3,
    "hp": 1,
    "melee": 1,
    "moves": 2,
    "abilities": [
      "Lucky"
    ],
    "cost": 15
  },
  "88": {
    "id": 88,
    "templateId": 90,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Halfling",
    "baseFantastic": false,
    "name": "Halfling Swordsmen",
    "race": "Halfling",
    "category": "Halfling",
    "figures": 8,
    "defense": 3,
    "resist": 4,
    "hp": 1,
    "melee": 2,
    "moves": 2,
    "abilities": [
      "Lucky",
      "Large Shield"
    ],
    "cost": 36,
    "upkeep": 1
  },
  "89": {
    "id": 89,
    "templateId": 91,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Halfling",
    "baseFantastic": false,
    "name": "Halfling Magicians",
    "race": "Halfling",
    "category": "Halfling",
    "figures": 4,
    "defense": 3,
    "resist": 8,
    "hp": 1,
    "melee": 1,
    "ranged": 7,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Lucky",
      "Caster 20 MP",
      "Missile Immunity"
    ],
    "cost": 150,
    "upkeep": 3
  },
  "90": {
    "id": 90,
    "templateId": 92,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Halfling",
    "baseFantastic": false,
    "name": "Halfling Shaman",
    "race": "Halfling",
    "category": "Halfling",
    "figures": 4,
    "defense": 3,
    "resist": 6,
    "hp": 1,
    "melee": 1,
    "ranged": 3,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Lucky",
      "Healing Spell",
      "Healer",
      "Purify"
    ],
    "cost": 75,
    "upkeep": 2
  },
  "91": {
    "id": 91,
    "templateId": 93,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Barbarian",
    "baseFantastic": false,
    "name": "Spellserkers",
    "race": "Barbarian",
    "category": "Barbarian",
    "figures": 4,
    "defense": 4,
    "resist": 6,
    "hp": 4,
    "melee": 3,
    "to_hit": 10,
    "moves": 3,
    "thrown_breath_type": "thrown",
    "thrown_breath": 5,
    "abilities": [
      "Caster 20 MP",
      "Missile Immunity"
    ],
    "cost": 120,
    "upkeep": 3
  },
  "92": {
    "id": 92,
    "templateId": 94,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Halfling",
    "baseFantastic": false,
    "name": "Slingers",
    "race": "Halfling",
    "category": "Halfling",
    "figures": 8,
    "defense": 1,
    "resist": 4,
    "hp": 1,
    "melee": 1,
    "ranged": 4,
    "moves": 2,
    "ammo": 6,
    "ranged_type": "Missile",
    "abilities": [
      "Lucky"
    ],
    "cost": 100,
    "upkeep": 1
  },
  "93": {
    "id": 93,
    "templateId": 95,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Elf",
    "baseFantastic": false,
    "name": "High Elf Spearmen",
    "race": "High Elf",
    "category": "High Elf",
    "figures": 6,
    "defense": 1,
    "resist": 4,
    "hp": 1,
    "melee": 2,
    "to_hit": 10,
    "moves": 2,
    "cost": 10
  },
  "94": {
    "id": 94,
    "templateId": 96,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Elf",
    "baseFantastic": false,
    "name": "High Elf Swordsmen",
    "race": "High Elf",
    "category": "High Elf",
    "figures": 6,
    "defense": 3,
    "resist": 5,
    "hp": 1,
    "melee": 3,
    "to_hit": 10,
    "moves": 2,
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "95": {
    "id": 95,
    "templateId": 97,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Elf",
    "baseFantastic": false,
    "name": "High Elf Halberdiers",
    "race": "High Elf",
    "category": "High Elf",
    "figures": 6,
    "defense": 4,
    "resist": 6,
    "hp": 2,
    "melee": 5,
    "to_hit": 10,
    "moves": 2,
    "abilities": [
      "Negate First Strike"
    ],
    "cost": 60,
    "upkeep": 2
  },
  "96": {
    "id": 96,
    "templateId": 98,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Elf",
    "baseFantastic": false,
    "name": "High Elf Cavalry",
    "race": "High Elf",
    "category": "High Elf",
    "figures": 4,
    "defense": 2,
    "resist": 5,
    "hp": 3,
    "melee": 5,
    "to_hit": 10,
    "moves": 5,
    "abilities": [
      "First Strike"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "97": {
    "id": 97,
    "templateId": 99,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Elf",
    "baseFantastic": false,
    "name": "High Elf Magicians",
    "race": "High Elf",
    "category": "High Elf",
    "figures": 4,
    "defense": 3,
    "resist": 9,
    "hp": 1,
    "melee": 1,
    "ranged": 7,
    "to_hit": 10,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Caster 20 MP",
      "Missile Immunity"
    ],
    "cost": 120,
    "upkeep": 3
  },
  "98": {
    "id": 98,
    "templateId": 101,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Elf",
    "baseFantastic": false,
    "name": "Longbowmen",
    "race": "High Elf",
    "category": "High Elf",
    "figures": 6,
    "defense": 2,
    "resist": 5,
    "hp": 1,
    "melee": 1,
    "ranged": 3,
    "to_hit": 10,
    "moves": 2,
    "ammo": 8,
    "ranged_type": "Missile",
    "abilities": [
      "Long Range"
    ],
    "cost": 50,
    "upkeep": 1
  },
  "99": {
    "id": 99,
    "templateId": 102,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Elf",
    "baseFantastic": false,
    "name": "Elven Lords",
    "race": "High Elf",
    "category": "High Elf",
    "figures": 4,
    "defense": 6,
    "resist": 10,
    "hp": 4,
    "melee": 5,
    "to_hit": 20,
    "moves": 4,
    "abilities": [
      "Poison Immunity",
      "Armor Piercing",
      "First Strike"
    ],
    "cost": 160,
    "upkeep": 4
  },
  "100": {
    "id": 100,
    "templateId": 103,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Elf",
    "baseFantastic": false,
    "name": "Pegasai",
    "race": "High Elf",
    "category": "High Elf",
    "figures": 4,
    "defense": 4,
    "resist": 8,
    "hp": 4,
    "melee": 4,
    "ranged": 3,
    "to_hit": 10,
    "moves": 5,
    "ammo": 8,
    "ranged_type": "Missile",
    "abilities": [
      "Flight"
    ],
    "cost": 120,
    "upkeep": 2
  },
  "101": {
    "id": 101,
    "templateId": 104,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "High Men Spearmen",
    "race": "High Men",
    "category": "High Men",
    "figures": 6,
    "defense": 1,
    "resist": 1,
    "hp": 1,
    "melee": 2,
    "moves": 2,
    "cost": 10
  },
  "102": {
    "id": 102,
    "templateId": 105,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "High Men Swordsmen",
    "race": "High Men",
    "category": "High Men",
    "figures": 6,
    "defense": 3,
    "resist": 2,
    "hp": 1,
    "melee": 3,
    "moves": 2,
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "103": {
    "id": 103,
    "templateId": 106,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "High Men Bowmen",
    "race": "High Men",
    "category": "High Men",
    "figures": 6,
    "defense": 1,
    "resist": 2,
    "hp": 1,
    "melee": 1,
    "ranged": 3,
    "moves": 2,
    "ammo": 8,
    "ranged_type": "Missile",
    "cost": 30,
    "upkeep": 1
  },
  "104": {
    "id": 104,
    "templateId": 107,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "High Men Cavalry",
    "race": "High Men",
    "category": "High Men",
    "figures": 4,
    "defense": 2,
    "resist": 2,
    "hp": 3,
    "melee": 5,
    "moves": 5,
    "abilities": [
      "First Strike"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "105": {
    "id": 105,
    "templateId": 108,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "High Men Priests",
    "race": "High Men",
    "category": "High Men",
    "figures": 4,
    "defense": 4,
    "resist": 6,
    "hp": 2,
    "melee": 3,
    "ranged": 5,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "spec_att_attrib": 1,
    "abilities": [
      "Healing Spell",
      "Resistance to All",
      "Healer",
      "Purify"
    ],
    "cost": 100,
    "upkeep": 3
  },
  "106": {
    "id": 106,
    "templateId": 109,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "High Men Magicians",
    "race": "High Men",
    "category": "High Men",
    "figures": 6,
    "defense": 3,
    "resist": 6,
    "hp": 1,
    "melee": 1,
    "ranged": 7,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Caster 20 MP",
      "Missile Immunity"
    ],
    "cost": 120,
    "upkeep": 3
  },
  "107": {
    "id": 107,
    "templateId": 110,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "High Men Engineers",
    "race": "High Men",
    "category": "High Men",
    "figures": 6,
    "defense": 1,
    "resist": 4,
    "hp": 1,
    "melee": 1,
    "moves": 1,
    "abilities": [
      "Wall Crusher"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "108": {
    "id": 108,
    "templateId": 111,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Crusaders",
    "race": "High Men",
    "category": "High Men",
    "figures": 8,
    "defense": 4,
    "resist": 6,
    "hp": 2,
    "melee": 5,
    "moves": 2,
    "abilities": [
      "Healing Spell",
      "Large Shield"
    ],
    "cost": 60,
    "upkeep": 2
  },
  "109": {
    "id": 109,
    "templateId": 112,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "High Men Pikemen",
    "race": "High Men",
    "category": "High Men",
    "figures": 8,
    "defense": 4,
    "resist": 4,
    "hp": 2,
    "melee": 4,
    "moves": 2,
    "abilities": [
      "Negate First Strike",
      "Armor Piercing"
    ],
    "cost": 75,
    "upkeep": 2
  },
  "110": {
    "id": 110,
    "templateId": 113,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Paladins",
    "race": "High Men",
    "category": "High Men",
    "figures": 4,
    "defense": 5,
    "resist": 8,
    "hp": 5,
    "melee": 6,
    "moves": 4,
    "spec_att_attrib": 1,
    "abilities": [
      "Holy Bonus",
      "Illusion Immunity",
      "Death Immunity",
      "Armor Piercing",
      "First Strike"
    ],
    "cost": 240,
    "upkeep": 5
  },
  "111": {
    "id": 111,
    "templateId": 114,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Klackon",
    "baseFantastic": false,
    "name": "Klackon Spearmen",
    "race": "Klackon",
    "category": "Klackon",
    "figures": 6,
    "defense": 3,
    "resist": 3,
    "hp": 1,
    "melee": 2,
    "moves": 2,
    "cost": 10
  },
  "112": {
    "id": 112,
    "templateId": 115,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Klackon",
    "baseFantastic": false,
    "name": "Klackon Swordsmen",
    "race": "Klackon",
    "category": "Klackon",
    "figures": 6,
    "defense": 5,
    "resist": 4,
    "hp": 1,
    "melee": 3,
    "moves": 2,
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "113": {
    "id": 113,
    "templateId": 116,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Klackon",
    "baseFantastic": false,
    "name": "Klackon Halberdiers",
    "race": "Klackon",
    "category": "Klackon",
    "figures": 6,
    "defense": 6,
    "resist": 5,
    "hp": 2,
    "melee": 5,
    "moves": 2,
    "abilities": [
      "Negate First Strike"
    ],
    "cost": 60,
    "upkeep": 2
  },
  "114": {
    "id": 114,
    "templateId": 117,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Klackon",
    "baseFantastic": false,
    "name": "Klackon Engineers",
    "race": "Klackon",
    "category": "Klackon",
    "figures": 6,
    "defense": 1,
    "resist": 4,
    "hp": 1,
    "melee": 1,
    "moves": 1,
    "abilities": [
      "Wall Crusher"
    ],
    "cost": 20,
    "upkeep": 1
  },
  "115": {
    "id": 115,
    "templateId": 118,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "High Men",
    "baseFantastic": false,
    "name": "Knights",
    "race": "High Men",
    "category": "High Men",
    "figures": 4,
    "defense": 5,
    "resist": 5,
    "hp": 3,
    "melee": 6,
    "moves": 5,
    "abilities": [
      "First Strike"
    ],
    "cost": 60,
    "upkeep": 3
  },
  "116": {
    "id": 116,
    "templateId": 119,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Klackon",
    "baseFantastic": false,
    "name": "Stag Beetle",
    "race": "Klackon",
    "category": "Klackon",
    "figures": 1,
    "defense": 7,
    "resist": 7,
    "hp": 20,
    "melee": 15,
    "moves": 4,
    "thrown_breath_type": "fire",
    "thrown_breath": 5,
    "cost": 160,
    "upkeep": 2
  },
  "117": {
    "id": 117,
    "templateId": 120,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Lizardman",
    "baseFantastic": false,
    "name": "Lizardman Spearmen",
    "race": "Lizardman",
    "category": "Lizardman",
    "figures": 6,
    "defense": 1,
    "resist": 2,
    "hp": 2,
    "melee": 2,
    "moves": 2,
    "cost": 10
  },
  "118": {
    "id": 118,
    "templateId": 121,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Lizardman",
    "baseFantastic": false,
    "name": "Lizardman Swordsmen",
    "race": "Lizardman",
    "category": "Lizardman",
    "figures": 6,
    "defense": 3,
    "resist": 3,
    "hp": 2,
    "melee": 3,
    "moves": 2,
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "119": {
    "id": 119,
    "templateId": 122,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Lizardman",
    "baseFantastic": false,
    "name": "Lizardman Halberdiers",
    "race": "Lizardman",
    "category": "Lizardman",
    "figures": 6,
    "defense": 4,
    "resist": 4,
    "hp": 3,
    "melee": 5,
    "moves": 2,
    "abilities": [
      "Negate First Strike"
    ],
    "cost": 60,
    "upkeep": 2
  },
  "120": {
    "id": 120,
    "templateId": 123,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Lizardman",
    "baseFantastic": false,
    "name": "Javelineers",
    "race": "Lizardman",
    "category": "Lizardman",
    "figures": 6,
    "defense": 3,
    "resist": 5,
    "hp": 2,
    "melee": 5,
    "ranged": 4,
    "moves": 2,
    "ammo": 6,
    "ranged_type": "Missile",
    "cost": 75,
    "upkeep": 2
  },
  "121": {
    "id": 121,
    "templateId": 124,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Lizardman",
    "baseFantastic": false,
    "name": "Lizardman Shaman",
    "race": "Lizardman",
    "category": "Lizardman",
    "figures": 4,
    "defense": 2,
    "resist": 5,
    "hp": 2,
    "melee": 2,
    "ranged": 3,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Healing Spell",
      "Healer",
      "Purify"
    ],
    "cost": 60,
    "upkeep": 2
  },
  "122": {
    "id": 122,
    "templateId": 126,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Lizardman",
    "baseFantastic": false,
    "name": "Dragon Turtle",
    "race": "Lizardman",
    "category": "Lizardman",
    "figures": 1,
    "defense": 9,
    "resist": 12,
    "hp": 20,
    "melee": 10,
    "moves": 2,
    "thrown_breath_type": "lightning",
    "thrown_breath": 5,
    "abilities": [
      "Fire Immunity"
    ],
    "cost": 100,
    "upkeep": 1
  },
  "123": {
    "id": 123,
    "templateId": 127,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nomad",
    "baseFantastic": false,
    "name": "Nomad Spearmen",
    "race": "Nomad",
    "category": "Nomad",
    "figures": 6,
    "defense": 1,
    "resist": 6,
    "hp": 1,
    "melee": 2,
    "ranged": 1,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Missile",
    "cost": 10
  },
  "124": {
    "id": 124,
    "templateId": 128,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nomad",
    "baseFantastic": false,
    "name": "Nomad Swordsmen",
    "race": "Nomad",
    "category": "Nomad",
    "figures": 6,
    "defense": 3,
    "resist": 7,
    "hp": 1,
    "melee": 3,
    "ranged": 2,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Missile",
    "abilities": [
      "Large Shield"
    ],
    "cost": 25,
    "upkeep": 1
  },
  "125": {
    "id": 125,
    "templateId": 129,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Troll",
    "baseFantastic": false,
    "name": "Troll Magicians",
    "race": "Troll",
    "category": "Troll",
    "figures": 4,
    "defense": 2,
    "resist": 8,
    "hp": 4,
    "melee": 4,
    "ranged": 7,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "spec_att_attrib": 1,
    "abilities": [
      "Caster 20 MP",
      "Regeneration",
      "Missile Immunity"
    ],
    "cost": 180,
    "upkeep": 3
  },
  "126": {
    "id": 126,
    "templateId": 130,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nomad",
    "baseFantastic": false,
    "name": "Nomad Priests",
    "race": "Nomad",
    "category": "Nomad",
    "figures": 4,
    "defense": 4,
    "resist": 11,
    "hp": 2,
    "melee": 3,
    "ranged": 5,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Healing Spell",
      "Healer",
      "Purify"
    ],
    "cost": 100,
    "upkeep": 3
  },
  "127": {
    "id": 127,
    "templateId": 131,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nomad",
    "baseFantastic": false,
    "name": "Nomad Magicians",
    "race": "Nomad",
    "category": "Nomad",
    "figures": 4,
    "defense": 3,
    "resist": 11,
    "hp": 1,
    "melee": 1,
    "ranged": 7,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Caster 20 MP",
      "Missile Immunity"
    ],
    "cost": 120,
    "upkeep": 3
  },
  "128": {
    "id": 128,
    "templateId": 132,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Troll",
    "baseFantastic": false,
    "name": "War Trolls",
    "race": "Troll",
    "category": "Troll",
    "figures": 4,
    "defense": 4,
    "resist": 6,
    "hp": 8,
    "melee": 8,
    "moves": 3,
    "spec_att_attrib": 1,
    "abilities": [
      "Regeneration"
    ],
    "cost": 150,
    "upkeep": 3
  },
  "129": {
    "id": 129,
    "templateId": 133,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nomad",
    "baseFantastic": false,
    "name": "Horsebowmen",
    "race": "Nomad",
    "category": "Nomad",
    "figures": 4,
    "defense": 2,
    "resist": 7,
    "hp": 3,
    "melee": 4,
    "ranged": 4,
    "moves": 4,
    "ammo": 4,
    "ranged_type": "Missile",
    "abilities": [
      "First Strike"
    ],
    "cost": 50,
    "upkeep": 1
  },
  "130": {
    "id": 130,
    "templateId": 134,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nomad",
    "baseFantastic": false,
    "name": "Nomad Pikemen",
    "race": "Nomad",
    "category": "Nomad",
    "figures": 6,
    "defense": 4,
    "resist": 8,
    "hp": 2,
    "melee": 4,
    "moves": 2,
    "abilities": [
      "Negate First Strike",
      "Armor Piercing"
    ],
    "cost": 75,
    "upkeep": 2
  },
  "131": {
    "id": 131,
    "templateId": 135,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nomad",
    "baseFantastic": false,
    "name": "Rangers",
    "race": "Nomad",
    "category": "Nomad",
    "figures": 4,
    "defense": 3,
    "resist": 8,
    "hp": 3,
    "melee": 6,
    "ranged": 7,
    "moves": 3,
    "ammo": 6,
    "ranged_type": "Missile",
    "abilities": [
      "Long Range",
      "Poison Immunity"
    ],
    "cost": 150,
    "upkeep": 3
  },
  "132": {
    "id": 132,
    "templateId": 136,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nomad",
    "baseFantastic": false,
    "name": "Griffins",
    "race": "Nomad",
    "category": "Nomad",
    "figures": 2,
    "defense": 5,
    "resist": 8,
    "hp": 10,
    "melee": 9,
    "moves": 4,
    "abilities": [
      "Flight",
      "Armor Piercing",
      "First Strike"
    ],
    "cost": 180,
    "upkeep": 3
  },
  "133": {
    "id": 133,
    "templateId": 137,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Orc Spearmen",
    "race": "Orc",
    "category": "Orc",
    "figures": 6,
    "defense": 1,
    "resist": 3,
    "hp": 1,
    "melee": 2,
    "moves": 2,
    "cost": 10
  },
  "134": {
    "id": 134,
    "templateId": 138,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Orc Swordsmen",
    "race": "Orc",
    "category": "Orc",
    "figures": 6,
    "defense": 3,
    "resist": 4,
    "hp": 1,
    "melee": 3,
    "moves": 2,
    "abilities": [
      "Large Shield"
    ],
    "cost": 25
  },
  "135": {
    "id": 135,
    "templateId": 139,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Orc Halberdiers",
    "race": "Orc",
    "category": "Orc",
    "figures": 6,
    "defense": 4,
    "resist": 5,
    "hp": 2,
    "melee": 5,
    "moves": 2,
    "abilities": [
      "Negate First Strike"
    ],
    "cost": 60
  },
  "136": {
    "id": 136,
    "templateId": 140,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Orc Bowmen",
    "race": "Orc",
    "category": "Orc",
    "figures": 6,
    "defense": 1,
    "resist": 4,
    "hp": 1,
    "melee": 1,
    "ranged": 3,
    "moves": 2,
    "ammo": 8,
    "ranged_type": "Missile",
    "cost": 30
  },
  "137": {
    "id": 137,
    "templateId": 141,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Orc Cavalry",
    "race": "Orc",
    "category": "Orc",
    "figures": 4,
    "defense": 2,
    "resist": 4,
    "hp": 3,
    "melee": 5,
    "moves": 5,
    "abilities": [
      "First Strike"
    ],
    "cost": 40
  },
  "138": {
    "id": 138,
    "templateId": 142,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Orc Shaman",
    "race": "Orc",
    "category": "Orc",
    "figures": 4,
    "defense": 3,
    "resist": 6,
    "hp": 1,
    "melee": 2,
    "ranged": 3,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Healing Spell",
      "Healer",
      "Purify"
    ],
    "cost": 50
  },
  "139": {
    "id": 139,
    "templateId": 143,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Orc Magicians",
    "race": "Orc",
    "category": "Orc",
    "figures": 4,
    "defense": 3,
    "resist": 8,
    "hp": 1,
    "melee": 1,
    "ranged": 7,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Caster 20 MP",
      "Missile Immunity"
    ],
    "cost": 120,
    "upkeep": 1
  },
  "140": {
    "id": 140,
    "templateId": 144,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Orc Engineers",
    "race": "Orc",
    "category": "Orc",
    "figures": 6,
    "defense": 1,
    "resist": 4,
    "hp": 1,
    "melee": 1,
    "moves": 1,
    "abilities": [
      "Wall Crusher"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "141": {
    "id": 141,
    "templateId": 145,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Troll",
    "baseFantastic": false,
    "name": "War Mammoths",
    "race": "Troll",
    "category": "Troll",
    "figures": 3,
    "defense": 6,
    "resist": 8,
    "hp": 12,
    "melee": 12,
    "moves": 2,
    "abilities": [
      "Wall Crusher",
      "Cold Immunity",
      "First Strike"
    ],
    "cost": 180,
    "upkeep": 5
  },
  "142": {
    "id": 142,
    "templateId": 146,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Orc",
    "baseFantastic": false,
    "name": "Wyvern Riders",
    "race": "Orc",
    "category": "Orc",
    "figures": 2,
    "defense": 5,
    "resist": 7,
    "hp": 10,
    "melee": 7,
    "moves": 5,
    "spec_att_attrib": 5,
    "abilities": [
      "Flight",
      "Poison Touch"
    ],
    "cost": 150,
    "upkeep": 2
  },
  "143": {
    "id": 143,
    "templateId": 147,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Troll",
    "baseFantastic": false,
    "name": "Troll Spearmen",
    "race": "Troll",
    "category": "Troll",
    "figures": 4,
    "defense": 1,
    "resist": 5,
    "hp": 4,
    "melee": 4,
    "moves": 2,
    "spec_att_attrib": 1,
    "abilities": [
      "Regeneration"
    ],
    "cost": 15
  },
  "144": {
    "id": 144,
    "templateId": 148,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Troll",
    "baseFantastic": false,
    "name": "Troll Swordsmen",
    "race": "Troll",
    "category": "Troll",
    "figures": 4,
    "defense": 3,
    "resist": 5,
    "hp": 4,
    "melee": 5,
    "moves": 2,
    "spec_att_attrib": 1,
    "abilities": [
      "Large Shield",
      "Regeneration"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "145": {
    "id": 145,
    "templateId": 149,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Troll",
    "baseFantastic": false,
    "name": "Troll Halberdiers",
    "race": "Troll",
    "category": "Troll",
    "figures": 4,
    "defense": 4,
    "resist": 5,
    "hp": 6,
    "melee": 7,
    "moves": 2,
    "spec_att_attrib": 1,
    "abilities": [
      "Regeneration",
      "Negate First Strike"
    ],
    "cost": 90,
    "upkeep": 2
  },
  "146": {
    "id": 146,
    "templateId": 150,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Troll",
    "baseFantastic": false,
    "name": "Troll Shaman",
    "race": "Troll",
    "category": "Troll",
    "figures": 4,
    "defense": 3,
    "resist": 6,
    "hp": 4,
    "melee": 4,
    "ranged": 3,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "spec_att_attrib": 2,
    "abilities": [
      "Healing Spell",
      "Healer",
      "Regeneration",
      "Purify"
    ],
    "cost": 80,
    "upkeep": 2
  },
  "147": {
    "id": 147,
    "templateId": 152,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Boars",
    "race": "Nature",
    "category": "Nature",
    "figures": 3,
    "defense": 5,
    "resist": 5,
    "hp": 5,
    "melee": 6,
    "to_hit": 10,
    "moves": 3,
    "abilities": [
      "Fantastic"
    ],
    "cost": 50,
    "upkeep": 1
  },
  "148": {
    "id": 148,
    "templateId": 153,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Fire Elemental",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 1,
    "defense": 5,
    "resist": 4,
    "hp": 10,
    "melee": 12,
    "moves": 2,
    "abilities": [
      "Weapon Immunity",
      "Fantastic",
      "Fire Immunity",
      "Stoning Immunity",
      "Poison Immunity"
    ],
    "cost": 70,
    "upkeep": 1
  },
  "149": {
    "id": 149,
    "templateId": 154,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Arcane",
    "baseFantastic": true,
    "name": "Magic Spirit",
    "race": "Arcane",
    "category": "Arcane",
    "figures": 1,
    "defense": 4,
    "resist": 8,
    "hp": 10,
    "melee": 5,
    "moves": 2,
    "abilities": [
      "Fantastic",
      "Meld With Node",
      "Non Corporeal",
      "Poison Immunity"
    ],
    "cost": 30,
    "upkeep": 1
  },
  "150": {
    "id": 150,
    "templateId": 155,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Hell Hounds",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 4,
    "defense": 2,
    "resist": 5,
    "hp": 4,
    "melee": 4,
    "to_hit": 10,
    "moves": 3,
    "thrown_breath_type": "fire",
    "thrown_breath": 4,
    "abilities": [
      "Fantastic"
    ],
    "cost": 40,
    "upkeep": 1
  },
  "151": {
    "id": 151,
    "templateId": 156,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Gargoyles",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 4,
    "defense": 9,
    "resist": 9,
    "hp": 4,
    "melee": 5,
    "to_hit": 10,
    "moves": 3,
    "abilities": [
      "Fantastic",
      "Stoning Immunity",
      "Poison Immunity"
    ],
    "cost": 130,
    "upkeep": 1
  },
  "152": {
    "id": 152,
    "templateId": 157,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Fire Giant",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 1,
    "defense": 5,
    "resist": 7,
    "hp": 18,
    "melee": 18,
    "ranged": 12,
    "to_hit": 10,
    "moves": 3,
    "ammo": 3,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Fireball Spell",
      "Fantastic",
      "Wall Crusher",
      "Fire Immunity"
    ],
    "cost": 210,
    "upkeep": 3
  },
  "153": {
    "id": 153,
    "templateId": 158,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Sorcery",
    "baseFantastic": true,
    "name": "Water Elemental",
    "race": "Sorcery",
    "category": "Sorcery",
    "figures": 1,
    "defense": 7,
    "resist": 7,
    "hp": 15,
    "melee": 14,
    "ranged": 14,
    "to_hit": 20,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Weapon Immunity",
      "Fantastic",
      "Fire Immunity",
      "Poison Immunity"
    ],
    "cost": 210,
    "upkeep": 3
  },
  "154": {
    "id": 154,
    "templateId": 159,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Chaos Spawn",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 1,
    "defense": 8,
    "resist": 12,
    "hp": 22,
    "melee": 1,
    "ranged": 4,
    "moves": 2,
    "ranged_type": "Gaze(Multiple)",
    "spec_att_attrib": 4,
    "abilities": [
      "Flight",
      "Cause Fear",
      "Fantastic",
      "Illusion Immunity",
      "Poison Touch"
    ],
    "cost": 238,
    "upkeep": 8
  },
  "155": {
    "id": 155,
    "templateId": 160,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Chimera",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 4,
    "defense": 5,
    "resist": 8,
    "hp": 8,
    "melee": 10,
    "to_hit": 10,
    "moves": 3,
    "thrown_breath_type": "fire",
    "thrown_breath": 6,
    "abilities": [
      "Flight",
      "Fantastic"
    ],
    "cost": 210,
    "upkeep": 4
  },
  "156": {
    "id": 156,
    "templateId": 161,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Doom Bat",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 1,
    "defense": 7,
    "resist": 10,
    "hp": 30,
    "melee": 16,
    "to_hit": 20,
    "moves": 6,
    "abilities": [
      "Flight",
      "Immolation",
      "Fantastic",
      "Doom"
    ],
    "cost": 360,
    "upkeep": 7
  },
  "157": {
    "id": 157,
    "templateId": 162,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Efreet",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 1,
    "defense": 7,
    "resist": 9,
    "hp": 27,
    "melee": 15,
    "ranged": 18,
    "to_hit": 20,
    "moves": 4,
    "ammo": 8,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Flight",
      "Caster 40 MP",
      "Immolation",
      "Fantastic",
      "Fire Immunity"
    ],
    "cost": 330,
    "upkeep": 9
  },
  "158": {
    "id": 158,
    "templateId": 163,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Hydra",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 9,
    "defense": 4,
    "resist": 12,
    "hp": 10,
    "melee": 9,
    "to_hit": 10,
    "moves": 2,
    "thrown_breath_type": "fire",
    "thrown_breath": 6,
    "spec_att_attrib": 7,
    "abilities": [
      "Fantastic",
      "Regeneration",
      "Supernatural"
    ],
    "cost": 300,
    "upkeep": 11
  },
  "159": {
    "id": 159,
    "templateId": 164,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Chaos",
    "baseFantastic": true,
    "name": "Great Drake",
    "race": "Chaos",
    "category": "Chaos",
    "figures": 1,
    "defense": 11,
    "resist": 15,
    "hp": 40,
    "melee": 35,
    "to_hit": 30,
    "moves": 4,
    "thrown_breath_type": "fire",
    "thrown_breath": 35,
    "abilities": [
      "Flight",
      "Fantastic",
      "Supernatural"
    ],
    "cost": 550,
    "upkeep": 15
  },
  "160": {
    "id": 160,
    "templateId": 165,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Skeletons",
    "race": "Death",
    "category": "Death",
    "figures": 7,
    "defense": 4,
    "resist": 3,
    "hp": 1,
    "melee": 3,
    "to_hit": 10,
    "moves": 2,
    "abilities": [
      "Fantastic",
      "Missile Immunity",
      "Illusion Immunity",
      "Cold Immunity",
      "Death Immunity",
      "Poison Immunity"
    ],
    "cost": 40
  },
  "161": {
    "id": 161,
    "templateId": 166,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Ghouls",
    "race": "Death",
    "category": "Death",
    "figures": 4,
    "defense": 3,
    "resist": 6,
    "hp": 3,
    "melee": 5,
    "ranged": 4,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(C)",
    "spec_att_attrib": 1,
    "abilities": [
      "Fantastic",
      "Create Undead",
      "Illusion Immunity",
      "Cold Immunity",
      "Death Immunity",
      "Poison Immunity",
      "Poison Touch"
    ],
    "cost": 100,
    "upkeep": 1
  },
  "162": {
    "id": 162,
    "templateId": 167,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Night Stalker",
    "race": "Death",
    "category": "Death",
    "figures": 1,
    "defense": 5,
    "resist": 8,
    "hp": 13,
    "melee": 7,
    "ranged": 0,
    "to_hit": 10,
    "moves": 3,
    "ranged_type": "Gaze(Death)",
    "spec_att_attrib": 3,
    "abilities": [
      "Weapon Immunity",
      "Fantastic",
      "Invisibility",
      "Illusion Immunity",
      "Cold Immunity",
      "Death Immunity",
      "Poison Immunity"
    ],
    "cost": 239,
    "upkeep": 1
  },
  "163": {
    "id": 163,
    "templateId": 168,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Werewolves",
    "race": "Death",
    "category": "Death",
    "figures": 6,
    "defense": 3,
    "resist": 4,
    "hp": 5,
    "melee": 6,
    "to_hit": 20,
    "moves": 3,
    "spec_att_attrib": 0,
    "abilities": [
      "Weapon Immunity",
      "Fantastic",
      "Regeneration",
      "Cold Immunity",
      "Death Immunity"
    ],
    "cost": 130,
    "upkeep": 2
  },
  "164": {
    "id": 164,
    "templateId": 169,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Demon",
    "race": "Death",
    "category": "Death",
    "figures": 1,
    "defense": 5,
    "resist": 7,
    "hp": 12,
    "melee": 14,
    "to_hit": 10,
    "moves": 2,
    "abilities": [
      "Weapon Immunity",
      "Flight",
      "Caster 40 MP",
      "Fantastic",
      "Missile Immunity",
      "Illusion Immunity",
      "Death Immunity"
    ],
    "cost": 238,
    "upkeep": 3
  },
  "165": {
    "id": 165,
    "templateId": 170,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Wraiths",
    "race": "Death",
    "category": "Death",
    "figures": 4,
    "defense": 6,
    "resist": 8,
    "hp": 8,
    "melee": 10,
    "to_hit": 20,
    "moves": 5,
    "spec_att_attrib": 3,
    "abilities": [
      "Weapon Immunity",
      "Flight",
      "Fantastic",
      "Non Corporeal",
      "Illusion Immunity",
      "Cold Immunity",
      "Death Immunity",
      "Poison Immunity",
      "Life Steal"
    ],
    "cost": 360,
    "upkeep": 5
  },
  "166": {
    "id": 166,
    "templateId": 171,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Shadow Demons",
    "race": "Death",
    "category": "Death",
    "figures": 4,
    "defense": 4,
    "resist": 6,
    "hp": 5,
    "melee": 5,
    "ranged": 5,
    "to_hit": 20,
    "moves": 2,
    "ammo": 8,
    "ranged_type": "Magic(C)",
    "spec_att_attrib": 2,
    "abilities": [
      "Weapon Immunity",
      "Flight",
      "Fantastic",
      "Plane Shift",
      "Non Corporeal",
      "Regeneration",
      "Illusion Immunity",
      "Cold Immunity",
      "Death Immunity",
      "Poison Immunity"
    ],
    "cost": 240,
    "upkeep": 4
  },
  "167": {
    "id": 167,
    "templateId": 172,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Death Knights",
    "race": "Death",
    "category": "Death",
    "figures": 4,
    "defense": 9,
    "resist": 10,
    "hp": 8,
    "melee": 12,
    "to_hit": 30,
    "moves": 5,
    "spec_att_attrib": 5,
    "abilities": [
      "Weapon Immunity",
      "Flight",
      "Fantastic",
      "Non Corporeal",
      "Illusion Immunity",
      "Cold Immunity",
      "Death Immunity",
      "Poison Immunity",
      "Armor Piercing",
      "First Strike",
      "Life Steal",
      "Supernatural"
    ],
    "cost": 550,
    "upkeep": 8
  },
  "168": {
    "id": 168,
    "templateId": 173,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Demon Lord",
    "race": "Death",
    "category": "Death",
    "figures": 1,
    "defense": 8,
    "resist": 13,
    "hp": 35,
    "melee": 25,
    "ranged": 20,
    "to_hit": 30,
    "moves": 4,
    "ammo": 8,
    "ranged_type": "Magic(C)",
    "spec_att_attrib": 2,
    "abilities": [
      "Weapon Immunity",
      "Flight",
      "Summon Demons Spell",
      "Cause Fear",
      "Fantastic",
      "Land Corruption",
      "Missile Immunity",
      "Illusion Immunity",
      "Death Immunity",
      "Life Steal",
      "Supernatural"
    ],
    "cost": 610,
    "upkeep": 18
  },
  "169": {
    "id": 169,
    "templateId": 174,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Death",
    "baseFantastic": true,
    "name": "Zombies",
    "race": "Death",
    "category": "Death",
    "figures": 6,
    "defense": 3,
    "resist": 3,
    "hp": 3,
    "melee": 4,
    "to_hit": 10,
    "moves": 1,
    "abilities": [
      "Fantastic",
      "Create Undead",
      "Illusion Immunity",
      "Cold Immunity",
      "Death Immunity"
    ],
    "cost": 70
  },
  "170": {
    "id": 170,
    "templateId": 175,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Life",
    "baseFantastic": true,
    "name": "Unicorns",
    "race": "Life",
    "category": "Life",
    "figures": 4,
    "defense": 4,
    "resist": 7,
    "hp": 8,
    "melee": 6,
    "to_hit": 20,
    "moves": 4,
    "spec_att_attrib": 2,
    "abilities": [
      "Resistance to All",
      "Fantastic",
      "Poison Immunity"
    ],
    "cost": 210,
    "upkeep": 4
  },
  "171": {
    "id": 171,
    "templateId": 176,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Life",
    "baseFantastic": true,
    "name": "Guardian Spirit",
    "race": "Life",
    "category": "Life",
    "figures": 1,
    "defense": 6,
    "resist": 10,
    "hp": 10,
    "melee": 7,
    "to_hit": 30,
    "moves": 2,
    "spec_att_attrib": 1,
    "abilities": [
      "Resistance to All",
      "Fantastic",
      "Meld With Node",
      "Non Corporeal",
      "Poison Immunity"
    ],
    "cost": 55,
    "upkeep": 1
  },
  "172": {
    "id": 172,
    "templateId": 177,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Life",
    "baseFantastic": true,
    "name": "Angel",
    "race": "Life",
    "category": "Life",
    "figures": 1,
    "defense": 9,
    "resist": 11,
    "hp": 27,
    "melee": 18,
    "to_hit": 20,
    "moves": 5,
    "spec_att_attrib": 1,
    "abilities": [
      "Flight",
      "Caster 20 MP",
      "Caster 40 MP",
      "Holy Bonus",
      "Fantastic",
      "Illusion Immunity",
      "Exorcise"
    ],
    "cost": 360,
    "upkeep": 8
  },
  "173": {
    "id": 173,
    "templateId": 178,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Life",
    "baseFantastic": true,
    "name": "Arch Angel",
    "race": "Life",
    "category": "Life",
    "figures": 1,
    "defense": 12,
    "resist": 18,
    "hp": 37,
    "melee": 21,
    "to_hit": 40,
    "moves": 4,
    "spec_att_attrib": 2,
    "abilities": [
      "Flight",
      "Caster 40 MP",
      "Holy Bonus",
      "Fantastic",
      "Healer",
      "Wind Walking",
      "Negate First Strike",
      "Illusion Immunity",
      "Supernatural"
    ],
    "cost": 610,
    "upkeep": 18
  },
  "174": {
    "id": 174,
    "templateId": 179,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "War Bears",
    "race": "Nature",
    "category": "Nature",
    "figures": 3,
    "defense": 5,
    "resist": 6,
    "hp": 7,
    "melee": 7,
    "to_hit": 10,
    "moves": 3,
    "abilities": [
      "Fantastic"
    ],
    "cost": 70,
    "upkeep": 1
  },
  "175": {
    "id": 175,
    "templateId": 180,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Sprites",
    "race": "Nature",
    "category": "Nature",
    "figures": 5,
    "defense": 2,
    "resist": 8,
    "hp": 1,
    "melee": 2,
    "ranged": 4,
    "to_hit": 10,
    "moves": 2,
    "ammo": 4,
    "ranged_type": "Magic(N)",
    "abilities": [
      "Flight",
      "Fantastic"
    ],
    "cost": 69,
    "upkeep": 2
  },
  "176": {
    "id": 176,
    "templateId": 181,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Cockatrices",
    "race": "Nature",
    "category": "Nature",
    "figures": 4,
    "defense": 5,
    "resist": 7,
    "hp": 7,
    "melee": 4,
    "to_hit": 10,
    "moves": 3,
    "spec_att_attrib": 4,
    "abilities": [
      "Flight",
      "Fantastic",
      "Stoning Touch"
    ],
    "cost": 210,
    "upkeep": 4
  },
  "177": {
    "id": 177,
    "templateId": 182,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Great Lizard",
    "race": "Nature",
    "category": "Nature",
    "figures": 1,
    "defense": 7,
    "resist": 7,
    "hp": 30,
    "melee": 18,
    "to_hit": 20,
    "moves": 3,
    "spec_att_attrib": 2,
    "abilities": [
      "Fantastic",
      "Regeneration"
    ],
    "cost": 240,
    "upkeep": 5
  },
  "178": {
    "id": 178,
    "templateId": 183,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Giant Spiders",
    "race": "Nature",
    "category": "Nature",
    "figures": 4,
    "defense": 5,
    "resist": 9,
    "hp": 5,
    "melee": 6,
    "to_hit": 10,
    "moves": 5,
    "spec_att_attrib": 3,
    "abilities": [
      "Web Spell",
      "Fantastic",
      "Poison Touch"
    ],
    "cost": 130,
    "upkeep": 2
  },
  "179": {
    "id": 179,
    "templateId": 184,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Stone Giant",
    "race": "Nature",
    "category": "Nature",
    "figures": 1,
    "defense": 12,
    "resist": 10,
    "hp": 25,
    "melee": 20,
    "ranged": 20,
    "to_hit": 20,
    "moves": 3,
    "ammo": 3,
    "ranged_type": "Boulder",
    "abilities": [
      "Fantastic",
      "Wall Crusher",
      "Stoning Immunity",
      "Poison Immunity"
    ],
    "cost": 329,
    "upkeep": 5
  },
  "180": {
    "id": 180,
    "templateId": 185,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Colossus",
    "race": "Nature",
    "category": "Nature",
    "figures": 1,
    "defense": 12,
    "resist": 15,
    "hp": 37,
    "melee": 25,
    "ranged": 25,
    "to_hit": 30,
    "moves": 3,
    "ammo": 4,
    "ranged_type": "Boulder",
    "abilities": [
      "Fantastic",
      "Wall Crusher",
      "Stoning Immunity",
      "Illusion Immunity",
      "Poison Immunity",
      "First Strike",
      "Supernatural"
    ],
    "cost": 610,
    "upkeep": 12
  },
  "181": {
    "id": 181,
    "templateId": 186,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Gorgons",
    "race": "Nature",
    "category": "Nature",
    "figures": 3,
    "defense": 7,
    "resist": 9,
    "hp": 14,
    "melee": 15,
    "ranged": 0,
    "to_hit": 20,
    "moves": 3,
    "ranged_type": "Gaze(Stoning)",
    "spec_att_attrib": 3,
    "abilities": [
      "Fantastic",
      "Supernatural"
    ],
    "cost": 450,
    "upkeep": 8
  },
  "182": {
    "id": 182,
    "templateId": 187,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Earth Elemental",
    "race": "Nature",
    "category": "Nature",
    "figures": 1,
    "defense": 4,
    "resist": 8,
    "hp": 30,
    "melee": 25,
    "to_hit": 10,
    "moves": 1,
    "abilities": [
      "Fantastic",
      "Wall Crusher",
      "Stoning Immunity",
      "Poison Immunity"
    ],
    "cost": 237,
    "upkeep": 5
  },
  "183": {
    "id": 183,
    "templateId": 188,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Behemoth",
    "race": "Nature",
    "category": "Nature",
    "figures": 1,
    "defense": 15,
    "resist": 13,
    "hp": 42,
    "melee": 25,
    "to_hit": 20,
    "moves": 3,
    "spec_att_attrib": 3,
    "abilities": [
      "Caster 40 MP",
      "Fantastic",
      "Regeneration",
      "Supernatural"
    ],
    "cost": 450,
    "upkeep": 12
  },
  "184": {
    "id": 184,
    "templateId": 189,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Nature",
    "baseFantastic": true,
    "name": "Great Wyrm",
    "race": "Nature",
    "category": "Nature",
    "figures": 1,
    "defense": 8,
    "resist": 14,
    "hp": 45,
    "melee": 36,
    "to_hit": 30,
    "moves": 3,
    "spec_att_attrib": 25,
    "abilities": [
      "Fantastic",
      "Armor Piercing",
      "Poison Touch",
      "Supernatural"
    ],
    "cost": 610,
    "upkeep": 15
  },
  "185": {
    "id": 185,
    "templateId": 190,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Sorcery",
    "baseFantastic": true,
    "name": "Floating Island",
    "race": "Sorcery",
    "category": "Sorcery",
    "figures": 1,
    "defense": 0,
    "resist": 9,
    "hp": 45,
    "melee": 0,
    "moves": 3,
    "abilities": [
      "Fantastic",
      "Stoning Immunity",
      "Death Immunity",
      "Poison Immunity"
    ],
    "cost": 30,
    "upkeep": 1
  },
  "186": {
    "id": 186,
    "templateId": 191,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Sorcery",
    "baseFantastic": true,
    "name": "Phantom Beast",
    "race": "Sorcery",
    "category": "Sorcery",
    "figures": 1,
    "defense": 0,
    "resist": 6,
    "hp": 25,
    "melee": 18,
    "to_hit": 10,
    "moves": 2,
    "abilities": [
      "Fantastic",
      "Non Corporeal",
      "Stoning Immunity",
      "Death Immunity",
      "Poison Immunity",
      "Illusion"
    ],
    "cost": 70,
    "upkeep": 3
  },
  "187": {
    "id": 187,
    "templateId": 192,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Sorcery",
    "baseFantastic": true,
    "name": "Phantom Warriors",
    "race": "Sorcery",
    "category": "Sorcery",
    "figures": 7,
    "defense": 0,
    "resist": 4,
    "hp": 1,
    "melee": 3,
    "moves": 2,
    "abilities": [
      "Fantastic",
      "Non Corporeal",
      "Stoning Immunity",
      "Death Immunity",
      "Poison Immunity",
      "Illusion"
    ],
    "cost": 30,
    "upkeep": 1
  },
  "188": {
    "id": 188,
    "templateId": 193,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Sorcery",
    "baseFantastic": true,
    "name": "Storm Giant",
    "race": "Sorcery",
    "category": "Sorcery",
    "figures": 1,
    "defense": 7,
    "resist": 9,
    "hp": 25,
    "melee": 18,
    "ranged": 18,
    "to_hit": 20,
    "moves": 3,
    "ammo": 5,
    "ranged_type": "Magic(C)",
    "abilities": [
      "Fantastic",
      "Wall Crusher",
      "Missile Immunity",
      "Armor Piercing"
    ],
    "cost": 330,
    "upkeep": 5
  },
  "189": {
    "id": 189,
    "templateId": 194,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Sorcery",
    "baseFantastic": true,
    "name": "Air Elemental",
    "race": "Sorcery",
    "category": "Sorcery",
    "figures": 1,
    "defense": 7,
    "resist": 9,
    "hp": 10,
    "melee": 15,
    "to_hit": 10,
    "moves": 5,
    "abilities": [
      "Weapon Immunity",
      "Flight",
      "Fantastic",
      "Invisibility",
      "Non Corporeal",
      "Stoning Immunity",
      "Poison Immunity",
      "Armor Piercing"
    ],
    "cost": 239,
    "upkeep": 5
  },
  "190": {
    "id": 190,
    "templateId": 195,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Sorcery",
    "baseFantastic": true,
    "name": "Djinn",
    "race": "Sorcery",
    "category": "Sorcery",
    "figures": 1,
    "defense": 8,
    "resist": 12,
    "hp": 29,
    "melee": 18,
    "ranged": 15,
    "to_hit": 30,
    "moves": 4,
    "ammo": 8,
    "ranged_type": "Magic(S)",
    "abilities": [
      "Flight",
      "Caster 20 MP",
      "Caster 40 MP",
      "Fantastic",
      "Wind Walking",
      "Supernatural"
    ],
    "cost": 450,
    "upkeep": 9
  },
  "191": {
    "id": 191,
    "templateId": 196,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Sorcery",
    "baseFantastic": true,
    "name": "Sky Drake",
    "race": "Sorcery",
    "category": "Sorcery",
    "figures": 1,
    "defense": 10,
    "resist": 14,
    "hp": 30,
    "melee": 28,
    "to_hit": 30,
    "moves": 4,
    "thrown_breath_type": "lightning",
    "thrown_breath": 21,
    "abilities": [
      "Flight",
      "Fantastic",
      "Illusion Immunity",
      "Magic Immunity",
      "Supernatural"
    ],
    "cost": 611,
    "upkeep": 15
  },
  "192": {
    "id": 192,
    "templateId": 197,
    "heroTypeId": null,
    "isHero": false,
    "baseRace": "Sorcery",
    "baseFantastic": true,
    "name": "Nagas",
    "race": "Sorcery",
    "category": "Sorcery",
    "figures": 3,
    "defense": 4,
    "resist": 7,
    "hp": 5,
    "melee": 5,
    "to_hit": 10,
    "moves": 3,
    "spec_att_attrib": 3,
    "abilities": [
      "Fantastic",
      "First Strike",
      "Poison Touch"
    ],
    "cost": 70,
    "upkeep": 2
  }
};
