; Special AI and system flags for units.
; 1 - Phoenix Stall. Don't engage in combat while there are at least 3 times as many normal units in the combat as units of this type to utilize the Healing Aura ability.
; 2 - Leave Walls. The unit is forced to always go outside during combat and never stay behind city walls to defend.
; 3 - Unimportant combat summon. The priority of most spells (like Fire Bolt, Disintegrate) against these targets is capped at a lower priority value.
; 4 - Force Web. This unit will have a minimal priority of 1 on the Web Spell so it can never be considered useless to cast.
; 5 - No Despair. The AI will NEVER cast Wave of Despair if this is their only affected target.
; 6 - Flying Ship strategy. The AI should aim to target this unit with Flight at high priority. Also includes Wraith Form if Wraith Form on ships allowing land movement is enabled.
; 7 - Focus Magic Target. The AI prioritizes targeting these units much higher with Focus Magic. (applies on Fair and higher difficulty only)
; 8 - Invalid Alone. Units marked with this flag cannot be generated as the only defender of lairs, towers and nodes.
; 9 - Invalid Companion. Units marked with this flag cannot be paired with units that have the "Invalid Alone" flag.
; Use these flags to prevent exploitable mosters to appear alone, such as Great Wyrms which are weak against flying enemies.
; 10 - Rare Monster. Units marked with this flag have half the normal chance to be the primary monster in a lair.
; Use this flag to reduce the probability of monsters that are high end enemies but easier to counter than usual, such as Hydra.
; 11 - Not Really Weak. Units above 300 "cost" cannot appear in low and medium budget lairs and nodes. Use this flag to mark monsters that are below 300 cost but still too strong to appear in low budget areas. (They can appear in medium budget areas though, in the range of 1100-1500.)
; Use this to ensure that players will usually be able to find lairs and nodes they can conquer in the first half of the game.
; 12 - Always Animated. Units with this flag are shown in an animated state even if they aren't flying.

; When loading this file in debug mode, the flags are logged to log.txt. Use this to confirm your custom settings and unit IDs are as intended.
[14]
flag2=Yes
[17]
flag2=Yes
[20]
flag2=Yes
[22]
flag2=Yes
[28]
flag2=Yes
[29]
flag2=Yes
[37]
flag5=Yes
[38]
flag6=Yes
[74]
flag2=Yes
[136]
flag2=Yes
[146]
flag2=Yes
[152]
flag3=Yes
flag5=Yes
Flag9=Yes
[153]
flag3=Yes
flag5=Yes
[158]
flag11=Yes
flag12=Yes
[160]
flag2=Yes
flag11=Yes
[161]
flag2=Yes
[162]
flag7=Yes
[163]
Flag10=Yes
[164]
flag2=Yes
[167]
flag2=Yes
[169]
flag7=Yes
[170]
flag2=Yes
flag7=Yes
[172]
flag2=Yes
flag7=Yes
[174]
flag3=Yes
flag5=Yes
[175]
flag2=Yes
[179]
Flag9=Yes
[181]
flag7=Yes
[182]
flag11=Yes
[183]
flag4=Yes
[185]
flag2=Yes
[187]
Flag9=Yes
[189]
flag2=Yes
flag8=Yes
[194]
flag11=Yes
[195]
flag2=Yes
flag7=Yes
[196]
flag2=Yes
[199]
flag2=Yes
[200]
flag1=Yes
