[1]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=0
; 0 - Warrior
; 1 - Mage
; 2 - Leader
; 3 - Warrior and Leader
; 4 - Mage Leader
; 5 - Warrior Mage
; 6 - All three classes
Prisonerturn=20
AIPreference=1
AIResurrectPreference=0
AIEquipOrder=0
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Constitution=1
Armsmaster=1
RequiredRealm=0
[2]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=0
Prisonerturn=0
AIPreference=1
AIResurrectPreference=1
AIEquipOrder=5
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Might=1
RequiredRealm=0
[3]
Spell1=52
Spell2=50
Spell3=45
Spell4=0
HeroMPPerLevel=7
HeroStartingMP=5
HeroRandomAbilities=0
HeroClass=1
Prisonerturn=0
AIPreference=4
AIResurrectPreference=0
AIEquipOrder=77
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Sage=1
RequiredRealm=0
[4]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=0
Prisonerturn=0
AIPreference=2
AIResurrectPreference=0
AIEquipOrder=1
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Noble=1
Logistics=1
RequiredRealm=0
[5]
Spell1=2
Spell2=4
Spell3=0
Spell4=0
HeroMPPerLevel=4
HeroStartingMP=6
HeroRandomAbilities=1
HeroClass=4
Prisonerturn=0
AIPreference=6
AIResurrectPreference=3
AIEquipOrder=95
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Soul Linker=1
RequiredRealm=0
[6]
Spell1=46
Spell2=53
Spell3=0
Spell4=0
HeroMPPerLevel=3
HeroStartingMP=10
HeroRandomAbilities=0
HeroClass=3
Prisonerturn=0
AIPreference=3
AIResurrectPreference=1
AIEquipOrder=7
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Leadership=1
RequiredRealm=0
[7]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=1
HeroClass=3
Prisonerturn=0
AIPreference=1
AIResurrectPreference=0
AIEquipOrder=3
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Supply Commander=1
RequiredRealm=0
[8]
Spell1=125
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=5
HeroStartingMP=10
HeroRandomAbilities=1
HeroClass=4
Prisonerturn=0
AIPreference=3
AIResurrectPreference=2
AIEquipOrder=7
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
RequiredRealm=0
[9]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=1
HeroClass=3
Prisonerturn=0
AIPreference=1
AIResurrectPreference=0
AIEquipOrder=2
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Blademaster=1
Powershot=1
RequiredRealm=0
[10]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=0
HeroClass=0
Prisonerturn=60
AIPreference=4
AIResurrectPreference=3
AIEquipOrder=14
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Charmed=1
Lucky=1
Agility=1
RequiredRealm=0
[11]
Spell1=13
Spell2=22
Spell3=5
Spell4=12
HeroMPPerLevel=5
HeroStartingMP=5
HeroRandomAbilities=0
HeroClass=1
Prisonerturn=10
AIPreference=2
AIResurrectPreference=0
AIEquipOrder=4
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Ritual Master=1
RequiredRealm=0
[12]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=0
Prisonerturn=50
AIPreference=4
AIResurrectPreference=1
AIEquipOrder=80
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Agility=2
RequiredRealm=0
[13]
Spell1=5
Spell2=56
Spell3=90
Spell4=165
HeroMPPerLevel=6
HeroStartingMP=7
HeroRandomAbilities=1
HeroClass=5
Prisonerturn=35
AIPreference=3
AIResurrectPreference=0
AIEquipOrder=8
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
Agility=1
RequiredRealm=0
[14]
Spell1=83
Spell2=96
Spell3=90
Spell4=109
HeroMPPerLevel=6
HeroStartingMP=24
HeroRandomAbilities=2
HeroClass=1
Prisonerturn=20
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=78
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Arcane Power=1
RequiredRealm=0
[15]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=18
HeroRandomAbilities=1
HeroClass=0
Prisonerturn=10
AIPreference=4
AIResurrectPreference=1
AIEquipOrder=12
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Blademaster=2
RequiredRealm=0
[16]
Spell1=41
Spell2=44
Spell3=0
Spell4=0
HeroMPPerLevel=5
HeroStartingMP=9
HeroRandomAbilities=1
HeroClass=4
Prisonerturn=0
AIPreference=5
AIResurrectPreference=1
AIEquipOrder=10
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Guiding Beacon=1
RequiredRealm=0
[17]
Spell1=2
Spell2=7
Spell3=0
Spell4=0
HeroMPPerLevel=5
HeroStartingMP=15
HeroRandomAbilities=2
HeroClass=6
Prisonerturn=30
AIPreference=3
AIResurrectPreference=1
AIEquipOrder=9
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Lucky=1
RequiredRealm=0
[18]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=0
Prisonerturn=30
AIPreference=5
AIResurrectPreference=3
AIEquipOrder=13
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Might=1
RequiredRealm=0
[19]
Spell1=169
Spell2=170
Spell3=172
Spell4=174
HeroMPPerLevel=5
HeroStartingMP=15
HeroRandomAbilities=2
HeroClass=1
Prisonerturn=20
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=79
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Charmed=1
RequiredRealm=0
[20]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=5
HeroStartingMP=10
HeroRandomAbilities=3
HeroClass=6
Prisonerturn=30
AIPreference=4
AIResurrectPreference=2
AIEquipOrder=11
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
Noble=1
RequiredRealm=0
[21]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=3
HeroClass=3
Prisonerturn=99
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=16
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Blademaster=1
RequiredRealm=0
[22]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=1
HeroClass=2
Prisonerturn=0
AIPreference=2
AIResurrectPreference=0
AIEquipOrder=5
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Leadership=1
Legendary=2
RequiredRealm=0
[23]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=0
Prisonerturn=35
AIPreference=5
AIResurrectPreference=3
AIEquipOrder=15
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Blademaster=1
Might=1
Charmed=1
RequiredRealm=0
[24]
Spell1=91
Spell2=101
Spell3=104
Spell4=0
HeroMPPerLevel=8
HeroStartingMP=18
HeroRandomAbilities=2
HeroClass=1
Prisonerturn=30
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=76
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Arcane Power=2
RequiredRealm=0
[25]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=6
HeroStartingMP=9
HeroRandomAbilities=5
HeroClass=6
Prisonerturn=40
AIPreference=4
AIResurrectPreference=2
AIEquipOrder=17
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
RequiredRealm=0
[26]
Spell1=45
Spell2=46
Spell3=67
Spell4=0
HeroMPPerLevel=14
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=1
Prisonerturn=35
AIPreference=8
AIResurrectPreference=4
AIEquipOrder=90
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
RequiredRealm=0
[27]
Spell1=125
Spell2=137
Spell3=0
Spell4=0
HeroMPPerLevel=5
HeroStartingMP=5
HeroRandomAbilities=2
HeroClass=0
Prisonerturn=150
AIPreference=6
AIResurrectPreference=4
AIEquipOrder=84
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Blademaster=1
Constitution=1
Agility=1
Armsmaster=1
RequiredRealm=0
[28]
Spell1=134
Spell2=125
Spell3=140
Spell4=150
HeroMPPerLevel=8
HeroStartingMP=16
HeroRandomAbilities=1
HeroClass=4
Prisonerturn=120
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=83
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
DivineBarrier=1
Charmed=1
Noble=1
Prayermaster=2
RequiredRealm=0
[29]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=1
HeroClass=3
Prisonerturn=150
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=81
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Legendary=1
Might=2
Prayermaster=1
RequiredRealm=0
[30]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=1
HeroClass=0
Prisonerturn=150
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=82
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Legendary=1
Might=1
Blademaster=1
Constitution=1
RequiredRealm=0
[31]
Spell1=21
Spell2=56
Spell3=68
Spell4=0
HeroMPPerLevel=7
HeroStartingMP=8
HeroRandomAbilities=4
HeroClass=6
Prisonerturn=100
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=20
EquipSlot1=2
EquipSlot2=6
EquipSlot3=5
Blademaster=1
Capacity=2
RequiredRealm=0
[32]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=0
HeroStartingMP=0
HeroRandomAbilities=2
HeroClass=3
Prisonerturn=130
AIPreference=5
AIResurrectPreference=2
AIEquipOrder=6
EquipSlot1=1
EquipSlot2=6
EquipSlot3=5
Leadership=2
Constitution=2
Noble=1
Armsmaster=2
Logistics=1
RequiredRealm=0
[33]
Spell1=163
Spell2=165
Spell3=195
Spell4=182
HeroMPPerLevel=10
HeroStartingMP=10
HeroRandomAbilities=0
HeroClass=4
Prisonerturn=120
AIPreference=8
AIResurrectPreference=5
AIEquipOrder=100
EquipSlot1=4
EquipSlot2=5
EquipSlot3=5
Arcane Power=2
Sage=2
Soul Linker=2
Ritual Master=1
RequiredRealm=0
[34]
Spell1=0
Spell2=0
Spell3=0
Spell4=0
HeroMPPerLevel=7
HeroStartingMP=5
HeroRandomAbilities=3
HeroClass=5
Prisonerturn=100
AIPreference=7
AIResurrectPreference=4
AIEquipOrder=85
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
Constitution=1
Arcane Power=1
RequiredRealm=0
[35]
Spell1=149
Spell2=125
Spell3=124
Spell4=141
HeroMPPerLevel=5
HeroStartingMP=10
HeroRandomAbilities=2
HeroClass=6
Prisonerturn=0
AIPreference=8
AIResurrectPreference=0
AIEquipOrder=82
EquipSlot1=3
EquipSlot2=6
EquipSlot3=5
Leadership=1
Constitution=1
Battlemage=2
Prayermaster=1
Guiding Beacon=1
DivineBarrier=1
Might=2
RequiredRealm=4

