[Maindata]
AIPrimaryRetortChance=50
[1]
; Nature
Primary=6
Secondary=16
[2]
; Sorcery
Primary=10
Secondary=14
[3]
; Chaos
Primary=7
Secondary=15
[4]
; Life
Primary=18
Secondary=11
[5]
; Death
Primary=12
Secondary=8
[6]
; Nature Sorcery
Primary=16
Secondary=10
[7]
;Nature Chaos
Primary=4
Secondary=2
[8]
; Nature Life
Primary=6
Secondary=18
[9]
; Nature Death
Primary=16
Secondary=15
[10]
; Sorcery Chaos
Primary=16
Secondary=7
[11]
; Sorcery Life
Primary=1
Secondary=18
[12]
; Sorcery Death
Primary=7
Secondary=14
[13]
; Chaos Life
Primary=4
Secondary=18
[14]
; Chaos Death
Primary=10
Secondary=16
[15]
; Death Life
Primary=12
Secondary=8
