[0]
; Barbarian using mostly germans and scandinavian city names
0=Bremen
1=Brandenburg
2=Bromburg
3=Bamberg
4=Burglitz
5=Buxtehude
6=Braunschweig
7=Freiburg
8=Flensburg
9=Hamburg
10=Hannover
11=Konstanz
12=Kufstein
13=Linz
14=Strassburg
15=Rostock
16=Schleswig
17=Stettin
18=Zwolle
19=Soest
20=Reykjavik
21=Teutoburg
22=Ramstein
23=Salzburg
24=Wartburg
25=Dublin
26=Aachen
27=Kiel
28=Oldenburg
29=Dortmond
30=Magdeburg
31=Hornburg
32=Steyr
33=Trier
34=Nordhorn
35=Basel
36=Ursella
37=Frankfurt
38=Jomsborg
39=Birka
40=Ribe
41=Jorvik
42=Vallhagar
43=Truso
44=Grimsby
45=Viborg
46=Holmgard
47=Vineta
48=Kaupang
49=Sigtuna
50=Lund
51=Aarhus
52=Odense
53=Bergen
54=Uppsala
55=Trondheim
56=Skara
57=Borgund
58=Reval
59=Stavanger
[1]
; Beastman, using ancient mesopotamian city names
0=Adab
1=Badtibira
2=Eridu
3=Isin
4=Larsa
5=Sippar
6=Umma
7=Anat
8=Kazallu
9=Kurbail
10=Akkade
11=Borsippa
12=Esnunna
13=Karkar
14=Maltai
15=Mari
16=Amidu
17=Sikanni
18=Enegi
19=Kes
20=Arbela
21=Girsu
22=Kis
23=Konoso
24=Rapiqu
25=Suruppag
26=Urfa
27=Eres
28=Kiabrig
29=Ugarit
30=Qatna
31=Der
32=Guzana
33=Kutha
34=Nippur
35=Telloh
36=Taidu
37=Gaes
38=Kiritab
39=Niya
40=Kalhu
41=Ebla
42=Harran
43=Lagas
44=Nuzi
45=Terqa
46=Sirqu
47=Gisbanda
48=Kisiga
49=Tummal
50=Kabnak
51=Emar
52=Huzirina
53=Larak
54=Puzrisdagan
55=Tuttul
56=Akkil
57=Irisagrig
58=Kuara
59=Zabban
[2]
; Dark Elf, take city names from Tolkien, Warhammer, Forgotten Realms, Warcraft
0=Leer
1=Amon Lanc
2=Tyrlinith
3=Suldanessellar
4=Arairia
5=Anlec
6=Achare
7=Yvresse
8=Athamault
9=Xorhun
10=Glaurachyndaar
11=Iecta
12=Ebenia
13=Arcadia
14=Gondola
15=Thanelorn
16=Anamarathor
17=Athel Maraya
18=Narathmault
19=Adderax
20=Gothemoth
21=Meraluna
22=Mandragora
23=Nysa
24=Telogrus
25=Athel Tamarha
26=Dimmuborgir
27=Lothlac
28=Adofhaeranede
29=Lilitu
30=Amara
31=Mhiilamniir
32=Reitheillaethor
33=Aruanda
34=Darnassus
35=Gaenvale
36=Nemo
37=Ascarle
38=Rucien Xan
39=Eldrethalas
40=Selenora
41=Luxuaria
42=Mystinia
43=Opalus
44=Umbrica
45=Melastirith
46=Nerome
47=Suspiriu
48=Tilindhet
49=Narthalas
50=Rhymanthiin
51=Faertelmiir
52=Aelinthaldaar
53=Nevaeh
54=Zin Azshari
55=Nadir
56=Anroc
57=Cendriane
58=Tintageer
59=Tuat
[3]
 Draconian, city named after dragon-like creatures
0=Illuyaka
1=Tinnin
2=Falak
3=Bahamut
4=Bashe
5=Gongong
6=Abzu
7=Mushussu
8=Tiamat
9=Apalala
10=Kaliya
11=Pakhangba
12=Vritra
13=Antaboga
14=Marraco
15=Fafnir
16=Graoully
17=Guivre
18=Herensuge
19=Jormungandr
20=Zilant
21=Carcolh
22=Oillipheist
23=Lotan
24=Azhdaha
25=Zahhak
26=Agorghan
27=Bakunawa
28=Lawu
29=Olimaw
30=Sawa
31=Samal
32=Kanlaon
33=Kur
34=Nidhoggr
35=Ejderha
36=Erenkyl
37=Bolla
38=Typhon
39=Kulshedra
40=Lindwyrm
41=Dreq
42=Tatzelwurm
43=Zmeu
44=Tarasque
45=Peluda
46=Knucker
47=Pukys
48=Krukis
49=Ladon
50=Amphisbaena
51=Fernyiges
52=Sarkany
53=Zomok
54=Tarantasio
55=Cuelebre
56=Slibinas
57=Aitvaras
58=Balaur
59=Yilbegan
[4]
; Dwarves mostly using names from Tolkien and Warhammer fantasy
0=Gundabad
1=Ultigar
2=Pyre
3=Bhufdar
4=Barkavarr
5=Ekrund
6=Ammarindar
7=Abanax
8=Izor
9=Agin
10=Thrund
11=Tyrfaerath
12=Karazakarak
13=Ankor
14=Azorn
15=Fraaszummdin
16=Hirn
17=Zanhoriloch
18=Lumbar
19=Nulbaraz
20=Krum
21=Drazh
22=Eksfilaz
23=Dorden
24=Gantuk
25=Intun
26=Kazaddum
27=Norn
28=Nidavellir
29=Gabilgathol
30=Agartha
31=Tumunzahar
32=Ghumzul
33=Sareda
34=Stostethorp
35=Zhufbar
36=Dronar
37=Zarakzil
38=Grom
39=Kadrin
40=Anis
41=Nulukkhizdin
42=Kaferkammaz
43=Ungor
44=Vlag
45=Orrud
46=Angazhar
47=Angkul
48=Azgal
49=Azgaraz
50=Vanrugh
51=Varn
52=Zanda
53=Ziflin
54=Erebor
55=Dinladuhr
56=Ornsmotek
57=Ravnsvake
58=Boldahr
59=Uzkulak
[5]
; Gnoll mostly using germanized slavic city names
0=Wismar
1=Danzig
2=Potsdam
3=Breslau
4=Brunn
5=Leipzig
6=Prague
7=Budweis
8=Olmutz
9=Posen
10=Dresden
11=Turku
12=Tarbatu
13=Aussig
14=Pardubitz
15=Zlin
16=Kladen
17=Brux
18=Troppau
19=Ostrau
20=Pilsen
21=Lysogora
22=Krakau
23=Lodzia
24=Iglau
25=Teplitz
26=Karwin
27=Tetschen
28=Komotau
29=Gablonz
30=Menges
31=Prossnitz
32=Jungbunzlau
33=Prerau
34=Trzynietz
35=Bilohiria
36=Ungvar
37=Lodomeria
38=Galitsch
39=Osha
40=Gardinas
41=Bresta
42=Yama
43=Tor
44=Warsau
45=Wilna
46=Kaunas
47=Lublin
48=Kattowitz
49=Gdingen
50=Radom
51=Memel
52=Oppeln
53=Volin
54=Kalisch
55=Liegnitz
56=Stolp
57=Kunau
58=Luben
59=Turau
[6]
; Halfling, kept they as they currently are
0=Miroban
1=Eastway
2=Palaor
3=Elyndendale
4=Cornwell
5=Jollyville
6=Hickorydale
7=Hialanth
8=Ethridge
9=Myrean
10=Mirndale
11=Honeypool
12=Eventon
13=Sunnydale
14=Bunnydale
15=Sacred Vale
16=Medowdale
17=Cornberry
18=Hillshire
19=Torwell
20=Twigwater
21=Willow
22=South Ribble
23=Lemontree
24=Glenfiddich
25=Underhill
26=Shieldhill
27=Townhill
28=Thornhill
29=Waterfoot
30=Tullibody
31=Thornton
32=Smithton
33=Rosewell
34=Mossblown
35=Mayfield
36=Livingston
37=Greenhill
38=Crysxton
39=Bunhill
40=Bothwell
41=Cheshire
42=Bellshill
43=Dunedin
44=Hempshire
45=Littleton
46=Smallville
47=Summerdale
48=Hammockdale
49=Pleasantville
50=Summerglen
51=Shimmerbury
52=Rosehost
53=Stillfair
54=Honeyband
55=Earthmeadow
56=Dewwell
57=Littleford
58=Damerel
59=Two Rivers
[7]
; High Elf, take city names from Tolkien, Warhammer, Forgotten Realms, Warcraft
0=Sirion
1=Forlond
2=Harlond
3=Vinyamar
4=Lothern
5=Cormanthor
6=Nordahaeril
7=Dynal
8=Rhynn
9=Lylros
10=Lanerell
11=Formenos
12=Kortirion
13=Dol Guldur
14=Elithis
15=Avallone
16=Elyr
17=Ruith
18=Caled
19=Bristar
20=Brithombar
21=Menegroth
22=Karyndis
23=Sharandar
24=Sharlarion
25=Amol
26=Galdor
27=Iriy
28=Onthrilaenthor
29=Aluinn
30=Caras Galadhon
31=Elysion
32=Nargothrond
33=Mithlond
34=Eldroth
35=Annwyn
36=Asphodel
37=Oeragor
38=Telardon
39=Hoeth
40=Edhelond
41=Imladris
42=Suramar
43=Ostinedhil
44=Auseriel
45=Akherynnar
46=Yrlaancel
47=Lithanel
48=Therion
49=Ellahana Raikeil
50=Eglarest
51=Gondolin
52=Tavrobel
53=Saphethion
54=Chrysalis
55=Lothlorien
56=Lhahast
57=Cairn Auriel
58=Tirion
59=Nordrassil
[8]
; High Man using british city names
0=Coventry
1=York
2=Nottingham
3=Birmingham
4=Dover
5=Liverpool
6=Brighton
7=Oxford
8=Reading
9=Exeter
10=Cambridge
11=Hastings
12=Canterbury
13=Banbury
14=Newcastle
15=Haven
16=Tintagel
17=Greenwich
18=Denislin
19=Newland
20=Lichfield
21=Manchester
22=Norwich
23=Montgomery
24=Durham
25=Leeds
26=Oldham
27=Sunderland
28=Leicester
29=Glastonbury
30=Truro
31=Dudley
32=Cardiff
33=Goodwitch
34=Preston
35=Salisbury
36=Camelot
37=Wells
38=Colchester
39=Winchester
40=Edinburgh
41=Carlisle
42=Stamford
43=Stirling
44=Lancester
45=Windsor
46=Gloucester
47=Chester
48=Badbury
49=Sandwich
50=Bristol
51=Hereford
52=Worcester
53=Lincoln
54=Perth
55=Plymouth
56=Chichester
57=Ely
58=Sheffield
59=Chelmsford
[9]
; Klackon using ancient egyptian city names
0=Tjebu
1=Mennefer
2=Shashotep
3=Khem
4=Henennesut
5=Zawty
6=Rapote
7=Qis
8=Akhetaten
9=Khemenu
10=Khito
11=Herwer
12=Hebenu
13=Tayudjayet
14=Ptkheka
15=Zau
16=Buhen
17=Khasut
18=Timinhor
19=Piemro
20=Thonis
21=Pikuat
22=Djedu
23=Hutheryib
24=Taremu
25=Setennu
26=Pachnamunis
27=Bukit
28=Saka
29=Tjaru
30=Weprehwy
31=Tamiat
32=Djedet
33=Semabehdet
34=Tepihu
35=Djanet
36=Hutwaret
37=Shedet
38=Abu
39=Swenett
40=Nubt
41=Behdet
42=Nekheb
43=Nekhen
44=Tasenet
45=Waset
46=Iken
47=Iuny
48=Sumenu
49=Djerty
50=Madu
51=Iushenshen
52=Gesy
53=Gebtu
54=Iunet
55=Seshesh
56=Abdju
57=Tjenu
58=Ipu
59=HutRepyt
[10]
; Lizardman, use city names from ancient cities in southeast Asia
0=Angkor
1=Kulen
2=Hariharalaya
3=Da
4=Sdok Kok
5=Borei
6=Srei
7=Champassak
8=Pimai
9=Sri Thep
10=Lawo
11=U Thong
12=Chaiya
13=Singora
14=Strung Treng
15=Wiangjun
16=Martaban
17=Pegu
18=Dagon
19=Thaton
20=Kauthara
21=Panduranga
22=Vijaya
23=Prei Nokor
24=Ta Muen
25=Bakheng
26=Krom
27=Bok
28=Koh Ker
29=Pre Rup
30=Rung
31=Bat Chum
32=Kdei So
33=Ta Keo
34=Chhmar
35=Ta Prohm
36=Trowulan
37=Chaktomuk
38=Lamphun
39=Tavoy
40=Moulein
41=Pattani
42=Tenasserim
43=Longvek
44=Kawali
45=Pamatan
46=Pakuan
47=Si Tep
48=Khu Bua
49=Tam
50=Kum Kam
51=Sambor
52=Cattigara
53=Banam
54=Temu
55=Preah Vihear
56=Chisor
57=Bakan Svay
58=Sikhoraphum
59=Ta Krabey
[11]
; Nomad, use arab and iranian cities names as were used by classical sources
0=Macoraba
1=Carthage
2=Sidon
3=Tyre
4=Tarsus
5=Byblos
6=Dumatha
7=Bostra
8=Palmyra
9=Hemesa
10=Cirta
11=Gades
12=Utica
13=Damascus
14=Malaca
15=Salamis
16=Tingis
17=Oea
18=Garama
19=Augila
20=Petra
21=Maracanda
22=Casia
23=Iathrippa
24=Zanzibar
25=Gerrha
26=Sabatha
27=Chach
28=Singara
29=Gazaca
30=Ecbatana
31=Hecatompylos
32=Chorasmia
33=Chaurana
34=Nisaia
35=Zadracarta
36=Istakhr
37=Karmana
38=Harmozeia
39=Mariaba
40=Phrada
41=Cufis
42=Zarang
43=Tusa
44=Capisa
45=Kophen
46=Bactra
47=Tarmita
48=Drapsaka
49=Chatracharta
50=Aspacara
51=Tyana
52=Sardis
53=Ancyra
54=Sinope
55=Issedon
56=Throana
57=Cumuda
58=Mazaka
59=Beroia
[12]
; Orc, using roman city names, emhasis on male end-heavy sound
0=Arretium
1=Ariminum
2=Auximum
3=Clusium
4=Sutrium
5=Antium
6=Saepinum
7=Misenum
8=Metapontum
9=Histonium
10=Iuvanum
11=Epidaurum
12=Dyrrachium
13=Corinthus
14=Peiraieus
15=Saguntum
16=Selinus
17=Soluntum
18=Tauromenium
19=Rhugium
20=Canusium
21=Nemausus
22=Lucentum
23=Toletum
24=Brigaecium
25=Avaricum
26=Cenabum
27=Limnoum
28=Darioritum
29=Vorgium
30=Mediolanum
31=Octodurus
32=Tridentium
33=Iuvavum
34=Cambodunum
35=Virunum
36=Volgum
37=Metulum
38=Parentium
39=Splonum
40=Domavium
41=Sirmium
42=Margum
43=Tibiscum
44=Apulum
45=Deultum
46=Durostorum
47=Arbitus
48=Oescus
49=Naissus
50=Rusazus
51=Noviomagus
52=Durovernum
53=Moridunum
54=Lindum
55=Isurium
56=Luguvalium
57=Gesoriacum
58=Bagacum
59=Mogontiacum
[13]
; Troll, using southern bantu language place names in southern Africa
0=Dukuza
1=Mbazwana
2=Obonjeni
3=Ezulwini
4=Idutywa
5=lmbali
6=Ncwadi
7=Umgungundlovu
8=Mankayane
9=Umzimkulu
10=Eshowe
11=Moyeni
12=Thekwini
13=Golela
14=Langa
15=Imbubo
16=Ndwedwe
17=Umhlali
18=Mbabane
19=Zwelitsha
20=Hlobane
21=Mpemvana
22=Ubombo
23=Hhohho
24=Mqanduli
25=Magudu
26=Ngagane
27=Umzinto
28=Belekazana
29=Tembisa
30=Impendle
31=Mpumalanga
32=Uhlawe
33=Hlatikulu
34=Nyanga
35=Mahlabatini
36=Nkandla
37=Utago
38=Bisho
39=Thabazimbi
40=Isando
41=Mtubatuba
42=Ulundi
43=Hluti
44=Tabankulu
45=Maseru
46=Nongoma
47=Bulembu
48=Bongolethu
49=Cedara
50=Ixopo
51=Mtunzini
52=Umbumbulu
53=Lobamba
54=Umtata
55=Mapumulo
56=Nqutu
57=Mmabatho
58=Engcobo
59=Emanzana
[22]
; Xuanyuan, using ancient chinese city names
0=Linzi
1=Changan
2=Fenghao
3=Hetu
4=Jiankang
5=Jicheng
6=Shangdu
7=Xiadu
8=Xianyang
9=Xuchang
10=Yangcheng
11=Diqiu
12=Yinxu
13=Yueyang
14=Zhaoge
15=Zhenxun
16=Dishi
17=Henglong
18=Shangqiu
19=Liye
20=Luodai
21=Miran
22=Zongzhou
23=Shanghu
24=Shicheng
25=Qinghua
26=Wangcheng
27=Xiangzhou
28=Pingyang
29=Puban
30=Chengzhou
31=Yangmei
32=Zhuxian
33=Shangjing
34=Anyang
35=Hechuan
36=Laoqiu
37=Yanjing
38=Dadu
39=Shuntian
40=Changchun
41=Qiongshi
42=Datong
43=Emin
44=Fenghao
45=Haojing
46=Daliang
47=Yuanqu
48=Bianjing
49=Jianye
50=Jiankang
51=Yingtian
52=Tianjing
53=Daxia
54=Yinchuan
55=Yingchang
56=Zhaoqing
57=Wanqiu
58=Qiongsang
59=Gaoyang
[23]
; Rakhshasa, use ancient indian city names
0=Amaravatin
1=Patalam
2=Mithilam
3=Bhattiprolun
4=Pushpagirin
5=Dialgam
6=Shravastin
7=Anantnag
8=Ujjayinin
9=Elurun
10=Vijayawadam
11=Bhojakatam
12=Abimanyupuram
13=Ghantasalam
14=Anjanerin
15=Ahichchhatram
16=Nalandam
17=Pataliputram
18=Bijbeharam
19=Rajapuram
20=Hastinapuram
21=Tamraliptam
22=Asurgaram
23=Vaishalin
24=Kampilam
25=Janakapuram
26=Bithooram
27=Madhepuram
28=Kanchipuram
29=Mohanavatin
30=Angam
31=Mahishmatin
32=Kapilavastun
33=Pithapuram
34=Champapuram
35=Sagalam
36=Tosalin
37=Ayodhyam
38=Vanchin
39=Kosambin
40=Muthathin
41=Chitrakoot
42=Nasikam
43=Kundinapuram
44=Pushkalavatin
45=Akingam
46=Malinipuram
47=Kushavatin
48=Prasthalam
49=Dharanikotam
50=Sankissam
51=Kushinagaram
52=Tulambam
53=Barsanam
54=Takshashilam
55=Shringverpuram
56=Dachnipuram
57=Dwarkam
58=Lakipuram
59=Mathuram
[24]
; Hawkmen, use precolumbian city names
0=Teotihuacan
1=Palenque
2=Tikal
3=Machu Pichu
4=Chichen Itza
5=Mictlan
6=Titicaca
7=Cuzco
8=Nakbe
9=Chocola
10=Uxmal
11=Coba
12=Mayapan
13=Xalapa
14=Texcoco
15=Azcapotzalco
16=Tlacopan
17=Tlaxcala
18=Amecameca
19=Chalco
20=Tenochtitlan
21=Tenayuca
22=Colhuacan
23=Chapultepec
24=Coyoacan
25=Xochimilco
26=Cholula
27=Cuahnahuac
28=Tollocan
29=Tatanka
30=Cahokia
31=Tehuantepec
32=Tecuzalco
33=Vilcabamba
34=Tepexpan
35=Cuicuilco
36=Motul
37=Tepoztlan
38=Cuzcatlan
39=Teonanacatl
40=Acoma
41=Popocatepetl
42=Chalcatzingo
43=Cibola
44=Hawikuh
45=Nojpeten
46=Tlatelolco
47=Stadacona
48=Kanata
49=Aztalan
50=Huamanga
51=Tiwanaku
52=Iskanwaya
53=Oroncota
54=Huaricanga
55=Paititi
56=Chan Chan
57=Xauxa
58=Cajamarca
59=Tumebamba
[25]
; Goblin, city names based on mushroom in japanese
0=Shirohaka
1=Tsukuri
2=Matsu
3=Fuusen
4=Morihara
5=Haetori
6=Kikurage
7=Yamadori
8=Enoki
9=Buna
10=Uramurasaki
11=Akahatsu
12=Akamomi
13=Chichi
14=Aikawa
15=Hanahouki
16=Amigasa
17=Hira
18=Muki
19=Kabairo
20=Hotei
21=Shii
22=Eringi
23=Tamoji
24=Usuhira
25=Saketsuba
26=Nameko
27=Arage
28=Hanagasa
29=Iwa
30=Fukuro
31=Meshimakobu
32=Tsurigane
33=Mannen
34=Sugihira
35=Hata
36=Kuri
37=Karahatsu
38=Kenawa
39=Benitengu
40=Nigikuri
41=Keshou
42=Kirinomi
43=Kaki
44=Hitoyo
45=Himehouki
46=Tsukiyo
47=Abura
48=Bakamatsu
49=Kogane
50=Kurohatsu
51=Karakasa
52=Ami
53=Manjuugasa
54=Amihira
55=Anzu
56=Aohatsu
57=Chahouki
58=Daikoku
59=Fujiiro
