; Note : maximal amount of retorts supported is 3 per wizard
[1]
; "Merlin" - originally myth of Merlin, he is not "the sage" but "the seer"
Nature=5
Life=5
Retort1=Astrologer
Hand=1
Voice=36
[2]
; "Sss'ra" chnage to "Druk'gyalpo" - "Druk Gyalpo" mean thunder dragon king, title of king of Bhutan, already good, stay the same
Chaos=5
Life=5
Retort1=Myrran
Retort2=Sage Master
Hand=6
Voice=35
[3]
; "Raven" change to "Tadodaho" - great medicineman and highest spiritual leader of Iroquois, Sorcery and Nature could use Runemaster well
Sorcery=6
Nature=5
Retort1=Runemaster
Hand=1
Voice=36
[4]
; "Tauron" change to "Idris" - "the Ardent Lord" is more suitable name for chaos channeller
Chaos=10
Retort1=Channeler
Hand=1
Voice=35
[5]
; "Sharee" change to "Iansa" - Oya-Iyansan is yoruba's orisha of winds, ligthning, violent storms, death, and rebirth. already good, stay the same
Chaos=5
Death=6
Retort1=Conjurer
Hand=3
Voice=34
[6]
; "Freya" - already good, stay the same
Nature=10
Retort1=Guardian
Hand=2
Voice=34
[7]
; "Lo Pan" change to "Kongming" - Zhuge Ling "Kongming" from RoTK is famous as strategist
Sorcery=5
Chaos=5
Retort1=Tactician
Hand=1
Voice=36
[8]
; "Horus" change to "Hadriex"
Sorcery=2
Nature=2
Chaos=2
Life=2
Death=2
Retort1=Procurator
Retort2=Archmage
Hand=1
Voice=36
[9]
; "Jafar" - "Ja'far ibn Yahya", vizer of Harun al-Rashid, descendent of chief priest family of Zoroastrian/Buddhist (Manichean in disguise?) temple in Central Asia and has reputation as patrons of sciences, pure sorcery realm not suitable for warlord retort so change to sage master and archmage
Sorcery=10
Retort1=Alchemist
Hand=1
Voice=35
[10]
; "Ariel" - name of Jewish/Christian angel of creation who has power over earth and air, in Gnostism identify Ariel with Demiurge, as runemaster moved to Raven so give her famous and charismatic instead
Life=10
Retort1=Charismatic
Retort2=Benefactor
Hand=2
Voice=34
[11]
; "Oberic" - Archeic form of "Oberon" wizard king of the elves/dwarves, give him warlord instead of Jafar
Nature=5
Chaos=5
Retort1=Warlord
Hand=5
[12]
; "Tlaloc" - Mexican god of rain and fertility, already good, stay the same
Nature=5
Death=6
Retort1=Cult Leader
Hand=4
Voice=36
[13]
; "Rjak" change to "Resheph" - Sun of Underworld, Resheph is canaanite god of war and plague/pestilence
Death=10
Retort1=Enchanter
Hand=1
Voice=36
[14]
; "Kali" change to "Grimhildr" - Sorceress queen in many Norse sagas and name of Snow White's evil queen and her mirror suit artificer well
Sorcery=6
Death=5
Retort1=Artificer
Hand=2
Voice=34
