[Maindata]
AIPrimaryRetortChance=50
[1]
; Nature
Primary=6
Secondary=16
[2]
; Sorcery
Primary=10
Secondary=4
[3]
; Chaos
Primary=7
Secondary=15
[4]
; Life
Primary=8
Secondary=14
[5]
; Death
Primary=12
Secondary=8
[6]
; Nature Sorcery
Primary=16
Secondary=10
[7]
;Nature Chaos
Primary=2
Secondary=18
[8]
; Nature Life
Primary=6
Secondary=2
[9]
; Nature Death
Primary=1
Secondary=12
[10]
; Sorcery Chaos
Primary=14
Secondary=1
[11]
; Sorcery Life
Primary=1
Secondary=13
[12]
; Sorcery Death
Primary=7
Secondary=8
[13]
; Chaos Life
Primary=4
Secondary=14
[14]
; Chaos Death
Primary=10
Secondary=9
[15]
; Death Life
Primary=17
Secondary=12
