[System]
; Number of animations to load from this file, up to 500
Total=1
[1]
; File name for the image files. Extension must be .PNG.
Name=Ice_Ball
; Last animation frame file to load (first is 0. Highest allowed = 1000)
LastFrame=15
; The spell's effect is applied the first time this frame is displayed
TriggerFrame=11
; How many game ticks the animation frame is displayed for. (assuming 30 FPS)
Frame0T=4
; The X and Y position adjustment compared to the center
Frame0X=81
Frame0Y=-110

Frame1T=4
Frame1X=73
Frame1Y=-102

Frame2T=4
Frame2X=65
Frame2Y=-94

Frame3T=4
Frame3X=53
Frame3Y=-86

Frame4T=4
Frame4X=45
Frame4Y=-78

Frame5T=4
Frame5X=37
Frame5Y=-70

Frame6T=4
Frame6X=29
Frame6Y=-62

Frame7T=4
Frame7X=21
Frame7Y=-54

Frame8T=4
Frame8X=13
Frame8Y=-46

Frame9T=4
Frame9X=5
Frame9Y=-38

Frame10T=4
Frame10X=-6
Frame10Y=-30

Frame11T=2
Frame11X=-6
Frame11Y=-23

Frame12T=2
Frame12X=-6
Frame12Y=-23

Frame13T=2
Frame13X=-6
Frame13Y=-23

Frame14T=2
Frame14X=-6
Frame14Y=-23

Frame15T=2
Frame15X=-6
Frame15Y=-23
