; When modding buildings, please be aware that having too many buildings displayed at
; the same time might lead to the last building(s) having no room left to display.
; Starting from version 1.2.0, this will not freeze the game anymore but the building won't
; be displayed, so the player cannot sell it, so keeping the size and amount of buildings
; low enough to display them all is strongly recommended, if necessary, by using the "replaces" feature more often.
;
; AIBuyPrio is how many times the buying price the AI needs to own in gold to buy the building.
; AIEarlyBuyPrio is same for cities below 7000 population.
; Both default to 100 if not included. These only affect whether the AI spends gold to produce these faster.
; For decisions on what to build, see AIProd.CAS and AIBuilding.CAS
;
; Set Fortress=1 for buildings you want players to have in their starting city.
; Set Outpost=1 for buildings you want players to have in new outposts.
[1]
Name=Trade Goods
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=0
[2]
Name=Housing
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=0
X=1
Y=1
Vizier=0
VizierMilitary=0
AnimationFrames=2
[3]
Name=Barracks
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=125
X=2
Y=2
Vizier=0
VizierMilitary=73
AnimationFrames=8
[4]
Name=Colosseum
Requirement1=3
Requirement2=8
Replaces=0
Upkeep=0
Cost=250
X=2
Y=2
Vizier=0
VizierMilitary=30
AnimationFrames=0
[5]
Name=Fighter's Guild
Requirement1=8
Requirement2=0
Replaces=8
Upkeep=4
Cost=330
X=3
Y=1
Vizier=0
VizierMilitary=73
AnimationFrames=8
AIBuyPrio=4
AIEarlyBuyPrio=4
[6]
Name=Armorer's Guild
Requirement1=5
Requirement2=0
Replaces=5
Upkeep=6
Cost=400
X=2
Y=1
Vizier=0
VizierMilitary=60
AnimationFrames=8
Tree=1
[7]
Name=War College
Requirement1=3
Requirement2=0
Replaces=3
Upkeep=2
Cost=450
X=2
Y=1
Vizier=0
VizierMilitary=55
AnimationFrames=0
[8]
Name=Smithy
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=125
X=2
Y=1
Vizier=20
VizierMilitary=80
AnimationFrames=8
AIBuyPrio=2
AIEarlyBuyPrio=2
Fortress=1
Outpost=1
[9]
Name=Stables
Requirement1=8
Requirement2=0
Replaces=0
Upkeep=2
Cost=60
X=3
Y=1
Vizier=0
VizierMilitary=80
AnimationFrames=8
[10]
Name=Animist's Guild
Requirement1=29
Requirement2=31
Replaces=31
Upkeep=3
Cost=240
X=2
Y=1
Vizier=60
VizierMilitary=60
AnimationFrames=0
[11]
Name=Fantastic Stable
Requirement1=9
Requirement2=5
Replaces=9
Upkeep=5
Cost=500
X=2
Y=1
Vizier=0
VizierMilitary=58
AnimationFrames=8
Tree=1
[12]
Name=Ship Yard
Requirement1=110
Requirement2=0
Replaces=0
Upkeep=1
Cost=50
X=1
Y=1
Vizier=40
VizierMilitary=60
AnimationFrames=0
OnShore=1
[13]
Name=Magic Market
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=2
Cost=72
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
AIBuyPrio=100
AIEarlyBuyPrio=1
[14]
Name=Maritime Guild
Requirement1=5
Requirement2=12
Replaces=12
Upkeep=5
Cost=370
X=1
Y=1
Vizier=0
VizierMilitary=20
AnimationFrames=8
OnShore=1
[15]
Name=Sawmill
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=4
Cost=68
X=2
Y=1
Vizier=100
VizierMilitary=100
AnimationFrames=8
AIBuyPrio=4
AIEarlyBuyPrio=1
Fortress=1
[16]
Name=Library
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=1
Cost=60
X=3
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[17]
Name=Sage's Guild
Requirement1=16
Requirement2=0
Replaces=16
Upkeep=4
Cost=300
X=2
Y=1
Vizier=60
VizierMilitary=60
AnimationFrames=0
[18]
Name=Oracle
Requirement1=22
Requirement2=32
Replaces=0
Upkeep=3
Cost=300
X=2
Y=1
Vizier=30
VizierMilitary=30
AnimationFrames=0
ScoutingRange=4
[19]
Name=Alchemist's Guild
Requirement1=16
Requirement2=0
Replaces=0
Upkeep=3
Cost=100
X=1
Y=1
Vizier=70
VizierMilitary=70
AnimationFrames=8
AIBuyPrio=4
AIEarlyBuyPrio=4
[20]
Name=University
Requirement1=32
Requirement2=0
Replaces=32
Upkeep=3
Cost=120
X=3
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[21]
Name=Wizard's Guild
Requirement1=13
Requirement2=0
Replaces=13
Upkeep=5
Cost=600
X=1
Y=1
Vizier=55
VizierMilitary=55
AnimationFrames=8
AIBuyPrio=4
AIEarlyBuyPrio=4
[22]
Name=Shrine
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=1
Cost=120
X=2
Y=1
Vizier=60
VizierMilitary=60
AnimationFrames=0
[23]
Name=Amplifying Tower
Requirement1=19
Requirement2=0
Replaces=19
Upkeep=12
Cost=600
X=2
Y=1
Vizier=58
VizierMilitary=55
AnimationFrames=0
AIBuyPrio=4
AIEarlyBuyPrio=4
[24]
Name=Parthenon
Requirement1=32
Requirement2=0
Replaces=0
Upkeep=2
Cost=200
X=3
Y=3
Vizier=80
VizierMilitary=80
AnimationFrames=0
[25]
Name=Cathedral
Requirement1=22
Requirement2=0
Replaces=22
Upkeep=2
Cost=400
X=2
Y=2
Vizier=58
VizierMilitary=58
AnimationFrames=0
[26]
Name=Marketplace
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=80
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
AIBuyPrio=100
AIEarlyBuyPrio=1
[27]
Name=Bank
Requirement1=32
Requirement2=26
Replaces=26
Upkeep=2
Cost=200
X=2
Y=1
Vizier=60
VizierMilitary=60
AnimationFrames=0
[28]
Name=Merchant's Guild
Requirement1=12
Requirement2=32
Replaces=0
Upkeep=3
Cost=400
X=2
Y=1
Vizier=40
VizierMilitary=60
AnimationFrames=0
[29]
Name=Granary
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=2
Cost=80
X=1
Y=1
Vizier=80
VizierMilitary=70
AnimationFrames=0
[30]
Name=Farmer's Market
Requirement1=29
Requirement2=26
Replaces=29
Upkeep=3
Cost=180
X=2
Y=1
Vizier=80
VizierMilitary=60
AnimationFrames=0
[31]
Name=Forester's Guild
Requirement1=101
Requirement2=15
Replaces=15
Upkeep=1
Cost=130
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[32]
Name=Builder's Hall
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=0
Cost=20
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[33]
Name=Mechanician Guild
Requirement1=20
Requirement2=34
Replaces=0
Upkeep=3
Cost=200
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[34]
Name=Miner's Guild
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=2
Cost=120
X=2
Y=1
Vizier=80
VizierMilitary=80
AnimationFrames=0
[35]
Name=Monument
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=1
Cost=72
X=1
Y=1
Vizier=70
VizierMilitary=75
AnimationFrames=0
AIBuyPrio=100
AIEarlyBuyPrio=1
[36]
Name=Linking Towers
Requirement1=35
Requirement2=16
Replaces=35
Upkeep=5
Cost=400
X=2
Y=1
Vizier=35
VizierMilitary=45
AnimationFrames=0
Tree=1
AIBuyPrio=4
AIEarlyBuyPrio=4
[37]
Name=City Walls
Requirement1=0
Requirement2=0
Replaces=0
Upkeep=1
Cost=75
X=1
Y=1
Vizier=0
VizierMilitary=73
AnimationFrames=0
IsWall=1
ScoutingRange=3
