; Individual hero names
[0]
Name1=Brax
Name2=Dolgin
Name3=Grendel
Name4=Beorn
Name5=Flynn
Name6=Fafnir
Name7=Sindre
Name8=Durinn
Name9=Otr
Name10=Dvalinn
Name11=Grimr
Name12=Kili
Name13=Ori
Name14=Vegdrasill
[1]
Name1=Gunther
Name2=Wolfar
Name3=Angus
Name4=Fritz
Name5=Brennus
Name6=Kurt
Name7=Gunnar
Name8=Hartwig
Name9=Igor
Name10=Conor
Name11=Klaus
Name12=Hans
Name13=Morgen
Name14=Attila
[2]
Name1=Zaldron
Name2=Jesrael
Name3=Sardon
Name4=Tiberius
Name5=Zorin
Name6=Zabrim
Name7=Joshua
Name8=Elijah
Name9=Noah
Name10=Ezekiel
Name11=Sardor
Name12=Sargon
Name13=Luciano
Name14=Zoltan
[3]
Name1=B'Shan
Name2=Abdul
Name3=Shaza
Name4=Fazeel
Name5=Wizier
Name6=Ali
Name7=Hamza
Name8=Hassan
Name9=Suleiman
Name10=Aziz
Name11=Hodja
Name12=Faruk
Name13=Said
Name14=Amir
[4]
Name1=Rakir
Name2=Salkirg
Name3=Wyn
Name4=Reya
Name5=Fleir
Name6=Tvar
Name7=Gaynar
Name8=Smiargon
Name9=Yrkon
Name10=Moongum
Name11=Jangren
Name12=Airir
Name13=Ailean
Name14=Duncan
[5]
Name1=Valana
Name2=Lauren
Name3=Lidia
Name4=Veronica
Name5=Adrianna
Name6=Mischa
Name7=Lou
Name8=Tanja
Name9=Aischa
Name10=Josephine
Name11=Michelle
Name12=Joleen
Name13=Marian
Name14=Matilda
[6]
Name1=Baghtru
Name2=Rockfist
Name3=Yaga
Name4=Maktu
Name5=Orgaak
Name6=Gonk
Name7=Borgakh
Name8=Ugak
Name9=Poogugh
Name10=Oguk
Name11=Urug
Name12=Gnabadug
Name13=Durak
Name14=Bierauge
[7]
Name1=Serena
Name2=Shardis
Name3=Sasha
Name4=Karla
Name5=Anastasia
Name6=Theresa
Name7=Celestria
Name8=Althea
Name9=Rafaela
Name10=Shaushka
Name11=Alyona
Name12=Ester
Name13=Yulia
Name14=Minerva
[8]
Name1=Shuri
Name2=Artemis
Name3=Shanna
Name4=Umalla
Name5=Farra
Name6=Akari
Name7=Shiori
Name8=Yuki
Name9=Yuna
Name10=Devana
Name11=Eagleeye
Name12=Atlantina
Name13=Cyrene
Name14=Fianna
[9]
Name1=Theria
Name2=Shadow
Name3=Misty
Name4=Doria
Name5=Tamara
Name6=Beretta
Name7=Claudia
Name8=Dagger
Name9=Vixen
Name10=Medea
Name11=Trixie
Name12=Sarka
Name13=Ruse
Name14=Rebecca
[10]
Name1=Greyfairer
Name2=Tholin
Name3=Greenleaf
Name4=Blackhawk
Name5=Feylass
Name6=Athol
Name7=Barclay
Name8=Bernard
Name9=Duncan
Name10=Errol
Name11=Crazyhorse
Name12=Fingal
Name13=Ian
Name14=Redcloud
[11]
Name1=Taki
Name2=Quai
Name3=Chang
Name4=Tonaga
Name5=Enendo
Name6=Tao
Name7=Mondo
Name8=Aomi
Name9=Chai
Name10=Dong
Name11=Zhong
Name12=Cheng
Name13=Tai
Name14=Tako
[12]
Name1=Reywind
Name2=Stalkaor
Name3=Darius
Name4=Wylas
Name5=Deamond
Name6=Gilmore
Name7=Desmond
Name8=Darian
Name9=Baksis
Name10=Milad
Name11=Norul
Name12=Safan
Name13=Merewald
Name14=Oswin
[13]
Name1=Malleus
Name2=Delian
Name3=Furius
Name4=Karnak
Name5=Landreux
Name6=Brantley
Name7=Brenton
Name8=Aiden
Name9=Kai
Name10=Blaze
Name11=Ignatius
Name12=Kenneth
Name13=Brent
Name13=Brando
Name14=Ignacio
[14]
Name1=Tumu
Name2=Altahza
Name3=Shaka
Name4=Huracus
Name5=Kaizlar
Name6=Tumo
Name7=Talib
Name8=Sadik
Name9=Obi
Name10=Rafiki
Name11=Leto
Name12=Joda
Name13=Kafu
Name14=Dobagnus
[15]
Name1=Jaer
Name2=Graydon
Name3=Aquilon
Name4=Shadowin
Name5=Arcus
Name6=Jael
Name7=Jarlath
Name8=Graham
Name9=Flint
Name10=Rune
Name11=Brendon
Name12=Elton
Name13=Garrik
Name14=Nodin
[16]
Name1=Marcus
Name2=Cassius
Name3=Tantris
Name4=Waylish
Name5=Wolf
Name6=Strider
Name7=Aloysius
Name8=Androcles
Name9=Borys
Name10=Valdus
Name11=Titus
Name12=Silvius
Name13=Rufus
Name14=Remus
[17]
Name1=Fang
Name2=Dreadwing
Name3=Drakus
Name4=Druel
Name5=Hiss
Name6=Drake
Name7=Draco
Name8=Ormr
Name9=Pendragon
Name10=Drago
Name11=Drakon
Name12=Draken
Name13=Glaufang
Name14=Smoke
[18]
Name1=Morgana
Name2=Tabatha
Name3=Karlota
Name4=Elicia
Name5=Cassandra
Name6=Astarte
Name7=Bellatrix
Name8=Hecate
Name9=Desdemona
Name10=Inanna
Name11=Lucinda
Name12=Esmeralda
Name13=Aradia
Name14=Isis
[19]
Name1=Aureus
Name2=Orlo
Name3=Metallis
Name4=Sheenar
Name5=Balzius
Name6=Aurelius
Name7=Bazi
Name8=Midas
Name9=Abriz
Name10=Aureliano
Name11=Flavius
Name12=Orlando
Name13=Zarathustra
Name14=Zlatan
[20]
Name1=Shin Bo
Name2=Omi
Name3=Mongo
Name4=Reyon
Name5=Dakan
Name6=Avinash
Name7=Akshat
Name8=Anan
Name9=Amon
Name10=Ishwar
Name11=Momochi 
Name12=Alop
Name13=Shakti
Name14=Fuma
[21]
Name1=Spyder
Name2=Jester
Name3=Marco
Name4=Dupre
Name5=Eroll
Name6=Anwir
Name7=Buster
Name8=Diablos
Name9=Dionysos
Name10=Fox
Name11=Loki
Name12=Peter
Name13=Robin
Name14=Sly
[22]
Name1=Shalla
Name2=Diana
Name3=Lana
Name4=Delilah
Name5=Sonja
Name6=Aella
Name7=Olga
Name8=Urte
Name9=Nina
Name10=Alexandra
Name11=Daria
Name12=Kapitolina
Name13=Bogomila
Name14=Xenia
[23]
Name1=Yramrag
Name2=Grofzinar
Name3=Malefix
Name4=Farad
Name5=Solnar
Name6=Bolverkr
Name7=Borutag
Name8=Abigar
Name9=Malacoda 
Name10=Orobas
Name11=Teivel
Name12=Radnar
Name13=Volt
Name14=Raijin
[24]
Name1=Mystic X
Name2=Nymos
Name3=Morphis
Name4=Beast
Name5=Misterio
Name6=Tiger
Name7=Monsieur X
Name8=Dude
Name9=Hombre
Name10=Amigo
Name11=Stranger
Name12=Outlander
Name13=Somebody
Name14=John Doe
[25]
Name1=Aerie
Name2=Stella
Name3=Miranda
Name4=Windaria
Name5=Mira
Name6=Glinda
Name7=Aiden
Name8=Aleah
Name9=Arien
Name10=Azora
Name11=Phoebe
Name12=Samantha
Name13=Wanda
Name14=Xoara
[26]
Name1=Deth Stryke
Name2=Aleron
Name3=Destin
Name4=Nicholas
Name5=Walter
Name6=Ladislau
Name7=Dragomir
Name8=Gore
Name9=Wilhelm
Name10=Owain
Name11=Eugen
Name12=Infestus
Name13=Anvil
Name14=Slayer
[27]
Name1=Elana
Name2=Victoria
Name3=Aphena
Name4=Helena
Name5=Justine
Name6=Evelina
Name7=Cosima
Name8=Indira
Name9=Amara
Name10=Almina
Name11=Maliha
Name12=Anwen
Name13=Emilia
Name14=Elena
[28]
Name1=Roland
Name2=Charles
Name3=Fairley
Name4=Cecil
Name5=Andreas
Name6=Arthur
Name7=Baldric
Name8=Alexander
Name9=Cedric
Name10=Erik
Name11=Richard
Name12=Sebastian
Name13=Orlando
Name14=Gawain
[29]
Name1=Mortu
Name2=Redblade
Name3=Marek
Name4=Kane
Name5=Garrock
Name6=Hector
Name7=Mordred
Name8=Blake
Name9=Kazimir
Name10=Dracul
Name11=Morpheus
Name12=Tristan
Name13=Cadogan
Name14=Cain
[30]
Name1=Alorra
Name2=Gwendolyn
Name3=Darlona
Name4=Demeta
Name5=Lita
Name6=Elwyn
Name7=Gwyneth
Name8=Eluned
Name9=Alwena
Name10=Beccah
Name11=Ceridwen
Name12=Morwen
Name13=Alwina
Name14=Blodwen
[31]
Name1=Sir Harold
Name2=Sir Henry
Name3=Sir Stephan
Name4=Sir Sheldon
Name5=Sir Thomas
Name6=Sir West
Name7=Sir Lionel
Name8=Sir Ector
Name9=Christian
Name10=Sir William
Name11=Robert
Name12=Sir John
Name13=Sir Edward
Name14=Lancelot
[32]
Name1=Ravashack
Name2=Ulrik
Name3=Thanatos
Name4=Lazarus
Name5=Lucian
Name6=Vlad
Name7=Astaroth
Name8=Morte
Name9=Orpheus
Name10=Lestat
Name11=Narlok
Name12=Jarlath
Name13=Lucifer
Name14=Mephisto
[33]
Name1=Warrax
Name2=Kolimak
Name3=Harlak
Name4=Ruel
Name5=Moray
Name6=Vulcan
Name7=Abeloth 
Name8=Tyson
Name9=Brabax
Name10=Bautista
Name11=Miguel
Name12=Raul
Name13=Bronte
Name14=Barrak
[34]
Name1=Torin
Name2=Azrael
Name3=Lawrence
Name4=Purseus
Name5=Heuron
Name6=Cadogan
Name7=Ascelin
Name8=Sol
Name9=Davorin
Name10=Gabriel
Name11=Hod
Name12=Keter
Name13=Puriel
Name14=Netzach