; Note : When adding a new race, 
; if it's available for neutrals, at least one unit of that race must exist the system can pick to generate their garrison.
[0]
Unrest0=0
Unrest1=1
Unrest2=3
Unrest3=3
Unrest4=1
Unrest5=0
Unrest6=1
Unrest7=2
Unrest8=3
Unrest9=1
Unrest10=0
Unrest11=1
Unrest12=0
Unrest13=2
OutpostGrowth=30
CityGrowth=90
DisallowedBuilding1=25
DisallowedBuilding2=32
DisallowedBuilding3=34
DisallowedBuilding4=16
DisallowedBuilding5=11
DisallowedBuilding6=6
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=0
StartingUnit=40
Name=Barbarian
Plane=Arcanus
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=0
NeutralStartingBuilding4=22
NeutralStartingBuilding5=9
NeutralStartingBuilding6=0
NeutralStartingBuilding7=3
NeutralStartingBuilding8=0
NeutralStartingBuilding9=7
NeutralStartingBuilding10=0
SettlerProductioncost=100
[1]
Unrest0=1
Unrest1=0
Unrest2=1
Unrest3=1
Unrest4=1
Unrest5=1
Unrest6=1
Unrest7=1
Unrest8=3
Unrest9=1
Unrest10=1
Unrest11=1
Unrest12=1
Unrest13=1
OutpostGrowth=-5
CityGrowth=70
DisallowedBuilding1=14
DisallowedBuilding2=0
DisallowedBuilding3=0
DisallowedBuilding4=0
DisallowedBuilding5=0
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=0
StartingUnit=47
Name=Beastmen
Plane=Myrror
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=32
NeutralStartingBuilding4=0
NeutralStartingBuilding5=24
NeutralStartingBuilding6=5
NeutralStartingBuilding7=16
NeutralStartingBuilding8=19
NeutralStartingBuilding9=0
NeutralStartingBuilding10=0
SettlerProductioncost=150
[2]
Unrest0=3
Unrest1=0
Unrest2=0
Unrest3=0
Unrest4=3
Unrest5=3
Unrest6=0
Unrest7=2
Unrest8=2
Unrest9=1
Unrest10=2
Unrest11=0
Unrest12=1
Unrest13=3
OutpostGrowth=20
CityGrowth=40
DisallowedBuilding1=14
DisallowedBuilding2=0
DisallowedBuilding3=0
DisallowedBuilding4=0
DisallowedBuilding5=0
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=1
StartingUnit=58
Name=Dark Elf
Plane=Myrror
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=0
NeutralStartingBuilding4=9
NeutralStartingBuilding5=13
NeutralStartingBuilding6=5
NeutralStartingBuilding7=3
NeutralStartingBuilding8=21
NeutralStartingBuilding9=0
NeutralStartingBuilding10=0
SettlerProductioncost=150
[3]
Unrest0=0
Unrest1=0
Unrest2=0
Unrest3=0
Unrest4=3
Unrest5=3
Unrest6=0
Unrest7=0
Unrest8=3
Unrest9=4
Unrest10=-1
Unrest11=1
Unrest12=1
Unrest13=3
OutpostGrowth=-10
CityGrowth=60
DisallowedBuilding1=33
DisallowedBuilding2=11
DisallowedBuilding3=0
DisallowedBuilding4=0
DisallowedBuilding5=0
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=0
StartingUnit=67
Name=Draconian
Plane=Myrror
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=0
NeutralStartingBuilding4=15
NeutralStartingBuilding5=22
NeutralStartingBuilding6=24
NeutralStartingBuilding7=13
NeutralStartingBuilding8=21
NeutralStartingBuilding9=0
NeutralStartingBuilding10=3
SettlerProductioncost=150
[4]
Unrest0=0
Unrest1=0
Unrest2=3
Unrest3=3
Unrest4=0
Unrest5=0
Unrest6=0
Unrest7=3
Unrest8=1
Unrest9=1
Unrest10=0
Unrest11=0
Unrest12=4
Unrest13=1
OutpostGrowth=0
CityGrowth=20
DisallowedBuilding1=9
DisallowedBuilding2=4
DisallowedBuilding3=27
DisallowedBuilding4=28
DisallowedBuilding5=17
DisallowedBuilding6=13
DisallowedBuilding7=23
DisallowedBuilding8=35
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=0
StartingUnit=76
Name=Dwarf
Plane=Myrror
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=8
NeutralStartingBuilding2=32
NeutralStartingBuilding3=20
NeutralStartingBuilding4=0
NeutralStartingBuilding5=5
NeutralStartingBuilding6=0
NeutralStartingBuilding7=16
NeutralStartingBuilding8=19
NeutralStartingBuilding9=0
NeutralStartingBuilding10=3
SettlerProductioncost=200
[5]
Unrest0=0
Unrest1=0
Unrest2=3
Unrest3=3
Unrest4=2
Unrest5=0
Unrest6=1
Unrest7=2
Unrest8=4
Unrest9=1
Unrest10=0
Unrest11=2
Unrest12=1
Unrest13=1
OutpostGrowth=0
CityGrowth=60
DisallowedBuilding1=32
DisallowedBuilding2=13
DisallowedBuilding3=14
DisallowedBuilding4=11
DisallowedBuilding5=0
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=2
StartingUnit=84
Name=Gnoll
Plane=Arcanus
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=16
NeutralStartingBuilding4=5
NeutralStartingBuilding5=9
NeutralStartingBuilding6=19
NeutralStartingBuilding7=0
NeutralStartingBuilding8=3
NeutralStartingBuilding9=0
NeutralStartingBuilding10=7
SettlerProductioncost=150
[6]
Unrest0=1
Unrest1=0
Unrest2=0
Unrest3=0
Unrest4=0
Unrest5=1
Unrest6=0
Unrest7=0
Unrest8=0
Unrest9=0
Unrest10=1
Unrest11=0
Unrest12=0
Unrest13=1
OutpostGrowth=40
CityGrowth=60
DisallowedBuilding1=6
DisallowedBuilding2=9
DisallowedBuilding3=14
DisallowedBuilding4=3
DisallowedBuilding5=10
DisallowedBuilding6=35
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=0
StartingUnit=90
Name=Halfling
Plane=Arcanus
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=0
NeutralStartingBuilding4=22
NeutralStartingBuilding5=0
NeutralStartingBuilding6=0
NeutralStartingBuilding7=13
NeutralStartingBuilding8=21
NeutralStartingBuilding9=0
NeutralStartingBuilding10=0
SettlerProductioncost=150
[7]
Unrest0=3
Unrest1=0
Unrest2=2
Unrest3=0
Unrest4=3
Unrest5=3
Unrest6=0
Unrest7=0
Unrest8=2
Unrest9=0
Unrest10=1
Unrest11=0
Unrest12=4
Unrest13=3
OutpostGrowth=20
CityGrowth=30
DisallowedBuilding1=14
DisallowedBuilding2=4
DisallowedBuilding3=0
DisallowedBuilding4=0
DisallowedBuilding5=0
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=1
StartingUnit=96
Name=High Elf
Plane=Arcanus
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=16
NeutralStartingBuilding2=8
NeutralStartingBuilding3=9
NeutralStartingBuilding4=15
NeutralStartingBuilding5=31
NeutralStartingBuilding6=19
NeutralStartingBuilding7=0
NeutralStartingBuilding8=3
NeutralStartingBuilding9=13
NeutralStartingBuilding10=21
SettlerProductioncost=150
[8]
Unrest0=1
Unrest1=2
Unrest2=2
Unrest3=3
Unrest4=0
Unrest5=2
Unrest6=0
Unrest7=2
Unrest8=1
Unrest9=4
Unrest10=3
Unrest11=2
Unrest12=3
Unrest13=4
OutpostGrowth=10
CityGrowth=60
DisallowedBuilding1=11
DisallowedBuilding2=0
DisallowedBuilding3=0
DisallowedBuilding4=0
DisallowedBuilding5=0
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=0
StartingUnit=105
Name=High Men
Plane=Arcanus
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=32
NeutralStartingBuilding4=9
NeutralStartingBuilding5=24
NeutralStartingBuilding6=3
NeutralStartingBuilding7=5
NeutralStartingBuilding8=7
NeutralStartingBuilding9=16
NeutralStartingBuilding10=19
SettlerProductioncost=150
[9]
Unrest0=2
Unrest1=3
Unrest2=4
Unrest3=4
Unrest4=2
Unrest5=2
Unrest6=3
Unrest7=3
Unrest8=4
Unrest9=-4
Unrest10=2
Unrest11=3
Unrest12=2
Unrest13=2
OutpostGrowth=20
CityGrowth=110
DisallowedBuilding1=14
DisallowedBuilding2=27
DisallowedBuilding3=33
DisallowedBuilding4=22
DisallowedBuilding5=28
DisallowedBuilding6=7
DisallowedBuilding7=11
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=2
StartingUnit=115
Name=Klackon
Plane=Arcanus
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=0
NeutralStartingBuilding4=5
NeutralStartingBuilding5=0
NeutralStartingBuilding6=3
NeutralStartingBuilding7=0
NeutralStartingBuilding8=19
NeutralStartingBuilding9=0
NeutralStartingBuilding10=0
SettlerProductioncost=150
[10]
Unrest0=0
Unrest1=1
Unrest2=3
Unrest3=0
Unrest4=1
Unrest5=1
Unrest6=0
Unrest7=3
Unrest8=4
Unrest9=1
Unrest10=-1
Unrest11=2
Unrest12=1
Unrest13=0
OutpostGrowth=30
CityGrowth=70
DisallowedBuilding1=32
DisallowedBuilding2=34
DisallowedBuilding3=12
DisallowedBuilding4=7
DisallowedBuilding5=9
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=2
StartingUnit=121
Name=Lizardmen
Plane=Arcanus
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=0
NeutralStartingBuilding4=22
NeutralStartingBuilding5=16
NeutralStartingBuilding6=19
NeutralStartingBuilding7=5
NeutralStartingBuilding8=3
NeutralStartingBuilding9=0
NeutralStartingBuilding10=0
SettlerProductioncost=120
[11]
Unrest0=1
Unrest1=1
Unrest2=1
Unrest3=1
Unrest4=1
Unrest5=1
Unrest6=0
Unrest7=1
Unrest8=3
Unrest9=3
Unrest10=1
Unrest11=0
Unrest12=1
Unrest13=1
OutpostGrowth=0
CityGrowth=80
DisallowedBuilding1=14
DisallowedBuilding2=29
DisallowedBuilding3=4
DisallowedBuilding4=0
DisallowedBuilding5=0
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=0
StartingUnit=128
Name=Nomad
Plane=Arcanus
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=8
NeutralStartingBuilding2=15
NeutralStartingBuilding3=9
NeutralStartingBuilding4=16
NeutralStartingBuilding5=5
NeutralStartingBuilding6=19
NeutralStartingBuilding7=0
NeutralStartingBuilding8=3
NeutralStartingBuilding9=0
NeutralStartingBuilding10=7
SettlerProductioncost=100
[12]
Unrest0=0
Unrest1=0
Unrest2=3
Unrest3=1
Unrest4=3
Unrest5=0
Unrest6=0
Unrest7=4
Unrest8=3
Unrest9=1
Unrest10=0
Unrest11=0
Unrest12=0
Unrest13=0
OutpostGrowth=-10
CityGrowth=90
DisallowedBuilding1=0
DisallowedBuilding2=0
DisallowedBuilding3=0
DisallowedBuilding4=0
DisallowedBuilding5=0
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=0
StartingUnit=138
Name=Orc
Plane=Arcanus
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=8
NeutralStartingBuilding3=0
NeutralStartingBuilding4=22
NeutralStartingBuilding5=9
NeutralStartingBuilding6=5
NeutralStartingBuilding7=0
NeutralStartingBuilding8=3
NeutralStartingBuilding9=0
NeutralStartingBuilding10=7
SettlerProductioncost=150
[13]
Unrest0=0
Unrest1=2
Unrest2=3
Unrest3=3
Unrest4=1
Unrest5=0
Unrest6=0
Unrest7=3
Unrest8=4
Unrest9=1
Unrest10=0
Unrest11=3
Unrest12=0
Unrest13=0
OutpostGrowth=-20
CityGrowth=60
DisallowedBuilding1=32
DisallowedBuilding2=11
DisallowedBuilding3=17
DisallowedBuilding4=0
DisallowedBuilding5=0
DisallowedBuilding6=0
DisallowedBuilding7=0
DisallowedBuilding8=0
DisallowedBuilding9=0
DisallowedBuilding10=0
HouseType=2
StartingUnit=148
Name=Troll
Plane=Myrror
Playable=1
NeutralAllowed=1
NeutralStartingBuilding0=0
NeutralStartingBuilding1=0
NeutralStartingBuilding2=0
NeutralStartingBuilding3=22
NeutralStartingBuilding4=8
NeutralStartingBuilding5=0
NeutralStartingBuilding6=5
NeutralStartingBuilding7=3
NeutralStartingBuilding8=0
NeutralStartingBuilding9=7
NeutralStartingBuilding10=0
SettlerProductioncost=150
[14]
; This is the generic unit race. Ships and catapults use it.
Name=
Playable=0
NeutralAllowed=0
[15]
Name=Arcane
Playable=0
NeutralAllowed=0
[16]
Name=Nature
Playable=0
NeutralAllowed=0
[17]
Name=Sorcery
Playable=0
NeutralAllowed=0
[18]
Name=Chaos
Playable=0
NeutralAllowed=0
[19]
Name=Life
Playable=0
NeutralAllowed=0
[20]
Name=Death
Playable=0
NeutralAllowed=0
[21]
; Race used by Mystic Surge and Raise Dead spell as temporal effect.
Name=Mystic
Playable=0
NeutralAllowed=0
