[Special]
WildGameFood=8
VolcanoOwnerProduction=7
ForestGaiaProduction=9
OnRiverGoldBonus=20
NearShoreGoldBonus=10
; Minimal food required for starting fortress cities for each player.
; When no appropriate area can be found in a large number of rolls, the system will deviate from these values.
; Setting the requirements too high can lead to map generation freezing in an endless loop, unable to find a location.
MinFoodWet=12
MinFoodNormal=10
MinFoodDryVolcanicFrozen=8
; Maximal total ore value allowed on starting cities.
; When no appropriate area can be found in a large number of rolls, the system can deviate from this value.
; Setting this value too high can lead to runaway AI players with extremely good starts.
MaxOreQuality=10
[0]
; Ocean
Prod=0
Food=0
Gold=0
[1]
; Shore
Prod=0
Food=2
Gold=0
[2]
; Lake
Prod=0
Food=8
Gold=0
[3]
; River Mouth
Prod=0
Food=10
Gold=0
[4]
; Grassland
Prod=0
Food=6
Gold=0
[5]
; Hill
Prod=3
Food=2
Gold=0
[6]
; Mountain
Prod=7
Food=0
Gold=0
[7]
; Volcano
Prod=0
Food=0
Gold=0
[8]
; Desert
Prod=3
Food=0
Gold=0
[9]
; Swamp
Prod=0
Food=2
Gold=0
[10]
; Tundra
Prod=0
Food=0
Gold=0
[11]
; River
Prod=0
Food=8
Gold=0
[12]
; Forest
Prod=3
Food=2
Gold=0
[13]
; Chaos Node
Prod=7
Food=0
Gold=0
[14]
; Nature Node
Prod=3
Food=10
Gold=0
[15]
; Sorcery Node
Prod=0
Food=8
Gold=0
[16]
; Start of River
Prod=0
Food=8
Gold=0
[Colors]
; Pixel colors for the procedurally generated terrain graphics
OverlandGrassArcanus1=$3C5D3C
OverlandGrassArcanus2=$24744C
OverlandGrassArcanus3=$247524
OverlandGrassArcanus4=$247524
OverlandGrassArcanus5=$246431
OverlandGrassArcanus6=$24744C
OverlandGrassMyrror1=$415169
OverlandGrassMyrror2=$38455D
OverlandGrassMyrror3=$3c4149
OverlandGrassMyrror4=$10345D
OverlandGrassMyrror5=$303c51
OverlandGrassMyrror6=$450445
CombatGrassArcanus1=$24754D
CombatGrassArcanus2=$3C5D3C
CombatGrassArcanus3=$388E61
CombatGrassArcanus4=$044524
CombatGrassArcanus5=$105D38
CombatGrassArcanus6=$247524
CombatGrassMyrror1=$3C4048
CombatGrassMyrror2=$044444
CombatGrassMyrror3=$405068
CombatGrassMyrror4=$313B5B
CombatGrassMyrror5=$74244C
CombatGrassMyrror6=$4C5058
