; 1 = Nature
; 2 = Sorcery
; 3 = Chaos
; 4 = Life
; 5 = Death
[Enchants]
; Number of entries to read from this file
MaxEnchantAura=35
; Auras are displayed in the order defined in this file.
; Later auras replace earlier ones if both enchantments are present on the unit.
; Spell Lock
Aura1EnchantID=26
Aura1Color=2
; Sanctify
Aura2EnchantID=42
Aura2Color=4
; Mystic Surge
Aura3EnchantID=32
Aura3Color=3
; Water Walking
Aura4EnchantID=18
Aura4Color=1
; Wind Walking
Aura5EnchantID=29
Aura5Color=2
; True Sight
Aura6EnchantID=41
Aura6Color=4
; Focus Magic
Aura7EnchantID=49
Aura7Color=2
; Resist Elements
Aura8EnchantID=16
Aura8Color=1
; Land Link
Aura9EnchantID=19
Aura9Color=1
; Holy Armor
Aura10EnchantID=38
Aura10Color=4
; Holy Weapon
Aura11EnchantID=39
Aura11Color=4
; Flame Blade
Aura12EnchantID=31
Aura12Color=3
; Bless
Aura13EnchantID=51
Aura13Color=4
; Discipline
Aura14EnchantID=56
Aura14Color=4
; Resist Magic
Aura15EnchantID=23
Aura15Color=2
; Heroism
Aura16EnchantID=40
Aura16Color=4
; Animated
Aura17EnchantID=50
Aura17Color=5
; Immolation
Aura18EnchantID=36
Aura18Color=3
; Endurance
Aura19EnchantID=37
Aura19Color=4
; Chaos Channel Breath
Aura20EnchantID=33
Aura20Color=3
; Chaos Channel Armor
Aura21EnchantID=35
Aura21Color=3
; Guardian Wind
Aura22EnchantID=24
Aura22Color=2
; Wraith Form
Aura23EnchantID=47
Aura23Color=5
; Cloak of Fear
Aura24EnchantID=45
Aura24Color=5
; Elemental Armor
Aura25EnchantID=20
Aura25Color=1
; Lionheart
Aura26EnchantID=43
Aura26Color=4
; Invulnerability
Aura27EnchantID=44
Aura27Color=4
; Iron Skin
Aura28EnchantID=21
Aura28Color=1
; Blood Lust
Aura29EnchantID=48
Aura29Color=5
; Chaos Channels Flight
Aura30EnchantID=34
Aura30Color=3
; Flight
Aura31EnchantID=27
Aura31Color=2
; Regeneration
Aura32EnchantID=22
Aura32Color=1
; Haste
Aura33EnchantID=15
Aura33Color=2
; Destiny
Aura34EnchantID=57
Aura34Color=4
; Magic Immunity
Aura35EnchantID=30
Aura35Color=2
[Items]
; Number of entries to read from this file
MaxItemAura=38
; Water Walking
Aura1ItemPowerID=54
Aura1Color=1
; Path finding
Aura2ItemPowerID=55
Aura2Color=1
; Stealth
Aura3ItemPowerID=73
Aura3Color=5
; True Sight
Aura4ItemPowerID=50
Aura4Color=4
; Necromancy
Aura5ItemPowerID=45
Aura5Color=5
; Flaming
Aura6ItemPowerID=36
Aura6Color=3
; Stoning
Aura7ItemPowerID=56
Aura7Color=1
; Vampiric
Aura8ItemPowerID=43
Aura8Color=5
; Death 
Aura9ItemPowerID=44
Aura9Color=5
; Destruction
Aura10ItemPowerID=41
Aura10Color=3
; Resist Elements
Aura11ItemPowerID=57
Aura11Color=1
; Bless
Aura12ItemPowerID=48
Aura12Color=4
; Recharge
Aura13ItemPowerID=69
Aura13Color=3
; Holy Avenger
Aura14ItemPowerID=49
Aura14Color=4
; Egoism
Aura15ItemPowerID=70
Aura15Color=5
; Immolation
Aura16ItemPowerID=68
Aura16Color=3
; Shadow
Aura17ItemPowerID=46
Aura17Color=5
; Wraithform
Aura18ItemPowerID=45
Aura18Color=5
; Resist Magic
Aura19ItemPowerID=62
Aura19Color=2
; Guardian Wind
Aura20ItemPowerID=61
Aura20Color=2
; Fear
Aura21ItemPowerID=42
Aura21Color=5
; Insulation
Aura22ItemPowerID=37
Aura22Color=3
; Amplifier
Aura23ItemPowerID=72
Aura23Color=3
; Elemental Armor
Aura24ItemPowerID=58
Aura24Color=1
; Flight
Aura25ItemPowerID=63
Aura25Color=2
; Pandora's Box
Aura26ItemPowerID=38
Aura26Color=3
; Lion Heart
Aura27ItemPowerID=51
Aura27Color=4
; Invisibility
Aura28ItemPowerID=65
Aura28Color=2
; Divine Protection
Aura29ItemPowerID=52
Aura29Color=4
; Invulnerability
Aura30ItemPowerID=53
Aura30Color=4
; Lightning
Aura31ItemPowerID=39
Aura31Color=3
; Dark Force
Aura32ItemPowerID=71
Aura32Color=5
; Phantasmal
Aura33ItemPowerID=64
Aura33Color=2
; Merging
Aura34ItemPowerID=59
Aura34Color=1
; Teleportation
Aura35ItemPowerID=66
Aura35Color=2
; Doom
Aura36ItemPowerID=40
Aura36Color=3
; Regeneration
Aura37ItemPowerID=60
Aura37Color=1
; Haste
Aura38ItemPowerID=67
Aura38Color=2
